import type { DesktopToolDescriptor } from "./desktopToolDescriptorTypes";

export const mcpServerToolDescriptors: DesktopToolDescriptor[] = [
  {
    name: "ambient_mcp_standard_import_describe",
    label: "MCP Standard Import Describe",
    description: "Build a reviewed ToolHive import plan for a validated package-backed Standard MCP candidate.",
    promptSnippet:
      "ambient_mcp_standard_import_describe: Review exact source, runtime, permissions, secrets, and ToolHive run plan for one package-backed Standard MCP candidate.",
    promptGuidelines: [
      "Use ambient_mcp_standard_import_describe only after ambient_mcp_autowire_review returns a standard-mcp-import handoff.",
      "Prefer candidateRef when ambient_mcp_autowire_review provides one; otherwise pass the candidate object and expectedCandidateHash exactly as returned by ambient_mcp_autowire_review.",
      "When this returns no blockers, follow its nextToolName/nextToolInput directly: call ambient_mcp_standard_import_install with the returned candidateRef/expectedCandidateHash instead of searching for another install tool.",
      "This supports reviewed package-backed Standard MCP imports such as official server.json metadata that resolves to uvx, npx, pinned OCI sources, or source-built custom-image artifacts with source.resolvedCommit and image digest.",
      "MCPB candidates are recognized but should show a deferred unsupported-lane blocker until Ambient validates ToolHive MCPB run support.",
      "If this tool returns fallbackRoutes or nextToolName/nextToolInput, follow that exact reviewed Ambient route before trying broader search, source-build, local bridge, shell, or manual ToolHive alternatives.",
      "Read blockers and warnings before install. If required secrets are missing, call ambient_mcp_secret_request with the candidate/candidateRef and envName, then retry describe; never put secret values in chat, args, logs, descriptors, env fields, or placeholder files.",
      "This tool does not start the MCP server, but it writes a deterministic permission-profile preview under Ambient userData.",
      "Do not bypass Ambient with the bundled thv binary from shell for installs; raw ToolHive workloads are unmanaged by Ambient and will not have reviewed state, permission profiles, descriptor policy, or managed uninstall/update paths.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        candidate: {
          type: "object",
          description: "Exact MCP autowire candidate JSON object returned by ambient_mcp_autowire_plan/review.",
          additionalProperties: true,
        },
        candidateRef: {
          type: "string",
          description: "Ambient-issued reviewed candidate reference. Prefer this over re-sending a large candidate object when available.",
        },
        expectedCandidateHash: {
          type: "string",
          description: "Candidate hash from ambient_mcp_autowire_plan or ambient_mcp_autowire_review.",
        },
        secretBindings: {
          type: "array",
          description: "Optional Ambient-managed secret references for declared candidate secrets. Never include secret values.",
          items: {
            type: "object",
            properties: {
              envName: { type: "string", description: "Declared environment variable name." },
              secretRef: { type: "string", description: "Ambient-managed secret reference, not a raw secret value." },
            },
            required: ["envName", "secretRef"],
            additionalProperties: false,
          },
        },
      },
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "write-external",
    permissionScope: "mcp-server-discovery",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 30_000,
    runtimeSupport: ["chat"],
  },
  {
    name: "ambient_mcp_standard_import_install",
    label: "MCP Standard Import Install",
    description: "With approval, install, import, start, or repair one reviewed package-backed or source-built Standard MCP candidate through ToolHive after Standard import describe.",
    promptSnippet:
      "ambient_mcp_standard_import_install: Install/start a reviewed package-backed Standard MCP candidate after import describe, runtime preflight, and user approval.",
    promptGuidelines: [
      "Use ambient_mcp_standard_import_install only after ambient_mcp_standard_import_describe shows no blockers and the user wants the capability installed.",
      "If ambient_mcp_standard_import_describe returned nextToolName=ambient_mcp_standard_import_install, call this tool directly with the returned nextToolInput. Do not call ambient_tool_search again for that immediate next step.",
      "Prefer candidateRef when available so Pi does not have to repeat a large reviewed candidate object in install arguments.",
      "Search aliases: install reviewed Standard MCP import; start package-backed MCP candidate; run Standard MCP through ToolHive; repair reviewed Standard MCP import.",
      "This supports reviewed ToolHive uvx, npx, pinned OCI, and source-built custom-image import sources derived from validated Standard MCP metadata. Do not use it for arbitrary URLs, local paths, or custom shell commands.",
      "Do not try to install MCPB candidates through this tool until describe returns no deferred MCPB blocker.",
      "Ambient performs a ToolHive container-runtime preflight and requests approval with exact source, permissions, secrets, warnings, and run plan before running ToolHive.",
      "This tool is an ensure operation: if the server is already installed but its Ambient-managed ToolHive runtime shape is stale, missing reviewed volumes, or missing managed file-exchange state, Ambient repairs/reinstalls it instead of treating serverId alone as success.",
      "If required secrets are reported as blockers, call ambient_mcp_secret_request and retry; never ask the user to paste secret values into chat or create placeholder env files.",
      "Do not fall back to shelling out to bundled thv for installs unless the user explicitly requests unmanaged ToolHive debugging. Use Ambient MCP install tools so state, permission profiles, review records, and tool descriptor policy are persisted.",
      "After a successful install, use ambient_mcp_tool_search, ambient_mcp_tool_describe, and ambient_mcp_tool_call directly to exercise installed MCP tools; do not re-enter the generic tool router unless those direct tools are inactive.",
      "Do not use this tool in Planner Mode.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        candidate: {
          type: "object",
          description: "Exact MCP autowire candidate JSON object returned by ambient_mcp_autowire_plan/review.",
          additionalProperties: true,
        },
        candidateRef: {
          type: "string",
          description: "Ambient-issued reviewed candidate reference. Prefer this over re-sending a large candidate object when available.",
        },
        expectedCandidateHash: {
          type: "string",
          description: "Candidate hash from ambient_mcp_autowire_plan or ambient_mcp_autowire_review.",
        },
        secretBindings: {
          type: "array",
          description: "Optional Ambient-managed secret references for declared candidate secrets. Never include secret values.",
          items: {
            type: "object",
            properties: {
              envName: { type: "string", description: "Declared environment variable name." },
              secretRef: { type: "string", description: "Ambient-managed secret reference, not a raw secret value." },
            },
            required: ["envName", "secretRef"],
            additionalProperties: false,
          },
        },
      },
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "run-process",
    permissionScope: "mcp-server-install",
    supportsDryRun: false,
    supportsUndo: true,
    idempotency: "recommended",
    defaultTimeoutMs: 300_000,
    runtimeSupport: ["chat"],
  },
  {
    name: "ambient_mcp_remote_proxy_describe",
    label: "MCP Remote Proxy Describe",
    description: "Build a reviewed ToolHive proxy plan for a validated Remote MCP endpoint candidate.",
    promptSnippet:
      "ambient_mcp_remote_proxy_describe: Review exact endpoint, network, secrets, and ToolHive proxy run plan for one Remote MCP candidate.",
    promptGuidelines: [
      "Use ambient_mcp_remote_proxy_describe only after ambient_mcp_autowire_review returns a remote-mcp-proxy handoff.",
      "Pass the candidate object and expectedCandidateHash exactly as returned by ambient_mcp_autowire_review.",
      "This supports Remote MCP endpoints with streamable-http or sse transport, proxied through ToolHive instead of direct Ambient remote MCP.",
      "Required remote secrets block install. Call ambient_mcp_secret_request with the candidate and envName, then retry describe. Optional secrets can remain unbound for anonymous/lower-limit operation; do not pass secret values in chat, args, logs, descriptors, headers, or placeholder files.",
      "This tool does not connect to the remote MCP endpoint yet, but it writes a deterministic permission-profile preview under Ambient userData.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        candidate: {
          type: "object",
          description: "Exact MCP autowire candidate JSON object returned by ambient_mcp_autowire_plan/review.",
          additionalProperties: true,
        },
        expectedCandidateHash: {
          type: "string",
          description: "Candidate hash from ambient_mcp_autowire_plan or ambient_mcp_autowire_review.",
        },
        secretBindings: {
          type: "array",
          description: "Optional Ambient-managed secret references for declared candidate secrets. Bound remote Authorization secrets are delivered through a short-lived ToolHive bearer-token file.",
          items: {
            type: "object",
            properties: {
              envName: { type: "string", description: "Declared environment variable or remote auth secret name." },
              secretRef: { type: "string", description: "Ambient-managed secret reference, not a raw secret value." },
            },
            required: ["envName", "secretRef"],
            additionalProperties: false,
          },
        },
      },
      required: ["candidate"],
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "write-external",
    permissionScope: "mcp-server-discovery",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 30_000,
    runtimeSupport: ["chat"],
  },
  {
    name: "ambient_mcp_remote_proxy_install",
    label: "MCP Remote Proxy Install",
    description: "With approval, connect one reviewed Remote MCP endpoint through a ToolHive-managed proxy workload.",
    promptSnippet:
      "ambient_mcp_remote_proxy_install: Install a reviewed Remote MCP endpoint through ToolHive after describe, runtime preflight, and user approval.",
    promptGuidelines: [
      "Use ambient_mcp_remote_proxy_install only after ambient_mcp_remote_proxy_describe shows no blockers and the user wants this remote capability installed.",
      "This path supports https Remote MCP endpoints with streamable-http or sse transport. Do not use it for local bridges, arbitrary package execution, or non-MCP HTTP APIs.",
      "Ambient performs a ToolHive runtime preflight and requests approval with exact endpoint, permissions, secrets, warnings, and run plan before running ToolHive.",
      "If secret bindings are reported as blockers, install without optional secrets or call ambient_mcp_secret_request for required secrets; never put secret values into ToolHive args or placeholder files.",
      "Do not use this tool in Planner Mode.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        candidate: {
          type: "object",
          description: "Exact MCP autowire candidate JSON object returned by ambient_mcp_autowire_plan/review.",
          additionalProperties: true,
        },
        expectedCandidateHash: {
          type: "string",
          description: "Candidate hash from ambient_mcp_autowire_plan or ambient_mcp_autowire_review.",
        },
        secretBindings: {
          type: "array",
          description: "Optional Ambient-managed secret references for declared candidate secrets. Bound remote Authorization secrets are delivered through a short-lived ToolHive bearer-token file.",
          items: {
            type: "object",
            properties: {
              envName: { type: "string", description: "Declared environment variable or remote auth secret name." },
              secretRef: { type: "string", description: "Ambient-managed secret reference, not a raw secret value." },
            },
            required: ["envName", "secretRef"],
            additionalProperties: false,
          },
        },
      },
      required: ["candidate"],
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "run-process",
    permissionScope: "mcp-server-install",
    supportsDryRun: false,
    supportsUndo: true,
    idempotency: "recommended",
    defaultTimeoutMs: 300_000,
    runtimeSupport: ["chat"],
  },
  {
    name: "ambient_mcp_guided_bridge_describe",
    label: "MCP Guided Bridge Describe",
    description: "Build a docs-guided local bridge setup plan for a validated guided-local MCP candidate without installing or starting anything.",
    promptSnippet:
      "ambient_mcp_guided_bridge_describe: Present setup steps, local app boundary, and exact loopback preflight targets for one guided-local MCP bridge candidate.",
    promptGuidelines: [
      "Use ambient_mcp_guided_bridge_describe only after ambient_mcp_autowire_review returns a guided-local-bridge handoff.",
      "Pass the candidate object and expectedCandidateHash exactly as returned by ambient_mcp_autowire_review.",
      "This is the right path for GhidraMCP-style integrations that require a user-installed local app, extension, and user-run bridge command.",
      "Do not install Ghidra, install extensions, run package managers, start bridge commands, containerize the app, or call bridge tools from this describe step.",
      "If the candidate declares secrets, pass existing Ambient secret refs in secretBindings or call ambient_mcp_secret_request first; never ask for raw secret values.",
      "Read setup checkpoints and hard blockers. If setup is complete and the user approves a local check, call ambient_mcp_guided_bridge_preflight next.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        candidate: {
          type: "object",
          description: "Exact MCP autowire candidate JSON object returned by ambient_mcp_autowire_plan/review.",
          additionalProperties: true,
        },
        expectedCandidateHash: {
          type: "string",
          description: "Candidate hash from ambient_mcp_autowire_plan or ambient_mcp_autowire_review.",
        },
        secretBindings: {
          type: "array",
          description: "Ambient-managed secret refs for guided-local bridge metadata. Values must come from ambient_mcp_secret_request or saved refs, never chat text.",
          items: {
            type: "object",
            properties: {
              envName: { type: "string" },
              secretRef: { type: "string" },
            },
            required: ["envName", "secretRef"],
            additionalProperties: false,
          },
        },
      },
      required: ["candidate"],
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "none",
    permissionScope: "mcp-guided-local-bridge",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 30_000,
    runtimeSupport: ["chat"],
  },
  {
    name: "ambient_mcp_guided_bridge_preflight",
    label: "MCP Guided Bridge Preflight",
    description: "With approval, check exact loopback endpoints for a guided-local MCP bridge without installing, starting, or calling bridge tools.",
    promptSnippet:
      "ambient_mcp_guided_bridge_preflight: After user setup and approval, probe exact loopback endpoints for one guided-local MCP bridge candidate.",
    promptGuidelines: [
      "Use ambient_mcp_guided_bridge_preflight only after ambient_mcp_guided_bridge_describe and only when the user indicates setup is complete.",
      "This tool performs bounded GET requests to the exact reviewed loopback bridge and upstream local-app URLs. It does not install or launch software and does not call MCP tools.",
      "For GhidraMCP, expect the user-run MCP SSE bridge on 127.0.0.1:8081 and the Ghidra extension HTTP server on 127.0.0.1:8080 unless the reviewed candidate says otherwise.",
      "If preflight fails, report setup checkpoints instead of trying shell commands or broader local-network probes.",
      "Do not use this tool in Planner Mode.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        candidate: {
          type: "object",
          description: "Exact MCP autowire candidate JSON object returned by ambient_mcp_autowire_plan/review.",
          additionalProperties: true,
        },
        expectedCandidateHash: {
          type: "string",
          description: "Candidate hash from ambient_mcp_autowire_plan or ambient_mcp_autowire_review.",
        },
        timeoutMs: {
          type: "number",
          description: "Optional per-endpoint timeout in milliseconds. Defaults to 2000, capped at 30000.",
        },
      },
      required: ["candidate"],
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "read-external",
    permissionScope: "mcp-guided-local-bridge",
    supportsDryRun: false,
    supportsUndo: false,
    idempotency: "recommended",
    defaultTimeoutMs: 30_000,
    runtimeSupport: ["chat"],
  },
  {
    name: "ambient_mcp_guided_bridge_register",
    label: "MCP Guided Bridge Register",
    description: "With approval, re-check and register one user-guided local MCP bridge in Ambient global MCP state, then perform harmless tool descriptor discovery.",
    promptSnippet:
      "ambient_mcp_guided_bridge_register: After guided setup and preflight, register a loopback local MCP bridge for Ambient MCP tool discovery.",
    promptGuidelines: [
      "Use ambient_mcp_guided_bridge_register only after ambient_mcp_guided_bridge_describe and when the user wants Ambient to use the already-running local bridge.",
      "This tool repeats the exact loopback preflight, writes global Ambient MCP state, and performs tools/list descriptor discovery only. It does not install, launch, modify, stop, or update local software.",
      "For GhidraMCP, this registers the user-run SSE bridge endpoint so ambient_mcp_tool_search/describe can discover list/read tools through the compact MCP bridge.",
      "If the candidate declares secrets, pass existing Ambient secret refs in secretBindings or call ambient_mcp_secret_request before registration; registration records refs only and never passes raw values to Pi.",
      "If registration succeeds but descriptor discovery fails, report the local setup issue and do not try shell commands, package managers, or broader local-network probes.",
      "Do not use this tool in Planner Mode.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        candidate: {
          type: "object",
          description: "Exact MCP autowire candidate JSON object returned by ambient_mcp_autowire_plan/review.",
          additionalProperties: true,
        },
        expectedCandidateHash: {
          type: "string",
          description: "Candidate hash from ambient_mcp_autowire_plan or ambient_mcp_autowire_review.",
        },
        timeoutMs: {
          type: "number",
          description: "Optional per-endpoint timeout in milliseconds. Defaults to 2000 for preflight and uses the MCP bridge timeout for descriptor discovery.",
        },
        secretBindings: {
          type: "array",
          description: "Ambient-managed secret refs for guided-local bridge metadata. Values must come from ambient_mcp_secret_request or saved refs, never chat text.",
          items: {
            type: "object",
            properties: {
              envName: { type: "string" },
              secretRef: { type: "string" },
            },
            required: ["envName", "secretRef"],
            additionalProperties: false,
          },
        },
      },
      required: ["candidate"],
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "write-external",
    permissionScope: "mcp-guided-local-bridge",
    supportsDryRun: false,
    supportsUndo: true,
    idempotency: "recommended",
    defaultTimeoutMs: 60_000,
    runtimeSupport: ["chat"],
  },
  {
    name: "ambient_mcp_server_search",
    label: "MCP Server Search",
    description: "Search ToolHive registry MCP servers and Ambient-recommended MCP import handoffs before reviewing or installing one through Ambient.",
    promptSnippet: "ambient_mcp_server_search: Search ToolHive registry MCP servers and Ambient-recommended MCP import handoffs by capability, server id, tag, or tool name.",
    promptGuidelines: [
      "Use ambient_mcp_server_search when the user asks for an MCP plugin/server capability and the exact ToolHive registry server id is not already known.",
      "This searches registry-backed MCP servers plus a small Ambient-reviewed recommendation set. It does not inspect arbitrary GitHub URLs, install servers, start containers, or expose every MCP tool schema to context.",
      "After selecting a ToolHive registry/default server, call ambient_mcp_server_describe before ambient_mcp_server_install. Built-in defaults such as Scrapling use the same serverId tools, and Ambient routes them through the default capability installer.",
      "If a result says it is an Ambient-recommended Standard MCP import, follow its nextAction only when no built-in default matches or the user explicitly asks for the generic import: use ambient_mcp_autowire_plan with the listed targetUrl, then ambient_mcp_autowire_review.",
      "For arbitrary GitHub URLs or non-registry sources, use the MCP autowire planning flow instead of this registry install path.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        query: { type: "string", description: "Search terms describing the desired MCP server capability." },
        limit: { type: "number", description: "Maximum result count. Defaults to 20 and is capped by Desktop." },
        refresh: { type: "boolean", description: "Whether to ask ToolHive to refresh registry metadata before searching." },
      },
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "read-external",
    permissionScope: "mcp-server-discovery",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 30_000,
    runtimeSupport: ["chat"],
  },
  {
    name: "ambient_mcp_server_describe",
    label: "MCP Server Describe",
    description: "Build a reviewed install description and ToolHive run plan for one ToolHive registry MCP server.",
    promptSnippet: "ambient_mcp_server_describe: Review exact source, runtime, permissions, secrets, validation, and ToolHive run plan for one registry MCP server.",
    promptGuidelines: [
      "Use ambient_mcp_server_describe after ambient_mcp_server_search selects a server and before any install attempt. For Ambient built-in defaults such as Scrapling, this returns the default capability review rather than the generic registry lane.",
      "Pass the exact ToolHive registry serverId. Do not substitute GitHub URLs, package names, npx/uvx URLs, local paths, or arbitrary image names.",
      "If the registry result or user request requires local filesystem access, pass runtimeVolumes during describe and install. Use a safe containerPath under /projects/<name> and mode=ro unless the user explicitly requests write access.",
      "Read blockers and warnings. If required secrets are missing, call ambient_mcp_secret_request with serverId and envName, then retry describe; never put secret values in chat, args, logs, descriptors, env fields, or placeholder files.",
      "This tool does not start the MCP server, but it may write a deterministic permission-profile preview under Ambient userData so the review contains an exact ToolHive plan.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        serverId: { type: "string", description: "Exact ToolHive registry server id, for example io.github.stacklok/context7." },
        refresh: { type: "boolean", description: "Whether to ask ToolHive to refresh registry metadata before describing." },
        runtimeVolumes: {
          type: "array",
          description: "Optional reviewed ToolHive runtime mounts for registry servers that need local filesystem access. Use mode=ro unless the user explicitly asks for write access.",
          items: {
            type: "object",
            properties: {
              hostPath: { type: "string", description: "Absolute host path to expose. Broad roots and secret-looking paths are rejected." },
              containerPath: { type: "string", description: "Safe absolute container path, for example /projects/fixture." },
              mode: { type: "string", enum: ["ro", "rw"], description: "ro for read-only, rw only with explicit user request." },
              purpose: { type: "string", description: "Short reason this mount is required." },
            },
            required: ["hostPath", "containerPath", "mode"],
            additionalProperties: false,
          },
        },
        secretBindings: {
          type: "array",
          description: "Optional Ambient-managed secret references for declared registry secrets. Never include secret values.",
          items: {
            type: "object",
            properties: {
              envName: { type: "string", description: "Declared registry environment variable name." },
              secretRef: { type: "string", description: "Ambient-managed secret reference, not a raw secret value." },
            },
            required: ["envName", "secretRef"],
            additionalProperties: false,
          },
        },
      },
      required: ["serverId"],
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "write-external",
    permissionScope: "mcp-server-discovery",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 30_000,
    runtimeSupport: ["chat"],
  },
  {
    name: "ambient_mcp_server_install",
    label: "MCP Server Install",
    description: "With approval, install and start one reviewed ToolHive registry MCP server in the Ambient ToolHive group.",
    promptSnippet: "ambient_mcp_server_install: Install a reviewed ToolHive registry MCP server after describe, runtime preflight, and user approval.",
    promptGuidelines: [
      "Use ambient_mcp_server_install only after ambient_mcp_server_describe shows no blockers and the user wants this MCP server installed. For Ambient built-in defaults such as Scrapling, this delegates to the default capability installer and opens runtime setup if Docker/Podman is missing.",
      "This V1 install path supports ToolHive registry server ids only. Do not use it for arbitrary GitHub URLs, npx://, uvx://, local .mcp.json, local paths, or custom images.",
      "If ambient_mcp_server_describe used runtimeVolumes, pass the same runtimeVolumes to install so approval, permission profile, and ToolHive --volume flags match.",
      "Ambient performs a ToolHive container-runtime preflight and requests approval with exact source, permissions, secrets, warnings, and run plan before running ToolHive.",
      "If required secrets are reported as blockers, call ambient_mcp_secret_request and retry; Desktop will attach saved MCP secret refs automatically. Never ask the user to paste secret values into chat or create placeholder env files.",
      "After install, the server is managed by Ambient state under app userData. Tool-level search/describe/call is a separate MCP tool-bridge phase.",
      "Do not use this tool in Planner Mode.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        serverId: { type: "string", description: "Exact ToolHive registry server id that was reviewed by ambient_mcp_server_describe." },
        refresh: { type: "boolean", description: "Whether to ask ToolHive to refresh registry metadata before install preview." },
        runtimeVolumes: {
          type: "array",
          description: "Reviewed ToolHive runtime mounts from ambient_mcp_server_describe. Required for filesystem registry servers.",
          items: {
            type: "object",
            properties: {
              hostPath: { type: "string", description: "Absolute host path to expose." },
              containerPath: { type: "string", description: "Safe absolute container path, for example /projects/fixture." },
              mode: { type: "string", enum: ["ro", "rw"], description: "ro for read-only, rw only with explicit user request." },
              purpose: { type: "string", description: "Short reason this mount is required." },
            },
            required: ["hostPath", "containerPath", "mode"],
            additionalProperties: false,
          },
        },
        secretBindings: {
          type: "array",
          description: "Optional Ambient-managed secret references for declared registry secrets. Never include secret values.",
          items: {
            type: "object",
            properties: {
              envName: { type: "string", description: "Declared registry environment variable name." },
              secretRef: { type: "string", description: "Ambient-managed secret reference, not a raw secret value." },
            },
            required: ["envName", "secretRef"],
            additionalProperties: false,
          },
        },
      },
      required: ["serverId"],
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "run-process",
    permissionScope: "mcp-server-install",
    supportsDryRun: false,
    supportsUndo: true,
    idempotency: "recommended",
    defaultTimeoutMs: 300_000,
    runtimeSupport: ["chat"],
  },
  {
    name: "ambient_mcp_server_list",
    label: "MCP Server List",
    description: "List Ambient-managed ToolHive MCP servers with persisted install state and current workload status when available.",
    promptSnippet: "ambient_mcp_server_list: List installed Ambient-managed ToolHive MCP servers before status checks or uninstall.",
    promptGuidelines: [
      "Use ambient_mcp_server_list when the user asks what MCP servers/plugins are installed, running, stopped, or available for uninstall.",
      "This lists only Ambient-managed ToolHive MCP servers. It does not enumerate arbitrary Docker containers, system ToolHive workloads, or every MCP tool schema.",
      "If workload status is unknown or ToolHive list fails, use the persisted Ambient install state and report the runtime-list error instead of assuming the server is gone.",
      "Use ambient_mcp_server_uninstall with the exact serverId or workloadName returned here to remove one installed server.",
    ],
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "none",
    permissionScope: "mcp-server-discovery",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 30_000,
    runtimeSupport: ["chat"],
  },
  {
    name: "ambient_mcp_server_diagnostics",
    label: "MCP Server Diagnostics",
    description: "Read redacted diagnostics for one Ambient-managed MCP server, including workload status, validation state, descriptor snapshot, permission profile, secret binding presence, and bounded ToolHive logs.",
    promptSnippet: "ambient_mcp_server_diagnostics: Inspect one Ambient-managed MCP server after install validation fails, runtime health changes, or descriptor discovery behaves unexpectedly.",
    promptGuidelines: [
      "Use ambient_mcp_server_diagnostics when an MCP install returns validation_failed, a server looks unhealthy, tools/list fails, or the user asks why an Ambient-managed MCP server is not usable.",
      "Pass an exact serverId, workloadName, or both from ambient_mcp_server_list or an install result. If a serverId is ambiguous, call ambient_mcp_server_list and retry with the exact workloadName.",
      "This tool is read-only. It may read bounded ToolHive logs for the selected Ambient workload, but it does not shell out arbitrarily, restart containers, install packages, call MCP tools, or expose secret values.",
      "Report validationError, descriptor snapshot status, permission profile hash verification, and secret-binding presence. Never ask the user to paste raw secrets into chat.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        serverId: { type: "string", description: "Installed MCP server id, for example io.github.stacklok/context7." },
        workloadName: { type: "string", description: "Installed Ambient ToolHive workload name." },
        logLines: { type: "number", description: "Maximum recent ToolHive log lines to request. Defaults to 80 and is capped at 500." },
      },
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "none",
    permissionScope: "mcp-server-discovery",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 30_000,
    runtimeSupport: ["chat"],
  },
  {
    name: "ambient_mcp_server_default_update_describe",
    label: "MCP Default Update Describe",
    description: "Review bundled Ambient default-catalog update state and diff for one installed MCP server.",
    promptSnippet:
      "ambient_mcp_server_default_update_describe: Show the reviewed default-catalog descriptor diff and safe reinstall handoff for one installed MCP server.",
    promptGuidelines: [
      "Use ambient_mcp_server_default_update_describe when ambient_mcp_server_list reports defaultCatalog=update-available or defaultCatalog=untracked.",
      "Pass an exact serverId, workloadName, or both. If a serverId is ambiguous, call ambient_mcp_server_list and retry with the exact workloadName.",
      "This tool is read-only. It does not stop workloads, reinstall servers, mark descriptors current, or trust changed MCP tool descriptors.",
      "If the user approves the update handoff, use ambient_mcp_server_uninstall for the old workload and ambient_mcp_server_install for the same serverId. Do not relabel the installed descriptor as current without reinstalling.",
      "Preserve Ambient-managed secret refs. If reinstall needs secretBindings, use existing refs or request Ambient secret entry; never ask the user to paste secret values into chat.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        serverId: { type: "string", description: "Installed MCP server id, for example io.github.stacklok/context7." },
        workloadName: { type: "string", description: "Installed Ambient ToolHive workload name." },
      },
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "none",
    permissionScope: "mcp-server-discovery",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 30_000,
    runtimeSupport: ["chat"],
  },
  {
    name: "ambient_mcp_runtime_repair_describe",
    label: "MCP Runtime Repair Describe",
    description: "Preview typed Autowire plan repairs for an installed MCP runtime failure using diagnostics evidence.",
    promptSnippet:
      "ambient_mcp_runtime_repair_describe: Convert clear MCP runtime diagnostics into typed Autowire plan repair operations without editing raw ToolHive state.",
    promptGuidelines: [
      "Use this after ambient_mcp_server_diagnostics, install validation_failed, blocked network evidence, missing env errors, or a failed smoke call.",
      "Pass serverId/workloadName when repairing an installed server, or revisionId/candidateRef/candidate when repairing a candidate before reinstall.",
      "Include exact failureText or logText with the blocked host, URL, missing env name, or other validation evidence. Ambiguous filesystem failures need explicit path/mount details before an edit is proposed.",
      "This is a dry run. If it returns repair-available and the user approves, call ambient_mcp_runtime_repair_apply with the same selector and evidence.",
      "Never replace this with raw thv commands, permission profile edits, generated manifest edits, or state file patches.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        serverId: { type: "string", description: "Installed MCP server id when repairing an installed server." },
        workloadName: { type: "string", description: "Installed Ambient ToolHive workload name." },
        revisionId: { type: "string", description: "Recorded Autowire plan revision id to repair." },
        candidateRef: { type: "string", description: "Ambient-issued candidate reference to repair." },
        candidate: { type: "object", description: "Exact MCP autowire candidate JSON when no revision or ref exists.", additionalProperties: true },
        expectedCandidateHash: { type: "string", description: "Optional current candidate hash to prevent stale repair edits." },
        failureText: { type: "string", description: "Exact bounded failure text, validation error, or blocked resource message." },
        logText: { type: "string", description: "Optional bounded redacted log excerpt from diagnostics." },
        reason: { type: "string", description: "Brief reason for this repair, shown in revision history and approval." },
      },
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "none",
    permissionScope: "mcp-server-discovery",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "required",
    defaultTimeoutMs: 30_000,
    runtimeSupport: ["chat"],
  },
  {
    name: "ambient_mcp_runtime_repair_apply",
    label: "MCP Runtime Repair Apply",
    description: "After explicit user approval, record typed Autowire repair edits and return sanctioned review and reinstall handoffs.",
    promptSnippet:
      "ambient_mcp_runtime_repair_apply: With explicit user approval, record typed MCP runtime repair edits as a new Autowire plan revision. Do not mutate raw ToolHive state.",
    promptGuidelines: [
      "Use only after ambient_mcp_runtime_repair_describe previews the exact operations and the user gives explicit user approval.",
      "This records a new candidate revision and candidateRef. It does not patch ToolHive permission profile files or mutate raw ToolHive state.",
      "After apply, prefer directRepairNextToolName/directRepairNextToolInput when present; this routes the repaired candidate through the normal Standard MCP install approval and ToolHive runtime service.",
      "If no direct repair handoff is present, call ambient_mcp_autowire_review with the returned candidateRef and expectedCandidateHash, then follow the normal Standard MCP, Remote MCP, registry, or guided bridge handoff.",
      "If no repair is available, ask for more diagnostics rather than guessing a permission profile or shell command.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        serverId: { type: "string", description: "Installed MCP server id when repairing an installed server." },
        workloadName: { type: "string", description: "Installed Ambient ToolHive workload name." },
        revisionId: { type: "string", description: "Recorded Autowire plan revision id to repair." },
        candidateRef: { type: "string", description: "Ambient-issued candidate reference to repair." },
        candidate: { type: "object", description: "Exact MCP autowire candidate JSON when no revision or ref exists.", additionalProperties: true },
        expectedCandidateHash: { type: "string", description: "Optional current candidate hash to prevent stale repair edits." },
        failureText: { type: "string", description: "Exact bounded failure text, validation error, or blocked resource message." },
        logText: { type: "string", description: "Optional bounded redacted log excerpt from diagnostics." },
        reason: { type: "string", description: "Brief reason for this repair, shown in revision history and approval." },
      },
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "write-external",
    permissionScope: "mcp-runtime-repair",
    supportsDryRun: false,
    supportsUndo: false,
    idempotency: "required",
    defaultTimeoutMs: 30_000,
    runtimeSupport: ["chat"],
  },
  {
    name: "ambient_mcp_secret_request",
    label: "MCP Secret Request",
    description: "Ask Desktop to open a user-facing secret entry dialog for a declared MCP server or candidate env requirement.",
    promptSnippet: "ambient_mcp_secret_request: Request Desktop-owned secret entry for a declared MCP install env requirement.",
    promptGuidelines: [
      "Use ambient_mcp_secret_request when an MCP describe/install tool reports a missing required secret or the reviewed candidate declares a required secret before install.",
      "For ToolHive registry servers, pass serverId and envName. For Standard MCP or Remote MCP candidates, pass candidateRef when available, or the exact candidate object, plus envName and expectedCandidateHash when available.",
      "This tool opens a Desktop dialog; Pi receives no secret value and should not ask the user to paste the secret into chat.",
      "After the user saves the secret, retry ambient_mcp_server_describe/install, ambient_mcp_standard_import_describe/install, or ambient_mcp_remote_proxy_describe/install. Ambient will resolve saved MCP secret refs automatically.",
      "Do not create .env placeholder files, commit secret files, bind arbitrary workspace files, or put secret values in tool arguments, logs, descriptors, or chat.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        serverId: { type: "string", description: "Exact ToolHive registry server id when the secret belongs to a registry/default MCP server." },
        candidate: {
          type: "object",
          description: "Exact MCP autowire candidate JSON object returned by ambient_mcp_autowire_plan/review.",
          additionalProperties: true,
        },
        candidateRef: {
          type: "string",
          description: "Ambient-issued reviewed candidate reference from ambient_mcp_autowire_plan/review. Prefer this over re-sending a large candidate object when available.",
        },
        expectedCandidateHash: {
          type: "string",
          description: "Optional candidate hash from ambient_mcp_autowire_plan or ambient_mcp_autowire_review.",
        },
        envName: {
          type: "string",
          description: "Declared MCP environment variable name to request, for example KATZILLA_API_KEY.",
        },
      },
      required: ["envName"],
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "none",
    permissionScope: "mcp-server-secret",
    supportsDryRun: false,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 30_000,
    runtimeSupport: ["chat"],
  },
  {
    name: "ambient_mcp_server_uninstall",
    label: "MCP Server Uninstall",
    description: "With approval, stop and remove one Ambient-managed ToolHive MCP server workload and Ambient install state.",
    promptSnippet: "ambient_mcp_server_uninstall: Remove one installed Ambient-managed ToolHive MCP server by exact serverId or workloadName.",
    promptGuidelines: [
      "Use ambient_mcp_server_uninstall only for servers returned by ambient_mcp_server_list or known to be Ambient-managed ToolHive workloads.",
      "Pass an exact serverId or workloadName. If the result is ambiguous, call ambient_mcp_server_list and retry with both identifiers.",
      "Ambient requests approval with the exact workload, status, endpoint, and permission profile before stopping/removing the workload.",
      "This does not delete user secrets unless a future secret cleanup flow explicitly asks for that approval.",
      "Do not use this tool in Planner Mode.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        serverId: { type: "string", description: "Exact installed MCP server id, for example io.github.stacklok/context7." },
        workloadName: { type: "string", description: "Exact Ambient ToolHive workload name, for example ambient-stacklok-context7-..." },
      },
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "run-process",
    permissionScope: "mcp-server-install",
    supportsDryRun: false,
    supportsUndo: false,
    idempotency: "recommended",
    defaultTimeoutMs: 120_000,
    runtimeSupport: ["chat"],
  },
];
