import type { DesktopToolDescriptor, WorkflowCapabilityGuidanceDescriptor } from "./desktopToolDescriptorTypes";

const ambientCliWorkflowGuidance: WorkflowCapabilityGuidanceDescriptor[] = [
  {
    id: "ambient-cli-describe-before-run",
    summary: "Ambient CLI execution is pinned to selected command metadata and a preflight describe step.",
    text:
      "Ambient CLI workflow guidance: use ambient_cli_search unless the exact installed package and command are already selected in compiler capability metadata. Every ambient_cli execution must identify the package with literal packageName or packageId, identify the descriptor command with literal command, and depend on a matching ambient_cli_describe node before execution. Do not emit ambient_cli for unselected, unavailable, dynamic, or undescribed commands.",
    applicabilityTags: ["ambient_cli", "ambient_cli_search", "ambient_cli_describe", "preflight", "capability-grant"],
    risk: "high",
    validatorRefs: [
      "ambient_cli.capability_required",
      "ambient_cli.literal_command_required",
      "ambient_cli.literal_identity_required",
      "ambient_cli.describe_required",
      "ambient_cli.search_required",
    ],
  },
  {
    id: "ambient-cli-missing-env-setup",
    summary: "Ambient CLI commands with missing env compile as setup workflows instead of failed executions.",
    text:
      "Ambient CLI missing-env workflow guidance: if selected Ambient CLI capability metadata includes missingEnv, do not emit the secret-backed ambient_cli execution yet. Emit a setup workflow that describes the package, then uses ambient_cli_secret_request as tool.call or ambient_cli_env_bind as mutation.stage for one declared envName, and finishes with output.final instructions to retry or recompile after Desktop reports the env configured.",
    applicabilityTags: ["ambient_cli", "ambient_cli_secret_request", "ambient_cli_env_bind", "missing-env", "setup"],
    risk: "high",
    validatorRefs: [
      "ambient_cli.capability_missing_env",
      "ambient_cli.secret_env_not_declared",
      "ambient_cli.secret_request_tool_call_required",
      "ambient_cli.env_bind_mutation_stage_required",
    ],
  },
  {
    id: "ambient-cli-secret-redaction",
    summary: "Ambient CLI secret values stay out of workflow IR and are bound through Desktop-managed secret paths.",
    text:
      "Ambient CLI secret workflow guidance: never include API keys, tokens, passwords, private keys, or other secret values in ambient_cli args, model input, checkpoints, logs, or generated files. ambient_cli_secret_request carries only packageName or packageId plus envName. ambient_cli_env_bind carries only packageName or packageId, envName, and a workspace-relative ignored secret filePath. Desktop injects declared env requirements at runtime; workflows must not pass secret-bearing CLI flags or literal secret values.",
    applicabilityTags: ["ambient_cli", "secret", "env", "redaction", "ambient_cli_env_bind", "ambient_cli_secret_request"],
    risk: "high",
    validatorRefs: [
      "ambient_cli.secret_value_rejected",
      "ambient_cli.secret_literal_args_required",
      "ambient_cli.secret_env_invalid",
      "ambient_cli.env_bind_file_path_invalid",
    ],
  },
];

export const ambientCliToolDescriptors: DesktopToolDescriptor[] = [
  {
    name: "ambient_cli_package_preview",
    label: "CLI Package Preview",
    description: "Preview a local, reviewed bundled, or pinned Git-backed Ambient CLI package without installing it.",
    promptSnippet: "ambient_cli_package_preview: Inspect a local directory, reviewed bundled source, or pinned Git source for an Ambient CLI package descriptor.",
    promptGuidelines: [
      "Use ambient_cli_package_preview before installing CLI packages from URL or Git references.",
      "For reviewed first-party bundled packages, use the exact bundled:<package-name> source, for example bundled:ambient-tinystyler.",
      "For Git sources, include sha and optional path; unpinned Git installs are not supported.",
      "This tool is read-only except for temporary clone/cache work that is deleted before returning.",
      "Descriptor health checks may use timeoutProfile, progressPatterns, and devicePolicy metadata when preview execution is requested.",
      "Summarize commands, skills, health checks, and errors before asking for install approval.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        source: { type: "string", description: "Workspace-local package directory, reviewed bundled:<package-name> source, or Git URL/path to inspect." },
        path: { type: "string", description: "Optional package subdirectory inside a Git repository." },
        ref: { type: "string", description: "Optional Git ref for preview context." },
        sha: { type: "string", description: "Pinned Git commit SHA. Required for Git-backed install." },
        descriptor: {
          type: "object",
          description: "Optional Ambient CLI descriptor overlay for reviewed packages that ship SKILL.md but no ambient-cli.json.",
          additionalProperties: true,
        },
        installDependencies: {
          type: "boolean",
          description: "Whether to install lockfile-backed npm dependencies in a temporary preview copy before health checks.",
        },
      },
      required: ["source"],
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "read-external",
    permissionScope: "cli-package-preview",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 1_200_000,
  },
  {
    name: "ambient_cli_package_install",
    label: "CLI Package Install",
    description: "Install a local, reviewed bundled, or pinned Git-backed descriptor-backed Ambient CLI package into Ambient-owned workspace state.",
    promptSnippet: "ambient_cli_package_install: With approval, install a local, reviewed bundled, or pinned Git-backed Ambient CLI package that declares skills and commands.",
    promptGuidelines: [
      "Use ambient_cli_package_install when the user asks Ambient to install a local CLI skill package.",
      "For reviewed first-party bundled packages, use the exact bundled:<package-name> source, for example bundled:ambient-tinystyler.",
      "Do not use this tool as the primary path for user-generated capabilities. For create/build/add capability requests, use the Capability Builder plan/scaffold/preview/validate/register flow instead.",
      "For Git sources, include sha and optional path; unpinned Git installs are not supported.",
      "Only descriptor-backed packages with ambient-cli.json or package.json ambient.cli are executable.",
      "For reviewed upstream packages that only ship SKILL.md, pass a descriptor overlay and summarize it before install approval.",
      "Set installDependencies only after confirming the package uses an npm package-lock; Ambient runs npm ci --ignore-scripts in the copied package.",
      "Descriptor health checks may use timeoutProfile, progressPatterns, and devicePolicy metadata; do not force CPU when a descriptor-managed device policy recommends MPS/CUDA.",
      "This tool copies package files into Ambient-owned workspace state and mounts declared skills on the next Pi session refresh.",
      "This is the approved route for agent skill packages; avoid raw writes to ~/.agents/skills, ~/.codex/skills, or ~/.ambient/skills unless the user explicitly approved a scoped direct path write.",
      "Do not use this tool for bare SKILL.md repositories without either a package descriptor or an explicit descriptor overlay.",
      "Do not use this tool in Planner Mode.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        source: { type: "string", description: "Workspace-local package directory, reviewed bundled:<package-name> source, or Git URL/path to copy into Ambient-managed CLI package state." },
        path: { type: "string", description: "Optional package subdirectory inside a Git repository." },
        ref: { type: "string", description: "Optional Git ref for preview context." },
        sha: { type: "string", description: "Pinned Git commit SHA. Required for Git-backed install." },
        descriptor: {
          type: "object",
          description: "Optional Ambient CLI descriptor overlay written into the copied package before health checks and registration.",
          additionalProperties: true,
        },
        installDependencies: {
          type: "boolean",
          description: "Whether to run npm ci --ignore-scripts in the copied package before health checks and registration.",
        },
      },
      required: ["source"],
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "write-workspace",
    permissionScope: "cli-package-install",
    supportsDryRun: false,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 1_200_000,
  },
  {
    name: "ambient_cli_package_install_pi_catalog",
    label: "Pi Catalog CLI Install",
    description: "Resolve a supported Pi catalog or npm package URL into a reviewed Ambient CLI adapter and install it.",
    promptSnippet: "ambient_cli_package_install_pi_catalog: With approval, install a supported Pi catalog package as an Ambient CLI package.",
    promptGuidelines: [
      "This is the preferred install path for supported first-party Pi catalog packages.",
      "Use ambient_cli_package_install_pi_catalog when the user gives a pi.dev package URL and asks Ambient to install or use it.",
      "This tool resolves the Pi catalog URL through npm metadata to a pinned Git repository and directory.",
      "Only packages with a reviewed first-party Ambient CLI adapter are installable; unsupported Pi extensions are rejected.",
      "Report the resolved repository, commit SHA, adapter commands, and security scan before or after requesting install approval.",
      "Descriptor health checks may use timeoutProfile, progressPatterns, and devicePolicy metadata during install.",
      "After install, use ambient_cli with the packageName and command names returned by this tool.",
      "Do not use this tool in Planner Mode.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        source: {
          type: "string",
          description: "Pi catalog URL, npm: package spec, or supported npm package name, for example https://pi.dev/packages/pi-arxiv?name=arxiv.",
        },
      },
      required: ["source"],
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "write-workspace",
    permissionScope: "cli-package-install",
    supportsDryRun: false,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 1_200_000,
  },
  {
    name: "ambient_cli_env_bind",
    label: "CLI Env Bind",
    description: "Bind a declared Ambient CLI package environment variable to a workspace-local secret file without exposing the value to Pi.",
    promptSnippet: "ambient_cli_env_bind: With approval, bind an installed Ambient CLI package env requirement to a workspace-local secret file.",
    promptGuidelines: [
      "Use ambient_cli_env_bind only for env variables declared by an installed Ambient CLI package.",
      "The file path must stay inside the workspace and should point at a user-provided ignored secret file.",
      "Never pass, print, summarize, or infer the secret value. This tool validates that the file exists and is non-empty.",
      "After binding, use ambient_cli normally; Desktop injects the secret into the child process.",
    ],
    workflowGuidance: ambientCliWorkflowGuidance,
    inputSchema: {
      type: "object",
      properties: {
        packageId: { type: "string", description: "Exact installed Ambient CLI package id." },
        packageName: { type: "string", description: "Installed Ambient CLI package name." },
        envName: { type: "string", description: "Declared environment variable name to bind." },
        filePath: { type: "string", description: "Workspace-local file path containing the secret value." },
      },
      required: ["envName", "filePath"],
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "write-workspace",
    permissionScope: "ambient-cli-env",
    supportsDryRun: false,
    supportsUndo: true,
    idempotency: "recommended",
    defaultTimeoutMs: 120_000,
  },
  {
    name: "ambient_cli_secret_request",
    label: "CLI Secret Request",
    description: "Ask Desktop to open a user-facing secret entry dialog for a declared Ambient CLI package env requirement.",
    promptSnippet: "ambient_cli_secret_request: Request a Desktop-owned secret entry dialog for a missing installed Ambient CLI env requirement.",
    promptGuidelines: [
      "Use ambient_cli_secret_request when ambient_cli reports a missing declared env requirement and the user has not provided a secret file path.",
      "Pass packageName or packageId plus envName. Do not ask the user to paste the secret into chat.",
      "This tool opens a Desktop dialog; Pi receives only whether the request was surfaced, never the secret value.",
      "After the user saves the secret, retry the original ambient_cli command.",
    ],
    workflowGuidance: ambientCliWorkflowGuidance,
    inputSchema: {
      type: "object",
      properties: {
        packageId: { type: "string", description: "Exact installed Ambient CLI package id." },
        packageName: { type: "string", description: "Installed Ambient CLI package name." },
        envName: { type: "string", description: "Declared environment variable name to request." },
      },
      required: ["envName"],
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "none",
    permissionScope: "ambient-cli-env",
    supportsDryRun: false,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 120_000,
  },
  {
    name: "ambient_cli_search",
    label: "CLI Capability Search",
    description: "Search installed Ambient CLI package capabilities before running a mediated CLI command.",
    promptSnippet: "ambient_cli_search: Search installed Ambient CLI package commands and skills by task, package, command, or domain.",
    promptGuidelines: [
      "Use ambient_cli_search when the user asks for a capability and the exact installed package and command are not already known.",
      "This tool searches installed Ambient CLI packages only; it does not install packages, search marketplaces, or run package code.",
      "After choosing a package, always call ambient_cli_describe before first execution. Do not go directly from ambient_cli_search to ambient_cli.",
      "For missing declared env requirements, use ambient_cli_secret_request or ambient_cli_env_bind before ambient_cli.",
    ],
    workflowGuidance: ambientCliWorkflowGuidance,
    inputSchema: {
      type: "object",
      properties: {
        query: { type: "string", description: "Search terms describing the desired installed CLI capability." },
        limit: { type: "number", description: "Maximum result count. Defaults to 8 and is capped by Desktop." },
        includeUnavailable: { type: "boolean", description: "Whether to include installed packages with descriptor or health errors." },
        kind: { type: "string", enum: ["any", "package", "skill", "command"], description: "Optional capability kind filter." },
        packageName: { type: "string", description: "Optional exact installed package name filter." },
        command: { type: "string", description: "Optional exact descriptor command name filter." },
      },
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "none",
    permissionScope: "ambient-cli-discovery",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 30_000,
  },
  {
    name: "ambient_cli_describe",
    label: "CLI Capability Describe",
    description: "Describe one installed Ambient CLI package with structured command metadata and optional bounded skill text.",
    promptSnippet: "ambient_cli_describe: Load command metadata and optional SKILL.md text for one installed Ambient CLI package before running ambient_cli.",
    promptGuidelines: [
      "Use ambient_cli_describe after ambient_cli_search selects a package and before first execution of that package.",
      "This tool is read-only and allowed in Planner Mode; it does not run package code, install packages, or read secret values.",
      "Pass packageName or packageId. Pass command when only one descriptor command is relevant.",
      "Set includeSkill=true only when the structured command metadata is not enough; Desktop bounds returned SKILL.md text.",
      "Use returned env guidance before ambient_cli when required env is missing.",
    ],
    workflowGuidance: ambientCliWorkflowGuidance,
    inputSchema: {
      type: "object",
      properties: {
        packageId: { type: "string", description: "Exact installed Ambient CLI package id." },
        packageName: { type: "string", description: "Installed Ambient CLI package name." },
        command: { type: "string", description: "Optional exact descriptor command name to narrow the description." },
        includeSkill: { type: "boolean", description: "Whether to include bounded raw SKILL.md text." },
        includeSummary: { type: "boolean", description: "Whether to include cached RLM summaries when available. Defaults to true." },
        maxSkillChars: { type: "number", description: "Maximum raw skill text characters when includeSkill is true. Desktop caps this value." },
      },
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "none",
    permissionScope: "ambient-cli-discovery",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 30_000,
  },
  {
    name: "ambient_cli",
    label: "Ambient CLI",
    description: "Run a command declared by an installed Ambient CLI package.",
    promptSnippet: "ambient_cli: Run an installed Ambient CLI package command with explicit package and command names.",
    promptGuidelines: [
      "Use ambient_cli only for commands declared by installed Ambient CLI packages.",
      "Call ambient_cli_search first unless the exact installed package and descriptor command are already known from this thread.",
      "Call ambient_cli_describe before first execution of a package in the thread. If ambient_cli returns a preflight-description result, no command was executed; read it and retry ambient_cli once only when execution is still appropriate.",
      "Always pass packageName or packageId and the descriptor command name.",
      "Arguments must be strings and cwd must stay within the descriptor cwd policy.",
      "Respect descriptor timeoutProfile, progressPatterns, and devicePolicy metadata returned by ambient_cli_describe; Desktop applies those fields during execution.",
      "For missing declared env requirements, use ambient_cli_env_bind first; never pass secret values or file contents to ambient_cli.",
      "Summarize stdout, stderr, command, cwd, duration, timeout profile, and device selection after execution.",
    ],
    workflowGuidance: ambientCliWorkflowGuidance,
    inputSchema: {
      type: "object",
      properties: {
        packageId: { type: "string", description: "Exact installed Ambient CLI package id." },
        packageName: { type: "string", description: "Installed Ambient CLI package name." },
        command: { type: "string", description: "Descriptor command name to run." },
        args: { type: "array", items: { type: "string" }, description: "Additional string arguments passed after descriptor args." },
        cwd: { type: "string", description: "Optional cwd relative to the descriptor cwd policy root." },
      },
      required: ["command"],
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "run-process",
    permissionScope: "ambient-cli",
    supportsDryRun: false,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 1_200_000,
  }
];
