import type { DesktopToolDescriptor } from "./desktopToolDescriptorTypes";
import { mediaAcquisitionWorkflowGuidelines } from "./desktopToolSharedWorkflowGuidance";

export const gitToolDescriptors: DesktopToolDescriptor[] = [
  {
    name: "ambient_git_status",
    label: "Ambient Git Status",
    description:
      "Read the active thread Git topology, including worktree ownership, branch state, dirty counts, and recommended next Git actions.",
    promptSnippet: "ambient_git_status: Read-only worktree-aware Git topology and next-action guidance.",
    promptGuidelines: [
      "Use this before committing, merging, pushing, or preparing a pull request when the current thread may be in a Git worktree.",
      "This tool is read-only and returns the active thread workspace, project root, current branch, dirty state, and known main worktree owner.",
      "Prefer Ambient Git tools over raw git shell commands for commit, finish-to-main, and push workflows unless the user explicitly requests manual Git commands.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        targetBranch: { type: "string", description: "Optional target integration branch. Defaults to main." },
      },
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "none",
    permissionScope: "git-read",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "required",
    defaultTimeoutMs: 8_000,
    runtimeSupport: ["chat"],
  },
  {
    name: "ambient_git_commit",
    label: "Ambient Git Commit",
    description: "Stage selected active-thread worktree changes and commit them with a typed, worktree-aware safety boundary.",
    promptSnippet: "ambient_git_commit: Commit active thread worktree changes; use paths or all=true with a clear commit message.",
    promptGuidelines: [
      "Use this when the user asks to commit the current thread's work.",
      "This tool commits inside the active thread worktree/workspace. It refuses shared project-root commits unless allowSharedWorkspace=true.",
      "Use all=true to stage all current thread worktree changes, or pass explicit relative paths. Do not pass absolute paths.",
      "If this tool reports blockers, address them before calling ambient_git_finish_to_main.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        message: { type: "string", description: "Commit message." },
        paths: { type: "array", items: { type: "string" }, description: "Workspace-relative paths to stage before committing." },
        all: { type: "boolean", description: "Stage all active thread workspace changes before committing." },
        dryRun: { type: "boolean", description: "Return the planned commit action without staging or committing." },
        allowSharedWorkspace: {
          type: "boolean",
          description: "Allow committing from the shared project root when no active thread worktree is in use.",
        },
      },
      required: ["message"],
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "write-workspace",
    permissionScope: "git-commit",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 60_000,
    runtimeSupport: ["chat"],
  },
  {
    name: "ambient_git_finish_to_main",
    label: "Ambient Git Finish To Main",
    description:
      "Merge a committed thread branch into main through the correct main-owning or managed integration worktree, run validation, and optionally push.",
    promptSnippet: "ambient_git_finish_to_main: Finish committed thread work into main with validation and optional push.",
    promptGuidelines: [
      "Use this when the user asks to merge thread work to main, push main, or finish the branch.",
      "Call ambient_git_commit first if the thread worktree still has local changes.",
      "Pass validationCommands for the smallest meaningful local checks. Push happens only after validation succeeds and push=true.",
      "Do not use raw git shell commands to locate the main-owning worktree unless this tool reports a blocker that explicitly requires manual investigation.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        targetBranch: { type: "string", description: "Target integration branch. Defaults to main." },
        validationCommands: {
          type: "array",
          items: { type: "string" },
          description: "Commands to run in the target worktree after merge and before push.",
        },
        push: { type: "boolean", description: "Push the target branch after validation succeeds." },
        mergeMessage: { type: "string", description: "Optional merge commit message." },
        integrationWorktreePath: { type: "string", description: "Optional managed integration worktree path inside the project root." },
      },
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "write-workspace",
    permissionScope: "git-finish-to-main",
    supportsDryRun: false,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 300_000,
    runtimeSupport: ["chat"],
  },
];

export const bashToolDescriptor: DesktopToolDescriptor = {
  name: "bash",
  label: "Bash",
  description: "Run shell commands in the active workspace through Ambient Desktop's tool runner.",
  promptSnippet: "bash: Run shell commands in the active workspace.",
  promptGuidelines: [
    "Use bash for deterministic workspace commands such as tests, builds, and file-system inspection.",
    "Prefer non-destructive commands and summarize important output before continuing.",
    "When creating task scratch files, drafts, feedback, scores, generated source, or intermediate artifacts, keep them inside the active workspace, such as .ambient/tmp/ or another workspace-relative path; do not use /tmp for user-task artifacts unless the user explicitly approves outside-workspace access.",
    "Use short timeout values only for quick probes. For first page loads, dev servers, installs, builds, or dependency repairs, allow enough time for compilation and inspect logs if a listening server returns no bytes.",
    "If a bash timeout says the process tree was killed with zero output bytes, do not keep retrying the same short timeout; check process state, server logs, runtime architecture, or rerun with a justified longer timeout.",
    "When reporting user-facing absolute local files such as Downloads, Desktop, or Documents results, format them as Markdown file links with file:// URLs, for example [Keynote Presentation(2).pptx](file:///Users/example/Downloads/Keynote%20Presentation(2).pptx), so Ambient Desktop can preview or open them.",
    "When bash writes an image, audio, or video artifact and the result says Ambient Desktop will attempt an inline media preview, include the artifact path and refer to the preview only if it is visibly present; do not claim inline media rendering is unsupported.",
  ],
  inputSchema: {
    type: "object",
    properties: {
      command: { type: "string", description: "Shell command to run." },
      timeout: {
        type: "number",
        description:
          "Optional command timeout in seconds. Use short values only for quick probes; use longer values for builds, installs, dev servers, and first page loads.",
      },
    },
    required: ["command"],
    additionalProperties: false,
  },
  source: "pi-builtin",
  sideEffects: "run-process",
  permissionScope: "shell",
  supportsDryRun: false,
  supportsUndo: false,
  idempotency: "not-supported",
  defaultTimeoutMs: 120_000,
};

export const asyncBashToolDescriptors: DesktopToolDescriptor[] = [
  {
    name: "bash_start",
    label: "Bash Start",
    description: "Start a detached shell command in the active workspace and return a pollable async job.",
    promptSnippet: "bash_start: Start a detached shell command and use bash_poll to inspect it later.",
    promptGuidelines: [
      "Use bash_start for commands that may run longer than one tool turn, such as builds, servers, migrations, or long diagnostics.",
      "Use bash_poll with wait_ms as the bounded wait primitive instead of asking for a separate sleep command.",
      "Pass yield_ms when a short initial output window is useful, then continue with since_seq/next_since_seq from bash_poll.",
      "Poll output is bounded; after the job exits, use file_read or long_context_process on returned artifact paths for exact large output.",
      "Prefer tty:false unless an interactive command specifically requires terminal behavior.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        cmd: { type: "string", description: "Shell command to start." },
        cwd: { type: "string", description: "Optional workspace-relative or absolute working directory." },
        yield_ms: { type: "number", description: "Optional initial wait for post-start output, capped by Ambient." },
        idle_timeout_ms: { type: "number", description: "Optional idle timeout reset by stdout/stderr activity." },
        tty: { type: "boolean", description: "Run through a PTY when terminal behavior is required. Defaults to false." },
      },
      required: ["cmd"],
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "run-process",
    permissionScope: "shell",
    supportsDryRun: false,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 15_000,
  },
  {
    name: "bash_poll",
    label: "Bash Poll",
    description: "Poll a detached bash job, optionally waiting briefly for new output or terminal status.",
    promptSnippet: "bash_poll: Poll async bash output by job_id and since_seq; wait_ms provides bounded sleeping.",
    promptGuidelines: [
      "Use bash_poll to check running bash_start jobs and to wait for bounded intervals with wait_ms.",
      "Carry next_since_seq forward as since_seq to avoid re-reading the same output.",
      "Keep max_bytes bounded; use returned artifact paths after terminal status for exact large output.",
      "If the job is still running and user-visible progress is needed later, schedule a thread_wake_schedule continuation.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        job_id: { type: "string", description: "Job id returned by bash_start." },
        since_seq: { type: "number", description: "Only return events after this sequence number. Defaults to 0." },
        wait_ms: { type: "number", description: "Optional bounded wait for new output/status before returning." },
        max_bytes: { type: "number", description: "Maximum bytes of event/output preview to return." },
      },
      required: ["job_id"],
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "none",
    permissionScope: "shell",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "recommended",
    defaultTimeoutMs: 35_000,
  },
  {
    name: "bash_write",
    label: "Bash Write",
    description: "Write stdin to a running detached bash job and return an updated snapshot.",
    promptSnippet: "bash_write: Send stdin to a running async bash job.",
    promptGuidelines: [
      "Use bash_write only for jobs that are intentionally waiting for stdin.",
      "Do not send secrets through bash_write unless the user explicitly requested that workflow and the command is trusted.",
      "Use wait_ms to wait briefly for output caused by the write.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        job_id: { type: "string", description: "Job id returned by bash_start." },
        chars: { type: "string", description: "Characters to write to stdin." },
        wait_ms: { type: "number", description: "Optional bounded wait for output after writing." },
      },
      required: ["job_id", "chars"],
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "run-process",
    permissionScope: "shell",
    supportsDryRun: false,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 35_000,
  },
  {
    name: "bash_cancel",
    label: "Bash Cancel",
    description: "Cancel a running detached bash job and return its latest snapshot.",
    promptSnippet: "bash_cancel: Terminate an async bash job by job_id.",
    promptGuidelines: [
      "Use bash_cancel when an async command is no longer needed, appears stuck, or the user asks to stop it.",
      "Report whether cancellation completed or is still escalating based on the returned status.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        job_id: { type: "string", description: "Job id returned by bash_start." },
        reason: { type: "string", description: "Optional cancellation reason for the transcript." },
      },
      required: ["job_id"],
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "run-process",
    permissionScope: "shell",
    supportsDryRun: false,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 10_000,
  },
  {
    name: "thread_wake_schedule",
    label: "Thread Wake Schedule",
    description: "Schedule this Ambient thread to wake later with a follow-up continuation.",
    promptSnippet:
      "thread_wake_schedule: Schedule this thread to continue later, optionally tied to an async bash or async long-context job.",
    promptGuidelines: [
      "Use thread_wake_schedule when a running async job should be checked after the current turn ends.",
      "Include job_id for async job check-ins so the continuation receives the latest available job snapshot.",
      'For async long-context check-ins, include payload {"job_kind":"long_context"}; omitted job_kind keeps legacy async bash behavior.',
      "Use operation_key for a logical check-in stream. A new pending wake with the same operation key supersedes older pending wakes for this thread.",
      "Prefer short, concrete reasons that explain what the continuation should inspect.",
      "Do not use this as a general sleep command inside a running turn; use bash_poll wait_ms for bounded waits.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        after_ms: { type: "number", description: "Delay from now in milliseconds." },
        at: { type: "string", description: "Absolute ISO timestamp. Used when after_ms is absent." },
        reason: { type: "string", description: "Reason and instruction for the wake continuation." },
        job_id: { type: "string", description: "Optional async job id to include in the continuation." },
        operation_key: {
          type: "string",
          description: "Optional stable logical operation key. Pending wakes with the same key in this thread are superseded.",
        },
        payload: { type: "object", description: "Optional small structured payload for the continuation." },
      },
      required: ["reason"],
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "write-workspace",
    permissionScope: "thread-continuation",
    supportsDryRun: false,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 10_000,
  },
  {
    name: "thread_wake_cancel",
    label: "Thread Wake Cancel",
    description: "Cancel a pending scheduled wake for this Ambient thread.",
    promptSnippet: "thread_wake_cancel: Cancel a pending wake_id in the active thread.",
    promptGuidelines: [
      "Use thread_wake_cancel when a pending scheduled continuation is no longer needed.",
      "This tool is scoped to the active thread; do not use it for wake IDs from other threads.",
      "Prefer thread_wake_resolve when the wake's underlying work completed successfully before delivery.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        wake_id: { type: "string", description: "Pending wake id returned by thread_wake_schedule." },
      },
      required: ["wake_id"],
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "write-workspace",
    permissionScope: "thread-continuation",
    supportsDryRun: false,
    supportsUndo: false,
    idempotency: "recommended",
    defaultTimeoutMs: 10_000,
  },
  {
    name: "thread_wake_resolve",
    label: "Thread Wake Resolve",
    description: "Mark a pending scheduled wake in this Ambient thread as resolved without starting a continuation turn.",
    promptSnippet: "thread_wake_resolve: Resolve a pending wake_id in the active thread when the check-in is no longer needed.",
    promptGuidelines: [
      "Use thread_wake_resolve when the condition the wake would check has already been handled.",
      "Include a short reason explaining why no continuation is needed.",
      "This tool is scoped to the active thread; do not use it for wake IDs from other threads.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        wake_id: { type: "string", description: "Pending wake id returned by thread_wake_schedule." },
        reason: { type: "string", description: "Optional reason for resolving this wake." },
      },
      required: ["wake_id"],
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "write-workspace",
    permissionScope: "thread-continuation",
    supportsDryRun: false,
    supportsUndo: false,
    idempotency: "recommended",
    defaultTimeoutMs: 10_000,
  },
];

export const fileToolDescriptors: DesktopToolDescriptor[] = [
  {
    name: "file_read",
    label: "File Read",
    description: "Read a UTF-8 text file, PDF with extractable text, or supported Office document inside the active workspace.",
    promptSnippet: "file_read: Read a UTF-8 text file, PDF, or supported .docx/.pptx/.xlsx Office document inside the active workspace.",
    promptGuidelines: [
      "Use file_read for deterministic file inspection before planning edits.",
      "For .pdf files, file_read returns extracted plain text in content plus PDF metadata; if a PDF is scanned or image-only, the PDF metadata says no extractable text.",
      "For .docx, .pptx, and .xlsx files, file_read returns extracted plain text in content plus Office metadata.",
      "Use long_context_process for summarization, extraction, or QA over long PDFs, Office documents, decks, and spreadsheets.",
      "Do not use file_read for arbitrary binary files or secrets unless the user explicitly asked.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        path: { type: "string", description: "Workspace-relative path to read." },
      },
      required: ["path"],
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "none",
    permissionScope: "workspace-file-read",
    supportsDryRun: false,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 10_000,
  },
  {
    name: "local_directory_list",
    label: "Local Directory List",
    description:
      "List bounded metadata for a user-approved local directory such as Downloads, Desktop, or Documents without reading file contents.",
    promptSnippet:
      "local_directory_list: List file/folder names, types, extensions, sizes, and mtimes for a local directory after approval.",
    promptGuidelines: [
      "Use local_directory_list when the user explicitly asks to inspect a local folder outside the active workspace, such as ~/Downloads, ~/Desktop, or ~/Documents.",
      "This tool returns metadata only. Use local_file_read for selected text files, PDFs, or supported Office documents when contents are necessary.",
      "The result includes skipped metadata for hidden, secret-like, or unreadable paths. Preserve skipped counts/reasons in reports without reading or exposing file contents.",
      "Keep maxEntries and maxDepth bounded. Prefer maxDepth: 1 for broad categorization tasks.",
      "Do not use Google Drive tools for local filesystem folders named Downloads, Desktop, or Documents unless the user explicitly asks for Google Drive.",
    ],
    workflowGuidance: [
      {
        id: "local-directory-skipped-metadata",
        summary: "Directory inventory workflows preserve skipped-entry coverage metadata without reading skipped contents.",
        text: 'Local-directory workflow guidance: use tool.call with tool:"local_directory_list" for explicit local Downloads/Desktop/Documents folder inventories; do not substitute connector.call workspace.inventory.listFiles. local_directory_list returns exactly these coverage handles: listNode.entries, listNode.skipped, listNode.truncated, listNode.totalKnownEntries, listNode.rootPath, and listNode.rootName. Do not invent files, skippedFiles, or truncatedOrTotal paths. When any workflow step consumes {"fromHandle":"listNode.entries"} for inventory, categorization, reporting, or synthesis, preserve {"fromHandle":"listNode.skipped"}, {"fromHandle":"listNode.truncated"}, and {"fromHandle":"listNode.totalKnownEntries"} from the same result as separate fields in checkpoint.write, model.call input, document.render input, and output.final. Report skipped counts and reasons as metadata only, and never read or expose skipped file contents.',
        applicabilityTags: ["local_directory_list", "directory-inventory", "skipped-metadata", "coverage", "local-filesystem"],
        risk: "high",
        validatorRefs: ["validateWorkflowProgramStatic", "audit.local_directory_skipped_metadata_required"],
      },
    ],
    inputSchema: {
      type: "object",
      properties: {
        path: { type: "string", description: "Local directory path, for example ~/Downloads or /Users/name/Downloads." },
        maxEntries: { type: "number", description: "Maximum directory entries to return, capped at 500. Defaults to 200." },
        maxDepth: { type: "number", description: "Maximum directory depth to inspect, capped at 4. Defaults to 1." },
        includeHidden: { type: "boolean", description: "Whether to include hidden dotfiles. Defaults to false." },
      },
      required: ["path"],
      additionalProperties: false,
    },
    outputSchema: {
      type: "object",
      properties: {
        rootPath: { type: "string" },
        rootName: { type: "string" },
        entries: { type: "array" },
        truncated: { type: "boolean" },
        totalKnownEntries: { type: "number" },
        skipped: { type: "array" },
      },
      required: ["rootPath", "rootName", "entries", "truncated", "totalKnownEntries"],
      additionalProperties: true,
    },
    source: "first-party",
    sideEffects: "read-external",
    permissionScope: "local-directory-read",
    supportsDryRun: false,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 10_000,
  },
  {
    name: "local_file_read",
    label: "Local File Read",
    description:
      "Read a user-approved local UTF-8 text file, PDF with extractable text, or supported Office document outside or inside the active workspace.",
    promptSnippet: "local_file_read: Read a local text file, PDF, or supported .docx/.pptx/.xlsx Office document after approval.",
    promptGuidelines: [
      "Use local_file_read only after local_directory_list or the user provides an explicit local path.",
      "For .pdf files, local_file_read returns extracted plain text in content plus PDF metadata; if a PDF is scanned or image-only, the PDF metadata says no extractable text.",
      "For .docx, .pptx, and .xlsx files, local_file_read returns extracted plain text in content plus Office metadata.",
      "Use local_file_read selectively; do not bulk-read an entire personal directory when filenames and metadata are sufficient.",
      "Do not read secret-like paths or hidden files unless the user explicitly asks and approves the access.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        path: { type: "string", description: "Local file path, for example ~/Downloads/notes.md or /Users/name/Downloads/notes.md." },
      },
      required: ["path"],
      additionalProperties: false,
    },
    outputSchema: {
      type: "object",
      properties: {
        path: { type: "string" },
        absolutePath: { type: "string" },
        fileUrl: { type: "string" },
        content: { type: "string" },
        truncated: { type: "boolean" },
        kind: { type: "string" },
        language: { type: "string" },
        size: { type: "number" },
        mtimeMs: { type: "number" },
        pdfText: { type: "object" },
        officeText: { type: "object" },
      },
      required: ["path", "absolutePath", "content", "truncated", "kind"],
      additionalProperties: true,
    },
    source: "first-party",
    sideEffects: "read-external",
    permissionScope: "local-file-read",
    supportsDryRun: false,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 10_000,
  },
  {
    name: "file_write",
    label: "File Write",
    description: "Write UTF-8 text to a file inside the active workspace.",
    promptSnippet: "file_write: Write UTF-8 text to a file inside the active workspace.",
    promptGuidelines: [
      "Use file_write only inside workflow.stageMutation or after explicit approval for the staged file change.",
      "Prefer writing complete deterministic file content over incremental ad hoc edits.",
    ],
    workflowGuidance: [
      {
        id: "file-write-staged-mutation",
        summary: "Workspace file writes are staged mutations with approval-bound execution.",
        text: "File write workflow guidance: use file_write only as mutation.stage with a clear changeSet so Desktop stages the workspace write for explicit approval. Do not emit raw tool.call file_write, do not add approval.required after mutation.stage, and do not use file_write when it is absent from selected capabilities.",
        applicabilityTags: ["file_write", "mutation.stage", "staged-write", "approval"],
        risk: "high",
        validatorRefs: [
          "validateWorkflowProgramStatic",
          "dryRunWorkflowProgramOutput",
          "ir.mutation_stage_required",
          "ir.unavailable_tool",
        ],
      },
    ],
    inputSchema: {
      type: "object",
      properties: {
        path: { type: "string", description: "Workspace-relative path to write." },
        content: { type: "string", description: "UTF-8 text content to write." },
      },
      required: ["path", "content"],
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "write-workspace",
    permissionScope: "workspace-file-write",
    supportsDryRun: false,
    supportsUndo: false,
    idempotency: "recommended",
    defaultTimeoutMs: 10_000,
  },
];

export const mediaToolDescriptors: DesktopToolDescriptor[] = [
  {
    name: "media_download",
    label: "Media Download",
    description: "Download a remote image into the workspace only after validating HTTP status, MIME type, size, and image bytes.",
    promptSnippet:
      "media_download: Download and validate a remote image into a workspace artifact that Ambient Desktop can preview inline.",
    promptGuidelines: [
      ...mediaAcquisitionWorkflowGuidelines,
      "Use media_download instead of bash/curl for routine remote image downloads.",
      "Pass a direct candidate image URL and a workspace-relative outputPath such as bunny.jpg or media/bunny.png.",
      "The first version supports expectedKind=image only and rejects HTML redirects, error pages, empty bodies, oversized responses, and unsupported image bytes before writing the artifact.",
      "If the result says Ambient Desktop will attempt an inline media preview, stop downloading alternatives unless the user asked for more options.",
      "In the final answer, include the artifact path and refer to the preview only if it is visibly present; do not claim inline image display is unsupported.",
      "Use sourceUrl and licenseNote for lightweight source/license metadata, but do not overclaim license status when the source is uncertain.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        url: { type: "string", description: "Direct http(s) candidate image URL to download and validate." },
        outputPath: { type: "string", description: "Workspace-relative image artifact path to write after validation." },
        expectedKind: {
          type: "string",
          enum: ["image"],
          description: "Expected media kind. The first implementation supports image only.",
        },
        sourceUrl: { type: "string", description: "Optional source page URL for metadata and attribution context." },
        licenseNote: { type: "string", description: "Optional concise license/source note. Do not invent license claims." },
      },
      required: ["url", "outputPath"],
      additionalProperties: false,
    },
    outputSchema: {
      type: "object",
      properties: {
        artifactPath: { type: "string" },
        mediaKind: { type: "string", enum: ["image"] },
        mimeType: { type: "string" },
        bytes: { type: "number" },
        width: { type: "number" },
        height: { type: "number" },
        sourceUrl: { type: "string" },
        licenseNote: { type: "string" },
        inlinePreviewEligible: { type: "boolean" },
        renderedInline: { type: "boolean" },
        displayInstruction: { type: "string" },
        metadataPath: { type: "string" },
      },
      required: ["artifactPath", "mediaKind", "mimeType", "bytes", "inlinePreviewEligible", "displayInstruction", "metadataPath"],
      additionalProperties: true,
    },
    source: "first-party",
    sideEffects: "write-workspace",
    permissionScope: "media-download",
    supportsDryRun: false,
    supportsUndo: false,
    idempotency: "recommended",
    defaultTimeoutMs: 60_000,
    runtimeSupport: ["chat"],
  },
];
