import { miniCpmRemoteEndpointReviewChecklistText } from "../../shared/miniCpmRemoteEndpointSecurity";
import type { DesktopToolDescriptor } from "./desktopToolDescriptorTypes";

export const voiceToolDescriptors: DesktopToolDescriptor[] = [
  {
    name: "ambient_voice_status",
    label: "Ambient Voice Status",
    description: "Inspect Ambient Desktop voice settings and installed TTS voice providers.",
    promptSnippet: "ambient_voice_status: Inspect current voice settings and installed selectable voice providers.",
    promptGuidelines: [
      "Call ambient_voice_status before changing Ambient voice provider, voice, format, enablement, autoplay, mode, long-reply, or max-character settings.",
      "Use the exact providerCapabilityId and voiceId values returned by this tool when calling ambient_voice_select.",
      "Use preferredVoice/default voice metadata from this output when the user asks to switch back to a provider without naming a specific voice.",
      "Voice cloning metadata is informational only; do not attempt cloning through provider CLIs, browser, shell, or cloud APIs during ordinary voice setup or selection.",
      "Use ambient_voice_policy_update, not ambient_voice_select, for voice policy changes such as enable/disable, autoplay, mode, long-reply behavior, or max spoken characters.",
      "Use this tool to answer questions about the current voice provider or installed voice providers.",
      "For requests like 'switch to Piper', 'use ElevenLabs', 'change the voice to Amy', or 'turn voice off', first call ambient_voice_status, then call the relevant voice settings tool if a change is needed.",
      "Do not tell the user to open Settings when Ambient voice settings tools are available.",
      "Do not run provider CLIs, shell commands, install, repair, or register packages merely to inspect current voice selection.",
    ],
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "none",
    permissionScope: "voice-settings-read",
    supportsDryRun: false,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 10_000,
    runtimeSupport: ["chat"],
  },
  {
    name: "ambient_voice_select",
    label: "Ambient Voice Select",
    description: "With approval, switch Ambient Desktop's selected voice provider or voice using installed provider metadata.",
    promptSnippet: "ambient_voice_select: With approval, switch Ambient Desktop's selected voice provider or voice.",
    promptGuidelines: [
      "Call ambient_voice_status first and pass exact providerCapabilityId and voiceId values from its output whenever possible.",
      "Use ambient_voice_select only when the user explicitly asks to switch provider, switch voice, or change voice output format.",
      "When switching providers and the user does not specify a voice, Ambient will reuse that provider's remembered default voice when available.",
      "Use ambient_voice_policy_update, not this tool, to enable or disable voice, change autoplay, change mode, change long-reply behavior, or change max spoken characters.",
      "For 'switch to Piper' or another installed provider, select that installed provider; do not start provider onboarding, repair, validation, registration, or Ambient CLI execution.",
      "For 'switch voice to Amy' or another declared voice, keep the current provider unless the requested voice uniquely belongs to a different installed provider.",
      "If a provider or voice name is ambiguous, ask a concise clarification instead of guessing.",
      "Do not install, repair, register, run ambient_cli, use shell, or instruct the user to open Settings merely to switch the selected voice provider or voice.",
      "This tool changes Ambient core voice settings; TTS providers still only synthesize audio and do not control chat voice policy.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        providerCapabilityId: { type: "string", description: "Exact provider capability id from ambient_voice_status." },
        providerAlias: { type: "string", description: "Optional natural provider alias. Use only if it uniquely resolves." },
        voiceId: { type: "string", description: "Exact voice id from ambient_voice_status for the selected provider." },
        voiceAlias: {
          type: "string",
          description: "Optional natural voice alias. Use only if it uniquely resolves for the selected provider.",
        },
        format: {
          type: "string",
          enum: ["mp3", "wav", "ogg"],
          description: "Optional output format; must be supported by the selected provider.",
        },
        reason: { type: "string", description: "Short reason to show in the approval card." },
      },
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "write-workspace",
    permissionScope: "voice-settings-write",
    supportsDryRun: false,
    supportsUndo: false,
    idempotency: "recommended",
    defaultTimeoutMs: 15_000,
    runtimeSupport: ["chat"],
  },
  {
    name: "ambient_voice_list_voices",
    label: "Ambient Voice List Voices",
    description: "Search declared and cached dynamic voices for an installed Ambient voice provider.",
    promptSnippet: "ambient_voice_list_voices: Search installed provider voices without dumping large voice catalogs into context.",
    promptGuidelines: [
      "Call ambient_voice_status first so you know installed provider capability ids and whether a provider supports dynamic discovery.",
      "Use ambient_voice_list_voices when the user asks for voices by name, locale, language, style, gender, or a provider has too many voices for ambient_voice_status.",
      "Pass exact providerCapabilityId from ambient_voice_status whenever more than one provider is installed.",
      "Use query, locale, language, style, and limit to keep results bounded.",
      "If cacheStatus is none or stale and the desired voice is not found, explain that a voice catalog refresh is needed; do not call provider CLIs, shell, browser, or ambient_cli directly.",
      "Use ambient_voice_select only after resolving an exact voiceId from this tool or ambient_voice_status.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        providerCapabilityId: { type: "string", description: "Exact provider capability id from ambient_voice_status." },
        query: {
          type: "string",
          description: "Optional text query matching id, label, description, locale, language, gender, style, or preview text.",
        },
        locale: { type: "string", description: "Optional exact locale filter such as en-US." },
        language: { type: "string", description: "Optional exact language filter such as English." },
        style: { type: "string", description: "Optional style/tag filter such as narration, warm, conversational, or British." },
        limit: { type: "number", description: "Maximum voices to return, 1-50. Defaults to 12." },
        includeStale: { type: "boolean", description: "Include stale cached dynamic voices if the cache is expired." },
      },
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "none",
    permissionScope: "voice-settings-read",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 10_000,
    runtimeSupport: ["chat"],
  },
  {
    name: "ambient_voice_refresh_voices",
    label: "Ambient Voice Refresh Voices",
    description: "With approval when needed, refresh cached dynamic voices for an installed Ambient voice provider.",
    promptSnippet: "ambient_voice_refresh_voices: Refresh a provider voice catalog through Ambient's controlled voice discovery runner.",
    promptGuidelines: [
      "Call ambient_voice_status first and pass the exact providerCapabilityId for a provider that declares dynamic voice discovery.",
      "Use ambient_voice_refresh_voices when ambient_voice_list_voices reports cacheStatus none or stale, or when the user explicitly asks to refresh provider voices.",
      "For cloud/API providers this may make a small provider API call and requires approval; explain that before calling when user intent is ambiguous.",
      "Do not call provider CLIs, shell, browser, or ambient_cli directly to list provider voices; use this tool so Ambient can preserve artifacts, approvals, and cache metadata.",
      "After a successful refresh, call ambient_voice_list_voices with query, locale, language, style, and limit filters to find exact voice ids.",
      "This tool only refreshes voice catalog metadata; use ambient_voice_select to change the selected provider or voice.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        providerCapabilityId: { type: "string", description: "Exact provider capability id from ambient_voice_status." },
        reason: { type: "string", description: "Short reason to show in the approval card for cloud/network refreshes." },
      },
      required: ["providerCapabilityId"],
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "run-process",
    permissionScope: "voice-catalog-refresh",
    supportsDryRun: false,
    supportsUndo: false,
    idempotency: "recommended",
    defaultTimeoutMs: 60_000,
    runtimeSupport: ["chat"],
  },
  {
    name: "ambient_voice_clone_plan",
    label: "Ambient Voice Clone Plan",
    description: "Read-only planning for voice cloning support on an installed Ambient voice provider.",
    promptSnippet:
      "ambient_voice_clone_plan: Explain whether a provider supports voice cloning and what consent, files, secrets, privacy, cost, and output requirements apply.",
    promptGuidelines: [
      "Call ambient_voice_status first so you know installed provider capability ids and selected provider state.",
      "Use ambient_voice_clone_plan when the user asks whether voice cloning is supported, how cloning would work, what files are needed, or what risks/costs apply.",
      "This tool is read-only. It does not upload audio, create cloned voices, train models, call provider APIs, or run provider CLIs.",
      "Do not use shell, browser, ambient_cli, or provider-specific commands to create or inspect cloning state from this planning step.",
      "Before any future clone creation, require explicit user confirmation that they have rights and consent for all source audio.",
      "Source audio for cloning must be user-selected workspace files or Ambient artifacts, not pasted chat blobs or hidden recordings.",
      "For cloud cloning, explain network upload, provider privacy/retention, required secrets, and potential costs.",
      "For local cloning, explain model assets, runtime, storage, and hardware-fit implications.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        providerCapabilityId: {
          type: "string",
          description: "Exact provider capability id from ambient_voice_status. Defaults to the selected provider when omitted.",
        },
        providerAlias: { type: "string", description: "Optional natural provider alias. Use only if it uniquely resolves." },
      },
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "none",
    permissionScope: "voice-settings-read",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 10_000,
    runtimeSupport: ["chat"],
  },
  {
    name: "ambient_voice_clone_create_preview",
    label: "Ambient Voice Clone Create Preview",
    description:
      "Validate source audio references and consent for a future voice clone creation approval without creating or uploading a clone.",
    promptSnippet:
      "ambient_voice_clone_create_preview: Validate user-selected source audio files and consent for a future voice clone create request, without uploading audio or creating a voice.",
    promptGuidelines: [
      "Call ambient_voice_clone_plan first so the user sees provider cloning requirements and guardrails.",
      "Use this tool only after the user has selected workspace audio files or Ambient artifact paths and explicitly confirmed they have rights and consent for those samples.",
      "Pass workspace-relative sourceAudioFiles only. Do not pass pasted audio data, URLs, hidden recordings, or paths outside the workspace.",
      "This tool is a preview. It validates files and consent but does not upload audio, create cloned voices, train models, run provider CLIs, or call cloud APIs.",
      "If readyForCreateApproval is true, summarize the preview and ask whether the user wants to proceed with a future approval-gated clone creation workflow.",
      "If validation fails, ask for corrected files or consent instead of attempting clone creation.",
      "Do not use shell, browser, ambient_cli, or provider-specific commands to bypass this preview.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        providerCapabilityId: {
          type: "string",
          description: "Exact provider capability id from ambient_voice_status. Defaults to the selected provider when omitted.",
        },
        providerAlias: { type: "string", description: "Optional natural provider alias. Use only if it uniquely resolves." },
        sourceAudioFiles: {
          type: "array",
          items: { type: "string" },
          description: "Workspace-relative audio file paths selected by the user for cloning.",
        },
        consentConfirmed: {
          type: "boolean",
          description: "True only when the user explicitly confirms they have rights and consent for every source audio sample.",
        },
        cloneName: { type: "string", description: "Optional user-visible name for the future cloned voice." },
        notes: { type: "string", description: "Optional user-visible notes about intended voice use." },
      },
      required: ["sourceAudioFiles", "consentConfirmed"],
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "none",
    permissionScope: "voice-clone-preview",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 10_000,
    runtimeSupport: ["chat"],
  },
  {
    name: "ambient_voice_clone_create",
    label: "Ambient Voice Clone Create",
    description: "With approval, create a cloned voice through a reviewed installed Ambient voice provider implementation.",
    promptSnippet:
      "ambient_voice_clone_create: After preview and approval, create a cloned voice through Ambient's reviewed provider workflow.",
    promptGuidelines: [
      "Call ambient_voice_clone_plan first, then ambient_voice_clone_create_preview with the same provider, source files, consent, and clone name.",
      "Use this tool only when ambient_voice_clone_create_preview returned readyForCreateApproval true and the user explicitly asked to proceed.",
      "Pass the same workspace-relative sourceAudioFiles used in the preview. Do not pass pasted audio data, URLs, hidden recordings, or paths outside the workspace.",
      "This tool is approval-gated and may upload source audio for cloud providers or train/create local assets for local providers.",
      "Do not use shell, browser, ambient_cli, provider CLIs, or raw cloud APIs to create clones; Ambient owns approval, provider execution, cache update, and optional selection.",
      "If the provider does not declare a reviewed voiceCloning.createCommand, explain that the provider must be repaired/upgraded before clone creation.",
      "After success, use the returned exact voiceId for selection or testing. Do not invent cloned voice ids.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        providerCapabilityId: {
          type: "string",
          description: "Exact provider capability id from ambient_voice_status. Defaults to the selected provider when omitted.",
        },
        providerAlias: { type: "string", description: "Optional natural provider alias. Use only if it uniquely resolves." },
        sourceAudioFiles: {
          type: "array",
          items: { type: "string" },
          description: "Workspace-relative audio file paths selected by the user for cloning.",
        },
        consentConfirmed: {
          type: "boolean",
          description: "True only when the user explicitly confirms they have rights and consent for every source audio sample.",
        },
        cloneName: { type: "string", description: "User-visible name for the cloned voice." },
        notes: { type: "string", description: "Optional user-visible notes or description for the cloned voice." },
        selectCreatedVoice: { type: "boolean", description: "Whether to select the created voice for chat output after creation." },
        reason: { type: "string", description: "Short reason to show in the approval card." },
      },
      required: ["sourceAudioFiles", "consentConfirmed", "cloneName"],
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "run-process",
    permissionScope: "voice-clone-create",
    supportsDryRun: false,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 180_000,
    runtimeSupport: ["chat"],
  },
  {
    name: "ambient_voice_clone_status",
    label: "Ambient Voice Clone Status",
    description: "Read provider-side or cached status for a cloned voice through a reviewed Ambient voice provider workflow.",
    promptSnippet: "ambient_voice_clone_status: Check cloned voice status through Ambient's reviewed provider workflow.",
    promptGuidelines: [
      "Call ambient_voice_status first, then use an exact providerCapabilityId and voiceId.",
      "Use this tool when the user asks whether a cloned voice exists, is ready, requires verification, or is still processing.",
      "This tool is read-only. It must not create, delete, upload, train, or select a voice.",
      "If the result includes a provider dashboard or verification URL, mention it as an optional user-requested next step; do not open browser links automatically.",
      "If the provider does not declare a reviewed voiceCloning.statusCommand, report that status is only available from cached voice metadata or provider UI until the package is upgraded.",
      "Do not use shell, browser, ambient_cli, provider CLIs, or raw cloud APIs to bypass this first-party tool.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        providerCapabilityId: {
          type: "string",
          description: "Exact provider capability id from ambient_voice_status. Defaults to the selected provider when omitted.",
        },
        providerAlias: { type: "string", description: "Optional natural provider alias. Use only if it uniquely resolves." },
        voiceId: {
          type: "string",
          description: "Exact cloned voice id to check. Defaults to the selected voice when it belongs to the provider.",
        },
        voiceAlias: { type: "string", description: "Optional natural voice alias. Use only if it uniquely resolves." },
      },
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "run-process",
    permissionScope: "voice-clone-status",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "recommended",
    defaultTimeoutMs: 60_000,
    runtimeSupport: ["chat"],
  },
  {
    name: "ambient_voice_clone_delete",
    label: "Ambient Voice Clone Delete",
    description: "With approval, delete a cloned voice through a reviewed Ambient voice provider workflow.",
    promptSnippet:
      "ambient_voice_clone_delete: Delete a cloned voice through Ambient's reviewed provider workflow after explicit approval.",
    promptGuidelines: [
      "Call ambient_voice_status first, then use an exact providerCapabilityId and voiceId.",
      "Use this tool only when the user explicitly asks to delete/remove a cloned voice.",
      "This tool is approval-gated because deletion may permanently remove provider-side or local cloned voice assets.",
      "If the provider does not declare a reviewed voiceCloning.deleteCommand, explain that deletion must wait for a package upgrade instead of improvising with provider tools.",
      "After deletion, Ambient removes the voice from the dynamic voice cache and clears the selected voice if it was selected.",
      "Do not use shell, browser, ambient_cli, provider CLIs, or raw cloud APIs to bypass this first-party tool.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        providerCapabilityId: {
          type: "string",
          description: "Exact provider capability id from ambient_voice_status. Defaults to the selected provider when omitted.",
        },
        providerAlias: { type: "string", description: "Optional natural provider alias. Use only if it uniquely resolves." },
        voiceId: {
          type: "string",
          description: "Exact cloned voice id to delete. Defaults to the selected voice when it belongs to the provider.",
        },
        voiceAlias: { type: "string", description: "Optional natural voice alias. Use only if it uniquely resolves." },
        reason: { type: "string", description: "Short reason to show in the approval card." },
      },
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "run-process",
    permissionScope: "voice-clone-delete",
    supportsDryRun: false,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 60_000,
    runtimeSupport: ["chat"],
  },
  {
    name: "ambient_voice_policy_update",
    label: "Ambient Voice Policy Update",
    description: "With approval, update Ambient Desktop's core voice policy settings without switching providers.",
    promptSnippet:
      "ambient_voice_policy_update: With approval, update voice enablement, autoplay, mode, long-reply behavior, max spoken characters, or generated-audio cache size.",
    promptGuidelines: [
      "Call ambient_voice_status first so you know the current policy before changing it.",
      "Use ambient_voice_policy_update only when the user explicitly asks to enable voice, disable voice, change autoplay, change voice mode, change long-reply behavior, change max spoken characters, or change generated voice artifact cache size.",
      "Use ambient_voice_select, not this tool, for provider, voice, or output-format selection.",
      "Do not install, repair, register, run ambient_cli, use shell, or instruct the user to open Settings merely to update voice policy.",
      "Mode values are off, assistant-final, always, and tagged. Prefer assistant-final for normal chat readback unless the user asks otherwise.",
      "Long-reply values are summarize, skip, and ask. Use summarize when the user wants long answers spoken briefly, skip when they do not want long answers voiced, and ask when they want confirmation first.",
      "Set maxChars only when the user explicitly asks for a spoken-length cap or limit.",
      "Set artifactCacheMaxMb only when the user explicitly asks for a generated audio cache size limit. Use 0 to disable retaining generated voice audio.",
      "This tool changes Ambient core voice policy; TTS providers still only synthesize audio and do not control chat voice policy.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        enabled: { type: "boolean", description: "Enable or disable Ambient chat voice output." },
        autoplay: { type: "boolean", description: "Enable or disable automatic playback after synthesis." },
        mode: { type: "string", enum: ["off", "assistant-final", "always", "tagged"], description: "Core voice mode." },
        longReply: {
          type: "string",
          enum: ["summarize", "skip", "ask"],
          description: "What Ambient should do before voicing long replies.",
        },
        maxChars: { type: "number", description: "Maximum visible assistant characters to speak directly; integer from 100 to 10000." },
        artifactCacheMaxMb: {
          type: "number",
          description: "Maximum generated voice artifact cache size in MB; integer from 0 to 1024. Default is 30.",
        },
        reason: { type: "string", description: "Short reason to show in the approval card." },
      },
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "write-workspace",
    permissionScope: "voice-settings-write",
    supportsDryRun: false,
    supportsUndo: false,
    idempotency: "recommended",
    defaultTimeoutMs: 15_000,
    runtimeSupport: ["chat"],
  },
  {
    name: "ambient_voice_test",
    label: "Ambient Voice Test",
    description: "With approval, synthesize a tiny test phrase through the currently selected Ambient voice provider.",
    promptSnippet: "ambient_voice_test: With approval, test the currently selected Ambient voice provider through the core voice runtime.",
    promptGuidelines: [
      "Call ambient_voice_status first to confirm a selected, available provider before testing.",
      "Use ambient_voice_test when the user asks to verify, test, try, or confirm the selected voice provider works.",
      "If the user asks to switch and verify, call ambient_voice_select for the switch, then ambient_voice_test after the selection succeeds.",
      "Do not use ambient_cli, shell, provider CLIs, install, repair, validate, or register tools merely to test the selected chat voice provider.",
      "This test may run a local TTS provider or make a small cloud TTS request, so it requires approval.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        text: { type: "string", description: "Optional short phrase to synthesize. Keep it brief." },
        reason: { type: "string", description: "Short reason to show in the approval card." },
      },
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "run-process",
    permissionScope: "voice-provider-test",
    supportsDryRun: false,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 60_000,
    runtimeSupport: ["chat"],
  },
];

export const sttToolDescriptors: DesktopToolDescriptor[] = [
  {
    name: "ambient_stt_status",
    label: "Ambient STT Status",
    description: "Inspect Ambient Desktop speech input settings and installed STT providers.",
    promptSnippet: "ambient_stt_status: Inspect current speech input settings and installed selectable STT providers.",
    promptGuidelines: [
      "Call ambient_stt_status before changing Ambient speech input provider, spoken language, enablement, silence timing, no-speech gate, auto-send, shortcut, or queue policy.",
      "Use the exact providerCapabilityId values returned by this tool when calling ambient_stt_select.",
      "Use ambient_stt_select for provider or spoken-language selection.",
      "Use ambient_stt_policy_update for enablement, silence-before-transcribe, RMS no-speech gate, auto-send, push-to-talk shortcut, stop-TTS-on-speech, or queue-while-agent-runs policy.",
      "Use ambient_stt_test only with workspace-relative WAV artifact paths; do not pass raw audio bytes, base64 audio, hidden recordings, or URLs.",
      "Do not tell the user to open Settings when Ambient STT tools are available.",
      "Do not run provider CLIs, shell commands, install, repair, or register packages merely to inspect current STT selection.",
    ],
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "none",
    permissionScope: "stt-settings-read",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 10_000,
    runtimeSupport: ["chat"],
  },
  {
    name: "ambient_stt_select",
    label: "Ambient STT Select",
    description: "With approval, switch Ambient Desktop's selected speech input provider or spoken language.",
    promptSnippet: "ambient_stt_select: With approval, switch Ambient Desktop's selected STT provider or spoken language.",
    promptGuidelines: [
      "Call ambient_stt_status first and pass exact providerCapabilityId values from its output whenever possible.",
      "Use ambient_stt_select only when the user explicitly asks to switch speech input provider, choose Qwen3-ASR, change spoken language, or enable speech input as part of provider selection.",
      "Use ambient_stt_policy_update, not this tool, for silence-before-transcribe, no-speech gate, auto-send, shortcut, TTS barge-in, or queue policy changes.",
      "For 'use Qwen for speech' or another installed provider, select that installed provider; do not start provider onboarding, repair, validation, registration, or Ambient CLI execution.",
      "If a provider or language name is ambiguous, ask a concise clarification instead of guessing.",
      "Do not install, repair, register, run ambient_cli, use shell, or instruct the user to open Settings merely to switch the selected STT provider or language.",
      "This tool changes Ambient core speech input settings; STT providers still only transcribe audio and do not control chat submission policy.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        providerCapabilityId: { type: "string", description: "Exact provider capability id from ambient_stt_status." },
        providerAlias: { type: "string", description: "Optional natural provider alias. Use only if it uniquely resolves." },
        spokenLanguage: {
          type: "string",
          description: "Spoken language to transcribe, for example English, Spanish, Japanese, or French.",
        },
        enabled: { type: "boolean", description: "Optionally enable or disable speech input as part of the selection." },
        reason: { type: "string", description: "Short reason to show in the approval card." },
      },
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "write-workspace",
    permissionScope: "stt-settings-write",
    supportsDryRun: false,
    supportsUndo: false,
    idempotency: "recommended",
    defaultTimeoutMs: 15_000,
    runtimeSupport: ["chat"],
  },
  {
    name: "ambient_stt_policy_update",
    label: "Ambient STT Policy Update",
    description: "With approval, update Ambient Desktop speech input policy without switching providers.",
    promptSnippet:
      "ambient_stt_policy_update: With approval, update speech input enablement, silence, no-speech gate, auto-send, shortcut, or queue policy.",
    promptGuidelines: [
      "Call ambient_stt_status first so you know the current policy before changing it.",
      "Use ambient_stt_policy_update only when the user explicitly asks to enable or disable speech input, change spoken language without switching providers, change silence-before-transcribe, change RMS no-speech gate, change auto-send, configure shortcut, stop TTS on speech, or queue utterances while the agent runs.",
      "Use ambient_stt_select, not this tool, for provider selection.",
      "For push-to-talk, keep queueWhileAgentRuns true unless the user explicitly asks for different interruption semantics.",
      "Do not install, repair, register, run ambient_cli, use shell, or instruct the user to open Settings merely to update STT policy.",
      "This tool changes Ambient core speech input policy; STT providers still only transcribe audio and do not steer active agent requests.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        enabled: { type: "boolean", description: "Enable or disable Ambient speech input." },
        spokenLanguage: { type: "string", description: "Spoken language to transcribe without switching providers." },
        autoSendAfterTranscription: {
          type: "boolean",
          description: "Whether ready transcripts are sent automatically as visible user messages.",
        },
        silenceFinalizeSeconds: {
          type: "number",
          description: "Seconds of trailing silence before finalizing a recording, from 0.3 to 2.5.",
        },
        noSpeechGateEnabled: { type: "boolean", description: "Enable or disable RMS no-speech filtering before provider invocation." },
        noSpeechGateRmsThresholdDbfs: { type: "number", description: "RMS dBFS threshold for no-speech filtering, from -90 to -20." },
        stopTtsOnSpeech: { type: "boolean", description: "Whether new speech stops current TTS playback." },
        queueWhileAgentRuns: {
          type: "boolean",
          description: "Whether utterances recorded during an active agent run queue as later visible user turns.",
        },
        pushToTalkShortcut: { type: "string", description: "Canonical push-to-talk shortcut label to set." },
        clearPushToTalkShortcut: { type: "boolean", description: "Clear the configured push-to-talk shortcut." },
        reason: { type: "string", description: "Short reason to show in the approval card." },
      },
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "write-workspace",
    permissionScope: "stt-settings-write",
    supportsDryRun: false,
    supportsUndo: false,
    idempotency: "recommended",
    defaultTimeoutMs: 15_000,
    runtimeSupport: ["chat"],
  },
  {
    name: "ambient_stt_test",
    label: "Ambient STT Test",
    description: "With approval, transcribe a workspace-relative WAV artifact through the selected Ambient STT provider.",
    promptSnippet: "ambient_stt_test: With approval, test the selected Ambient STT provider using a workspace-relative WAV artifact.",
    promptGuidelines: [
      "Call ambient_stt_status first to confirm a selected, available provider before testing.",
      "Use ambient_stt_test when the user asks to verify, test, try, or confirm the selected speech input provider works.",
      "Pass audioPath only as a workspace-relative WAV file or managed Ambient STT artifact path. Do not pass raw audio bytes, base64 audio, URLs, or paths outside the workspace.",
      "If audioPath is omitted, Ambient may reuse the latest Settings microphone validation WAV artifact when one exists.",
      "If the user asks to switch and verify, call ambient_stt_select for the switch, then ambient_stt_test after selection succeeds.",
      "Do not use ambient_cli, shell, provider CLIs, install, repair, validate, or register tools merely to test the selected speech input provider.",
      "This test may run a local STT provider and access model assets, so it requires approval.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        audioPath: {
          type: "string",
          description: "Workspace-relative WAV artifact path. Omit only to reuse the latest Settings validation sample.",
        },
        spokenLanguage: { type: "string", description: "Optional spoken language override for this test." },
        reason: { type: "string", description: "Short reason to show in the approval card." },
      },
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "run-process",
    permissionScope: "stt-provider-test",
    supportsDryRun: false,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 120_000,
    runtimeSupport: ["chat"],
  },
];

const miniCpmVisionTaskSchema = {
  type: "string",
  enum: ["ui_review", "game_visual_review", "screenshot_ocr", "image_description", "design_comparison", "video_frame_review"],
};

const miniCpmVisionImageReferenceSchema = {
  type: "object",
  properties: {
    path: {
      type: "string",
      description:
        "Workspace-relative path from selected context, a browser_screenshot/media artifact path, or an approved absolute local path.",
    },
    absolute: {
      type: "boolean",
      description: "True only when the selected context path is an approved absolute local file path outside the workspace.",
    },
    source: {
      type: "string",
      enum: ["workspace_file", "browser_screenshot", "chat_attachment", "media_artifact", "selected_screenshot", "external_file"],
      description: "Optional source hint for audit text and prompt shaping.",
    },
    label: {
      type: "string",
      description: "Optional short label such as before, after, reference, current, or the attachment filename.",
    },
  },
  required: ["path"],
  additionalProperties: false,
};

const miniCpmVisionBrowserScreenshotReferenceSchema = {
  type: "object",
  properties: {
    ref: {
      type: "string",
      enum: ["latest"],
      description: "Use latest to analyze the most recent browser_screenshot artifact captured in this thread.",
    },
    artifactRef: {
      type: "string",
      enum: ["latest_browser_screenshot"],
      description: "Stable typed reference emitted by browser_screenshot visualEvidence metadata.",
    },
    label: {
      type: "string",
      description: "Optional short label for audit text.",
    },
  },
  additionalProperties: false,
};

const miniCpmVisionVideoReferenceSchema = {
  type: "object",
  properties: {
    path: {
      type: "string",
      description: "Workspace-relative video path, or an approved absolute local path when allowExternalMediaPaths is true.",
    },
    absolute: {
      type: "boolean",
      description: "True only when path is an approved absolute local path.",
    },
    source: {
      type: "string",
      enum: ["workspace_file", "chat_attachment", "media_artifact", "external_file"],
      description: "Optional video source hint for audit text and prompt shaping.",
    },
    label: {
      type: "string",
      description: "Optional short label such as clip, selected attachment, screen recording, or the filename.",
    },
    frameTimestampMs: {
      type: "number",
      description: "Optional frame timestamp in milliseconds, between 0 and 120000. Defaults to 1000ms.",
    },
  },
  required: ["path"],
  additionalProperties: false,
};

export const visionToolDescriptors: DesktopToolDescriptor[] = [
  {
    name: "ambient_visual_minicpm_setup",
    label: "MiniCPM-V Setup",
    description: "Install, repair, validate, stop, or uninstall Ambient Desktop's first-party MiniCPM-V visual-analysis provider.",
    promptSnippet:
      "ambient_visual_minicpm_setup: Install, validate, repair, stop, or uninstall the MiniCPM-V visual-analysis provider without raw ambient_cli commands.",
    promptGuidelines: [
      "Use this when the user asks to set up, repair, validate, stop, uninstall, clean up, or bind MiniCPM-V as an Ambient visual-understanding provider.",
      "When no endpointUrl, runtimeBinaryPath, or runtimeArchivePath is supplied for install/repair, Ambient may use the default managed runtime download for pinned macOS arm64/Linux x64 artifacts; Windows remains disabled.",
      "Use runtimeBinaryPath only for a user-approved local llama-server path when the user wants a user-managed runtime instead of Ambient's managed runtime.",
      "Use runtimeArchivePath only for a user-approved pinned llama.cpp archive; Ambient extracts it into .ambient/vision/minicpm-v/runtime, verifies archive and extracted-binary checksums, writes a receipt, and only then binds the workspace-owned llama-server.",
      "Read the returned runtimeContract and runtimeInstall before claiming support status; they record acquisition mode, cache ownership, preflight checks, default-download status, and manifestVerification.",
      `Use endpointUrl only for an explicitly approved already-running local OpenAI-compatible endpoint on localhost/127.0.0.1/[::1]. Remote endpoints are blocked until the MiniCPM-V hosted-endpoint security review covers ${miniCpmRemoteEndpointReviewChecklistText()}.`,
      "For endpointUrl setup, include validationImagePath when possible so Ambient validates /v1/models plus one redacted image request before claiming active state.",
      "Use validationImagePath only for workspace-relative images unless the user explicitly approved an outside-workspace path through Ambient.",
      "For action=stop, Ambient stops only the workspace-local managed daemon and preserves package install state, runtime cache, endpoint bindings, and external model caches. Treat stopped as healthy idle state.",
      "For action=uninstall, Ambient removes only the Ambient-installed MiniCPM-V package copy and managed workspace cache; user-managed llama-server binaries and external model caches are preserved.",
      "Do not use shell, ambient_cli_package_install, ambient_cli_env_bind, or raw MiniCPM package commands for routine MiniCPM-V setup when this tool is available.",
      "If setup returns needs-runtime, report the missing runtime guidance and stop rather than guessing install commands.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        action: {
          type: "string",
          enum: ["install", "repair", "validate", "stop", "uninstall"],
          description: "Setup action to perform. Defaults to install.",
        },
        installRuntime: {
          type: "boolean",
          description:
            "Optional. For install/repair, defaults to true and lets Ambient download the pinned macOS/Linux managed runtime when no explicit runtime source is supplied. Use false to validate/package setup without downloading.",
        },
        runtimeBinaryPath: {
          type: "string",
          description:
            "Optional approved local llama-server binary path to bind for MiniCPM-V. Do not combine with endpointUrl or runtimeArchivePath.",
        },
        runtimeArchivePath: {
          type: "string",
          description:
            "Optional approved local pinned llama.cpp archive to extract into Ambient's workspace-managed MiniCPM-V runtime cache. Do not combine with endpointUrl or runtimeBinaryPath.",
        },
        runtimeArtifactId: {
          type: "string",
          description:
            "Optional runtime manifest artifact id when runtimeArchivePath is provided, such as llama-cpp-macos-arm64-metal, llama-cpp-linux-x64-vulkan-nvidia, or llama-cpp-windows-x64-cpu. Defaults to the current platform lane.",
        },
        endpointUrl: {
          type: "string",
          description: `Optional approved local endpoint origin such as http://127.0.0.1:39217 for an already-running MiniCPM-compatible server. Do not combine with runtimeBinaryPath or runtimeArchivePath. Remote endpoints remain blocked until security review covers ${miniCpmRemoteEndpointReviewChecklistText()}.`,
        },
        validationImagePath: {
          type: "string",
          description: "Optional workspace-relative image path to analyze as setup validation.",
        },
        validationTask: miniCpmVisionTaskSchema,
        validationPrompt: {
          type: "string",
          description:
            "Optional task prompt override for validation. Prefer built-in task presets unless the user asks a specific visual question.",
        },
      },
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "run-process",
    permissionScope: "visual-provider-setup",
    supportsDryRun: false,
    supportsUndo: false,
    idempotency: "recommended",
    defaultTimeoutMs: 360_000,
    runtimeSupport: ["chat", "workflow"],
  },
  {
    name: "ambient_visual_analyze",
    label: "Visual Analyze",
    description:
      "Analyze a workspace screenshot, approved local image, or sampled short-video frame through the first-party MiniCPM-V visual provider.",
    promptSnippet:
      "ambient_visual_analyze: Inspect a local screenshot, image, or sampled video frame with MiniCPM-V and return structured visual observations.",
    promptGuidelines: [
      "Use this when the user asks what is visible in a screenshot/image/video frame, wants UI or game visual QA, asks for screenshot OCR, or asks to compare visible design quality.",
      'After browser_screenshot in the same thread, prefer browserScreenshot:{ref:"latest"} or browserScreenshot:{artifactRef:"latest_browser_screenshot"} instead of retyping timestamped screenshot artifact paths.',
      "Pass image.path for selected context, chat attachments, browser_screenshot results, media_download results, and other media artifacts when that structured path is available; imagePath remains accepted for a plain workspace-relative path.",
      "Pass video.path or videoPath for a short local video or screen-recording clip when the user asks for frame-level video inspection; Ambient will sample one frame locally and send only that extracted PNG frame to MiniCPM-V.",
      "Set video.frameTimestampMs or frameTimestampMs when the user identified a relevant moment; otherwise let Ambient sample the default 1000ms frame and mark motion conclusions as uncertain.",
      "For before/after or reference/current visual comparisons, pass the current image as image or imagePath and the baseline as referenceImage or referenceImagePath, then set task to design_comparison.",
      `Pass endpointUrl only when the user explicitly approved an already-running local endpoint. Do not pass remote endpoints; they remain blocked until the MiniCPM-V hosted-endpoint review covers ${miniCpmRemoteEndpointReviewChecklistText()}. Do not ask Ambient to start or stop a user-managed endpoint.`,
      "Set allowExternalMediaPaths=true only when the user explicitly approved reading a local image or video outside the workspace; Ambient will copy it into managed workspace storage first.",
      "Choose the closest task preset instead of writing a long custom prompt. Use prompt only for a targeted user question.",
      "Use the returned observations and limitations as evidence. Do not claim MiniCPM-V inspected anything outside the supplied image, comparison pair, or sampled frame.",
      "Do not call ambient_cli_search, ambient_cli_describe, ambient_cli, shell, or provider package commands merely to analyze a visual input when this first-party tool is available.",
      "Do not add ambient_visual_minicpm_setup nodes for ordinary image, screenshot, OCR, or video-frame analysis. Use setup only when the user explicitly asks to install, validate, repair, uninstall, or bind the MiniCPM-V provider.",
      "Do not create workflow nodes for MiniCPM-V status, start, stop, or daemon cleanup. The ambient_visual_analyze tool owns provider startup, health checks, retries, and cleanup boundaries for ordinary analysis workflows.",
    ],
    workflowGuidance: [
      {
        id: "visual-analysis-required",
        summary: "Visual workflows use MiniCPM-V evidence instead of filename-only or metadata-only synthesis.",
        text: "Visual-analysis workflow guidance: when the user asks to inspect, categorize, classify, compare, OCR, or summarize images, screenshots, or video frames, collect actual visual evidence with ambient_visual_analyze. Do not substitute model.call over filenames, folder metadata, or guessed descriptions for the visual inspection step. Do not create ambient_cli nodes for minicpm_vision_status, minicpm_vision_start, minicpm_vision_analyze, minicpm_vision_stop, or any ambient-minicpm package command; ambient_visual_analyze is the workflow tool for ordinary visual analysis and owns provider lifecycle internally.",
        applicabilityTags: ["ambient_visual_analyze", "visual-evidence", "image-classification", "ocr", "screenshot-qa"],
        risk: "high",
        validatorRefs: ["workflow visual dogfood gates"],
      },
      {
        id: "visual-loop-map-tool-call-shape",
        summary: "Batch visual analysis uses bounded loop.map tool fan-out over a concrete array output path.",
        text: 'Visual loop-map workflow guidance: for multiple local images, list the folder with local_directory_list, select bounded image entries, then use loop.map with items referencing a declared array handle such as {"fromHandle":"listImages.entries"} or {"fromHandle":"selectVisibleImages.items"}. Do not use a whole-node reference such as {"fromNode":"list-images"} for item fan-out, and do not wrap the reference in a one-element array. The nested map should be {"kind":"tool.call","tool":"ambient_visual_analyze","args":{"image":{"path":{"fromItem":"item","path":"absolutePath"},"absolute":true,"source":"external_file","label":{"fromItem":"item","path":"name"}},"task":"image_description","allowExternalMediaPaths":true}} with explicit maxItems and maxConcurrency at 4 unless a lower value is needed.',
        applicabilityTags: ["ambient_visual_analyze", "loop.map", "local_directory_list", "batch-visual-analysis"],
        risk: "high",
        validatorRefs: ["validateWorkflowProgramStatic"],
      },
      {
        id: "visual-model-role",
        summary: "After visual evidence collection, the selected Ambient model synthesizes the observations.",
        text: "Visual synthesis workflow guidance: after ambient_visual_analyze returns bounded observations, use the selected Ambient Desktop model with model.call, model.map, or model.reduce to categorize or synthesize that evidence. Do not ask the user to choose a random cloud or local LLM provider inside the generated workflow.",
        applicabilityTags: ["ambient_visual_analyze", "model.call", "model.reduce", "visual-synthesis"],
        risk: "medium",
        validatorRefs: [],
      },
    ],
    inputSchema: {
      type: "object",
      properties: {
        imagePath: {
          type: "string",
          description:
            "Backward-compatible workspace-relative image path, or an approved absolute local path when allowExternalImagePaths is true.",
        },
        image: {
          ...miniCpmVisionImageReferenceSchema,
          description: "Structured primary image reference from selected context, browser_screenshot, media artifact, or chat attachment.",
        },
        browserScreenshot: {
          ...miniCpmVisionBrowserScreenshotReferenceSchema,
          description:
            "Stable reference to the most recent browser_screenshot artifact captured in this thread. Prefer this over copying timestamped artifact paths from browser_screenshot text.",
        },
        videoPath: {
          type: "string",
          description:
            "Workspace-relative video path to sample into one frame, or an approved absolute local path when allowExternalMediaPaths is true.",
        },
        video: {
          ...miniCpmVisionVideoReferenceSchema,
          description:
            "Structured short-video reference from a chat attachment, media artifact, or workspace file. Ambient extracts one PNG frame before MiniCPM-V analysis.",
        },
        frameTimestampMs: {
          type: "number",
          description: "Optional frame timestamp in milliseconds for videoPath/video inputs. Defaults to 1000ms.",
        },
        referenceImagePath: {
          type: "string",
          description:
            "Optional baseline/reference image for design comparison. Prefer referenceImage when selected context metadata is available.",
        },
        referenceImage: {
          ...miniCpmVisionImageReferenceSchema,
          description: "Structured baseline/reference image for design comparison.",
        },
        task: miniCpmVisionTaskSchema,
        prompt: {
          type: "string",
          description:
            "Optional targeted visual question or review prompt. Prefer task presets for routine UI/game/OCR/image description work.",
        },
        outputJsonPath: {
          type: "string",
          description: "Optional workspace-relative JSON artifact path. Omit to let Ambient choose a managed path.",
        },
        endpointUrl: {
          type: "string",
          description: `Optional approved local endpoint origin for an already-running MiniCPM-compatible server. Remote endpoint URLs are rejected until security review covers ${miniCpmRemoteEndpointReviewChecklistText()}.`,
        },
        allowExternalImagePaths: {
          type: "boolean",
          description:
            "Backward-compatible image-only external read approval. Prefer allowExternalMediaPaths for new image or video inputs.",
        },
        allowExternalMediaPaths: {
          type: "boolean",
          description:
            "Allow Ambient to copy an approved outside-workspace local image or video into managed workspace storage before analysis.",
        },
        offline: {
          type: "boolean",
          description: "Run llama.cpp in offline mode. Use when model assets are already cached.",
        },
        maxTokens: {
          type: "number",
          description: "Optional MiniCPM response token cap. Defaults to the provider preset.",
        },
      },
      additionalProperties: false,
    },
    outputSchema: {
      type: "object",
      properties: {
        summary: { type: "string" },
        observations: {
          type: "array",
          items: {
            type: "object",
            properties: {
              kind: { type: "string" },
              description: { type: "string" },
              confidence: { type: "string" },
              evidence: { type: "string" },
            },
            required: ["kind", "description", "confidence", "evidence"],
            additionalProperties: false,
          },
        },
        limitations: { type: "array", items: { type: "string" } },
        artifacts: {
          type: "object",
          properties: { jsonPath: { type: "string" } },
          required: ["jsonPath"],
          additionalProperties: true,
        },
      },
      required: ["summary", "observations", "limitations", "artifacts"],
      additionalProperties: true,
    },
    source: "first-party",
    sideEffects: "run-process",
    permissionScope: "visual-analysis",
    supportsDryRun: false,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 360_000,
    runtimeSupport: ["chat", "workflow"],
  },
];

export const localDeepResearchToolDescriptors: DesktopToolDescriptor[] = [
  {
    name: "ambient_local_deep_research_provider_status",
    label: "Local Deep Research Provider Status",
    description: "Inspect Ambient's configured Local Deep Research provider stack and active top provider.",
    promptSnippet:
      "ambient_local_deep_research_provider_status: Inspect configured Local Deep Research providers and the active top provider.",
    promptGuidelines: [
      "Call this when the user asks which Local Deep Research provider is active or whether the Open Book path should route through LiteResearcher or another configured provider.",
      "Only the top enabled provider in the research order is active for the next run.",
      "If the user asks about a provider absent from this status, call ambient_local_deep_research_provider_search or ambient_local_deep_research_provider_describe before saying whether Ambient knows or can add it.",
    ],
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "none",
    permissionScope: "local-deep-research-routing",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "required",
    defaultTimeoutMs: 30_000,
    runtimeSupport: ["chat"],
  },
  {
    name: "ambient_local_deep_research_provider_search",
    label: "Local Deep Research Provider Search",
    description: "Search configured and known addable Local Deep Research providers without dumping all provider cards into context.",
    promptSnippet:
      "ambient_local_deep_research_provider_search: Search configured and known addable Local Deep Research providers before claiming support or installability.",
    promptGuidelines: [
      "Call this when the user asks whether Ambient has, recommends, can add, or can prioritize a local deep research provider.",
      "Use ambient_local_deep_research_provider_describe for an exact provider before recommending setup or preference changes.",
      "Known-addable provider cards are not necessarily installed or runnable; they need their own setup validation before they can be made active.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        query: { type: "string", description: "Provider name, id, model, package, secret, or host to search for." },
        limit: { type: "number", description: "Maximum configured and known-addable providers per section, 1-25." },
      },
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "none",
    permissionScope: "local-deep-research-routing",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "required",
    defaultTimeoutMs: 30_000,
    runtimeSupport: ["chat"],
  },
  {
    name: "ambient_local_deep_research_provider_describe",
    label: "Local Deep Research Provider Describe",
    description: "Describe one configured or known addable Local Deep Research provider, including active order and setup guidance.",
    promptSnippet:
      "ambient_local_deep_research_provider_describe: Describe a Local Deep Research provider before claiming whether it is active, configured, addable, or should be prioritized.",
    promptGuidelines: [
      "Call this with a provider name or id before changing Local Deep Research provider order.",
      "If the provider is configured, ambient_local_deep_research_provider_update can make it top priority or set the complete order.",
      "If the provider is known-addable, use provider catalog/setup planning first; do not make it active until it is configured and validated.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        provider: { type: "string", description: "Provider name, id, model, package, secret, or host." },
        limit: { type: "number", description: "Maximum nearby matches per section when there is no exact match, 1-25." },
      },
      required: ["provider"],
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "none",
    permissionScope: "local-deep-research-routing",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "required",
    defaultTimeoutMs: 30_000,
    runtimeSupport: ["chat"],
  },
  {
    name: "ambient_local_deep_research_provider_update",
    label: "Local Deep Research Provider Update",
    description: "Persistently update Ambient's global Local Deep Research provider order with approval.",
    promptSnippet:
      "ambient_local_deep_research_provider_update: With approval, persistently set, prefer, reset, or configure Ambient's Local Deep Research provider.",
    promptGuidelines: [
      "Call ambient_local_deep_research_provider_status first and pass an exact configured provider id whenever possible.",
      "Use action=prefer_provider to make one configured provider top priority. Use action=set_order only when the user asks for a specific complete ordering.",
      "Use action=set_final_synthesis to configure whether the provider returns a local final answer or a synthesis-ready evidence packet for a parent/cloud model to finish.",
      "Use action=reset_defaults to make LiteResearcher the default active provider again.",
      "Do not use this to install unknown providers or store secrets. Known-addable providers need setup and validation first.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        action: {
          type: "string",
          enum: ["set_order", "prefer_provider", "reset_defaults", "set_final_synthesis"],
          description: "Persistent provider action. Defaults from supplied fields.",
        },
        providerOrder: {
          type: "array",
          items: { type: "string" },
          description: "Complete ordered configured provider ids or labels for action=set_order.",
        },
        providerId: { type: "string", description: "Exact configured provider id for action=prefer_provider." },
        providerAlias: { type: "string", description: "Configured provider alias when providerId is not known." },
        preferredProvider: { type: "string", description: "Compatibility alias for providerId/providerAlias." },
        finalSynthesisMode: {
          type: "string",
          enum: ["local", "evidence_only"],
          description:
            "For action=set_final_synthesis. local returns a repaired local final answer; evidence_only returns a synthesis-ready evidence packet for the parent/provider to finish.",
        },
        mode: {
          type: "string",
          enum: ["local", "evidence_only"],
          description: "Compatibility alias for finalSynthesisMode.",
        },
        sourceLimit: {
          type: "number",
          description: "For evidence packets and repair prompts, maximum observed source URLs to surface. Defaults to 12.",
        },
        evidencePreviewChars: {
          type: "number",
          description: "For evidence packets and no-tools synthesis fallback, per-tool evidence preview characters. Defaults to 1200.",
        },
        reason: { type: "string", description: "User-facing reason for the persistent order change." },
      },
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "write-workspace",
    permissionScope: "local-deep-research-routing",
    supportsDryRun: false,
    supportsUndo: true,
    idempotency: "recommended",
    defaultTimeoutMs: 30_000,
    runtimeSupport: ["chat"],
  },
  {
    name: "ambient_local_deep_research_setup",
    label: "Local Deep Research Setup",
    description:
      "Inspect, install, repair, or smoke test Ambient Desktop's first-party Local Deep Research readiness contract for LiteResearcher, shared llama.cpp runtime status, model profile selection, and current web research provider routing.",
    promptSnippet:
      "ambient_local_deep_research_setup: Read, install, repair, validate, or smoke test the Local Deep Research setup/readiness contract before claiming LiteResearcher support, validating, or starting research.",
    promptGuidelines: [
      "Use this before setting up, validating, diagnosing, or starting first-party Local Deep Research with LiteResearcher.",
      "Use action=status for a read-only readiness check. Use action=install or action=repair only when the user asks to set up or repair Local Deep Research. Use action=validate for setup/provider checks. Use action=smoke only after the user wants real local model/runtime proof or validation evidence.",
      "For install/repair, first read installerShape: it declares the local-model installer shape, selected model family/profile/quant, expected disk, memory fit, runtime artifact, loopback server-port policy, progress event, cancellation, logs, cleanup, and smoke-test contract.",
      "For install/repair/smoke, Ambient requires user approval in workspace mode before multi-GB model downloads or lease-managed llama-server launches; Power User full-access mode records the usual audit and proceeds.",
      "For install/repair, Ambient downloads the selected LiteResearcher GGUF into managed state and reuses the shared llama.cpp runtime managed download/extract path after approval.",
      "For validate, Ambient checks managed assets, provider routing, Q8 override policy, and the provider-preference product smoke, then writes JSON validation evidence.",
      "For smoke, Ambient launches the managed LiteResearcher GGUF through the shared llama.cpp runtime, sends a tiny local chat request, and writes JSON/Markdown smoke evidence.",
      "Read modelSelection, modelInstall, llamaRuntime, installerShape, managedAssets, providerSnapshot, blockers, warnings, and nextActions before telling the user what is ready or missing.",
      "Pass q8Override=true only when the user explicitly asks to try or prefer Q8 on a machine that may not default to Q8.",
      "Do not use raw shell, ambient_cli, Ollama, or upstream LiteResearcher Serper/Scrape.do setup for this first-party path.",
      "Provider routing is captured from current Ambient Search & Web preferences at call time; if the user changes preferred search or scrape providers, call this tool again before the next research run.",
      "If setup returns needs-install after install/repair, describe the returned installResult and nextActions instead of inventing install commands.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        action: {
          type: "string",
          enum: ["status", "install", "repair", "validate", "smoke"],
          description:
            "Read, install, repair, validate, or real-asset smoke test the Local Deep Research setup/readiness contract. Defaults to status.",
        },
        q8Override: {
          type: "boolean",
          description: "Advanced override. Request the Q8 LiteResearcher profile when deterministic memory policy allows or warns.",
        },
      },
      additionalProperties: false,
    },
    outputSchema: {
      type: "object",
      properties: {
        capabilityId: { type: "string" },
        setupStatus: { type: "string", enum: ["ready", "needs-install", "blocked"] },
        modelSelection: { type: "object" },
        modelInstall: { type: "object" },
        llamaRuntime: { type: "object" },
        installerShape: { type: "object" },
        managedAssets: { type: "object" },
        installResult: { type: "object" },
        validation: { type: "object" },
        smoke: { type: "object" },
        providerSnapshot: { type: "object" },
        warnings: { type: "array" },
        blockers: { type: "array" },
        nextActions: { type: "array" },
      },
      required: [
        "capabilityId",
        "setupStatus",
        "modelSelection",
        "modelInstall",
        "llamaRuntime",
        "installerShape",
        "managedAssets",
        "providerSnapshot",
        "warnings",
        "blockers",
        "nextActions",
      ],
      additionalProperties: true,
    },
    source: "first-party",
    sideEffects: "run-process",
    permissionScope: "local-deep-research-setup",
    supportsDryRun: false,
    supportsUndo: false,
    idempotency: "recommended",
    defaultTimeoutMs: 900_000,
    runtimeSupport: ["chat", "workflow"],
  },
  {
    name: "ambient_local_deep_research_run",
    label: "Local Deep Research Run",
    description:
      "Run Ambient Desktop's first-party Local Deep Research capability with LiteResearcher, the managed llama.cpp runtime, and the current Ambient web research provider stack.",
    promptSnippet:
      "ambient_local_deep_research_run: Run Local Deep Research for source-heavy public-web synthesis after setup reports ready.",
    promptGuidelines: [
      "Use this for substantial public-web research when the user wants a local first-party research path.",
      "Call ambient_local_deep_research_setup first when readiness is uncertain; this run tool also refreshes the setup/provider snapshot at run start.",
      "The run uses current Ambient Search & Web preferences for search and fetch. If preferences change, the next run captures the new provider snapshot.",
      "The active provider's final synthesis mode is captured at run start. Pass finalSynthesisMode only for a one-run override.",
      "Do not ask LiteResearcher to use Serper, Scrape.do, Ollama, raw shell, or arbitrary external plugins. Ambient brokers all search/fetch calls.",
      "Expect artifacts to include the final report, model profile, provider snapshot, tool calls, provider attempts, and llama-server diagnostics.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        question: {
          type: "string",
          description: "The research question or synthesis task.",
        },
        q8Override: {
          type: "boolean",
          description: "Advanced override. Request Q8 when deterministic memory policy allows or warns.",
        },
        maxToolCalls: {
          type: "number",
          description: "Optional bounded search/fetch tool-call budget. Defaults to 12.",
        },
        localResearchBudget: {
          type: "object",
          description: "Optional run-scoped Local Deep Research budget contract from the composer effort selector.",
          properties: {
            schemaVersion: {
              type: "string",
              enum: ["ambient-local-deep-research-run-budget-v1"],
            },
            enabled: {
              type: "boolean",
              description: "Always true for an active Local Deep Research composer run.",
            },
            effort: {
              type: "string",
              enum: ["quick", "balanced", "deep", "exhaustive", "custom"],
            },
            maxToolCalls: {
              type: "number",
              description: "Resolved search/fetch tool-call cap for this run.",
            },
            source: {
              type: "string",
              enum: ["user_default", "run_override", "tool_input"],
            },
            onExhausted: {
              type: "string",
              enum: ["summarize", "ask_to_continue"],
            },
          },
          required: ["schemaVersion", "enabled", "effort", "maxToolCalls", "source", "onExhausted"],
          additionalProperties: false,
        },
        maxTurns: {
          type: "number",
          description:
            "Optional bounded model turn budget. Ambient normalizes this upward to preserve the 3-turn final synthesis reserve, so tool intensity still controls only search/fetch calls.",
        },
        finalSynthesisMode: {
          type: "string",
          enum: ["local", "evidence_only"],
          description:
            "Optional one-run override. local returns a repaired local final answer; evidence_only returns a synthesis-ready evidence packet.",
        },
      },
      required: ["question"],
      additionalProperties: false,
    },
    outputSchema: {
      type: "object",
      properties: {
        capabilityId: { type: "string" },
        status: { type: "string" },
        setupStatus: { type: "string" },
        modelProfileId: { type: "string" },
        contextTokens: { type: "number" },
        providerSnapshot: { type: "object" },
        localResearchBudget: { type: "object" },
        finalSynthesisReserveTurns: { type: "number" },
        toolBudget: { type: "object" },
        toolExecutions: { type: "array" },
        finalText: { type: "string" },
        error: { type: "string" },
        artifacts: { type: "object" },
        llamaServer: { type: "object" },
      },
      required: ["capabilityId", "status", "setupStatus", "providerSnapshot"],
      additionalProperties: true,
    },
    source: "first-party",
    sideEffects: "run-process",
    permissionScope: "local-deep-research-run",
    supportsDryRun: false,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 900_000,
    runtimeSupport: ["chat", "workflow"],
  },
];

export const localRuntimeToolDescriptors: DesktopToolDescriptor[] = [
  {
    name: "ambient_local_model_runtime_status",
    label: "Local Model Runtime Status",
    description:
      "Inspect Ambient's live local model runtime inventory, memory policy, active owner leases, stop blockers, and untracked local model processes.",
    promptSnippet:
      "ambient_local_model_runtime_status: Read-only local model runtime inventory for managed, tracked, and untracked local model processes.",
    promptGuidelines: [
      "Use this before diagnosing local model memory, runtime ownership, sub-agent local model usage, or whether a local runtime can be stopped safely.",
      "This tool is read-only. It does not stop, restart, unload, adopt, or kill any process.",
      "Treat active sub-agent leases as ordinary Stop blockers. If forceTerminationRequiresSubagentCancellation is true, explain that forced termination must explicitly cancel or mark the owning sub-agent first.",
      "Treat untracked processes as visible diagnostics only. Do not claim Ambient can safely stop an untracked process.",
      "Read memoryPolicy, activeLeases, entries, owners, and stopDecision before recommending local model launch, stop, restart, or cleanup actions.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        includeStopped: {
          type: "boolean",
          description:
            "Include known stopped runtime state rows when available. Defaults to false so the status focuses on live residency.",
        },
        limit: {
          type: "number",
          description: "Maximum runtime rows to include in the text preview, 1-50. Structured details include the full snapshot.",
        },
      },
      additionalProperties: false,
    },
    outputSchema: {
      type: "object",
      properties: {
        schemaVersion: { type: "string" },
        capturedAt: { type: "string" },
        summary: { type: "object" },
        inventory: { type: "object" },
        registry: { type: "object" },
      },
      required: ["schemaVersion", "capturedAt", "summary", "inventory", "registry"],
      additionalProperties: true,
    },
    source: "first-party",
    sideEffects: "none",
    permissionScope: "local-model-runtime-status",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "required",
    defaultTimeoutMs: 30_000,
    runtimeSupport: ["chat", "workflow"],
  },
  {
    name: "ambient_local_model_runtime_start",
    label: "Local Model Runtime Start",
    description:
      "Start an Ambient-managed or provider-declared stopped local model runtime when the shared runtime inventory says ordinary Load is allowed.",
    promptSnippet:
      "ambient_local_model_runtime_start: Start a managed stopped local model runtime or provider-declared runtime after checking inventory lifecycleDecision.load, active leases, and tracking status.",
    promptGuidelines: [
      "Call ambient_local_model_runtime_status with includeStopped=true first or use a runtimeId from a recent status result that includes stopped rows.",
      "This tool starts managed stopped local-text rows or non-text local runtime rows that expose providerLifecycle.start. It does not install providers, create new model profiles, or adopt untracked processes.",
      "Ordinary Start is blocked when the runtime is already running, untracked, lacks provider-declared lifecycle controls, or active sub-agent leases own the runtime.",
      "Use dryRun=true to verify that a stopped runtime can be started without launching a process.",
      "Report the returned memoryPolicy and runtime memory evidence when explaining Start readiness or blockers.",
      "If Start is blocked, report the lifecycleDecision.load reason and owning sub-agent labels instead of trying shell commands.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        runtimeId: {
          type: "string",
          description: "Runtime target id from inventory.entries[].modelRuntimeId or entries[].id.",
        },
        dryRun: {
          type: "boolean",
          description: "Check whether Start would be allowed without launching anything.",
        },
      },
      required: ["runtimeId"],
      additionalProperties: false,
    },
    outputSchema: {
      type: "object",
      properties: {
        status: { type: "string" },
        result: { type: "object" },
        before: { type: "object" },
        after: { type: "object" },
      },
      required: ["status", "result", "before"],
      additionalProperties: true,
    },
    source: "first-party",
    sideEffects: "run-process",
    permissionScope: "local-model-runtime-start",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "required",
    defaultTimeoutMs: 30_000,
    runtimeSupport: ["chat", "workflow"],
  },
  {
    name: "ambient_local_model_runtime_stop",
    label: "Local Model Runtime Stop",
    description:
      "Stop an Ambient-managed or provider-declared local model runtime when the shared runtime inventory says ordinary Stop is allowed.",
    promptSnippet:
      "ambient_local_model_runtime_stop: Stop a managed local model runtime or provider-declared runtime after checking inventory stopDecision, active leases, and tracking status.",
    promptGuidelines: [
      "Call ambient_local_model_runtime_status first or use a runtimeId from a recent status result.",
      "This tool stops managed local-text rows or non-text local runtime rows that expose providerLifecycle.stop. It does not uninstall models, delete caches, or stop untracked processes.",
      "Ordinary Stop is blocked when active sub-agent leases own the runtime. Do not use force to silently kill a child-owned model; forced termination requires explicit child cancellation or failure marking first.",
      "Use dryRun=true to verify that a runtime can be stopped without terminating the process.",
      "Report the returned memoryPolicy and runtime memory evidence when explaining Stop readiness or blockers.",
      "If Stop is blocked, report the stopDecision reason and owning sub-agent labels instead of trying shell commands.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        runtimeId: {
          type: "string",
          description: "Runtime target id from inventory.entries[].modelRuntimeId or entries[].id.",
        },
        force: {
          type: "boolean",
          description: "Explicit forced-stop request. Active sub-agent leases still block until their child runs are cancelled or marked.",
        },
        dryRun: {
          type: "boolean",
          description: "Check whether Stop would be allowed without stopping anything.",
        },
      },
      required: ["runtimeId"],
      additionalProperties: false,
    },
    outputSchema: {
      type: "object",
      properties: {
        status: { type: "string" },
        result: { type: "object" },
        before: { type: "object" },
        after: { type: "object" },
      },
      required: ["status", "result", "before"],
      additionalProperties: true,
    },
    source: "first-party",
    sideEffects: "run-process",
    permissionScope: "local-model-runtime-stop",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "required",
    defaultTimeoutMs: 30_000,
    runtimeSupport: ["chat", "workflow"],
  },
  {
    name: "ambient_local_model_runtime_restart",
    label: "Local Model Runtime Restart",
    description:
      "Restart an Ambient-managed or provider-declared local model runtime when the shared runtime inventory says ordinary lifecycle control is allowed.",
    promptSnippet:
      "ambient_local_model_runtime_restart: Restart a managed local model runtime or provider-declared runtime after checking inventory stopDecision, active leases, and tracking status.",
    promptGuidelines: [
      "Call ambient_local_model_runtime_status first or use a runtimeId from a recent status result.",
      "This tool restarts managed local-text rows or non-text local runtime rows that expose providerLifecycle.restart. It does not install providers, create new model profiles, or restart untracked processes.",
      "Ordinary Restart is blocked when active sub-agent leases own the runtime. Do not use force to silently kill a child-owned model; forced termination requires explicit child cancellation or failure marking first.",
      "Use dryRun=true to verify that a runtime can be restarted without stopping or launching anything.",
      "Report the returned memoryPolicy and runtime memory evidence when explaining Restart readiness or blockers.",
      "If Restart is blocked, report the stopDecision reason and owning sub-agent labels instead of trying shell commands.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        runtimeId: {
          type: "string",
          description: "Runtime target id from inventory.entries[].modelRuntimeId or entries[].id.",
        },
        force: {
          type: "boolean",
          description:
            "Explicit forced-restart request. Active sub-agent leases still block until their child runs are cancelled or marked.",
        },
        dryRun: {
          type: "boolean",
          description: "Check whether Restart would be allowed without changing processes.",
        },
      },
      required: ["runtimeId"],
      additionalProperties: false,
    },
    outputSchema: {
      type: "object",
      properties: {
        status: { type: "string" },
        result: { type: "object" },
        before: { type: "object" },
        after: { type: "object" },
      },
      required: ["status", "result", "before"],
      additionalProperties: true,
    },
    source: "first-party",
    sideEffects: "run-process",
    permissionScope: "local-model-runtime-restart",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "required",
    defaultTimeoutMs: 30_000,
    runtimeSupport: ["chat", "workflow"],
  },
];

export const managedDownloadToolDescriptors: DesktopToolDescriptor[] = [
  {
    name: "ambient_download_start",
    label: "Managed Download Start",
    description:
      "Start an Ambient-managed background download with bounded destination paths, resumable .part files, Range retry support, and optional size/checksum validation.",
    promptSnippet:
      "ambient_download_start: Start a managed background download instead of using shell/curl for large files, archives, models, datasets, or installers.",
    promptGuidelines: [
      "Use this instead of shell, curl, wget, or custom download scripts when a user-approved task needs a large file, archive, model, dataset, or installer fetched into the workspace or Ambient-managed install state.",
      "Pass destinationKind=workspace for user-visible project artifacts, destinationKind=managed-install only for checksum-verified Ambient capability/runtime assets, or destinationKind=quarantine for unsigned/untrusted assets that must not enter executable install roots.",
      "Public download URLs must use HTTPS. Ambient blocks loopback, private LAN, link-local, metadata, unsafe-port, credential-bearing, and redirect-to-private targets before a request is sent; local HTTP fixtures require an explicit local-dev mode outside normal chat use.",
      "Use relative destinationPath values only. Ambient rejects absolute paths and traversal.",
      "Managed-install downloads require sha256 from a trusted manifest or release page. Do not invent checksums.",
      "Do not pass API keys, bearer tokens, cookies, or other secrets in URLs or arguments. Use an Ambient-managed secret-specific installer flow when authentication is required.",
      "After starting a long download, call ambient_download_wait to emit visible progress until completion. Use ambient_download_status for polling and ambient_download_cancel only when cancellation is requested or the task is no longer needed.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        url: { type: "string", description: "HTTPS URL to download. Public HTTP, localhost/private, metadata, unsafe-port, and credential-bearing URLs are blocked." },
        destinationPath: { type: "string", description: "Relative destination path. Defaults to .ambient/downloads/<url filename>." },
        destinationKind: {
          type: "string",
          enum: ["workspace", "managed-install", "quarantine"],
          description:
            "Destination root. workspace is user-visible project state; managed-install is Ambient-owned install state and requires sha256; quarantine is a non-executable holding area for unsigned assets.",
        },
        overwrite: { type: "boolean", description: "Replace an existing completed destination file." },
        expectedBytes: { type: "number", description: "Optional exact expected byte size from a trusted manifest." },
        sha256: { type: "string", description: "Expected SHA-256 checksum from a trusted manifest. Required for destinationKind=managed-install." },
        resume: { type: "boolean", description: "Use an existing .part file and HTTP Range resume when possible. Defaults to true." },
        retryCount: { type: "number", description: "Retry count for transient download failures. Defaults to 2." },
      },
      required: ["url"],
      additionalProperties: false,
    },
    outputSchema: {
      type: "object",
      properties: {
        jobId: { type: "string" },
        status: { type: "string", enum: ["queued", "running", "completed", "failed", "canceled"] },
        destinationKind: { type: "string", enum: ["workspace", "managed-install", "quarantine"] },
        destinationPath: { type: "string" },
        absolutePath: { type: "string" },
        partPath: { type: "string" },
        bytesReceived: { type: "number" },
        totalBytes: { type: "number" },
        percent: { type: "number" },
        integrityStatus: { type: "string", enum: ["unverified", "pending-sha256", "sha256-verified"] },
        expectedBytes: { type: "number" },
        sha256: { type: "string" },
        computedSha256: { type: "string" },
        error: { type: "string" },
        finalUrl: { type: "string" },
      },
      required: ["jobId", "status", "destinationKind", "destinationPath", "absolutePath", "partPath", "bytesReceived", "integrityStatus"],
      additionalProperties: true,
    },
    source: "first-party",
    sideEffects: "write-workspace",
    permissionScope: "managed-download",
    supportsDryRun: false,
    supportsUndo: false,
    idempotency: "recommended",
    defaultTimeoutMs: 10_000,
    runtimeSupport: ["chat", "workflow"],
  },
  {
    name: "ambient_download_status",
    label: "Managed Download Status",
    description: "Read the current state of an Ambient-managed download job.",
    promptSnippet: "ambient_download_status: Poll a managed download job by jobId without starting another transfer.",
    promptGuidelines: [
      "Use this to inspect a previously started Ambient-managed download job.",
      "Do not start a duplicate download when a jobId already exists; inspect status first.",
      "If the job is still running and the user needs visible progress, call ambient_download_wait.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        jobId: { type: "string", description: "Managed download job id returned by ambient_download_start." },
      },
      required: ["jobId"],
      additionalProperties: false,
    },
    outputSchema: {
      type: "object",
      properties: {
        jobId: { type: "string" },
        status: { type: "string", enum: ["queued", "running", "completed", "failed", "canceled"] },
        destinationKind: { type: "string", enum: ["workspace", "managed-install", "quarantine"] },
        destinationPath: { type: "string" },
        bytesReceived: { type: "number" },
        totalBytes: { type: "number" },
        percent: { type: "number" },
        integrityStatus: { type: "string", enum: ["unverified", "pending-sha256", "sha256-verified"] },
        expectedBytes: { type: "number" },
        sha256: { type: "string" },
        computedSha256: { type: "string" },
        error: { type: "string" },
      },
      required: ["jobId", "status", "destinationKind", "destinationPath", "bytesReceived", "integrityStatus"],
      additionalProperties: true,
    },
    source: "first-party",
    sideEffects: "none",
    permissionScope: "managed-download",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "required",
    defaultTimeoutMs: 5_000,
    runtimeSupport: ["chat", "workflow"],
  },
  {
    name: "ambient_download_wait",
    label: "Managed Download Wait",
    description: "Wait for an Ambient-managed download while emitting visible progress updates that keep the local tool activity live.",
    promptSnippet:
      "ambient_download_wait: Wait on a managed download job and emit progress heartbeats until it completes, fails, or is canceled.",
    promptGuidelines: [
      "Call this after ambient_download_start when a download may take more than a few seconds.",
      "This tool emits progress updates while waiting. Prefer it over silent shell downloads for large files.",
      "If the user asks to stop or the job is no longer needed, call ambient_download_cancel.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        jobId: { type: "string", description: "Managed download job id returned by ambient_download_start." },
        heartbeatMs: { type: "number", description: "Optional progress heartbeat interval in milliseconds. Defaults to 2000." },
      },
      required: ["jobId"],
      additionalProperties: false,
    },
    outputSchema: {
      type: "object",
      properties: {
        jobId: { type: "string" },
        status: { type: "string", enum: ["queued", "running", "completed", "failed", "canceled"] },
        destinationKind: { type: "string", enum: ["workspace", "managed-install", "quarantine"] },
        destinationPath: { type: "string" },
        bytesReceived: { type: "number" },
        totalBytes: { type: "number" },
        percent: { type: "number" },
        integrityStatus: { type: "string", enum: ["unverified", "pending-sha256", "sha256-verified"] },
        expectedBytes: { type: "number" },
        sha256: { type: "string" },
        computedSha256: { type: "string" },
        error: { type: "string" },
      },
      required: ["jobId", "status", "destinationKind", "destinationPath", "bytesReceived", "integrityStatus"],
      additionalProperties: true,
    },
    source: "first-party",
    sideEffects: "write-workspace",
    permissionScope: "managed-download",
    supportsDryRun: false,
    supportsUndo: false,
    idempotency: "recommended",
    defaultTimeoutMs: 3_600_000,
    runtimeSupport: ["chat", "workflow"],
  },
  {
    name: "ambient_download_cancel",
    label: "Managed Download Cancel",
    description: "Cancel an active Ambient-managed download job while preserving any resumable .part file.",
    promptSnippet:
      "ambient_download_cancel: Cancel a managed download by jobId when the user asks to stop or the task no longer needs the file.",
    promptGuidelines: [
      "Use this only when the user asks to stop/cancel, or when a plan has changed and the download is no longer needed.",
      "Cancellation preserves the .part file so a future ambient_download_start to the same destination can resume when possible.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        jobId: { type: "string", description: "Managed download job id returned by ambient_download_start." },
      },
      required: ["jobId"],
      additionalProperties: false,
    },
    outputSchema: {
      type: "object",
      properties: {
        jobId: { type: "string" },
        status: { type: "string", enum: ["queued", "running", "completed", "failed", "canceled"] },
        destinationKind: { type: "string", enum: ["workspace", "managed-install", "quarantine"] },
        destinationPath: { type: "string" },
        bytesReceived: { type: "number" },
        integrityStatus: { type: "string", enum: ["unverified", "pending-sha256", "sha256-verified"] },
        error: { type: "string" },
      },
      required: ["jobId", "status", "destinationKind", "destinationPath", "bytesReceived", "integrityStatus"],
      additionalProperties: true,
    },
    source: "first-party",
    sideEffects: "write-workspace",
    permissionScope: "managed-download",
    supportsDryRun: false,
    supportsUndo: false,
    idempotency: "recommended",
    defaultTimeoutMs: 5_000,
    runtimeSupport: ["chat", "workflow"],
  },
];
