import type { DesktopToolDescriptor } from "./desktopToolDescriptorTypes";

export const messagingGatewaySignalToolDescriptors: DesktopToolDescriptor[] = [
  {
    name: "ambient_messaging_signal_real_unread_window_preview",
    label: "Signal Real Unread Window Preview",
    description: "Preview whether one real approval-gated Signal bounded unread single-read can run for an exact owner binding.",
    promptSnippet: "ambient_messaging_signal_real_unread_window_preview: Preview the reviewed real Signal single-read adapter separately from fake dogfood apply.",
    promptGuidelines: [
      "Use this when the user asks whether real Signal unread ingestion can run, or when distinguishing real Signal reads from the fake bridge dogfood path.",
      "This is preview-only. It does not request approval, contact the Signal bridge unread endpoint, read provider messages, write dedupe state, route projections, or send replies.",
      "The result reports whether the exact active owner binding and signal-real-bounded-unread-window-v0 gates are ready for one reviewed real single-read apply.",
      "Do not call ambient_messaging_signal_unread_window_apply as a substitute for real Signal ingestion; that tool is fake-bridge dogfood only.",
      "If blocked, do not retry with shell, browser, Signal Desktop UI, provider CLIs, generic binding tools, Telegram tools, or fake dogfood apply.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        providerId: { type: "string", enum: ["signal-cli"], description: "Optional provider id. If supplied, it must be signal-cli." },
        profileId: { type: "string", description: "Exact local Signal bridge profile id from the active binding. authProfileId is also accepted." },
        authProfileId: { type: "string", description: "Accepted alias for profileId." },
        conversationId: { type: "string", description: "Exact Signal conversation id from the active binding." },
        bindingId: { type: "string", description: "Required exact active Signal Remote Ambient Surface binding id for real reads." },
        limit: { type: "number", description: "Max unread messages for one approved single read. Defaults to 10, capped at 25." },
      },
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "none",
    permissionScope: "messaging-signal-real-unread-window-preview",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 10_000,
    runtimeSupport: ["chat", "workflow"],
  },
  {
    name: "ambient_messaging_signal_real_unread_window_apply",
    label: "Signal Real Unread Window Apply",
    description: "With approval, perform one real bounded Signal unread single-read for an exact owner binding and return sanitized dispatch metadata.",
    promptSnippet: "ambient_messaging_signal_real_unread_window_apply: Approval-gated real Signal single-read adapter for one exact owner binding.",
    promptGuidelines: [
      "Call ambient_messaging_signal_real_unread_window_preview first and apply only when it reports ready.",
      "Use only with an exact active Signal Remote Ambient Surface bindingId and the matching profileId/conversationId from that binding.",
      "This requests approval, calls exactly one reviewed bounded unread endpoint, drops duplicates/outgoing/empty/wrong-sender messages, routes accepted owner messages through the Remote Ambient Surface dispatch path, and writes dedupe state.",
      "The tool result returns only counts, message ids, queued projection ids/titles/kinds, and dropped reasons. It must not return provider message bodies in text or details.",
      "This does not start Signal, inspect Signal Desktop, run signal-cli, create/revoke bindings, start periodic polling, or send Signal messages.",
      "Do not use ambient_messaging_signal_unread_window_apply, shell, browser, Signal Desktop UI, provider CLIs, generic binding tools, or Telegram tools as a workaround.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        providerId: { type: "string", enum: ["signal-cli"], description: "Optional provider id. If supplied, it must be signal-cli." },
        profileId: { type: "string", description: "Exact local Signal bridge profile id from the active binding. authProfileId is also accepted." },
        authProfileId: { type: "string", description: "Accepted alias for profileId." },
        conversationId: { type: "string", description: "Exact Signal conversation id from the active binding." },
        bindingId: { type: "string", description: "Required exact active Signal Remote Ambient Surface binding id for real reads." },
        limit: { type: "number", description: "Max unread messages for one approved single read. Defaults to 10, capped at 25." },
      },
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "read-external",
    permissionScope: "messaging-signal-real-unread-window-apply",
    supportsDryRun: false,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 30_000,
    runtimeSupport: ["chat", "workflow"],
  },
  {
    name: "ambient_messaging_signal_real_polling_status",
    label: "Signal Real Polling Status",
    description: "Inspect Signal real polling runner state, counters, eligible bindings, and timer status without reading provider messages.",
    promptSnippet: "ambient_messaging_signal_real_polling_status: Explain Signal real polling runner state, counters, eligible bindings, and whether a timer is active.",
    promptGuidelines: [
      "Use this to answer whether Signal real polling is running, stopped, blocked, or in error.",
      "This is read-only. It must not request approval, start timers, contact the bridge unread endpoint, read Signal messages, write dedupe state, route projections, or send replies.",
      "If stopped, explain that start requires ambient_messaging_signal_real_polling_preview and approval through ambient_messaging_signal_real_polling_apply for one exact binding.",
      "Do not use shell, browser, Signal Desktop UI, provider CLIs, fake dogfood apply, generic binding tools, Telegram tools, or reply tools as a workaround.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        providerId: { type: "string", enum: ["signal-cli"], description: "Optional provider id. If supplied, it must be signal-cli." },
        limit: { type: "number", description: "Preview limit per future poll. Defaults to 10, capped at 25." },
        intervalMs: { type: "number", description: "Preview interval for a future polling runner. Defaults to 60000, min 30000, max 300000." },
      },
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "none",
    permissionScope: "messaging-signal-real-polling-status-read",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 10_000,
    runtimeSupport: ["chat", "workflow"],
  },
  {
    name: "ambient_messaging_signal_real_polling_preview",
    label: "Signal Real Polling Preview",
    description: "Preview Signal real polling start/stop gates for one exact owner binding without starting a timer or reading messages.",
    promptSnippet: "ambient_messaging_signal_real_polling_preview: Preview Signal real polling start/stop gates, approval requirement, single-read readiness, and timer side effects.",
    promptGuidelines: [
      "Use this before any attempt to start or stop Signal real polling.",
      "This is preview-only. It does not request approval, start timers, contact the bridge unread endpoint, read Signal messages, write dedupe state, route projections, or send replies.",
      "Start previews must include the exact bindingId/profileId/conversationId, real single-read readiness, interval, and approval requirement.",
      "Stop previews should make clear they only describe a future Ambient polling timer and do not revoke bindings, stop the Signal bridge, or send provider messages.",
      "Do not call ambient_messaging_signal_real_polling_apply when preview is blocked.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        action: { type: "string", enum: ["start", "stop"], description: "Start or stop future Signal real polling. Defaults to start." },
        providerId: { type: "string", enum: ["signal-cli"], description: "Optional provider id. If supplied, it must be signal-cli." },
        profileId: { type: "string", description: "Exact local Signal bridge profile id from the active binding. authProfileId is also accepted." },
        authProfileId: { type: "string", description: "Accepted alias for profileId." },
        conversationId: { type: "string", description: "Exact Signal conversation id from the active binding." },
        bindingId: { type: "string", description: "Required exact active Signal Remote Ambient Surface binding id for future polling." },
        limit: { type: "number", description: "Max unread messages per binding for each future poll. Defaults to 10, capped at 25." },
        intervalMs: { type: "number", description: "Future polling interval in milliseconds. Defaults to 60000, min 30000, max 300000." },
      },
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "none",
    permissionScope: "messaging-signal-real-polling-preview",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 10_000,
    runtimeSupport: ["chat", "workflow"],
  },
  {
    name: "ambient_messaging_signal_real_polling_apply",
    label: "Signal Real Polling Apply",
    description: "Apply an approved Signal real polling start/stop for one exact binding; start performs one immediate reviewed single-read before scheduling.",
    promptSnippet: "ambient_messaging_signal_real_polling_apply: Start or stop Signal real polling after preview; start requires approval and reuses the reviewed real single-read core.",
    promptGuidelines: [
      "Call ambient_messaging_signal_real_polling_preview first and apply only when preview is ready.",
      "Starting polling requires explicit approval, then performs one immediate bounded real unread poll through ambient_messaging_signal_real_unread_window_apply's reviewed core before scheduling future ticks.",
      "Stopping polling does not read provider messages, revoke bindings, stop the Signal bridge, or send provider messages.",
      "Do not use ambient_messaging_signal_unread_window_apply, shell, browser, Signal Desktop UI, provider CLIs, generic binding tools, or Telegram tools as a polling workaround.",
      "Outbound Signal replies use a separate approval-gated reviewed bridge reply contract.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        action: { type: "string", enum: ["start", "stop"], description: "Start or stop future Signal real polling. Defaults to start." },
        providerId: { type: "string", enum: ["signal-cli"], description: "Optional provider id. If supplied, it must be signal-cli." },
        profileId: { type: "string", description: "Exact local Signal bridge profile id from the active binding. authProfileId is also accepted." },
        authProfileId: { type: "string", description: "Accepted alias for profileId." },
        conversationId: { type: "string", description: "Exact Signal conversation id from the active binding." },
        bindingId: { type: "string", description: "Required exact active Signal Remote Ambient Surface binding id for future polling." },
        limit: { type: "number", description: "Max unread messages per binding for each future poll. Defaults to 10, capped at 25." },
        intervalMs: { type: "number", description: "Future polling interval in milliseconds. Defaults to 60000, min 30000, max 300000." },
      },
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "read-external",
    permissionScope: "messaging-signal-real-polling-apply",
    supportsDryRun: false,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 30_000,
    runtimeSupport: ["chat", "workflow"],
  },
  {
    name: "ambient_messaging_signal_bridge_reply_preview",
    label: "Signal Bridge Reply Preview",
    description: "Preview an approval-gated Signal outbound reply for one exact Remote Ambient Surface binding or relayable runtime event without sending messages.",
    promptSnippet: "ambient_messaging_signal_bridge_reply_preview: Preview Signal reply scope, bridge approvedReplySend capability, recipient owner, exact text, runtimeEventId relay text, and approval-gated send readiness.",
    promptGuidelines: [
      "Use this when Pi needs to answer whether Ambient can send a Signal reply for a Remote Ambient Surface projection or binding.",
      "For Ambient runtime notifications listed by ambient_messaging_gateway_status or ambient_messaging_signal_relay_diagnostics, pass runtimeEventId by itself; Ambient will generate the exact relay text and route through the event's queued projection.",
      "This is preview-only. It does not request approval, contact the bridge send endpoint, send Signal messages, read provider messages/history, start bridges, mutate bindings, run signal-cli, or inspect Signal Desktop.",
      "Prefer queuedProjectionId when replying to a queued Signal Remote Ambient Surface projection; otherwise include exact bindingId/profileId/conversationId/replyToMessageId/text.",
      "If blocked, follow the Repair steps returned by the preview or call ambient_messaging_signal_relay_diagnostics for a scoped readiness check before retrying.",
      "If preview is ready, call ambient_messaging_signal_bridge_reply_apply only after making clear that the apply path will request user approval for the exact Signal reply text.",
      "Explain that Signal chat-to-self ingestion and polling are separate from outbound Signal replies.",
      "Do not use shell, browser, Signal Desktop UI, signal-cli, Telegram tools, generic messaging tools, or Messaging Connector sends as a workaround.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        providerId: { type: "string", enum: ["signal-cli"], description: "Optional provider id. If supplied, it must be signal-cli." },
        queuedProjectionId: { type: "string", description: "Optional queued Signal Remote Ambient Surface projection id to reply to." },
        bindingId: { type: "string", description: "Exact active Signal Remote Ambient Surface binding id." },
        profileId: { type: "string", description: "Exact local Signal bridge profile id from the active binding. authProfileId is also accepted." },
        authProfileId: { type: "string", description: "Accepted alias for profileId." },
        conversationId: { type: "string", description: "Exact Signal conversation id from the active binding." },
        replyToMessageId: { type: "string", description: "Exact Signal provider message id to reply to. sourceMessageId is also accepted." },
        sourceMessageId: { type: "string", description: "Accepted alias for replyToMessageId." },
        text: { type: "string", description: "Reply text for a future approval-gated send. Capped at 4000 chars." },
        runtimeEventId: { type: "string", description: "Recent Remote Ambient Surface runtime event id from ambient_messaging_gateway_status. When supplied without text, Ambient generates exact Signal status relay text." },
      },
      anyOf: [
        { required: ["runtimeEventId"] },
        { required: ["text"] },
      ],
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "none",
    permissionScope: "messaging-signal-bridge-reply-preview",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 10_000,
    runtimeSupport: ["chat", "workflow"],
  },
  {
    name: "ambient_messaging_signal_bridge_reply_apply",
    label: "Signal Bridge Reply Apply",
    description: "Apply an approval-gated Signal outbound reply through the reviewed local bridge send contract.",
    promptSnippet: "ambient_messaging_signal_bridge_reply_apply: Request approval for one exact Signal reply or runtimeEventId relay and, if approved, send only through the reviewed bridge send endpoint.",
    promptGuidelines: [
      "Call ambient_messaging_signal_bridge_reply_preview first. Apply only when preview is ready for the exact active Signal Remote Ambient Surface binding and exact text.",
      "This apply requests first-party approval before sending. If approval is denied, no Signal message is sent.",
      "For runtime-event relays, pass the same runtimeEventId that was previewed so Ambient generates the same status text and records relay status on the event.",
      "The only send path is POST to the reviewed Signal bridge send endpoint for the exact profile/conversation scope; do not start bridges, read provider messages/history, mutate bindings, run signal-cli, or inspect Signal Desktop.",
      "If blocked, explain the blocker and the returned Repair steps; do not invent a workaround.",
      "Do not use shell, browser, Signal Desktop UI, signal-cli, Telegram tools, generic messaging tools, or Messaging Connector sends as a workaround.",
      "Keep Remote Ambient Surface chat-to-self ingestion separate from any future 'send messages to others' Messaging Connector capability.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        providerId: { type: "string", enum: ["signal-cli"], description: "Optional provider id. If supplied, it must be signal-cli." },
        queuedProjectionId: { type: "string", description: "Optional queued Signal Remote Ambient Surface projection id to reply to." },
        bindingId: { type: "string", description: "Exact active Signal Remote Ambient Surface binding id." },
        profileId: { type: "string", description: "Exact local Signal bridge profile id from the active binding. authProfileId is also accepted." },
        authProfileId: { type: "string", description: "Accepted alias for profileId." },
        conversationId: { type: "string", description: "Exact Signal conversation id from the active binding." },
        replyToMessageId: { type: "string", description: "Exact Signal provider message id to reply to. sourceMessageId is also accepted." },
        sourceMessageId: { type: "string", description: "Accepted alias for replyToMessageId." },
        text: { type: "string", description: "Reply text for a future approval-gated send. Capped at 4000 chars." },
        runtimeEventId: { type: "string", description: "Recent Remote Ambient Surface runtime event id from ambient_messaging_gateway_status. When supplied without text, Ambient generates exact Signal status relay text." },
      },
      anyOf: [
        { required: ["runtimeEventId"] },
        { required: ["text"] },
      ],
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "write-external",
    permissionScope: "messaging-signal-bridge-reply-apply",
    supportsDryRun: false,
    supportsUndo: false,
    idempotency: "recommended",
    defaultTimeoutMs: 10_000,
    runtimeSupport: ["chat", "workflow"],
  },
  {
    name: "ambient_messaging_signal_relay_diagnostics",
    label: "Signal Relay Diagnostics",
    description: "Inspect whether a Signal Remote Ambient Surface owner conversation can relay Ambient runtime events through the reviewed local bridge.",
    promptSnippet: "ambient_messaging_signal_relay_diagnostics: Read-only diagnostics for Signal owner relay readiness, bridge approvedReplySend state, queued projections, runtime events, and relay deliveries.",
    promptGuidelines: [
      "Use this before real Signal relay smoke tests or when explaining why a Remote Ambient Surface owner conversation cannot receive status replies.",
      "Pass profileId, conversationId, or bindingId when the user is asking about a specific Signal owner conversation.",
      "This tool verifies reviewed Signal bridge reply readiness; it does not imply Signal polling or unread ingestion is active.",
      "This tool does not start bridges, read Signal messages, read provider history, mutate bindings, run signal-cli, inspect Signal Desktop, or send provider messages.",
      "When status is blocked, surface the Repair steps verbatim before trying preview/apply again.",
      "If relayable runtime events are present and status is ready, use ambient_messaging_signal_bridge_reply_preview with runtimeEventId before any apply.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        providerId: { type: "string", enum: ["signal-cli"], description: "Optional provider id. If supplied, it must be signal-cli." },
        profileId: { type: "string", description: "Optional Signal auth profile id to inspect. authProfileId is also accepted." },
        authProfileId: { type: "string", description: "Accepted alias for profileId." },
        conversationId: { type: "string", description: "Optional Signal conversation id to inspect." },
        bindingId: { type: "string", description: "Optional exact Remote Ambient Surface binding id to inspect." },
      },
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "none",
    permissionScope: "messaging-signal-relay-diagnostics-read",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 10_000,
    runtimeSupport: ["chat", "workflow"],
  },
  {
    name: "ambient_messaging_signal_binding_readiness_preview",
    label: "Signal Binding Readiness Preview",
    description: "Preview why Signal Remote Ambient Surface binding creation remains blocked after directory selection, without creating bindings or reading Signal messages.",
    promptSnippet: "ambient_messaging_signal_binding_readiness_preview: Signal-specific Remote Ambient Surface binding readiness checklist after metadata-only directory selection.",
    promptGuidelines: [
      "Use this typed Signal tool after a Signal conversation directory preview/apply has selected a profile and conversation.",
      "This is preview-only. Pi must not call ambient_messaging_binding_apply for Signal.",
      "Explain the selected directory conversation, bridge-readable profile, bounded unread contract, missing or matched Signal owner authentication, and the separate typed runtime/inbound/reply adapters together.",
      "After matched Signal owner handoff metadata exists, use ambient_messaging_signal_remote_surface_preview/apply; the typed apply can persist binding metadata only after readiness gates and user approval.",
      "Do not use Telegram owner handoff, Telegram tools, shell, browser automation, Signal Desktop UI, or provider CLIs as a workaround for Signal owner identity.",
      "Signal runtime lifecycle and broad inbound ingestion remain disabled even after binding metadata is created; polling and outbound replies require their own typed Signal preview/apply tools.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        providerId: { type: "string", enum: ["signal-cli"], description: "Optional provider id. If supplied, it must be signal-cli." },
        profileId: { type: "string", description: "Optional local Signal bridge profile id. authProfileId is also accepted." },
        authProfileId: { type: "string", description: "Accepted alias for profileId." },
        conversationId: { type: "string", description: "Signal conversation id from the metadata-only directory result." },
        ownerUserId: { type: "string", description: "Future authenticated owner sender id. In this build it is not accepted as proof of Signal owner authentication." },
        ambientSurface: { type: "string", enum: ["chat", "projects", "workflow_agents", "settings", "notifications"], description: "Intended Remote Ambient Surface target." },
        maxDisclosureLabel: { type: "string", description: "Intended user-approved disclosure ceiling." },
        limit: { type: "number", description: "Future unread messages per poll limit. Defaults to 10, capped at 25." },
      },
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "none",
    permissionScope: "messaging-signal-binding-readiness-preview",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 10_000,
    runtimeSupport: ["chat", "workflow"],
  },
  {
    name: "ambient_messaging_signal_owner_handoff_preview",
    label: "Signal Owner Handoff Preview",
    description: "Preview the future Signal one-time owner authentication handoff contract without reading Signal unread messages or creating bindings.",
    promptSnippet: "ambient_messaging_signal_owner_handoff_preview: Preview-only Signal owner authentication handoff contract before any Signal Remote Ambient Surface binding apply exists.",
    promptGuidelines: [
      "Use this typed Signal tool after metadata-only Signal directory selection when explaining how owner authentication must work before binding creation.",
      "This is preview-only. The Signal owner handoff apply tool is a blocked no-I/O skeleton in this build, and Pi must not read Signal unread messages.",
      "A future apply must require explicit user approval, exact profile id, exact conversation id, a one-time setup code, and a bounded unread limit.",
      "The setup-code message body may only be compared inside the adapter; Pi-visible output must contain sender/dedupe metadata, counts, and no raw message text.",
      "Do not use Telegram owner handoff, Telegram tools, shell, browser automation, Signal Desktop UI, provider CLIs, or generic binding apply as a workaround.",
      "Signal owner handoff does not itself enable binding, polling, inbound routing, or outbound replies; each capability has a separate typed apply path.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        providerId: { type: "string", enum: ["signal-cli"], description: "Optional provider id. If supplied, it must be signal-cli." },
        profileId: { type: "string", description: "Optional local Signal bridge profile id. authProfileId is also accepted." },
        authProfileId: { type: "string", description: "Accepted alias for profileId." },
        conversationId: { type: "string", description: "Signal conversation id from the metadata-only directory result." },
        setupCode: { type: "string", description: "Optional future one-time setup code. If supplied, must be single-line, 6-120 characters. The preview never returns the full code." },
        limit: { type: "number", description: "Future max unread messages to inspect. Defaults to 10, capped at 25." },
      },
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "none",
    permissionScope: "messaging-signal-owner-handoff-preview",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 10_000,
    runtimeSupport: ["chat", "workflow"],
  },
  {
    name: "ambient_messaging_signal_owner_handoff_apply",
    label: "Signal Owner Handoff Apply",
    description: "With approval, apply the reviewed fake Signal owner-handoff bridge contract to read one bounded unread window and return only matched owner/dedupe metadata.",
    promptSnippet: "ambient_messaging_signal_owner_handoff_apply: Approval-gated fake-bridge Signal owner handoff; reads one bounded unread endpoint only when the preview says canApplyNow.",
    promptGuidelines: [
      "Call ambient_messaging_signal_owner_handoff_preview first and proceed only when that preview says canApplyNow=true.",
      "This apply is limited to the reviewed fake Signal bridge path. It remains blocked for real Signal unless the explicit fake-bridge apply gate and bridge readiness are present.",
      "Use this only after explicit user approval and only after the owner has sent the exact setup code in the selected Signal conversation.",
      "This reads exactly one bounded unread endpoint for the selected profile and conversation, compares setup-code text internally, and returns no Signal message bodies or setup-code text.",
      "If exactly one sender matches, use only the returned ownerUserId, sourceMessageId, and initialSeenMessageIds with ambient_messaging_signal_remote_surface_preview/apply.",
      "Do not feed the result into ambient_messaging_binding_apply; generic binding apply remains invalid for Signal.",
      "If handoffStatus is no-match, ambiguous, or not-attempted, fail closed and ask for a fresh unique setup code rather than trying shell, browser, Signal Desktop UI, provider CLI, Telegram owner handoff, or arbitrary history reads.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        providerId: { type: "string", enum: ["signal-cli"], description: "Optional provider id. If supplied, it must be signal-cli." },
        profileId: { type: "string", description: "Optional local Signal bridge profile id. authProfileId is also accepted." },
        authProfileId: { type: "string", description: "Accepted alias for profileId." },
        conversationId: { type: "string", description: "Signal conversation id from the metadata-only directory result." },
        setupCode: { type: "string", description: "One-time setup code sent by the owner in the selected Signal conversation. Must be single-line, 6-120 characters. The apply never returns the full code." },
        limit: { type: "number", description: "Future max unread messages to inspect. Defaults to 10, capped at 25." },
      },
      required: ["profileId", "conversationId", "setupCode"],
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "read-external",
    permissionScope: "messaging-signal-owner-handoff-apply",
    supportsDryRun: false,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 30_000,
    runtimeSupport: ["chat", "workflow"],
  },
  {
    name: "ambient_messaging_signal_remote_surface_preview",
    label: "Signal Remote Surface Preview",
    description: "Preview Signal-specific Remote Ambient Surface binding create or revoke operations without changing state.",
    promptSnippet: "ambient_messaging_signal_remote_surface_preview: Validate matched Signal owner-handoff metadata for create, or preview typed Signal binding revoke.",
    promptGuidelines: [
      "For action=create, use this typed Signal tool after ambient_messaging_signal_owner_handoff_apply returns handoffStatus=matched and canFeedBindingApply=true.",
      "For action=create, provide profileId, conversationId, ownerUserId, ownerHandoffSourceMessageId, initialSeenMessageIds, ambientSurface, and maxDisclosureLabel from the approved Signal owner handoff and user-selected surface.",
      "For action=revoke, provide bindingId from ambient_messaging_list_bindings with providerId=signal-cli and includeInactive=true.",
      "This preview never creates bindings, starts bridges, reads Signal messages, polls unread windows, sends replies, runs signal-cli, or inspects Signal Desktop.",
      "Do not call ambient_messaging_binding_apply for Signal. Generic binding apply remains invalid even when the owner-handoff metadata is present.",
      "Do not use Telegram owner handoff, Telegram tools, shell, browser automation, Signal Desktop UI, provider CLIs, or arbitrary Signal history reads as a workaround.",
      "No-match, ambiguous, denied, or not-attempted owner handoff results are non-authorizing and must not be fed into this tool.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        action: { type: "string", enum: ["create", "revoke"], description: "Defaults to create. Use revoke with bindingId to revoke an existing typed Signal binding." },
        bindingId: { type: "string", description: "Required when action=revoke." },
        reason: { type: "string", description: "Optional revocation reason." },
        providerId: { type: "string", enum: ["signal-cli"], description: "Optional provider id. If supplied, it must be signal-cli." },
        purpose: { type: "string", enum: ["remote_ambient_surface"], description: "Optional. Must be remote_ambient_surface." },
        profileId: { type: "string", description: "Signal local bridge profile id from the matched owner handoff." },
        authProfileId: { type: "string", description: "Accepted alias for profileId." },
        conversationId: { type: "string", description: "Signal conversation id from the metadata-only directory result and matched owner handoff." },
        ownerUserId: { type: "string", description: "Matched owner sender id returned by ambient_messaging_signal_owner_handoff_apply." },
        ownerHandoffSourceMessageId: { type: "string", description: "sourceMessageId returned by ambient_messaging_signal_owner_handoff_apply." },
        sourceMessageId: { type: "string", description: "Accepted alias for ownerHandoffSourceMessageId." },
        initialSeenMessageIds: { type: "array", items: { type: "string" }, description: "initialSeenMessageIds returned by ambient_messaging_signal_owner_handoff_apply. Must include ownerHandoffSourceMessageId." },
        ambientSurface: { type: "string", enum: ["chat", "projects", "workflow_agents", "settings", "notifications"] },
        maxDisclosureLabel: { type: "string", description: "User-approved disclosure ceiling, for example owner-private-runtime-summary." },
        threadId: { type: "string" },
        projectId: { type: "string" },
        workflowId: { type: "string" },
        chatThreadId: { type: "string" },
        permissionProfileId: { type: "string" },
        guardProfileId: { type: "string" },
        limit: { type: "number", description: "Future unread messages per poll limit. Defaults to 10, capped at 25." },
      },
      required: [],
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "none",
    permissionScope: "messaging-signal-remote-surface-preview",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 10_000,
    runtimeSupport: ["chat", "workflow"],
  },
  {
    name: "ambient_messaging_signal_remote_surface_apply",
    label: "Signal Remote Surface Apply",
    description: "With approval, create or revoke a Signal-specific Remote Ambient Surface binding without starting Signal or reading messages.",
    promptSnippet: "ambient_messaging_signal_remote_surface_apply: Approval-gated Signal-specific binding apply; creates/revokes owner-approved metadata only and keeps generic binding apply invalid.",
    promptGuidelines: [
      "Call ambient_messaging_signal_remote_surface_preview first with the same action and inputs.",
      "For action=create, this tool may request approval and persist Signal Remote Ambient Surface binding metadata after readiness gates pass.",
      "For action=revoke, this tool may request approval and revoke only the typed Signal binding record identified by bindingId.",
      "It must not start bridges, read Signal messages, poll unread windows, send replies, run signal-cli, or inspect Signal Desktop.",
      "After success, call ambient_messaging_list_bindings with providerId=signal-cli and includeInactive=true to verify the active or revoked binding record.",
      "Do not call ambient_messaging_binding_apply for Signal. Generic binding apply remains invalid.",
      "Do not use Telegram owner handoff, Telegram tools, shell, browser automation, Signal Desktop UI, provider CLIs, or arbitrary Signal history reads as a workaround.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        action: { type: "string", enum: ["create", "revoke"], description: "Defaults to create. Use revoke with bindingId to revoke an existing typed Signal binding." },
        bindingId: { type: "string", description: "Required when action=revoke." },
        reason: { type: "string", description: "Optional revocation reason." },
        providerId: { type: "string", enum: ["signal-cli"], description: "Optional provider id. If supplied, it must be signal-cli." },
        purpose: { type: "string", enum: ["remote_ambient_surface"], description: "Optional. Must be remote_ambient_surface." },
        profileId: { type: "string", description: "Signal local bridge profile id from the matched owner handoff." },
        authProfileId: { type: "string", description: "Accepted alias for profileId." },
        conversationId: { type: "string", description: "Signal conversation id from the metadata-only directory result and matched owner handoff." },
        ownerUserId: { type: "string", description: "Matched owner sender id returned by ambient_messaging_signal_owner_handoff_apply." },
        ownerHandoffSourceMessageId: { type: "string", description: "sourceMessageId returned by ambient_messaging_signal_owner_handoff_apply." },
        sourceMessageId: { type: "string", description: "Accepted alias for ownerHandoffSourceMessageId." },
        initialSeenMessageIds: { type: "array", items: { type: "string" }, description: "initialSeenMessageIds returned by ambient_messaging_signal_owner_handoff_apply. Must include ownerHandoffSourceMessageId." },
        ambientSurface: { type: "string", enum: ["chat", "projects", "workflow_agents", "settings", "notifications"] },
        maxDisclosureLabel: { type: "string", description: "User-approved disclosure ceiling, for example owner-private-runtime-summary." },
        threadId: { type: "string" },
        projectId: { type: "string" },
        workflowId: { type: "string" },
        chatThreadId: { type: "string" },
        permissionProfileId: { type: "string" },
        guardProfileId: { type: "string" },
        limit: { type: "number", description: "Future unread messages per poll limit. Defaults to 10, capped at 25." },
      },
      required: [],
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "write-workspace",
    permissionScope: "messaging-signal-remote-surface-write",
    supportsDryRun: false,
    supportsUndo: false,
    idempotency: "recommended",
    defaultTimeoutMs: 10_000,
    runtimeSupport: ["chat", "workflow"],
  },
  {
    name: "ambient_messaging_headless_ux_inventory",
    label: "Ambient Headless UX Inventory",
    description: "Inspect which basic Ambient runtime UX commands are ready, partial, planned, or renderer-only for headless/messaging use.",
    promptSnippet: "ambient_messaging_headless_ux_inventory: Inspect headless readiness for settings, project, workflow, chat, approval, messaging polling, and status commands.",
    promptGuidelines: [
      "Use this when planning Remote Ambient Surface support, Linux/headless operation, or messaging-native setup flows.",
      "Treat partial and planned rows as implementation gaps; do not claim the user can perform those operations headlessly until the inventory says ready.",
      "Use the exact Tool sequence and Examples rows from the inventory. Do not invent direct tools such as project-create, workflow-create, chat-create, or generic settings-update tools when the row points to the Remote Ambient Surface command preview/apply lane.",
      "For Settings, inspect the Settings catalog rows. Ready writable rows may be changed through their listed Remote Ambient Surface command examples; partial/planned rows should be described as not yet remotely writable.",
      "For messaging polling, use the inventory rows to choose one-shot polling for a single expected command and periodic polling for an ongoing owner Remote Ambient Surface loop.",
      "This tool is an inventory only. It does not create projects, create workflows, change settings, approve actions, or mutate state.",
      "This is read-only and safe in planner/headless contexts.",
    ],
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "none",
    permissionScope: "headless-runtime-inventory-read",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 10_000,
    runtimeSupport: ["chat", "workflow"],
  },
  {
    name: "ambient_messaging_binding_preview",
    label: "Ambient Messaging Binding Preview",
    description: "Preview a purpose-scoped messaging binding create or revoke operation without changing state.",
    promptSnippet: "ambient_messaging_binding_preview: Preview creating or revoking a Remote Ambient Surface or Messaging Connector binding.",
    promptGuidelines: [
      "Use this before creating or revoking a messaging binding.",
      "A binding preview never starts provider bridges, reads provider messages, or sends provider messages.",
      "Do not use this generic tool for Signal. Signal Remote Ambient Surface creation must use ambient_messaging_signal_remote_surface_preview/apply after matched owner handoff metadata; Ambient rejects generic Signal binding writes.",
      "For remote_ambient_surface bindings, include ownerUserId and the intended ambientSurface when known.",
      "For messaging_connector bindings, externalTrustClass must be external; do not expose private Ambient state through connector bindings.",
      "Show the user the purpose, provider, conversation, trust class, state path, and policy consequences before asking them to approve the real operation.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        action: { type: "string", enum: ["create", "revoke"] },
        bindingId: { type: "string", description: "Required when action=revoke." },
        reason: { type: "string", description: "Optional revocation reason." },
        providerId: { type: "string", description: "Required when action=create." },
        authProfileId: { type: "string", description: "Required when action=create." },
        conversationId: { type: "string", description: "Required when action=create." },
        threadId: { type: "string" },
        purpose: { type: "string", enum: ["remote_ambient_surface", "messaging_connector"], description: "Required when action=create." },
        ownerUserId: { type: "string" },
        projectId: { type: "string" },
        workflowId: { type: "string" },
        ambientSurface: { type: "string", enum: ["chat", "projects", "workflow_agents", "settings", "notifications"] },
        externalTrustClass: { type: "string", enum: ["owner", "delegate", "external"] },
        permissionProfileId: { type: "string" },
        guardProfileId: { type: "string" },
        maxDisclosureLabel: { type: "string" },
      },
      required: ["action"],
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "none",
    permissionScope: "messaging-binding-preview",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 10_000,
    runtimeSupport: ["chat", "workflow"],
  },
  {
    name: "ambient_messaging_binding_apply",
    label: "Ambient Messaging Binding Apply",
    description: "With approval, create or revoke a purpose-scoped messaging binding record without starting bridges or sending messages.",
    promptSnippet: "ambient_messaging_binding_apply: With approval, create or revoke a Remote Ambient Surface or Messaging Connector binding record.",
    promptGuidelines: [
      "Call ambient_messaging_binding_preview first and explain the resulting policy notes before this tool.",
      "Use this only after the user has explicitly approved creating or revoking the binding.",
      "This tool persists binding metadata only. It does not start provider bridges, ingest messages, or send outbound messages.",
      "Do not use this generic tool for Signal. Signal Remote Ambient Surface creation must use ambient_messaging_signal_remote_surface_preview/apply after matched owner handoff metadata; Ambient rejects generic Signal binding writes.",
      "After success, call ambient_messaging_list_bindings to verify the registered or revoked binding.",
      "Do not use this to bypass provider auth, owner verification, external-recipient disclosure limits, or future bridge lifecycle approval.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        action: { type: "string", enum: ["create", "revoke"] },
        bindingId: { type: "string", description: "Required when action=revoke." },
        reason: { type: "string", description: "Optional revocation reason." },
        providerId: { type: "string", description: "Required when action=create." },
        authProfileId: { type: "string", description: "Required when action=create." },
        conversationId: { type: "string", description: "Required when action=create." },
        threadId: { type: "string" },
        purpose: { type: "string", enum: ["remote_ambient_surface", "messaging_connector"], description: "Required when action=create." },
        ownerUserId: { type: "string" },
        projectId: { type: "string" },
        workflowId: { type: "string" },
        ambientSurface: { type: "string", enum: ["chat", "projects", "workflow_agents", "settings", "notifications"] },
        externalTrustClass: { type: "string", enum: ["owner", "delegate", "external"] },
        permissionProfileId: { type: "string" },
        guardProfileId: { type: "string" },
        maxDisclosureLabel: { type: "string" },
      },
      required: ["action"],
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "write-workspace",
    permissionScope: "messaging-binding-write",
    supportsDryRun: false,
    supportsUndo: true,
    idempotency: "recommended",
    defaultTimeoutMs: 10_000,
    runtimeSupport: ["chat", "workflow"],
  },
  {
    name: "ambient_messaging_remote_surface_binding_preview",
    label: "Remote Surface Binding Preview",
    description: "Provider-neutral Remote Ambient Surface binding preview that delegates to Telegram where safe and explains planned/non-implemented providers without changing state.",
    promptSnippet: "ambient_messaging_remote_surface_binding_preview: Provider-neutral preview for binding a messaging provider conversation to Remote Ambient Surface.",
    promptGuidelines: [
      "Use this when the provider is not known, when comparing providers, or when planning Remote Ambient Surface setup for a non-Telegram provider.",
      "This preview never creates/revokes bindings, starts provider bridges, reads provider messages, ingests events, or sends replies.",
      "For Telegram, this delegates to the Telegram typed preview shape and tells you which Telegram typed apply tool can be used after approval.",
      "For Signal after directory selection, use ambient_messaging_signal_binding_readiness_preview; do not call ambient_messaging_binding_apply for Signal.",
      "For planned providers such as Signal, treat the result as implementation guidance only; do not try Telegram tools, provider CLIs, shell commands, browser automation, or app UI automation.",
      "If this preview says no typed apply tool exists, stop at planning/status and explain the missing adapter work.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        action: { type: "string", enum: ["create", "revoke"] },
        providerId: { type: "string", description: "Required when action=create. Optional when action=revoke if bindingId exists locally." },
        purpose: { type: "string", enum: ["remote_ambient_surface"], description: "Optional when action=create; only remote_ambient_surface is accepted." },
        authProfileId: { type: "string", description: "Required when action=create. Provider auth/session profile id." },
        profileId: { type: "string", description: "Accepted alias for authProfileId for Telegram-shaped calls." },
        conversationId: { type: "string", description: "Required when action=create. Provider conversation/chat/channel id to bind." },
        ownerUserId: { type: "string", description: "Required when action=create. Authenticated owner sender id expected for the conversation." },
        ambientSurface: { type: "string", enum: ["chat", "projects", "workflow_agents", "settings", "notifications"], description: "Required when action=create." },
        maxDisclosureLabel: { type: "string", description: "Required when action=create. User-approved disclosure ceiling." },
        threadId: { type: "string" },
        projectId: { type: "string" },
        workflowId: { type: "string" },
        permissionProfileId: { type: "string" },
        guardProfileId: { type: "string" },
        bindingId: { type: "string", description: "Required when action=revoke." },
        reason: { type: "string", description: "Optional revocation reason." },
      },
      required: ["action"],
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "none",
    permissionScope: "messaging-remote-surface-binding-preview",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 10_000,
    runtimeSupport: ["chat", "workflow"],
  },
  {
    name: "ambient_messaging_remote_surface_event_preview",
    label: "Remote Surface Event Preview",
    description: "Provider-neutral preview for normalized Remote Ambient Surface inbound events without queueing projections or touching provider I/O.",
    promptSnippet: "ambient_messaging_remote_surface_event_preview: Preview how a normalized inbound provider event would route through Remote Ambient Surface.",
    promptGuidelines: [
      "Use this to ask whether a provider can route Remote Ambient Surface events before using provider-specific route/poll tools.",
      "This preview never starts providers, polls providers, reads provider history, sends replies, or queues projections.",
      "For Telegram, it previews the same binding and owner checks used by the Telegram bridge event route, but the real route remains ambient_messaging_telegram_bridge_event_route.",
      "For planned providers such as Signal, use the blockers as adapter work guidance and do not attempt Telegram-specific tools against that provider.",
      "A binding_required result means create an approved Remote Ambient Surface binding before projecting Ambient runtime state.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        providerId: { type: "string", description: "Exact messaging provider id, for example telegram-tdlib or signal-cli." },
        authProfileId: { type: "string", description: "Provider auth/session profile id. profileId is also accepted." },
        profileId: { type: "string", description: "Accepted alias for authProfileId." },
        conversationId: { type: "string", description: "Provider conversation/chat/channel id." },
        threadId: { type: "string", description: "Optional provider thread/topic id." },
        messageId: { type: "string", description: "Optional provider message id for deterministic preview ids." },
        senderId: { type: "string", description: "Provider sender/user id." },
        senderLabel: { type: "string", description: "Optional human-readable sender label." },
        text: { type: "string", description: "Normalized inbound text body." },
        receivedAt: { type: "string", description: "Optional ISO timestamp." },
      },
      required: ["providerId", "conversationId", "senderId", "text"],
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "none",
    permissionScope: "messaging-remote-surface-event-preview",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 10_000,
    runtimeSupport: ["chat", "workflow"],
  },
];
