import type { DesktopToolDescriptor } from "./desktopToolDescriptorTypes";

export const messagingGatewaySetupToolDescriptors: DesktopToolDescriptor[] = [
  {
    name: "ambient_messaging_remote_surface_activation_plan",
    label: "Remote Ambient Surface Activation Plan",
    description: "First tool for ordinary owner Remote Ambient Surface setup, activation, repair, or start requests, even when the user names Telegram, Signal, or another provider. It routes reviewed providers through the product activation-plan-first flow without provider message reads and returns repair guidance for unsupported providers.",
    promptSnippet: "ambient_messaging_remote_surface_activation_plan: Always start here for ordinary requests to set up, activate, repair, or start remote control of Ambient through Telegram or another messaging provider, even when the provider is named.",
    promptGuidelines: [
      "Use this first when the user asks to set up, activate, repair, or start remote control of Ambient Desktop through a messaging provider, including requests that explicitly say Telegram, Signal, WhatsApp, Matrix, Discord, Slack, SMS, or another provider.",
      "Do not skip directly to a provider-specific activation plan for ordinary setup/start/repair wording; this product shortcut decides whether a reviewed provider route exists and what tool is safe next.",
      "For Telegram, this product shortcut routes to ambient_messaging_telegram_owner_loop_activation_plan; call that activation plan next before low-level lifecycle, directory, handoff, binding, polling, command, or relay tools.",
      "If the provider is missing or unsupported, surface this tool's unsupported_provider repair/status prompts in chat; do not call generic Messaging Connector setup, provider-specific low-level tools, provider UIs, shell, browser automation, provider CLIs, or arbitrary history reads.",
      "Use the repair/status prompts returned by this tool as authoritative guidance for provider readiness, owner handoff, binding creation, polling start, and minReceivedAt freshness anchors.",
      "This shortcut is read-only: it does not start bridges, list provider chats, read provider messages, read history, mutate bindings, start polling, or send provider messages.",
      "Keep owner Remote Ambient Surface separate from chat-with-others messaging connectors.",
      "This is read-only and safe in planner/headless contexts.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        requestText: { type: "string", description: "Optional user request text, used only to infer provider words like Telegram or Signal." },
        providerId: { type: "string", description: "Optional exact provider id, for example telegram-tdlib." },
        provider: { type: "string", description: "Optional natural provider name, for example Telegram." },
        profileId: { type: "string", description: "Optional local provider auth profile id if already selected." },
        conversationId: { type: "string", description: "Optional provider conversation/chat id if already selected through a reviewed metadata-only directory." },
        setupCode: { type: "string", description: "Optional exact setup code for owner handoff." },
        ownerUserId: { type: "string", description: "Optional owner sender id returned by owner handoff when already known." },
        ownerHandoffSourceMessageId: { type: "string", description: "Optional owner handoff source message id to carry into binding creation." },
        bindingId: { type: "string", description: "Optional active Remote Ambient Surface binding id." },
        ambientSurface: { type: "string", enum: ["chat", "projects", "workflow_agents", "settings", "notifications"], description: "Optional target Ambient surface. Defaults to projects." },
        maxDisclosureLabel: { type: "string", description: "Optional disclosure ceiling. Defaults downstream to owner-private-runtime-summary." },
        minReceivedAt: { type: "string", description: "Optional ISO freshness anchor to carry into polling." },
        intervalMs: { type: "number", description: "Optional periodic polling interval in milliseconds." },
        limit: { type: "number", description: "Optional bounded unread/directory limit." },
      },
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "none",
    permissionScope: "messaging-remote-surface-activation-plan",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 10_000,
    runtimeSupport: ["chat", "workflow"],
  },
  {
    name: "ambient_messaging_remote_surface_provider_support_plan",
    label: "Remote Surface Provider Support Plan",
    description: "Read-only provider-support planning tool for unsupported Remote Ambient Surface providers such as Signal, WhatsApp, Matrix, Discord, Slack, or SMS. It captures adapter requirements, owner-auth constraints, headless support, approval gates, and validation targets without starting provider lifecycle or reading/sending provider messages.",
    promptSnippet: "ambient_messaging_remote_surface_provider_support_plan: Use only after ambient_messaging_remote_surface_activation_plan returns unsupported_provider, or when the owner explicitly asks to plan future reviewed Remote Ambient Surface provider support.",
    promptGuidelines: [
      "Call this after ambient_messaging_remote_surface_activation_plan returns unsupported_provider and the user asks to plan future reviewed support for that provider.",
      "This is planning-only provider onboarding. Do not implement, scaffold, install dependencies, link accounts/devices, run provider validation, start bridges, list chats, read provider messages/history, mutate bindings, start polling, or send provider messages.",
      "Do not call provider-specific low-level tools, provider desktop UI, shell, browser automation, provider CLIs, generic Messaging Connector setup, arbitrary history reads, provider message reads, provider sends, lifecycle/binding/polling/apply tools, or future-provider scaffolding unless the owner explicitly approves implementation after this plan.",
      "For Signal, Signal Desktop being installed is not a Remote Ambient Surface activation route. Plan a reviewed headless-capable adapter with explicit account/device-link setup, owner authentication, and preview/apply controls.",
      "The plan should discuss adapter requirements, owner-auth constraints, headless/no-GUI support, approval gates, and validation targets, then ask for approval before implementation.",
      "Keep owner Remote Ambient Surface separate from chat-with-others messaging connectors.",
      "This is read-only and safe in planner/headless contexts.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        requestText: { type: "string", description: "Optional user request text, used only to infer the unsupported provider." },
        providerId: { type: "string", description: "Optional provider id, for example signal-cli." },
        provider: { type: "string", description: "Optional natural provider name, for example Signal." },
        ambientSurface: { type: "string", enum: ["chat", "projects", "workflow_agents", "settings", "notifications"], description: "Optional target Ambient surface. Defaults to projects." },
        blockerContext: { type: "string", description: "Optional concise unsupported-provider blocker text from the latest activation card/tool result." },
      },
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "none",
    permissionScope: "messaging-remote-surface-provider-support-plan",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 10_000,
    runtimeSupport: ["chat", "workflow"],
  },
  {
    name: "ambient_messaging_list_providers",
    label: "Ambient Messaging Providers",
    description: "List Ambient runtime messaging providers and their purpose/headless readiness metadata.",
    promptSnippet: "ambient_messaging_list_providers: List installed Ambient messaging providers and headless readiness.",
    promptGuidelines: [
      "Use this before attempting messaging-provider setup, Remote Ambient Surface routing, or external Messaging Connector work.",
      "Messaging providers are transport surfaces. Do not infer permission to expose project, workflow, settings, or chat state from provider availability alone.",
      "Check purpose support before deciding whether a provider can be used for remote Ambient control or external messaging.",
      "Check headless-ready metadata when the user asks about server/Linux/no-GUI operation.",
      "For Remote Ambient Surface setup across providers, use ambient_messaging_remote_surface_binding_preview or ambient_messaging_remote_surface_event_preview before any provider-specific tools.",
      "This is read-only and safe in planner/headless contexts.",
    ],
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "none",
    permissionScope: "messaging-provider-read",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 10_000,
    runtimeSupport: ["chat", "workflow"],
  },
  {
    name: "ambient_messaging_provider_status",
    label: "Ambient Messaging Provider Status",
    description: "Inspect one Ambient runtime messaging provider by provider id.",
    promptSnippet: "ambient_messaging_provider_status: Inspect a specific Ambient messaging provider by providerId.",
    promptGuidelines: [
      "Call ambient_messaging_list_providers first unless the user supplied an exact providerId.",
      "Use the exact providerId returned by ambient_messaging_list_providers.",
      "Use this to inspect auth shape, event modes, purpose support, headless readiness, limits, and repair hints.",
      "Do not use provider CLIs, shell commands, or app-bundle docs just to inspect provider status.",
      "This is read-only and safe in planner/headless contexts.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        providerId: {
          type: "string",
          description: "Exact messaging provider id, for example telegram-tdlib.",
        },
      },
      required: ["providerId"],
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "none",
    permissionScope: "messaging-provider-read",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 10_000,
    runtimeSupport: ["chat", "workflow"],
  },
  {
    name: "ambient_messaging_telegram_owner_loop_activation_plan",
    label: "Telegram Owner Loop Activation Plan",
    description: "Second-step Telegram Remote Ambient Surface planner. Use after ambient_messaging_remote_surface_activation_plan routes to Telegram, or for explicit Telegram-plan diagnostics, without provider message reads.",
    promptSnippet: "ambient_messaging_telegram_owner_loop_activation_plan: Second-step planner after ambient_messaging_remote_surface_activation_plan routes ordinary setup/start/repair requests to Telegram.",
    promptGuidelines: [
      "For ordinary requests to set up, activate, repair, or start Telegram remote control of Ambient Desktop, call ambient_messaging_remote_surface_activation_plan first, then call this only if that shortcut selects Telegram.",
      "Use this directly only when the user explicitly asks to inspect the Telegram activation plan itself or when ambient_messaging_remote_surface_activation_plan already returned this as the recommended next tool.",
      "Call this before low-level Telegram directory, owner handoff, binding, or polling tools when the activation sequence is not already fully known.",
      "Follow the phase tool sequences returned by the plan. Do not skip typed preview tools, and call apply tools only after explicit approval.",
      "This plan tool is read-only: it does not start bridges, list provider chats, read provider messages, read history, create/revoke bindings, start polling, or send provider messages.",
      "For a fresh owner loop, the sequence is provider readiness, metadata-only directory, exact setup-code owner handoff, typed Remote Ambient Surface binding, periodic polling start, gateway status, command preview/apply, and relay preview.",
      "When starting periodic polling after handoff/setup/activation, pass minReceivedAt from the activation or first-command boundary so old unread backlog is marked stale.",
      "Keep Remote Ambient Surface separate from external Messaging Connector use; this path is owner-authenticated Ambient control only.",
      "This is read-only and safe in planner/headless contexts.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        profileId: { type: "string", description: "Optional local Telegram auth profile id if already selected." },
        conversationId: { type: "string", description: "Optional Telegram conversation/chat id if already selected from metadata-only directory." },
        setupCode: { type: "string", description: "Optional exact setup code the owner will send or has sent for owner handoff." },
        ownerUserId: { type: "string", description: "Optional owner sender id returned by owner handoff when already known." },
        ownerHandoffSourceMessageId: { type: "string", description: "Optional sourceMessageId returned by owner handoff; carry into binding creation." },
        bindingId: { type: "string", description: "Optional active Remote Ambient Surface binding id to plan polling for." },
        ambientSurface: { type: "string", enum: ["chat", "projects", "workflow_agents", "settings", "notifications"], description: "Optional target Ambient surface. Defaults to projects in plan guidance." },
        maxDisclosureLabel: { type: "string", description: "Optional disclosure ceiling. Defaults to owner-private-runtime-summary." },
        minReceivedAt: { type: "string", description: "Optional ISO freshness anchor to carry into polling preview/apply." },
        intervalMs: { type: "number", description: "Optional periodic polling interval in milliseconds. Defaults to 30000." },
        limit: { type: "number", description: "Optional bounded unread/directory limit to carry through plan guidance. Defaults to 10, capped at 25." },
      },
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "none",
    permissionScope: "messaging-telegram-owner-loop-activation-plan",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 10_000,
    runtimeSupport: ["chat", "workflow"],
  },
  {
    name: "ambient_messaging_telegram_session_preview",
    label: "Telegram Session Setup Preview",
    description: "Preview Telegram auth-profile/session setup without starting TDLib sessions, reading messages, or sending messages.",
    promptSnippet: "ambient_messaging_telegram_session_preview: Preview Telegram auth-profile/session setup before approval.",
    promptGuidelines: [
      "Use this before any Telegram auth/session setup action.",
      "This preview never starts a bridge, starts TDLib, reads provider messages, ingests events, or sends messages.",
      "Use action=start_auth to preview sending a Telegram login code to the user's phone through Telegram after approval.",
      "Use action=status to preview checking an existing Telegram auth profile after approval.",
      "Code and password submission are reserved for secure Desktop input handoff; never ask the user to paste Telegram codes or passwords into chat.",
      "For action=submit_code or action=submit_password, apply requests the value through the secure Desktop dialog after approval.",
      "Report only presence/absence of phone, code, password, API credentials, and session state; do not echo secret or phone values.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        action: { type: "string", enum: ["start_auth", "status", "submit_code", "submit_password"], description: "Telegram setup action to preview." },
        providerId: { type: "string", description: "Exact provider id. Must be telegram-tdlib when supplied." },
        profileId: { type: "string", description: "Local Telegram auth profile id, for example owner." },
        phoneNumber: { type: "string", description: "Required for action=start_auth. Redacted from all tool output." },
      },
      required: ["action", "profileId"],
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "none",
    permissionScope: "messaging-telegram-session-preview",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 10_000,
    runtimeSupport: ["chat", "workflow"],
  },
  {
    name: "ambient_messaging_telegram_session_apply",
    label: "Telegram Session Setup Apply",
    description: "Apply approved Telegram auth-profile/session setup without reading provider messages, ingesting events, or sending messages.",
    promptSnippet: "ambient_messaging_telegram_session_apply: Apply approved Telegram auth-profile/session setup.",
    promptGuidelines: [
      "Call ambient_messaging_telegram_session_preview first and explain the safety boundary before this tool.",
      "Use this only after explicit user approval.",
      "This tool may launch the supervised Telegram bridge for setup and call minimal auth endpoints only.",
      "This tool must not list chats, read provider messages, ingest events, create bindings, or send provider messages.",
      "For start_auth, tell the user Telegram may send a login code to their phone after approval, but do not echo the phone number in the response.",
      "For submit_code and submit_password, Ambient will request the missing value through a secure dialog after approval.",
      "Never ask for or use chat-pasted codes/passwords.",
      "After success or block, call ambient_messaging_gateway_status to inspect redacted readiness.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        action: { type: "string", enum: ["start_auth", "status", "submit_code", "submit_password"], description: "Telegram setup action to apply." },
        providerId: { type: "string", description: "Exact provider id. Must be telegram-tdlib when supplied." },
        profileId: { type: "string", description: "Local Telegram auth profile id, for example owner." },
        phoneNumber: { type: "string", description: "Required for action=start_auth. Redacted from all tool output." },
      },
      required: ["action", "profileId"],
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "run-process",
    permissionScope: "messaging-telegram-session-apply",
    supportsDryRun: false,
    supportsUndo: false,
    idempotency: "recommended",
    defaultTimeoutMs: 30_000,
    runtimeSupport: ["chat", "workflow"],
  },
  {
    name: "ambient_messaging_signal_session_preview",
    label: "Signal Session Setup Preview",
    description: "Preview recording Ambient-owned Signal local-bridge session metadata without running signal-cli, inspecting Signal Desktop, or reading Signal messages.",
    promptSnippet: "ambient_messaging_signal_session_preview: Preview no-I/O Signal setup metadata recording for the planned local bridge adapter.",
    promptGuidelines: [
      "Use this before any Signal setup metadata apply.",
      "This preview never runs signal-cli, inspects Signal Desktop, starts bridges, reads Signal messages/history/contacts/groups/attachments, sends messages, creates bindings, or enables Signal lifecycle.",
      "Signal Desktop being installed is not enough for Ambient messaging gateway operation; the target is a headless local bridge such as signal-cli.",
      "Only record Ambient-owned setup metadata: profile id, signal-cli config directory presence, and boolean readiness markers.",
      "Do not ask the user to paste phone numbers, Signal service ids, identity keys, registration ids, session keys, device names, contact names, or message text.",
      "If the signal-cli config directory is missing, explain the missing prerequisite instead of trying shell, Signal Desktop UI automation, browser automation, or provider CLI commands.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        providerId: { type: "string", enum: ["signal-cli"], description: "Optional provider id. If supplied, it must be signal-cli." },
        profileId: { type: "string", description: "Local Ambient Signal bridge profile id, for example owner." },
        signalCliConfigDir: { type: "string", description: "Optional signal-cli config directory. Defaults to AMBIENT_SIGNAL_CLI_CONFIG_DIR, SIGNAL_CLI_CONFIG_DIR, or ~/.local/share/signal-cli." },
        accountIdentifierPresent: { type: "boolean", description: "Optional safe marker that account identity metadata exists outside Pi-visible output. Do not provide the actual identifier." },
        linkedDevicePresent: { type: "boolean", description: "Optional safe marker that a linked device/session exists. Do not provide device details." },
        registrationMetadataPresent: { type: "boolean", description: "Optional safe marker that registration metadata exists. Do not provide registration values." },
      },
      required: ["profileId"],
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "none",
    permissionScope: "messaging-signal-session-preview",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 10_000,
    runtimeSupport: ["chat", "workflow"],
  },
  {
    name: "ambient_messaging_signal_session_apply",
    label: "Signal Session Setup Apply",
    description: "With approval, write Ambient-owned Signal local-bridge session metadata while keeping Signal runtime and bindings disabled.",
    promptSnippet: "ambient_messaging_signal_session_apply: Apply approved no-I/O Signal setup metadata recording for the planned local bridge adapter.",
    promptGuidelines: [
      "Call ambient_messaging_signal_session_preview first and explain the safety boundary.",
      "Use this only after explicit user approval.",
      "This writes an Ambient-owned bridge-session metadata file. It does not run signal-cli, inspect Signal Desktop, start bridges, read Signal messages/history/contacts/groups/attachments, send messages, create bindings, or enable Signal lifecycle.",
      "Signal remains implementation planned after apply. Conversation directory, bindings, inbound ingestion, and replies remain blocked until a reviewed local bridge adapter exists.",
      "After apply, call ambient_messaging_gateway_status to inspect redacted Signal readiness.",
      "Never place phone numbers, Signal service ids, identity keys, registration ids, session keys, device names, contact names, or message text in tool arguments.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        providerId: { type: "string", enum: ["signal-cli"], description: "Optional provider id. If supplied, it must be signal-cli." },
        profileId: { type: "string", description: "Local Ambient Signal bridge profile id, for example owner." },
        signalCliConfigDir: { type: "string", description: "Optional signal-cli config directory. Defaults to AMBIENT_SIGNAL_CLI_CONFIG_DIR, SIGNAL_CLI_CONFIG_DIR, or ~/.local/share/signal-cli." },
        accountIdentifierPresent: { type: "boolean", description: "Optional safe marker that account identity metadata exists outside Pi-visible output. Do not provide the actual identifier." },
        linkedDevicePresent: { type: "boolean", description: "Optional safe marker that a linked device/session exists. Do not provide device details." },
        registrationMetadataPresent: { type: "boolean", description: "Optional safe marker that registration metadata exists. Do not provide registration values." },
      },
      required: ["profileId"],
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "write-workspace",
    permissionScope: "messaging-signal-session-apply",
    supportsDryRun: false,
    supportsUndo: false,
    idempotency: "recommended",
    defaultTimeoutMs: 30_000,
    runtimeSupport: ["chat", "workflow"],
  },
  {
    name: "ambient_messaging_list_bindings",
    label: "Ambient Messaging Bindings",
    description: "List purpose-scoped Ambient messaging bindings without starting provider bridges or sending messages.",
    promptSnippet: "ambient_messaging_list_bindings: List Remote Ambient Surface and Messaging Connector bindings.",
    promptGuidelines: [
      "Use this to inspect whether a messaging conversation is already bound to Remote Ambient Surface or Messaging Connector purpose.",
      "Binding purpose controls policy, tools, prompt context, and event projection. Never treat a provider connection as an implicit binding.",
      "This read-only tool does not create bindings, start provider bridges, read external messages, or send messages.",
      "An empty result means no bindings are registered yet; do not improvise a binding in chat.",
      "Use ambient_messaging_conversation_directory_preview when the user asks what provider chats/conversations can be bound.",
      "This is read-only and safe in planner/headless contexts.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        providerId: { type: "string", description: "Optional exact provider id, for example telegram-tdlib." },
        purpose: {
          type: "string",
          enum: ["remote_ambient_surface", "messaging_connector"],
          description: "Optional binding purpose filter.",
        },
        includeInactive: {
          type: "boolean",
          description: "Include paused, revoked, and error bindings. Defaults to false.",
        },
      },
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "none",
    permissionScope: "messaging-binding-read",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 10_000,
    runtimeSupport: ["chat", "workflow"],
  },
  {
    name: "ambient_messaging_conversation_directory_preview",
    label: "Messaging Conversation Directory Preview",
    description: "Preview provider conversation-directory readiness, typed adapter availability, and known Ambient binding conversations without listing provider chats or reading provider history.",
    promptSnippet: "ambient_messaging_conversation_directory_preview: Read-only provider-neutral preview for what conversations can be bound, using safe readiness and existing Ambient bindings.",
    promptGuidelines: [
      "Use this when the user asks what chats, conversations, channels, or threads can be bound to Ambient messaging.",
      "This tool never starts provider bridges, lists provider chats, reads provider messages/history, sends messages, or mutates bindings.",
      "Known conversations come only from existing Ambient binding records. Treat them as routing metadata, not provider chat discovery.",
      "If a Provider directory tool is shown, call that typed preview tool before any provider directory apply. If Provider directory tool is none, do not use shell commands, provider CLIs, browser automation, app UI automation, or provider-specific tools to discover chats.",
      "For Telegram, use ambient_messaging_telegram_conversation_directory_preview/apply instead of shell, browser, Telegram Desktop UI, or provider CLIs.",
      "For Signal, use ambient_messaging_signal_conversation_directory_preview/apply only through the reviewed metadata-only bridge contract; owner binding, unread, polling, and reply capabilities each require their typed Signal tools and approval boundaries.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        providerId: { type: "string", description: "Optional exact provider id, for example telegram-tdlib or signal-cli. Omit to preview all providers." },
        authProfileId: { type: "string", description: "Optional provider auth/session profile id. profileId is also accepted." },
        profileId: { type: "string", description: "Accepted alias for authProfileId." },
        purpose: {
          type: "string",
          enum: ["remote_ambient_surface", "messaging_connector"],
          description: "Optional purpose filter. Defaults to remote_ambient_surface for readiness interpretation.",
        },
        includeInactive: {
          type: "boolean",
          description: "Include inactive/revoked/error Ambient binding records. Defaults to false.",
        },
        limit: {
          type: "number",
          description: "Maximum known auth profiles and binding conversations to include per provider. Defaults to 10, capped at 25.",
        },
      },
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "none",
    permissionScope: "messaging-conversation-directory-preview",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 10_000,
    runtimeSupport: ["chat", "workflow"],
  },
  {
    name: "ambient_messaging_telegram_conversation_directory_preview",
    label: "Telegram Conversation Directory Preview",
    description: "Preview one approval-gated Telegram chat-directory read for sanitized conversation metadata only.",
    promptSnippet: "ambient_messaging_telegram_conversation_directory_preview: Preview a bounded Telegram conversation-directory read through the reviewed local bridge.",
    promptGuidelines: [
      "Use this typed Telegram tool when the user wants to pick, list, or discover Telegram chats/conversations for Ambient messaging binding.",
      "Call this after ambient_messaging_conversation_directory_preview shows Telegram has a Provider directory tool, or when the user specifically asks for Telegram chats.",
      "This preview does not call the Telegram chat-list endpoint, start bridges, read message history, send messages, or create bindings.",
      "Apply is allowed only after Telegram is running in real mode, readiness is configured, the bridge is reachable, and the user explicitly approves one bounded directory read.",
      "Directory apply returns sanitized routing metadata only: conversation id, title, type, unread count, folder ids, and updated time.",
      "Directory apply requests the metadata-only bridge contract and rejects responses that include lastMessage payloads.",
      "After the user chooses a conversation, use the purpose-specific binding preview before any binding apply.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        profileId: { type: "string", description: "Optional local Telegram auth profile id. Required when more than one profile is available." },
        authProfileId: { type: "string", description: "Accepted alias for profileId." },
        query: { type: "string", description: "Optional chat title/user search query. Max 80 characters." },
        unreadOnly: { type: "boolean", description: "Filter to chats with unread count metadata. Defaults to false." },
        folderId: { type: "number", description: "Optional Telegram folder id filter." },
        limit: { type: "number", description: "Maximum conversations to return. Defaults to 10, capped at 25." },
      },
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "none",
    permissionScope: "messaging-telegram-conversation-directory-preview",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 10_000,
    runtimeSupport: ["chat", "workflow"],
  },
  {
    name: "ambient_messaging_telegram_conversation_directory_apply",
    label: "Telegram Conversation Directory Apply",
    description: "With approval, read one bounded Telegram chat directory and return sanitized conversation metadata for binding setup.",
    promptSnippet: "ambient_messaging_telegram_conversation_directory_apply: Apply an approved bounded Telegram conversation-directory read.",
    promptGuidelines: [
      "Call ambient_messaging_telegram_conversation_directory_preview first and explain readiness, approval, and metadata-only boundaries.",
      "Use this only after explicit user approval.",
      "This reads one bounded metadata-only Telegram chat-list endpoint through the reviewed local bridge. It does not start bridges, read message history, create bindings, or send messages.",
      "If the bridge returns lastMessage or other message-shaped payloads, Ambient rejects the result instead of sanitizing it in chat.",
      "Use only the sanitized conversation metadata returned by Ambient.",
      "After apply, use ambient_messaging_telegram_remote_surface_preview for Remote Ambient Surface bindings or the provider-neutral binding preview for Messaging Connector bindings.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        profileId: { type: "string", description: "Optional local Telegram auth profile id. Required when more than one profile is available." },
        authProfileId: { type: "string", description: "Accepted alias for profileId." },
        query: { type: "string", description: "Optional chat title/user search query. Max 80 characters." },
        unreadOnly: { type: "boolean", description: "Filter to chats with unread count metadata. Defaults to false." },
        folderId: { type: "number", description: "Optional Telegram folder id filter." },
        limit: { type: "number", description: "Maximum conversations to return. Defaults to 10, capped at 25." },
      },
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "read-external",
    permissionScope: "messaging-telegram-conversation-directory-apply",
    supportsDryRun: false,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 30_000,
    runtimeSupport: ["chat", "workflow"],
  },
  {
    name: "ambient_messaging_telegram_owner_handoff_preview",
    label: "Telegram Owner Handoff Preview",
    description: "Preview a bounded Telegram owner sender-id handoff for fresh Remote Ambient Surface setup.",
    promptSnippet: "ambient_messaging_telegram_owner_handoff_preview: Preview a one-time setup-code handoff to discover the Telegram ownerUserId needed for Remote Ambient Surface binding creation.",
    promptGuidelines: [
      "Use this after the user has chosen a Telegram conversation but before creating a fresh Remote Ambient Surface binding when ownerUserId is unknown.",
      "Ask the owner to send a unique setup code in that exact Telegram conversation. The code should be single-use and easy to distinguish from normal chat.",
      "Preview is read-only and does not call Telegram unread, sender-profile, chat-list, history, or send endpoints.",
      "Apply is allowed only after Telegram is running in real mode, readiness is configured, the bridge is reachable, and the user explicitly approves one bounded owner handoff read.",
      "Apply reads only the selected conversation's unread endpoint, internally filters by exact setup-code text, resolves sender profiles only for exact matches, and returns only the matched owner sender id.",
      "Do not use Telegram Desktop scraping, browser automation, provider CLIs, or arbitrary history reads to infer owner sender ids.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        profileId: { type: "string", description: "Local Telegram auth profile id." },
        conversationId: { type: "string", description: "Telegram conversation/chat id chosen from the metadata-only directory result." },
        setupCode: { type: "string", description: "Exact single-line setup code the owner will send in the selected Telegram conversation. 6-120 characters." },
        limit: { type: "number", description: "Maximum unread messages to inspect. Defaults to 10, capped at 25." },
      },
      required: ["profileId", "conversationId", "setupCode"],
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "none",
    permissionScope: "messaging-telegram-owner-handoff-preview",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 10_000,
    runtimeSupport: ["chat", "workflow"],
  },
  {
    name: "ambient_messaging_telegram_owner_handoff_apply",
    label: "Telegram Owner Handoff Apply",
    description: "With approval, read one bounded Telegram unread window for an exact setup-code match and return the matched owner sender id.",
    promptSnippet: "ambient_messaging_telegram_owner_handoff_apply: Apply an approved one-time setup-code handoff to discover ownerUserId for a Telegram Remote Ambient Surface binding.",
    promptGuidelines: [
      "Call ambient_messaging_telegram_owner_handoff_preview first and explain the exact safety boundary.",
      "Use this only after explicit user approval and only after the owner has sent the exact setup code in the selected Telegram conversation.",
      "This reads one bounded unread endpoint for the selected conversation and resolves sender profiles only for exact setup-code matches.",
      "This returns no provider message bodies, does not create bindings, does not list chats, does not read history, does not start bridges, and does not send Telegram messages.",
      "If exactly one owner sender is found, use the returned ownerUserId with ambient_messaging_telegram_remote_surface_preview/apply.",
      "Also pass the returned sourceMessageId as ownerHandoffSourceMessageId when creating the binding, so later polling treats the setup-code message as already consumed.",
      "If no match or multiple distinct matches are found, ask the owner to send a fresh unique setup code and repeat the handoff.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        profileId: { type: "string", description: "Local Telegram auth profile id." },
        conversationId: { type: "string", description: "Telegram conversation/chat id chosen from the metadata-only directory result." },
        setupCode: { type: "string", description: "Exact single-line setup code the owner sent in the selected Telegram conversation. 6-120 characters." },
        limit: { type: "number", description: "Maximum unread messages to inspect. Defaults to 10, capped at 25." },
      },
      required: ["profileId", "conversationId", "setupCode"],
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "read-external",
    permissionScope: "messaging-telegram-owner-handoff-apply",
    supportsDryRun: false,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 30_000,
    runtimeSupport: ["chat", "workflow"],
  },
  {
    name: "ambient_messaging_signal_conversation_directory_preview",
    label: "Signal Conversation Directory Preview",
    description: "Preview an approval-gated Signal metadata-only conversation-directory read through a reviewed local bridge contract without reading messages or enabling Signal runtime.",
    promptSnippet: "ambient_messaging_signal_conversation_directory_preview: Preview a bounded Signal metadata-only directory read through the reviewed bridge contract.",
    promptGuidelines: [
      "Use this typed Signal tool when the user asks about Signal conversation discovery, Signal Remote Ambient Surface setup, or the planned Signal adapter contract.",
      "This preview does not call the Signal directory endpoint, start bridges, run signal-cli, inspect Signal Desktop, read message history, send messages, or create bindings.",
      "Apply is allowed only when Signal readiness has accepted the reviewed bridge root/profile status contract, the bridge advertises metadataOnlyConversationDirectory, and a bridge-readable profile is selected.",
      "Directory apply returns sanitized routing metadata only: conversation id, title, type, unread count, folder ids, and updated time.",
      "Do not use shell commands, provider CLIs, browser automation, app UI automation, Signal Desktop storage, or Telegram-specific tools to discover Signal conversations.",
      "Signal Desktop being installed is not enough; the target is a headless local bridge with safe readiness and metadata-only routing rows.",
      "Directory metadata alone does not authorize binding, unread, polling, or reply behavior; use the typed Signal owner handoff, binding, unread, polling, and reply tools for those separately reviewed paths.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        providerId: { type: "string", enum: ["signal-cli"], description: "Optional provider id. If supplied, it must be signal-cli." },
        profileId: { type: "string", description: "Optional future Signal local bridge auth/session profile id." },
        authProfileId: { type: "string", description: "Accepted alias for profileId." },
        purpose: {
          type: "string",
          enum: ["remote_ambient_surface", "messaging_connector"],
          description: "Optional purpose to evaluate. Defaults to remote_ambient_surface.",
        },
        query: { type: "string", description: "Optional conversation title/contact query. Max 80 characters." },
        limit: { type: "number", description: "Maximum conversations to return. Defaults to 10, capped at 25." },
      },
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "none",
    permissionScope: "messaging-signal-conversation-directory-preview",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 10_000,
    runtimeSupport: ["chat", "workflow"],
  },
  {
    name: "ambient_messaging_signal_conversation_directory_apply",
    label: "Signal Conversation Directory Apply",
    description: "With approval, read one bounded Signal conversation directory from a reviewed local bridge and return sanitized metadata for setup.",
    promptSnippet: "ambient_messaging_signal_conversation_directory_apply: Apply an approved bounded Signal metadata-only directory read.",
    promptGuidelines: [
      "Call ambient_messaging_signal_conversation_directory_preview first and explain readiness, approval, and metadata-only boundaries.",
      "Use this only after explicit user approval.",
      "This reads one bounded metadata-only Signal conversation-directory endpoint through the reviewed local bridge. It does not start bridges, run signal-cli, inspect Signal Desktop, read message history, create bindings, or send messages.",
      "If the bridge returns lastMessage, text, body, or other message-shaped payload fields, Ambient rejects the result instead of sanitizing it in chat.",
      "Use only the sanitized conversation metadata returned by Ambient.",
      "Directory metadata apply does not authorize binding, unread, polling, or reply behavior; use the typed Signal owner handoff, binding, unread, polling, and reply tools for those separately reviewed paths.",
      "Do not retry blocked Signal discovery with shell, browser, provider CLI, Signal Desktop automation, or Telegram-specific tools.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        providerId: { type: "string", enum: ["signal-cli"], description: "Optional provider id. If supplied, it must be signal-cli." },
        profileId: { type: "string", description: "Optional future Signal local bridge auth/session profile id." },
        authProfileId: { type: "string", description: "Accepted alias for profileId." },
        purpose: {
          type: "string",
          enum: ["remote_ambient_surface", "messaging_connector"],
          description: "Optional purpose to evaluate. Defaults to remote_ambient_surface.",
        },
        query: { type: "string", description: "Optional conversation title/contact query. Max 80 characters." },
        limit: { type: "number", description: "Maximum conversations to return. Defaults to 10, capped at 25." },
      },
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "read-external",
    permissionScope: "messaging-signal-conversation-directory-apply",
    supportsDryRun: false,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 30_000,
    runtimeSupport: ["chat", "workflow"],
  },
  {
    name: "ambient_messaging_signal_unread_window_preview",
    label: "Signal Unread Window Preview",
    description: "Preview whether a bounded fake-bridge Signal unread-window read can route owner Remote Ambient Surface projections without returning message bodies.",
    promptSnippet: "ambient_messaging_signal_unread_window_preview: Preview the bounded Signal unread-window contract before calling the approval-gated apply tool.",
    promptGuidelines: [
      "Call this typed Signal preview before any Signal unread-window apply.",
      "Apply is available only when the reviewed fake bridge apply flag is enabled, the bridge readiness is accepted, and the input names one exact active owner Remote Ambient Surface binding.",
      "Use the Real Signal unread readiness section to distinguish fake-ready dogfood from the future approval-gated real single-read contract.",
      "Do not poll Signal through shell, browser, Signal Desktop, provider CLIs, generic binding tools, or Telegram-specific tools.",
      "Unread message bodies may only be consumed inside the adapter for dispatch routing; they must never be returned directly to Pi in tool text or details.",
      "Signal lifecycle and broad inbound ingestion remain disabled; polling and outbound replies are separate typed, approval-gated Signal paths.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        providerId: { type: "string", enum: ["signal-cli"], description: "Optional provider id. If supplied, it must be signal-cli." },
        profileId: { type: "string", description: "Optional local Signal bridge profile id. authProfileId is also accepted." },
        authProfileId: { type: "string", description: "Accepted alias for profileId." },
        conversationId: { type: "string", description: "Optional Signal conversation id from the metadata-only directory result." },
        bindingId: { type: "string", description: "Optional exact active Remote Ambient Surface binding id. Future apply must require this." },
        limit: { type: "number", description: "Future max unread messages per binding. Defaults to 10, capped at 25." },
      },
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "none",
    permissionScope: "messaging-signal-unread-window-preview",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 10_000,
    runtimeSupport: ["chat", "workflow"],
  },
  {
    name: "ambient_messaging_signal_unread_window_apply",
    label: "Signal Unread Window Apply",
    description: "With approval, read one bounded fake-bridge Signal unread window for an exact active owner binding and route sanitized Remote Ambient Surface dispatches.",
    promptSnippet: "ambient_messaging_signal_unread_window_apply: Approval-gated fake-bridge Signal unread-window read for one exact Remote Ambient Surface binding.",
    promptGuidelines: [
      "Call ambient_messaging_signal_unread_window_preview first and apply only when it reports ready.",
      "Use only with an exact active Signal Remote Ambient Surface bindingId and the matching profileId/conversationId from that binding.",
      "This reads exactly one bounded fake-bridge unread-window endpoint, drops duplicates, outgoing messages, empty messages, and wrong-sender messages, and routes accepted owner messages through the Remote Ambient Surface dispatch path.",
      "The tool result returns only counts, message ids, queued projection ids/titles/kinds, and dropped reasons. It must not return provider message bodies in text or details.",
      "This does not start Signal, inspect Signal Desktop, run signal-cli, create/revoke bindings, start periodic polling, or send Signal messages.",
      "If blocked or failed, do not retry with shell, browser, Signal Desktop UI, provider CLIs, generic binding tools, or Telegram-specific tools.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        providerId: { type: "string", enum: ["signal-cli"], description: "Optional provider id. If supplied, it must be signal-cli." },
        profileId: { type: "string", description: "Exact local Signal bridge profile id from the active binding. authProfileId is also accepted." },
        authProfileId: { type: "string", description: "Accepted alias for profileId." },
        conversationId: { type: "string", description: "Exact Signal conversation id from the active binding." },
        bindingId: { type: "string", description: "Required exact active Signal Remote Ambient Surface binding id." },
        limit: { type: "number", description: "Max unread messages to read once. Defaults to 10, capped at 25." },
      },
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "read-external",
    permissionScope: "messaging-signal-unread-window-apply",
    supportsDryRun: false,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 30_000,
    runtimeSupport: ["chat", "workflow"],
  },
  {
    name: "ambient_messaging_signal_unread_window_status",
    label: "Signal Unread Window Status",
    description: "Read Signal unread-window dedupe state, fake-vs-real readiness, and queued Signal Remote Ambient Surface projections without reading provider messages.",
    promptSnippet: "ambient_messaging_signal_unread_window_status: Inspect Signal unread-window dedupe/projection status after fake-bridge apply or when explaining blocked real Signal ingestion.",
    promptGuidelines: [
      "Use this after ambient_messaging_signal_unread_window_apply to inspect dedupe state, duplicate/idempotency behavior, and queued Signal projections.",
      "Use this when explaining the difference between the reviewed fake-bridge dogfood apply path and future real Signal unread ingestion.",
      "This is read-only: it does not start Signal, inspect Signal Desktop, run signal-cli, poll unread windows, read provider message bodies, mutate bindings, or send Signal messages.",
      "The result may include message ids, counts, timestamps, binding ids, queued projection ids/titles/kinds, and blocked diagnostics; it must not include provider message bodies.",
      "The real readiness status fake-ready means only the reviewed fake-bridge dogfood apply path is enabled; real-ready-for-approved-single-read means the contract gates are satisfied but real apply is still not implemented in this build.",
      "If real Signal ingestion is blocked, do not retry with shell, browser, Signal Desktop UI, provider CLIs, generic binding tools, or Telegram-specific tools.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        providerId: { type: "string", enum: ["signal-cli"], description: "Optional provider id. If supplied, it must be signal-cli." },
        profileId: { type: "string", description: "Optional local Signal bridge profile id. authProfileId is also accepted." },
        authProfileId: { type: "string", description: "Accepted alias for profileId." },
        conversationId: { type: "string", description: "Optional Signal conversation id to inspect." },
        bindingId: { type: "string", description: "Optional exact Signal Remote Ambient Surface binding id to inspect." },
        includeInactive: { type: "boolean", description: "When true, include paused/revoked/error Signal Remote Ambient Surface bindings. Defaults to false." },
      },
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "none",
    permissionScope: "messaging-signal-unread-window-status-read",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 10_000,
    runtimeSupport: ["chat", "workflow"],
  },
];
