import type { DesktopToolDescriptor } from "./desktopToolDescriptorTypes";

export const mcpAutowireToolDescriptors: DesktopToolDescriptor[] = [
  {
    name: "ambient_mcp_autowire_plan",
    label: "MCP Autowire Plan",
    description: "Analyze a GitHub URL, MCP metadata URL, or package target with bounded discovery and produce either a validated Ambient MCP install-lane candidate or a normal-app setup handoff without installing anything.",
    promptSnippet:
      "ambient_mcp_autowire_plan: Analyze a GitHub URL, MCP metadata page, or package target with bounded discovery and return a validated install-lane recommendation or normal-app setup handoff without installing.",
    promptGuidelines: [
      "Use ambient_mcp_autowire_plan for arbitrary GitHub URLs, MCP registry pages, awesome-mcp entries, or package targets such as npm:@scope/name and pypi:package-name before choosing an MCP, CLI, guided setup, or normal application setup path.",
      "For user prompts such as install this MCP, install this capability, add this server, or install this GitHub URL, call this planner before shell, git clone, curl, browser inspection, package-manager installs, or raw ToolHive commands.",
      "Pass the targetUrl/package target, optional schema/planning instructions, and only the discovery grants the user allowed. URL reads are bounded and policy-filtered by Desktop.",
      "This tool is read-only: it may fetch approved evidence URLs, but it does not install servers, start containers, call MCP tools, write package state, or run arbitrary source code.",
      "After this tool returns candidate evidence ids, use ambient_mcp_autowire_evidence_read for exact bounded evidence snippets instead of ad hoc network or shell reads.",
      "If the result classifies the source as normal_app or containerized_app and does not return a candidateRef, do not call ambient_mcp_autowire_review. Continue with ordinary setup using normal file, shell, browser, and ambient_setup_runtime_preflight before dependency installs.",
      "Read the returned blockers, warnings, evidence, runtime source, and recommended lane before proceeding. Registry-backed Standard MCP servers use ambient_mcp_server_search/describe/install; supported package-backed Standard MCP candidates go through ambient_mcp_autowire_review and ambient_mcp_standard_import_describe/install.",
      "When a project documents several install options, prefer supported Ambient lanes over deferred alternatives: ToolHive/default registry, hosted Remote MCP through ToolHive proxy, package-backed server.json/npm/PyPI/OCI Standard MCP, guided-local bridge, CLI wrapper, then exploratory. MCPB metadata is recognized but deferred until ToolHive MCPB execution is validated.",
      "For remote MCP candidates, show the remote endpoint and network/secret implications to the user. For guided-local-bridge candidates such as GhidraMCP, present manual setup steps rather than trying to containerize the local app bridge.",
      "Prefer progressive discovery. Do not dump a full plugin inventory into context or treat this planner as a generic web browser.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        targetUrl: {
          type: "string",
          description: "HTTPS GitHub repository, MCP metadata, registry, or awesome-mcp URL to analyze, or a package target such as npm:@scope/name, npm:package-name, pypi:package-name, or a scoped npm identifier.",
        },
        instructions: {
          type: "string",
          description: "Optional schema or planning instructions to apply while creating the candidate descriptor.",
        },
        allowedDiscovery: {
          type: "object",
          properties: {
            urlFetch: {
              type: "boolean",
              description: "Allow bounded URL reads for evidence. Defaults to true.",
            },
            githubRaw: {
              type: "boolean",
              description: "Allow raw.githubusercontent.com reads from the same GitHub repository. Defaults to true.",
            },
            search: {
              type: "boolean",
              description: "Allow bounded target-source discovery when supported. Current support searches only the target GitHub repository file tree.",
            },
            maxFetches: {
              type: "number",
              description: "Maximum approved URL reads. Defaults to 6 and is capped at 10.",
            },
            maxSearches: {
              type: "number",
              description: "Maximum approved source searches. Defaults to 2 and is capped at 5.",
            },
            maxBytesPerFetch: {
              type: "number",
              description: "Maximum characters returned from each fetched URL. Defaults to 24000 and is capped at 80000.",
            },
          },
          additionalProperties: false,
        },
      },
      required: ["targetUrl"],
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "read-external",
    permissionScope: "mcp-autowire-discovery",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 180_000,
    runtimeSupport: ["chat"],
  },
  {
    name: "ambient_mcp_autowire_review",
    label: "MCP Autowire Review",
    description: "Validate one MCP autowire candidate and return the deterministic install-lane handoff before any install or runtime import.",
    promptSnippet:
      "ambient_mcp_autowire_review: Validate an MCP autowire candidate JSON object and return the exact supported handoff path before installing anything.",
    promptGuidelines: [
      "Use ambient_mcp_autowire_review after ambient_mcp_autowire_plan returns Candidate JSON and before any MCP server install/import attempt.",
      "Prefer candidateRef when ambient_mcp_autowire_plan provides one; otherwise pass the candidate object exactly as returned by ambient_mcp_autowire_plan. Include expectedCandidateHash when available to detect stale or edited candidates.",
      "This tool is read-only. It validates candidate schema, evidence references, secrets, permissions, lane/runtime consistency, and whether the candidate maps to a currently supported Ambient runtime path.",
      "A toolhive-registry-install handoff proceeds to ambient_mcp_server_describe. A standard-mcp-import handoff proceeds to ambient_mcp_standard_import_describe. A remote-mcp-proxy handoff proceeds to ambient_mcp_remote_proxy_describe. A guided-local-bridge handoff proceeds to ambient_mcp_guided_bridge_describe for setup guidance and exact loopback preflight targets.",
      "Never use this tool to run package managers, connect to remote MCP endpoints, start local bridges, or bypass Ambient-managed secret entry.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        candidate: {
          type: "object",
          description: "Exact MCP autowire candidate JSON object returned by ambient_mcp_autowire_plan.",
          additionalProperties: true,
        },
        candidateRef: {
          type: "string",
          description: "Ambient-issued candidate reference from ambient_mcp_autowire_plan. Prefer this over re-sending a large candidate object when available.",
        },
        expectedCandidateHash: {
          type: "string",
          description: "Optional candidate hash from ambient_mcp_autowire_plan. If provided and stale, review is blocked.",
        },
        secretBindings: {
          type: "array",
          description: "Optional Ambient-managed secret references for declared candidate secrets. Never include secret values.",
          items: {
            type: "object",
            properties: {
              envName: { type: "string", description: "Declared environment variable name, for example CONTEXT7_API_KEY." },
              secretRef: { type: "string", description: "Ambient-managed secret reference, not a raw secret value." },
            },
            required: ["envName", "secretRef"],
            additionalProperties: false,
          },
        },
      },
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "none",
    permissionScope: "mcp-autowire-discovery",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 30_000,
    runtimeSupport: ["chat"],
  },
  {
    name: "ambient_mcp_autowire_evidence_read",
    label: "MCP Autowire Evidence Read",
    description: "Read one bounded HTTPS evidence item already attached to an MCP autowire candidate.",
    promptSnippet:
      "ambient_mcp_autowire_evidence_read: Read exact bounded evidence from a candidate evidence id instead of using curl or ad hoc network commands.",
    promptGuidelines: [
      "Use this when an MCP autowire candidate has an evidence id and you need the exact README, manifest, or source snippet before choosing the next typed MCP lane.",
      "Pass candidateRef when available and an exact evidenceId from the candidate. This tool only fetches the candidate's own HTTPS evidence locator.",
      "Do not use raw curl/wget/bash to read evidence that is already referenced by an autowire candidate.",
      "This tool is read-only and bounded. It does not install, clone, build, run, or modify state.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        candidate: {
          type: "object",
          description: "Exact MCP autowire candidate JSON object returned by ambient_mcp_autowire_plan/review.",
          additionalProperties: true,
        },
        candidateRef: {
          type: "string",
          description: "Ambient-issued candidate reference. Prefer this over re-sending a large candidate object when available.",
        },
        evidenceId: {
          type: "string",
          description: "Evidence id from candidate.evidence, for example source-readme.",
        },
        maxBytes: {
          type: "number",
          description: "Maximum characters to return. Defaults to 40000 and is capped at 80000.",
        },
      },
      required: ["evidenceId"],
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "read-external",
    permissionScope: "mcp-autowire-discovery",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "required",
    defaultTimeoutMs: 30_000,
    runtimeSupport: ["chat"],
  },
  {
    name: "ambient_mcp_autowire_plan_revision_list",
    label: "MCP Autowire Revision List",
    description: "List durable MCP autowire candidate plan revisions recorded by Ambient for this workspace.",
    promptSnippet:
      "ambient_mcp_autowire_plan_revision_list: List recorded MCP autowire plan revisions before editing, repairing, or resuming an install candidate.",
    promptGuidelines: [
      "Use this when you need the latest recorded Autowire candidate after a reset, restart, failed install, or repair discussion.",
      "Filter by candidateRef, candidateHash, serverId, or workloadName when you have one. Keep the result bounded with limit.",
      "This tool is read-only. It does not install, edit, repair, or mutate ToolHive.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        candidateRef: { type: "string", description: "Optional Ambient-issued candidate reference to filter revisions." },
        candidateHash: { type: "string", description: "Optional candidate hash to filter revisions." },
        serverId: { type: "string", description: "Optional MCP server id to filter revisions." },
        workloadName: { type: "string", description: "Optional Ambient ToolHive workload name to filter revisions." },
        limit: { type: "number", description: "Maximum revisions to return. Defaults to 50 and is capped by Desktop." },
      },
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "none",
    permissionScope: "mcp-autowire-discovery",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 30_000,
    runtimeSupport: ["chat"],
  },
  {
    name: "ambient_mcp_autowire_plan_revision_read",
    label: "MCP Autowire Revision Read",
    description: "Read one durable MCP autowire candidate plan revision, including exact candidate JSON and validation status.",
    promptSnippet:
      "ambient_mcp_autowire_plan_revision_read: Read one recorded MCP autowire plan revision by revisionId before editing or repairing it.",
    promptGuidelines: [
      "Use this after ambient_mcp_autowire_plan_revision_list when you need the exact candidate JSON or validation state.",
      "Prefer revisionId over re-planning when the task is to edit or repair a known candidate.",
      "This tool is read-only. It does not install, edit, repair, or mutate ToolHive.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        revisionId: { type: "string", description: "Exact revisionId returned by ambient_mcp_autowire_plan_revision_list or an edit/apply tool." },
      },
      required: ["revisionId"],
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "none",
    permissionScope: "mcp-autowire-discovery",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 30_000,
    runtimeSupport: ["chat"],
  },
  {
    name: "ambient_mcp_autowire_plan_edit_describe",
    label: "MCP Autowire Edit Describe",
    description: "Preview typed edits to an MCP autowire candidate plan without recording them.",
    promptSnippet:
      "ambient_mcp_autowire_plan_edit_describe: Preview typed Autowire plan edits such as adding network hosts, mounts, fixed args, secret declarations, or validation targets.",
    promptGuidelines: [
      "Use this when an install or validation reveals the Autowire plan needs a bounded correction. Do not edit ToolHive permission profiles, manifests, state files, or generated package files directly.",
      "Prefer revisionId or candidateRef. Pass operations as typed JSON objects; Desktop validates the edited candidate and reports whether the edit expands permissions.",
      "This tool is a dry run. If the user approves the preview, call ambient_mcp_autowire_plan_edit_apply with the same inputs.",
      "Supported operations include network.allowlist.add, network.mode.set, filesystem.mount.add/remove, runtime.packageArgument.add/remove, secret.declare, validation.expectedTools.add, and validation.smokeCall.set.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        revisionId: { type: "string", description: "Preferred recorded plan revision to edit." },
        candidateRef: { type: "string", description: "Ambient-issued candidate reference when revisionId is unavailable." },
        candidate: { type: "object", description: "Exact MCP autowire candidate JSON when no revisionId or candidateRef exists.", additionalProperties: true },
        expectedCandidateHash: { type: "string", description: "Optional current candidate hash to prevent stale edits." },
        reason: { type: "string", description: "Brief reason for the edit, shown in revision history and approval." },
        operations: {
          type: "array",
          description: "Typed Autowire edit operations.",
          items: { type: "object", additionalProperties: true },
        },
      },
      required: ["operations"],
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "none",
    permissionScope: "mcp-autowire-discovery",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "required",
    defaultTimeoutMs: 30_000,
    runtimeSupport: ["chat"],
  },
  {
    name: "ambient_mcp_autowire_plan_edit_apply",
    label: "MCP Autowire Edit Apply",
    description: "After explicit user approval, record a typed edit to an MCP autowire candidate plan and return the reviewed handoff path.",
    promptSnippet:
      "ambient_mcp_autowire_plan_edit_apply: With explicit user approval, record typed Autowire plan edits and return the next review handoff. Never mutate raw ToolHive state for plan repair.",
    promptGuidelines: [
      "Use only after ambient_mcp_autowire_plan_edit_describe shows the exact edits and the user gives explicit user approval.",
      "This records a new candidate revision and candidateRef; it does not install, restart, or edit raw ToolHive files.",
      "After apply, call ambient_mcp_autowire_review with the returned candidateRef and expectedCandidateHash before install or re-install.",
      "Never use shell, git, sed, or direct ToolHive profile edits to make the same change.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        revisionId: { type: "string", description: "Preferred recorded plan revision to edit." },
        candidateRef: { type: "string", description: "Ambient-issued candidate reference when revisionId is unavailable." },
        candidate: { type: "object", description: "Exact MCP autowire candidate JSON when no revisionId or candidateRef exists.", additionalProperties: true },
        expectedCandidateHash: { type: "string", description: "Optional current candidate hash to prevent stale edits." },
        reason: { type: "string", description: "Brief reason for the edit, shown in revision history and approval." },
        operations: {
          type: "array",
          description: "Typed Autowire edit operations.",
          items: { type: "object", additionalProperties: true },
        },
      },
      required: ["operations"],
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "write-external",
    permissionScope: "mcp-autowire-plan-edit",
    supportsDryRun: false,
    supportsUndo: false,
    idempotency: "required",
    defaultTimeoutMs: 30_000,
    runtimeSupport: ["chat"],
  },
  {
    name: "ambient_mcp_autowire_source_build_describe",
    label: "MCP Source Build Describe",
    description: "Derive a pinned Ambient-managed ToolHive source-build plan for a GitHub source-only MCP candidate.",
    promptSnippet:
      "ambient_mcp_autowire_source_build_describe: Derive the pinned commit, generated or existing Dockerfile recipe, image tag, and exact source-build create call for a GitHub MCP source.",
    promptGuidelines: [
      "Use this immediately after ambient_mcp_autowire_review returns a custom-source-build handoff.",
      "Prefer candidateRef and expectedCandidateHash from the review result. Do not rerun autowire planning when a valid candidateRef is available.",
      "This tool is read-only except for bounded commit resolution. It does not clone, build, run, install, or modify ToolHive state.",
      "If it returns ready-to-build, call ambient_mcp_autowire_source_build_create with the exact sourceBuild plan after approval.",
      "Do not use guided-local bridge, raw git clone, cargo build, README install scripts, claude mcp add, or raw ToolHive commands for source-only MCP install requests.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        candidate: {
          type: "object",
          description: "Exact MCP autowire candidate JSON object returned by ambient_mcp_autowire_plan/review.",
          additionalProperties: true,
        },
        candidateRef: {
          type: "string",
          description: "Ambient-issued candidate reference. Prefer this over re-sending a large candidate object when available.",
        },
        expectedCandidateHash: {
          type: "string",
          description: "Candidate hash from ambient_mcp_autowire_review.",
        },
        ref: {
          type: "string",
          description: "Optional Git ref to resolve. Defaults to HEAD. A full commit hash is accepted.",
        },
        sourceBuild: {
          type: "object",
          description: "Optional reviewed sourceBuild override. Omit to let Ambient derive the standard source-build plan.",
          additionalProperties: true,
        },
      },
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "read-external",
    permissionScope: "mcp-autowire-source-build",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "required",
    defaultTimeoutMs: 60_000,
    runtimeSupport: ["chat"],
  },
  {
    name: "ambient_mcp_autowire_source_build_create",
    label: "MCP Source Build Create",
    description: "With approval, build a GitHub source-only MCP into an Ambient-managed local OCI image and emit a custom-image candidate for ToolHive import.",
    promptSnippet:
      "ambient_mcp_autowire_source_build_create: Approval-gated Ambient source build that clones the pinned repo, builds an OCI image, records the digest, and returns the next Standard MCP import handoff.",
    promptGuidelines: [
      "Use this only after ambient_mcp_autowire_source_build_describe returns ready-to-build and the user approves the build.",
      "Prefer passing candidateRef, expectedCandidateHash, and the exact sourceBuild JSON from source_build_describe; if sourceBuild is missing or incomplete, Desktop re-derives the reviewed plan from the candidate before building.",
      "This tool owns the clone/build/inspect sequence inside Ambient userData. Do not replace it with shell git clone, cargo build, docker build, or local MCP bridge registration.",
      "If it returns ready-for-import, call ambient_mcp_standard_import_describe with the returned custom-image candidateRef and install only after the normal install approval.",
      "If it fails, read the build log path and report blockers; do not fall back to unmanaged local installs.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        candidate: {
          type: "object",
          description: "Exact MCP autowire candidate JSON object returned by ambient_mcp_autowire_plan/review/source_build_describe.",
          additionalProperties: true,
        },
        candidateRef: {
          type: "string",
          description: "Ambient-issued candidate reference. Prefer this over re-sending a large candidate object when available.",
        },
        expectedCandidateHash: {
          type: "string",
          description: "Candidate hash from ambient_mcp_autowire_review or source_build_describe.",
        },
        sourceBuild: {
          type: "object",
          description: "Preferred exact sourceBuild JSON emitted by ambient_mcp_autowire_source_build_describe. May be omitted; Desktop will derive the reviewed source-build plan from candidateRef/candidate.",
          additionalProperties: true,
        },
      },
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "run-process",
    permissionScope: "mcp-autowire-source-build",
    supportsDryRun: false,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 1_200_000,
    runtimeSupport: ["chat"],
  },
  {
    name: "ambient_mcp_autowire_custom_source_describe",
    label: "MCP Custom Source Describe",
    description: "Review a GitHub/source-backed MCP custom ToolHive source build plan and emit a pinned custom-image candidate when safe.",
    promptSnippet:
      "ambient_mcp_autowire_custom_source_describe: Review a custom ToolHive source build plan for a GitHub MCP source and emit a custom-image candidate only after commit and OCI digest are pinned.",
    promptGuidelines: [
      "Use ambient_mcp_autowire_custom_source_describe after ambient_mcp_autowire_source_build_create records an OCI digest, or when the user already has an existing reviewed image with a pinned commit and digest.",
      "When ambient_mcp_autowire_review returns a custom-source-build handoff, prefer ambient_mcp_autowire_source_build_describe first; do not ask Pi to invent sourceBuild JSON from prose.",
      "Pass candidateRef when available, plus sourceBuild JSON with resolvedCommit, image.identifier, optional image.digest, and a recipe describing existing-dockerfile, generated-dockerfile, or existing-reviewed-image.",
      "This tool is read-only. It does not clone, build, push, run, install, or modify ToolHive state.",
      "It rejects branch/tag commits, missing OCI digests for import, unreviewed generated Dockerfiles, unsafe image refs, secret-looking args, broad or write mounts, mounts without reviewed containerPath, and workspace-wide grants.",
      "If status is needs-build, use the returned blockers as the build contract and rerun this tool after the Ambient source-build lane records the OCI digest.",
      "If it emits a custom-image candidate or candidateRef, call ambient_mcp_standard_import_describe next and install only after user approval.",
      "Never fall back to unmanaged local commands, raw ToolHive state edits, or asking the user to paste secrets into chat.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        candidate: {
          type: "object",
          description: "Exact MCP autowire candidate JSON object returned by ambient_mcp_autowire_plan/review.",
          additionalProperties: true,
        },
        candidateRef: {
          type: "string",
          description: "Ambient-issued candidate reference. Prefer this over re-sending a large candidate object when available.",
        },
        expectedCandidateHash: {
          type: "string",
          description: "Candidate hash from ambient_mcp_autowire_plan or ambient_mcp_autowire_review.",
        },
        sourceBuild: {
          type: "object",
          description: "Reviewed custom source build facts. This is a plan/review artifact, not a shell command.",
          properties: {
            schemaVersion: { type: "string", description: "Use ambient-mcp-custom-source-build-v1." },
            sourceUrl: { type: "string", description: "GitHub source URL; should match the candidate source URL." },
            resolvedCommit: { type: "string", description: "Pinned Git commit hash, not a branch or tag." },
            image: {
              type: "object",
              properties: {
                identifier: { type: "string", description: "Reviewed local or registry OCI image reference to run through ToolHive." },
                digest: { type: "string", description: "OCI sha256 digest. Required before import handoff." },
              },
              required: ["identifier"],
              additionalProperties: false,
            },
            recipe: {
              type: "object",
              properties: {
                kind: { enum: ["existing-dockerfile", "generated-dockerfile", "existing-reviewed-image"] },
                contextPath: { type: "string", description: "Safe relative build context path in the source tree." },
                dockerfilePath: { type: "string", description: "Safe relative Dockerfile path when applicable." },
                generatedDockerfileReviewed: { type: "boolean", description: "Must be true before generated-dockerfile recipes can be promoted." },
                runtimeCommand: { type: "string", description: "Informational runtime command or entrypoint summary; not executed by this tool." },
                serverArgs: {
                  type: "array",
                  items: { type: "string" },
                  description: "Fixed server arguments to pass after the ToolHive image source.",
                },
                runtimeEnv: {
                  type: "array",
                  items: {
                    type: "object",
                    properties: {
                      name: { type: "string", description: "Fixed non-secret runtime environment variable name." },
                      value: { type: "string", description: "Fixed non-secret runtime value, such as a reviewed container path." },
                    },
                    required: ["name", "value"],
                    additionalProperties: false,
                  },
                  description: "Fixed non-secret environment values to deliver through Ambient's ToolHive env-file path. Secrets must use Ambient-managed secret bindings instead.",
                },
                evidenceRefs: {
                  type: "array",
                  items: { type: "string" },
                  description: "Candidate evidence ids supporting the recipe.",
                },
              },
              required: ["kind"],
              additionalProperties: false,
            },
            notes: {
              type: "array",
              items: { type: "string" },
            },
          },
          required: ["resolvedCommit", "image", "recipe"],
          additionalProperties: false,
        },
      },
      required: ["sourceBuild"],
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "none",
    permissionScope: "mcp-autowire-discovery",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 30_000,
    runtimeSupport: ["chat"],
  },
];
