import type { DesktopToolDescriptor, WorkflowCapabilityGuidanceDescriptor } from "./desktopToolDescriptorTypes";

const ambientWorkflowsGuidance: WorkflowCapabilityGuidanceDescriptor[] = [
  {
    id: "ambient-workflows-describe-before-inject",
    summary: "Recorded workflow playbooks are retrieved and described before bounded injection.",
    text:
      "Ambient Workflows guidance: use ambient_workflows_search unless the exact workflow id and version are already known. Call ambient_workflows_describe before ambient_workflows_inject. When a user asks to run a saved recorded workflow and callable launch tools are hidden or unavailable, inject the playbook and complete the task through the normal chat/tool loop as a manual playbook-guided run instead of stopping to ask about the feature gate. Use ambient_workflows_update, ambient_workflows_archive, ambient_workflows_unarchive, or ambient_workflows_restore_version only when the user explicitly asks to manage a saved playbook. Injection is non-executing guidance only: it attaches a bounded playbook summary, successful tool examples, Do Not patterns, validation criteria, and output shape to normal chat context.",
    applicabilityTags: ["ambient_workflows", "ambient_workflows_search", "ambient_workflows_describe", "ambient_workflows_inject", "ambient_workflows_update", "ambient_workflows_archive", "playbook"],
    risk: "medium",
    validatorRefs: ["ambient_workflows.describe_required", "ambient_workflows.version_required"],
  },
  {
    id: "ambient-workflows-no-automation-execution",
    summary: "Workflow Recorder playbooks do not execute automation in V1.",
    text:
      "Ambient Workflows V1 rule: do not treat recorded workflow playbooks as runnable code, hidden automation, or a substitute for live validation. Use the playbook as skill-like guidance, then perform the user's task through the normal chat/tool loop. Archived playbooks must stay hidden from default search and must not be injected until unarchived.",
    applicabilityTags: ["ambient_workflows", "playbook", "workflow-recorder", "skill-like"],
    risk: "medium",
    validatorRefs: ["ambient_workflows.non_executing"],
  },
];

export const ambientWorkflowToolDescriptors: DesktopToolDescriptor[] = [
  {
    name: "ambient_workflows_search",
    label: "Workflow Playbook Search",
    description: "Search confirmed Workflow Recorder playbooks before injecting bounded guidance into a normal chat.",
    promptSnippet: "ambient_workflows_search: Search saved Workflow Recorder playbooks by user task, trigger phrase, tool examples, output shape, or summary.",
    promptGuidelines: [
      "Use ambient_workflows_search when a task resembles a previously recorded workflow and the exact playbook id/version is not already known.",
      "This tool searches confirmed local Workflow Recorder playbooks only; it does not inspect legacy compiler workflows, run automation, or execute tools.",
      "After choosing a playbook, call ambient_workflows_describe before ambient_workflows_inject.",
      "Prefer a specific, recent, enabled playbook with matching successful tool examples over a broad generic result.",
    ],
    workflowGuidance: ambientWorkflowsGuidance,
    inputSchema: {
      type: "object",
      properties: {
        query: { type: "string", description: "Search terms describing the desired recorded workflow playbook." },
        limit: { type: "number", description: "Maximum result count. Defaults to 8 and is capped by Desktop." },
        includeDisabled: { type: "boolean", description: "Whether to include disabled saved playbooks. Defaults to false." },
        includeArchived: { type: "boolean", description: "Whether to include archived saved playbooks. Defaults to false." },
      },
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "none",
    permissionScope: "ambient-workflows-discovery",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 30_000,
    runtimeSupport: ["chat"],
  },
  {
    name: "ambient_workflows_describe",
    label: "Workflow Playbook Describe",
    description: "Describe one saved Workflow Recorder playbook with bounded markdown, successful examples, Do Not patterns, and validation guidance.",
    promptSnippet: "ambient_workflows_describe: Load one saved Workflow Recorder playbook before injecting it into chat context.",
    promptGuidelines: [
      "Use ambient_workflows_describe after ambient_workflows_search selects a relevant playbook.",
      "Pass the exact workflow id and, when available, the exact version returned by search.",
      "This tool is read-only and does not execute the workflow or call recorded tools.",
      "Set includeMarkdown=true only when the structured playbook summary is not enough; Desktop bounds returned workflow.md text.",
    ],
    workflowGuidance: ambientWorkflowsGuidance,
    inputSchema: {
      type: "object",
      properties: {
        id: { type: "string", description: "Exact saved workflow playbook id." },
        version: { type: "number", description: "Optional exact saved playbook version. Defaults to the current version." },
        includeMarkdown: { type: "boolean", description: "Whether to include bounded workflow.md text. Defaults to false." },
        includeArchived: { type: "boolean", description: "Whether to allow describing an archived playbook by exact id. Defaults to false." },
        maxMarkdownChars: { type: "number", description: "Maximum workflow.md characters when includeMarkdown is true. Desktop caps this value." },
      },
      required: ["id"],
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "none",
    permissionScope: "ambient-workflows-discovery",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 30_000,
    runtimeSupport: ["chat"],
  },
  {
    name: "ambient_workflows_callable_catalog",
    label: "Callable Workflow Catalog",
    description: "Inspect feature-flag-aware callable Symphony and recorded workflow catalog eligibility without launching workflows.",
    promptSnippet: "ambient_workflows_callable_catalog: Inspect which Symphony presets and recorded workflow playbooks are callable, hidden, child-gated, or excluded.",
    promptGuidelines: [
      "Use this before launching callable workflows when you need to know which workflow recipes are parent-visible, child role-policy gated, or excluded.",
      "This tool is read-only and does not execute workflows, spawn sub-agents, or call recorded tools.",
      "When ambient.subagents is disabled, callable workflow launch tools remain hidden and this tool does not expose hidden launch tool names.",
      "If the user asked to run a recorded workflow and a matching recorded_workflow entry is hidden only because ambient.subagents is disabled, do not stop to ask about enabling the feature flag; use the entry source id/version with ambient_workflows_describe and ambient_workflows_inject, then complete the task through normal chat/tools as a manual playbook-guided run.",
      "Use query to search labels, summaries, tool names, input fields, metrics, and exclusion reasons; use sourceKind to narrow to symphony_recipe or recorded_workflow, and includeExcluded=false when you only need launchable catalog entries.",
    ],
    workflowGuidance: ambientWorkflowsGuidance,
    inputSchema: {
      type: "object",
      properties: {
        limit: { type: "number", description: "Maximum catalog entry count. Defaults to 16 and is capped by Desktop." },
        includeExcluded: { type: "boolean", description: "Whether to include recorded workflows that are disabled, archived, missing, or not confirmed. Defaults to true." },
        sourceKind: { type: "string", description: "Optional source filter: symphony_recipe or recorded_workflow." },
        query: { type: "string", description: "Optional bounded search over labels, summaries, tool names, input fields, metrics, and exclusion reasons." },
      },
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "none",
    permissionScope: "ambient-workflows-discovery",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 30_000,
    runtimeSupport: ["chat"],
  },
  {
    name: "ambient_workflows_callable_describe",
    label: "Callable Workflow Describe",
    description: "Describe one callable Symphony or recorded workflow catalog entry with full bounded source preview, launch requirements, input shape, and child-gating status without launching it.",
    promptSnippet: "ambient_workflows_callable_describe: Load one exact callable workflow catalog entry after catalog search selects it.",
    promptGuidelines: [
      "Use this after ambient_workflows_callable_catalog selects a specific callable workflow entry or when you already know an exact callable tool name.",
      "Pass id from the catalog when possible; otherwise pass toolName, or sourceKind plus sourceId and optional sourceVersion.",
      "This tool is read-only and does not execute workflows, spawn sub-agents, register tools, or call recorded workflow steps.",
      "When ambient.subagents is disabled, this tool can explain hidden catalog metadata but still must not expose hidden launch tool names.",
      "If this describes a recorded workflow the user asked to run and the launch tool is hidden only because ambient.subagents is disabled, use the source id/version with ambient_workflows_describe and ambient_workflows_inject, then complete the task through normal chat/tools as a manual playbook-guided run.",
      "Use maxSourcePreviewLines to keep the readable source preview compact; Desktop caps the returned preview.",
    ],
    workflowGuidance: ambientWorkflowsGuidance,
    inputSchema: {
      type: "object",
      properties: {
        id: { type: "string", description: "Exact callable catalog entry id, for example symphony:map_reduce or recorded:workflow-id:v3." },
        toolName: { type: "string", description: "Exact callable workflow launch tool name when known." },
        sourceKind: { type: "string", description: "Optional source filter: symphony_recipe or recorded_workflow." },
        sourceId: { type: "string", description: "Exact recipe id or recorded workflow id when id/toolName is unavailable." },
        sourceVersion: { type: "string", description: "Optional source version to disambiguate recorded workflows." },
        includeExcluded: { type: "boolean", description: "Whether to allow describing excluded recorded workflows. Defaults to true." },
        includeSourcePreview: { type: "boolean", description: "Whether to include bounded readable source preview lines. Defaults to true." },
        includeSourceSearchTerms: { type: "boolean", description: "Whether to include bounded source search terms. Defaults to true." },
        maxSourcePreviewLines: { type: "number", description: "Maximum readable source preview lines. Defaults to 80 and is capped by Desktop." },
      },
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "none",
    permissionScope: "ambient-workflows-discovery",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 30_000,
    runtimeSupport: ["chat"],
  },
  {
    name: "ambient_workflows_inject",
    label: "Workflow Playbook Inject",
    description: "Attach bounded non-executing Workflow Recorder playbook guidance to the current chat turn.",
    promptSnippet: "ambient_workflows_inject: Inject a described saved workflow playbook as bounded guidance, not as runnable automation.",
    promptGuidelines: [
      "Use ambient_workflows_inject only after ambient_workflows_describe for the same playbook id/version in this thread.",
      "Injection is guidance only: continue through the normal chat/tool loop and validate live facts when needed.",
      "Do not call this for disabled playbooks, unreviewed drafts, or legacy compiler workflows.",
      "Use successful examples for tool argument shape and sequencing, and respect the Do Not section before retrying failed approaches.",
    ],
    workflowGuidance: ambientWorkflowsGuidance,
    inputSchema: {
      type: "object",
      properties: {
        id: { type: "string", description: "Exact saved workflow playbook id." },
        version: { type: "number", description: "Optional exact saved playbook version. Defaults to the current version." },
        maxMarkdownChars: { type: "number", description: "Maximum bounded workflow.md excerpt characters included in the injected guidance." },
      },
      required: ["id"],
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "none",
    permissionScope: "ambient-workflows-injection",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 30_000,
    runtimeSupport: ["chat"],
  },
  {
    name: "ambient_workflows_update",
    label: "Workflow Playbook Update",
    description: "Update a saved Workflow Recorder playbook by writing a new current version from structured fields.",
    promptSnippet: "ambient_workflows_update: Save user-approved edits to a Workflow Recorder playbook as a new version.",
    promptGuidelines: [
      "Use ambient_workflows_update only after describing the exact playbook and after the user asks to edit or accepts proposed changes.",
      "Pass the current baseVersion from ambient_workflows_describe; Desktop rejects stale versions.",
      "Update structured durable fields only. Do not ask to edit workflow.md directly and do not include run-specific local paths, secret values, or one-off filenames.",
      "After the update succeeds, describe the workflow again before injecting it.",
    ],
    workflowGuidance: ambientWorkflowsGuidance,
    inputSchema: {
      type: "object",
      properties: {
        id: { type: "string", description: "Exact saved workflow playbook id." },
        baseVersion: { type: "number", description: "Current version observed before editing. Desktop rejects stale edits." },
        title: { type: "string", description: "Optional replacement title. Defaults to draft.intent." },
        draft: {
          type: "object",
          properties: {
            intent: { type: "string", description: "Reusable workflow intent." },
            inputs: { type: "array", items: { type: "string" }, maxItems: 12 },
            successfulExamples: {
              type: "array",
              maxItems: 12,
              items: {
                type: "object",
                properties: {
                  toolName: { type: "string" },
                  inputPreview: { type: "string" },
                  resultPreview: { type: "string" },
                  artifactPath: { type: "string" },
                },
                required: ["toolName"],
                additionalProperties: false,
              },
            },
            doNot: {
              type: "array",
              maxItems: 12,
              items: {
                type: "object",
                properties: {
                  toolName: { type: "string" },
                  status: { type: "string", enum: ["failed", "skipped", "permission_blocked"] },
                  reason: { type: "string" },
                },
                required: ["status", "reason"],
                additionalProperties: false,
              },
            },
            validation: { type: "array", items: { type: "string" }, maxItems: 12 },
            outputShape: { type: "array", items: { type: "string" }, maxItems: 12 },
          },
          required: ["intent", "inputs", "successfulExamples", "doNot", "validation", "outputShape"],
          additionalProperties: false,
        },
      },
      required: ["id", "baseVersion", "draft"],
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "write-workspace",
    permissionScope: "ambient-workflows-management",
    supportsDryRun: false,
    supportsUndo: true,
    idempotency: "not-supported",
    defaultTimeoutMs: 30_000,
    runtimeSupport: ["chat"],
  },
  {
    name: "ambient_workflows_archive",
    label: "Workflow Playbook Archive",
    description: "Archive a saved Workflow Recorder playbook so it is hidden from default search and cannot be injected.",
    promptSnippet: "ambient_workflows_archive: Archive a saved workflow playbook after the user asks for cleanup.",
    promptGuidelines: [
      "Use ambient_workflows_archive only when the user explicitly asks to archive or hide a saved playbook.",
      "Pass the current baseVersion from ambient_workflows_describe; Desktop rejects stale archives.",
      "Archive is reversible and does not delete package files or version history.",
    ],
    workflowGuidance: ambientWorkflowsGuidance,
    inputSchema: {
      type: "object",
      properties: {
        id: { type: "string", description: "Exact saved workflow playbook id." },
        baseVersion: { type: "number", description: "Current version observed before archiving. Desktop rejects stale archive requests." },
        reason: { type: "string", description: "Short user-facing archive reason." },
      },
      required: ["id", "baseVersion"],
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "write-workspace",
    permissionScope: "ambient-workflows-management",
    supportsDryRun: false,
    supportsUndo: true,
    idempotency: "recommended",
    defaultTimeoutMs: 30_000,
    runtimeSupport: ["chat"],
  },
  {
    name: "ambient_workflows_unarchive",
    label: "Workflow Playbook Unarchive",
    description: "Restore an archived Workflow Recorder playbook to active library visibility.",
    promptSnippet: "ambient_workflows_unarchive: Unarchive a saved workflow playbook after the user asks to restore it.",
    promptGuidelines: [
      "Use ambient_workflows_unarchive only after finding an archived playbook with includeArchived=true.",
      "Pass the current baseVersion from ambient_workflows_describe; Desktop rejects stale unarchive requests.",
      "Unarchive does not force-enable a disabled playbook. Use the enable surface separately when needed.",
    ],
    workflowGuidance: ambientWorkflowsGuidance,
    inputSchema: {
      type: "object",
      properties: {
        id: { type: "string", description: "Exact saved workflow playbook id." },
        baseVersion: { type: "number", description: "Current version observed before unarchiving. Desktop rejects stale requests." },
      },
      required: ["id", "baseVersion"],
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "write-workspace",
    permissionScope: "ambient-workflows-management",
    supportsDryRun: false,
    supportsUndo: true,
    idempotency: "recommended",
    defaultTimeoutMs: 30_000,
    runtimeSupport: ["chat"],
  },
  {
    name: "ambient_workflows_restore_version",
    label: "Workflow Playbook Restore Version",
    description: "Restore a previous saved Workflow Recorder playbook version by creating a new current version.",
    promptSnippet: "ambient_workflows_restore_version: Promote a prior workflow playbook version to a new current version.",
    promptGuidelines: [
      "Use ambient_workflows_restore_version when the user asks to roll back or restore an older playbook version.",
      "This creates a new current version and preserves all older versions.",
      "After restore succeeds, describe the workflow again before injecting it.",
    ],
    workflowGuidance: ambientWorkflowsGuidance,
    inputSchema: {
      type: "object",
      properties: {
        id: { type: "string", description: "Exact saved workflow playbook id." },
        version: { type: "number", description: "Previous version number to restore." },
      },
      required: ["id", "version"],
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "write-workspace",
    permissionScope: "ambient-workflows-management",
    supportsDryRun: false,
    supportsUndo: true,
    idempotency: "not-supported",
    defaultTimeoutMs: 30_000,
    runtimeSupport: ["chat"],
  },
];
