import type { DesktopToolDescriptor } from "./desktopToolDescriptorTypes";

export const piPackageToolDescriptors: DesktopToolDescriptor[] = [
  {
    name: "ambient_pi_extension_install_sandboxed",
    label: "Sandboxed Pi Extension Install",
    description: "Compatibility-only installer for Ambient-managed sandboxed Pi extension packages; hidden from normal install routing.",
    promptSnippet: "ambient_pi_extension_install_sandboxed: Compatibility-only sandboxed Pi extension install, not a normal Pi marketplace route.",
    promptGuidelines: [
      "Do not use this for ordinary Pi marketplace install requests. First call ambient_install_route_plan, then use Ambient-owned wrapper routes or privileged review/rejection.",
      "Before using this for a pi.dev URL in a compatibility-only maintenance path, first try ambient_cli_package_install_pi_catalog. If a reviewed Ambient CLI adapter exists, use that adapter instead of this sandboxed extension lane.",
      "Use ambient_pi_extension_install_sandboxed only for explicit product-owned compatibility testing or migration of a sandboxed extension state that cannot use a wrapper route.",
      "This tool resolves pi.dev/npm metadata to a pinned Git source, copies the package into Ambient-managed state, and discovers registered tools through the compatibility host.",
      "Unknown filesystem, process, env, and network access is denied by the host; only listed allowedNetworkHosts are available.",
      "Do not use this tool for first-party Ambient CLI adapters such as pi-arxiv or youtube-transcript.",
      "After install, use ambient_pi_extension with packageName, toolName, and params returned by discovery.",
      "If the package cannot run in the sandbox, the tool returns a privileged-review-required scan result with scanOrigin sandbox-fallback; use ambient_pi_privileged_install only after user confirmation.",
      "Do not use this tool in Planner Mode.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        source: {
          type: "string",
          description: "Pi catalog URL, npm: package spec, or supported npm package name, for example https://pi.dev/packages/pi-arxiv?name=arxiv.",
        },
        allowedNetworkHosts: {
          type: "array",
          items: { type: "string" },
          description: "Optional network host allow-list for the sandboxed extension. Omit to use package defaults.",
        },
      },
      required: ["source"],
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "write-workspace",
    permissionScope: "pi-extension-sandbox-install",
    supportsDryRun: false,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 120_000,
  },
  {
    name: "ambient_pi_extension",
    label: "Sandboxed Pi Extension",
    description: "Run a tool registered by an installed sandboxed Pi extension package.",
    promptSnippet: "ambient_pi_extension: Run a tool from an installed sandboxed Pi extension package with Ambient permission mediation.",
    promptGuidelines: [
      "Use ambient_pi_extension only for tools discovered from installed sandboxed Pi extension packages.",
      "Always pass packageName or packageId, the exact toolName, and params as an object.",
      "Do not pass secret values in params. Use Ambient-managed secret binding flows when a package declares env requirements.",
      "Summarize bounded text output and any errors after execution.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        packageId: { type: "string", description: "Exact installed sandboxed Pi extension package id." },
        packageName: { type: "string", description: "Installed sandboxed Pi extension package name." },
        toolName: { type: "string", description: "Registered Pi extension tool name." },
        params: { type: "object", description: "Tool parameters object.", additionalProperties: true },
      },
      required: ["toolName"],
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "run-process",
    permissionScope: "pi-extension-sandbox",
    supportsDryRun: false,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 120_000,
  },
  {
    name: "ambient_pi_extension_uninstall_sandboxed",
    label: "Sandboxed Pi Extension Uninstall",
    description: "Uninstall an Ambient-managed sandboxed Pi extension package and remove its copied package files.",
    promptSnippet: "ambient_pi_extension_uninstall_sandboxed: With approval, uninstall an Ambient-managed sandboxed Pi extension by package id or name.",
    promptGuidelines: [
      "Use ambient_pi_extension_uninstall_sandboxed when the user wants to remove an installed sandboxed Pi extension.",
      "This tool only removes packages copied into Ambient-owned sandboxed Pi extension state.",
      "After uninstall, the package tools disappear after the Pi session refreshes or on the next turn.",
      "Do not use this tool in Planner Mode.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        packageId: { type: "string", description: "Exact installed sandboxed Pi extension package id." },
        packageName: { type: "string", description: "Installed sandboxed Pi extension package name." },
      },
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "write-workspace",
    permissionScope: "pi-extension-sandbox-uninstall",
    supportsDryRun: false,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 120_000,
  },
  {
    name: "ambient_pi_extension_history",
    label: "Sandboxed Pi Extension History",
    description: "Inspect installed sandboxed Pi extensions and retained removed-package history.",
    promptSnippet: "ambient_pi_extension_history: List installed sandboxed Pi extensions and retained removed-package history.",
    promptGuidelines: [
      "Use ambient_pi_extension_history when the user asks what sandboxed Pi extensions are installed or what removed sandboxed Pi extension history is retained.",
      "This is read-only and does not clear history, uninstall packages, or revoke grants.",
      "Use ambient_pi_extension_clear_history only when the user explicitly asks to clear retained removed-package history.",
    ],
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "none",
    permissionScope: "pi-extension-sandbox-history",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "recommended",
    defaultTimeoutMs: 30_000,
  },
  {
    name: "ambient_pi_extension_clear_history",
    label: "Sandboxed Pi Extension Clear History",
    description: "Clear retained removed-package history for Ambient-managed sandboxed Pi extensions.",
    promptSnippet: "ambient_pi_extension_clear_history: With approval, clear retained removed-package history for sandboxed Pi extensions without uninstalling active packages.",
    promptGuidelines: [
      "Use ambient_pi_extension_clear_history only when the user asks to clear retained removed sandboxed Pi extension history.",
      "This does not uninstall active sandboxed Pi extensions, delete audit rows, or revoke existing grants.",
      "Inspect history first with ambient_pi_extension_history when the user asks what will be cleared.",
      "Do not use this tool in Planner Mode.",
    ],
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "write-workspace",
    permissionScope: "pi-extension-sandbox-clear-history",
    supportsDryRun: false,
    supportsUndo: false,
    idempotency: "recommended",
    defaultTimeoutMs: 30_000,
  },
  {
    name: "ambient_pi_privileged_scan",
    label: "Privileged Pi Package Scan",
    description: "Run an advisory security scan for a Pi package that may require privileged installation.",
    promptSnippet: "ambient_pi_privileged_scan: Inspect a Pi package for privileged behaviors before install without executing package code.",
    promptGuidelines: [
      "Before privileged scan for a pi.dev URL, first try ambient_cli_package_install_pi_catalog. Do not scan first-party Ambient CLI adapters as privileged packages.",
      "Use ambient_pi_privileged_scan before any privileged Pi install.",
      "This scan is heuristic and does not prove a package is safe.",
      "Use this for lifecycle/hook/command/MCP/config-mutating packages such as context-mode.",
      "Set scanOrigin to sandbox-fallback when this scan follows a failed sandboxed Pi install preview.",
      "Summarize high-risk findings and ask the user before installing.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        source: { type: "string", description: "Pi catalog URL, npm package name, npm: spec, file URL, or local package path." },
        scanOrigin: { type: "string", enum: ["explicit", "sandbox-fallback"], description: "Why this privileged scan is being run. Defaults to explicit." },
      },
      required: ["source"],
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "read-external",
    permissionScope: "pi-privileged-scan",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "recommended",
    defaultTimeoutMs: 120_000,
  },
  {
    name: "ambient_pi_privileged_install",
    label: "Privileged Pi Package Install",
    description: "Install a privileged Pi package into Ambient-owned disabled state after scan review.",
    promptSnippet: "ambient_pi_privileged_install: With approval, install a privileged Pi package as disabled with an Ambient manifest.",
    promptGuidelines: [
      "Do not use ambient_pi_privileged_install for first-party Ambient CLI adapters. Use ambient_cli_package_install_pi_catalog or installed Ambient CLI search/describe/run instead.",
      "Use ambient_pi_privileged_install only after ambient_pi_privileged_scan and user confirmation.",
      "The package is copied into Ambient-owned state and remains disabled; this Alpha path does not activate hooks or mutate Pi settings.",
      "Do not use this for tool-only packages that can use the sandboxed Pi extension path.",
      "Pass scanOrigin sandbox-fallback when installing after ambient_pi_extension_install_sandboxed reported privileged review required.",
      "Do not use this tool in Planner Mode.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        source: { type: "string", description: "Pi catalog URL, npm package name, npm: spec, file URL, or local package path." },
        scanOrigin: { type: "string", enum: ["explicit", "sandbox-fallback"], description: "Why this privileged install is being run. Defaults to explicit." },
      },
      required: ["source"],
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "write-workspace",
    permissionScope: "pi-privileged-install",
    supportsDryRun: false,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 120_000,
  },
  {
    name: "ambient_pi_privileged_disable",
    label: "Privileged Pi Package Disable",
    description: "Disable a privileged Pi install managed by Ambient.",
    promptSnippet: "ambient_pi_privileged_disable: Disable an Ambient-managed privileged Pi install by package id or name.",
    promptGuidelines: [
      "Use ambient_pi_privileged_disable before uninstalling privileged Pi installs.",
      "Alpha privileged installs are disabled by default, so this may be a no-op.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        packageId: { type: "string", description: "Exact privileged Pi install id." },
        packageName: { type: "string", description: "Privileged Pi package name." },
      },
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "write-workspace",
    permissionScope: "pi-privileged-disable",
    supportsDryRun: false,
    supportsUndo: false,
    idempotency: "recommended",
    defaultTimeoutMs: 120_000,
  },
  {
    name: "ambient_pi_privileged_uninstall",
    label: "Privileged Pi Package Uninstall",
    description: "Uninstall an Ambient-managed privileged Pi package using its manifest.",
    promptSnippet: "ambient_pi_privileged_uninstall: With approval, uninstall an Ambient-managed privileged Pi package by package id or name.",
    promptGuidelines: [
      "Use ambient_pi_privileged_uninstall when the user wants to remove a privileged Pi install.",
      "This removes only Ambient manifest-owned files and registry entries.",
      "Warn the user that any direct Pi install or unmanaged package side effects may require manual cleanup.",
      "Do not use this tool in Planner Mode.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        packageId: { type: "string", description: "Exact privileged Pi install id." },
        packageName: { type: "string", description: "Privileged Pi package name." },
        deleteData: { type: "boolean", description: "Whether to delete Ambient-owned extension data when available." },
      },
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "write-workspace",
    permissionScope: "pi-privileged-uninstall",
    supportsDryRun: false,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 120_000,
  },
  {
    name: "ambient_pi_privileged_history",
    label: "Privileged Pi Package History",
    description: "Inspect installed privileged Pi packages and retained removed-package history.",
    promptSnippet: "ambient_pi_privileged_history: List installed privileged Pi packages and retained removed-package history.",
    promptGuidelines: [
      "Use ambient_pi_privileged_history when the user asks what privileged Pi packages are installed or what removed privileged Pi package history is retained.",
      "This is read-only and does not clear history, uninstall packages, or revoke grants.",
      "Use ambient_pi_privileged_clear_history only when the user explicitly asks to clear retained removed-package history.",
    ],
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "none",
    permissionScope: "pi-privileged-history",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "recommended",
    defaultTimeoutMs: 30_000,
  },
  {
    name: "ambient_pi_privileged_clear_history",
    label: "Privileged Pi Package Clear History",
    description: "Clear retained removed-package history for Ambient-managed privileged Pi packages.",
    promptSnippet: "ambient_pi_privileged_clear_history: With approval, clear retained removed-package history for privileged Pi packages without uninstalling active packages.",
    promptGuidelines: [
      "Use ambient_pi_privileged_clear_history only when the user asks to clear retained removed privileged Pi package history.",
      "This does not uninstall active privileged Pi packages, delete audit rows, revoke grants, or clean unmanaged host side effects.",
      "Inspect history first with ambient_pi_privileged_history when the user asks what will be cleared.",
      "Do not use this tool in Planner Mode.",
    ],
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "write-workspace",
    permissionScope: "pi-privileged-clear-history",
    supportsDryRun: false,
    supportsUndo: false,
    idempotency: "recommended",
    defaultTimeoutMs: 30_000,
  },
];
