import type { DesktopToolDescriptor } from "./desktopToolDescriptorTypes";

export const mcpUtilityToolDescriptors: DesktopToolDescriptor[] = [
  {
    name: "ambient_mcp_tool_search",
    label: "MCP Tool Search",
    description: "Search tools exposed by installed Ambient-managed ToolHive MCP servers without loading every tool schema up front.",
    promptSnippet: "ambient_mcp_tool_search: Search installed ToolHive-managed MCP tools by goal, server id, workload, or tool name.",
    promptGuidelines: [
      "Use ambient_mcp_tool_search after an MCP server is installed when the user wants to use a capability exposed by that server.",
      "When Scrapling is installed, prefer Scrapling tools for public page retrieval, documentation page reading, and structured extraction before falling back to browser_content; use Ambient browser tools for authenticated, highly interactive, CAPTCHA-gated, or visual-state browsing.",
      "This is progressive discovery for installed servers only. It does not install servers, inspect arbitrary URLs, or expose the full MCP tool inventory in the prompt.",
      "Search results are a bounded ranked set with compact description previews, stable toolRef, exact serverId, workloadName, and toolName. Call ambient_mcp_tool_describe for the exact tool before ambient_mcp_tool_call.",
      "Prefer exact serverId/workloadName from search results. Short server names are accepted only when Ambient can resolve them unambiguously.",
      "If a server reports descriptor drift or needs review, do not call its tools until a review flow clears that state. Hidden or policy-blocked tools are filtered or blocked by Ambient before any downstream MCP call.",
      "MCP installs and tool descriptor snapshots are app-global Ambient state. Per-call outputs and audit context are tied to the invoking workspace/thread.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        query: { type: "string", description: "Search terms describing the desired installed MCP tool capability." },
        serverId: { type: "string", description: "Optional installed server selector to search within. Exact serverId is preferred; exact workloadName or unambiguous short server name is accepted." },
        workloadName: { type: "string", description: "Optional exact Ambient ToolHive workload name to search within." },
        limit: { type: "number", description: "Maximum result count. Defaults to 8 and is capped at 20 by Desktop." },
        refresh: { type: "boolean", description: "Whether to refresh tool descriptors from running ToolHive workload endpoints before searching." },
      },
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "read-external",
    permissionScope: "mcp-tool-discovery",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 30_000,
    runtimeSupport: ["chat"],
  },
  {
    name: "ambient_mcp_tool_describe",
    label: "MCP Tool Describe",
    description: "Return one installed MCP tool contract, including server identity, descriptor review state, and JSON input schema.",
    promptSnippet: "ambient_mcp_tool_describe: Load the exact installed MCP tool schema before calling it.",
    promptGuidelines: [
      "Use ambient_mcp_tool_describe after ambient_mcp_tool_search selects a tool and before the first call.",
      "Pass the exact toolName plus serverId/workloadName from search results. The returned toolRef is also accepted as toolName when carrying one copyable identifier is easier.",
      "If several installed servers expose the same toolName, include exact serverId/workloadName or use the exact toolRef from search results.",
      "Use the returned JSON schema exactly. Do not invent fields or pass shell-style strings as arguments.",
      "If descriptor review is needs-review, stop and surface that the installed server changed its exposed tool contract. If tool policy says blocked, do not call it.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        toolName: { type: "string", description: "Exact installed MCP tool name, or the exact toolRef from ambient_mcp_tool_search." },
        serverId: { type: "string", description: "Optional installed server selector when the tool name may be ambiguous. Exact serverId is preferred; exact workloadName or unambiguous short server name is accepted." },
        workloadName: { type: "string", description: "Optional exact Ambient ToolHive workload name when the tool name may be ambiguous." },
        refresh: { type: "boolean", description: "Whether to refresh tool descriptors from the running workload endpoint before describing." },
      },
      required: ["toolName"],
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "read-external",
    permissionScope: "mcp-tool-discovery",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 30_000,
    runtimeSupport: ["chat"],
  },
  {
    name: "ambient_mcp_tool_call",
    label: "MCP Tool Call",
    description: "With approval, call one installed ToolHive-managed MCP tool through Ambient's compact MCP bridge.",
    promptSnippet: "ambient_mcp_tool_call: Call one installed MCP tool after search and describe with JSON arguments matching the schema.",
    promptGuidelines: [
      "Use ambient_mcp_tool_call only after ambient_mcp_tool_describe returns the selected tool contract.",
      "Pass exact serverId or workloadName when the selected tool name is ambiguous, or pass the exact toolRef as toolName. Do not call arbitrary endpoints or uninstalled servers.",
      "Put the selected MCP tool input object in the top-level arguments field, for example {\"toolName\":\"server/tool\",\"arguments\":{\"query\":\"docs\"}}. Do not put MCP arguments in toolInput.",
      "When the selected MCP tool needs a file path for user-provided inline content, use fileInputs with argumentPath plus content; Ambient stages the file into the managed ToolHive exchange and rewrites that argument to the container path. For existing files, pass a workspace-relative path in arguments and Ambient will stage it. Do not create temporary files with shell, /tmp, direct host paths, or direct ToolHive profile reads for MCP file staging.",
      "If ambient_mcp_tool_describe shows Managed file input hints, prefer those exact argumentPath values for inline CSV, JSON, text, or table data.",
      "If ambient_mcp_tool_describe shows Managed output path hints, provide a workspace-relative output filename in that argument so Ambient can pre-create a writable ToolHive exchange target and surface the generated artifact. Prefer this over relying on the MCP server's default sibling output path.",
      "Arguments are validated against the MCP tool JSON schema before execution. On validation failure, read the error and retry with corrected JSON.",
      "Ambient blocks calls when descriptor drift marks a server needs-review.",
      "Ambient also blocks tools disabled by per-tool policy and never exposes hidden tools through search or describe.",
      "If a call returns runtime-permission-blocked with nextToolName ambient_mcp_runtime_repair_describe, use that exact nextToolInput to preview/apply a typed Autowire repair; do not use tool policy updates, shell, direct ToolHive commands, or raw profile edits for runtime-profile fixes.",
      "Large tool outputs are preserved in workspace artifacts with a bounded preview, matching shell, CLI, and plugin MCP output handling.",
      "Do not use this tool in Planner Mode.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        toolName: { type: "string", description: "Exact installed MCP tool name, or the exact toolRef returned by describe/search." },
        serverId: { type: "string", description: "Optional installed server selector when the tool name may be ambiguous. Exact serverId is preferred; exact workloadName or unambiguous short server name is accepted." },
        workloadName: { type: "string", description: "Optional exact Ambient ToolHive workload name when the tool name may be ambiguous." },
        arguments: {
          type: "object",
          description: "JSON object matching the selected MCP tool input schema.",
          additionalProperties: true,
        },
        toolInput: {
          oneOf: [
            { type: "object", additionalProperties: true },
            { type: "string" },
          ],
          description: "Compatibility alias accepted only when a provider emits legacy wrapper input. Prefer arguments.",
        },
        fileInputs: {
          type: "array",
          description: "Optional inline files for MCP tools that require file path arguments. Ambient writes each content string into the managed ToolHive file exchange and sets the named argumentPath to the container path before schema validation.",
          items: {
            type: "object",
            properties: {
              argumentPath: { type: "string", description: "Dot-separated path inside arguments to receive the staged container file path, for example input_path or request.csvPath." },
              filename: { type: "string", description: "Optional safe display filename/extension for the staged file." },
              content: { type: "string", description: "Inline file content to stage. Do not include secrets." },
            },
            required: ["argumentPath", "content"],
            additionalProperties: false,
          },
        },
        refresh: { type: "boolean", description: "Whether to refresh descriptors from the running workload endpoint before the call. Defaults to true inside Desktop." },
      },
      required: ["toolName"],
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "plugin-defined",
    permissionScope: "mcp-tool-call",
    supportsDryRun: false,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 120_000,
    runtimeSupport: ["chat"],
  },
  {
    name: "ambient_mcp_tool_review_accept",
    label: "MCP Tool Review Accept",
    description: "With approval, trust the current descriptor snapshot for one installed ToolHive-managed MCP server after drift review.",
    promptSnippet: "ambient_mcp_tool_review_accept: Accept the current MCP tool descriptor snapshot after descriptor drift is reviewed.",
    promptGuidelines: [
      "Use ambient_mcp_tool_review_accept only when ambient_mcp_tool_search or ambient_mcp_tool_describe reports descriptor review needs-review and the user explicitly wants to trust the current descriptors.",
      "Pass exact serverId or workloadName. Include expectedDescriptorHash from the review text when available so Ambient can reject stale acceptance.",
      "This does not call downstream MCP tools, install servers, or change permissions. It only clears descriptor drift for the current installed server snapshot.",
      "After this succeeds, retry ambient_mcp_tool_describe or ambient_mcp_tool_call with the reviewed schema.",
      "Do not use this tool in Planner Mode.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        serverId: { type: "string", description: "Optional exact installed server id." },
        workloadName: { type: "string", description: "Optional exact Ambient ToolHive workload name." },
        expectedDescriptorHash: {
          type: "string",
          description: "Optional descriptor hash from the reviewed snapshot. If provided and stale, Ambient rejects the acceptance.",
        },
      },
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "write-external",
    permissionScope: "mcp-tool-review",
    supportsDryRun: false,
    supportsUndo: false,
    idempotency: "recommended",
    defaultTimeoutMs: 30_000,
    runtimeSupport: ["chat"],
  },
  {
    name: "ambient_mcp_tool_policy_update",
    label: "MCP Tool Policy Update",
    description: "With approval, hide, block, require approval for, or restore one installed MCP tool using Ambient's app-global per-tool policy.",
    promptSnippet:
      "ambient_mcp_tool_policy_update: Update Ambient's per-tool policy for one installed MCP tool after the user asks to hide, block, require approval for, or restore that tool.",
    promptGuidelines: [
      "Use ambient_mcp_tool_policy_update only for installed MCP tools after ambient_mcp_tool_search, ambient_mcp_tool_describe, or ambient_mcp_tool_review_accept identifies the exact tool.",
      "Pass the exact toolName plus serverId/workloadName, or pass the exact toolRef as toolName. This tool can restore hidden tools when the exact name/ref is already known from descriptor review.",
      "Set visibility=hidden to remove a tool from normal search/describe results. Set callPolicy=blocked to prevent calls. Set callPolicy=approval-required to force explicit approval even when broader permission mode would otherwise allow convenience.",
      "Use clear=true to restore the default visible/default-call policy. Do not combine clear with visibility, callPolicy, or reason.",
      "This writes app-global Ambient MCP state only. It does not change ToolHive container permissions, trust descriptor drift, reinstall servers, stop workloads, or call the downstream MCP tool.",
      "Do not use this tool in Planner Mode.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        toolName: { type: "string", description: "Exact installed MCP tool name, or the exact toolRef returned by search/describe/review." },
        serverId: { type: "string", description: "Optional installed server selector when the tool name may be ambiguous." },
        workloadName: { type: "string", description: "Optional exact Ambient ToolHive workload name when the tool name may be ambiguous." },
        visibility: { type: "string", enum: ["visible", "hidden"], description: "Optional visibility override. hidden removes the tool from normal search and describe." },
        callPolicy: { type: "string", enum: ["default", "blocked", "approval-required"], description: "Optional call override for this installed tool." },
        reason: { type: "string", description: "Optional short user-facing reason stored with the policy." },
        clear: { type: "boolean", description: "Whether to clear the policy and restore visible/default behavior. Do not combine with other policy fields." },
        refresh: { type: "boolean", description: "Whether to refresh descriptors before selecting the tool. Defaults to cached descriptors when available." },
      },
      required: ["toolName"],
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "write-external",
    permissionScope: "mcp-tool-policy",
    supportsDryRun: false,
    supportsUndo: true,
    idempotency: "recommended",
    defaultTimeoutMs: 30_000,
    runtimeSupport: ["chat"],
  },
  {
    name: "ambient_mcp_aggregation_status",
    label: "MCP Aggregation Status",
    description: "Evaluate whether installed MCP servers are ready for a future vMCP aggregation experiment while keeping the compact Ambient bridge primary.",
    promptSnippet:
      "ambient_mcp_aggregation_status: Read-only check for whether installed MCP servers are stable enough to consider vMCP aggregation.",
    promptGuidelines: [
      "Use ambient_mcp_aggregation_status only when discussing whether Ambient should prototype vMCP aggregation for already-installed MCP servers.",
      "This is a read-only readiness gate. It does not create a vMCP server, expose every MCP tool as a Pi tool, install servers, trust descriptor drift, change policies, or call downstream MCP tools.",
      "A ready-for-experiment result still means keep the compact ambient_mcp_tool_search/describe/call bridge as the product path and keep aggregation disabled by default.",
      "If status is defer or blocked, follow the returned recommendedAction instead of attempting aggregation through shell, ToolHive raw commands, or custom MCP processes.",
      "The report checks installed server count, trusted descriptor snapshots, ToolHive permission profile hash verification, callable visible tools, duplicate tool names, and a server-prefixed namespace preview.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        refresh: { type: "boolean", description: "Whether to refresh tool descriptors from running workload endpoints before evaluating readiness." },
        minServerCount: { type: "number", description: "Minimum stable installed server count before aggregation is useful. Defaults to 2 and is floored at 2." },
      },
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "read-external",
    permissionScope: "mcp-aggregation-readiness",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 30_000,
    runtimeSupport: ["chat"],
  },
  {
    name: "ambient_json_repair",
    label: "JSON Repair",
    description: "Repair invalid JSON after a schema validation failure using a constrained Ambient/Pi JSON-schema call.",
    promptSnippet:
      "ambient_json_repair: Recovery-only tool for repairing invalid JSON after deterministic schema validation fails; do not use as a first-pass JSON generator.",
    promptGuidelines: [
      "Use ambient_json_repair only after you already have invalid JSON text, the target JSON schema, and concrete validation errors.",
      "Do not call this tool for first-pass JSON generation, general rewriting, code repair, policy interpretation, or schema design.",
      "Pass the smallest relevant invalidJsonText, exact schemaName, exact schema object, and validationErrors from the deterministic validator.",
      "Never send API keys, bearer tokens, passwords, private keys, OAuth tokens, or other secret values. Ambient rejects likely secret-bearing inputs before model execution.",
      "Keep preserveSemantics true unless the user or host validation explicitly asks for a value-changing repair.",
      "If the tool returns repaired=false, surface the missing information or validation error instead of inventing values.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        schemaName: {
          type: "string",
          description: "Short name for the target schema. Used for the constrained Ambient/Pi response format and result metadata.",
        },
        schema: {
          type: "object",
          description: "Target JSON Schema object that the repaired value must satisfy.",
          additionalProperties: true,
        },
        invalidJsonText: {
          type: "string",
          description: "The invalid JSON text to repair. Keep it minimal and do not include secrets.",
        },
        validationErrors: {
          type: "array",
          minItems: 1,
          maxItems: 20,
          items: { type: "string" },
          description: "Deterministic parse/schema validation errors that explain why invalidJsonText failed.",
        },
        repairInstruction: {
          type: "string",
          description: "Optional narrow instruction for the repair. Do not include secrets or unrelated context.",
        },
        preserveSemantics: {
          type: "boolean",
          description: "Defaults to true. When true, Pi should only repair facts inferable from the invalid JSON and validation errors.",
        },
      },
      required: ["schemaName", "schema", "invalidJsonText", "validationErrors"],
      additionalProperties: false,
    },
    outputSchema: {
      type: "object",
      properties: {
        repaired: { type: "boolean" },
        schemaName: { type: "string" },
        value: {},
        inputHash: { type: "string" },
        schemaHash: { type: "string" },
        repairedHash: { type: "string" },
        validation: {
          type: "object",
          properties: {
            valid: { type: "boolean" },
            errors: { type: "array", items: { type: "string" } },
          },
          required: ["valid"],
          additionalProperties: false,
        },
        missingInformation: { type: "array", items: { type: "string" } },
      },
      required: ["repaired", "schemaName", "inputHash", "schemaHash", "validation"],
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "none",
    permissionScope: "json-repair",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "required",
    defaultTimeoutMs: 120_000,
    runtimeSupport: ["chat"],
  },
];
