import type { DesktopToolDescriptor } from "./desktopToolDescriptorTypes";

export const longContextToolDescriptors: DesktopToolDescriptor[] = [
  {
    name: "long_context_process",
    label: "Long Context Process",
    description:
      "Process long text, structured workflow evidence, or workspace-readable text with Lambda-RLM-style split/filter/map/reduce summarization, QA, classification, extraction, and analysis.",
    promptSnippet:
      "long_context_process: Use Lambda-RLM-style long-context processing when workflow evidence is too large or deeply structured for a direct model.call.",
    promptGuidelines: [
      "Use long_context_process before model.call when connector/tool outputs have many records, long fields, or deeply nested JSON that would make the model input large or incomplete.",
      "For workspace-local long documents, pass workspacePaths containing UTF-8 text files, PDFs with extractable text, or supported Office documents (.docx/.pptx/.xlsx) instead of using bash or package installs.",
      "In workflows, pass structured connector or tool output in text when needed; Desktop serializes JSON-compatible values for the long-context runtime.",
      "Use taskType classification, summarization, extraction, analysis, or qa to create a bounded intermediate result, then pass that result to model.call for final schema shaping.",
      "Keep maxModelCalls bounded and preserve source counts/truncation metadata in the downstream model.call input.",
      "Do not use long_context_process for short inputs where ordinary deterministic shaping or model.call is enough.",
    ],
    workflowGuidance: [
      {
        id: "long-context-preprocess",
        summary: "Large or deeply structured evidence is preprocessed before final model shaping.",
        text:
          "Long-context workflow guidance: when long_context_process is available and workflow evidence has many records, long fields, or deeply nested JSON, insert a long_context_process tool.call before final model.call. Do not pass connector.map.items, connector.paginate.items, tool.paginate.items, collection.map.items, collection.dedupe.items, or collection.chunk.chunks directly to one model.call; feed the long-context response plus source counts and truncation metadata into final schema shaping.",
        applicabilityTags: ["long_context_process", "large-collection", "model.call", "connector-output"],
        risk: "high",
        validatorRefs: ["validateWorkflowProgramStatic"],
      },
    ],
    inputSchema: {
      type: "object",
      properties: {
        taskType: {
          type: "string",
          enum: ["summarization", "qa", "translation", "classification", "extraction", "analysis", "general"],
          description: "Optional Lambda-RLM task type.",
        },
        instruction: { type: "string", description: "Goal or extraction/classification instruction." },
        question: { type: "string", description: "Question for QA or relevance filtering." },
        text: { description: "String or structured JSON-compatible evidence to process." },
        workspacePaths: {
          type: "array",
          items: { type: "string" },
          description: "Workspace-relative UTF-8 text files, PDFs with extractable text, or supported Office documents (.docx/.pptx/.xlsx) to read and append to the input.",
        },
        contextWindowChars: { type: "number", description: "Character window for each Lambda-RLM pass." },
        accuracyTarget: { type: "number", description: "Planner accuracy target." },
        aLeaf: { type: "number", description: "Estimated leaf-call accuracy." },
        aCompose: { type: "number", description: "Estimated reducer-call accuracy." },
        maxModelCalls: { type: "number", description: "Bounded maximum model calls." },
        timeoutMs: { type: "number", description: "Per-model-call timeout in milliseconds." },
        maxOutputChars: { type: "number", description: "Maximum returned response characters." },
      },
      required: ["maxModelCalls"],
      additionalProperties: false,
    },
    outputSchema: {
      type: "object",
      properties: {
        response: { type: "string" },
        taskType: { type: "string" },
        inputLength: { type: "number" },
        chunkCount: { type: "number" },
        modelCalls: { type: "number" },
        truncated: { type: "boolean" },
      },
      required: ["response", "taskType", "inputLength", "chunkCount", "modelCalls"],
    },
    source: "first-party",
    sideEffects: "none",
    permissionScope: "long-context",
    supportsDryRun: false,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 300_000,
    runtimeSupport: ["chat", "workflow"],
  },
  {
    name: "long_context_start",
    label: "Long Context Start",
    description:
      "Start detached Lambda-RLM long-context processing and return a pollable async job snapshot.",
    promptSnippet:
      "long_context_start: Start large long_context_process work in the background, then use long_context_poll to inspect progress and completion.",
    promptGuidelines: [
      "Use long_context_start when long documents, many workspacePaths, or a high maxModelCalls budget may take longer than one tool turn.",
      "Pass workspacePaths instead of copying large document text into the tool input when the files are already in the workspace.",
      "Pass yield_ms when a short initial progress window is useful, then carry next_since_seq into long_context_poll as since_seq.",
      "If the job should be checked after this turn ends, call thread_wake_schedule with job_id and payload {\"job_kind\":\"long_context\"}.",
      "Use long_context_process instead for short synchronous work.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        taskType: {
          type: "string",
          enum: ["summarization", "qa", "translation", "classification", "extraction", "analysis", "general"],
          description: "Optional Lambda-RLM task type.",
        },
        instruction: { type: "string", description: "Goal or extraction/classification instruction." },
        question: { type: "string", description: "Question for QA or relevance filtering." },
        text: { description: "String or structured JSON-compatible evidence to process." },
        workspacePaths: {
          type: "array",
          items: { type: "string" },
          description: "Workspace-relative UTF-8 text files, PDFs with extractable text, or supported Office documents (.docx/.pptx/.xlsx) to read and append to the input.",
        },
        recentToolResults: {
          type: "object",
          description: "Optional selector for recent successful Pi session tool results to append from the session.",
          additionalProperties: true,
        },
        contextWindowChars: { type: "number", description: "Character window for each Lambda-RLM pass." },
        accuracyTarget: { type: "number", description: "Planner accuracy target." },
        aLeaf: { type: "number", description: "Estimated leaf-call accuracy." },
        aCompose: { type: "number", description: "Estimated reducer-call accuracy." },
        maxModelCalls: { type: "number", description: "Bounded maximum model calls." },
        timeoutMs: { type: "number", description: "Per-model-call timeout in milliseconds." },
        maxOutputChars: { type: "number", description: "Maximum returned response characters." },
        yield_ms: { type: "number", description: "Optional initial wait for progress before returning, capped by Ambient." },
        poll_hint_ms: { type: "number", description: "Suggested follow-up poll interval in milliseconds." },
      },
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "none",
    permissionScope: "long-context",
    supportsDryRun: false,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 15_000,
    runtimeSupport: ["chat"],
  },
  {
    name: "long_context_poll",
    label: "Long Context Poll",
    description: "Poll a detached long-context job, optionally waiting briefly for new progress or terminal status.",
    promptSnippet:
      "long_context_poll: Poll async long-context progress by job_id and since_seq; wait_ms provides bounded waiting.",
    promptGuidelines: [
      "Use long_context_poll after long_context_start to check progress and final results.",
      "Carry next_since_seq forward as since_seq to avoid re-reading the same progress events.",
      "Use wait_ms for bounded waiting inside a turn; schedule thread_wake_schedule only for later user-visible check-ins.",
      "Use returned result_artifact after terminal status when exact final text is needed.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        job_id: { type: "string", description: "Job id returned by long_context_start." },
        since_seq: { type: "number", description: "Only return events after this sequence number. Defaults to 0." },
        wait_ms: { type: "number", description: "Optional bounded wait for new progress/status before returning." },
        max_bytes: { type: "number", description: "Maximum bytes of event/result preview to return." },
      },
      required: ["job_id"],
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "none",
    permissionScope: "long-context",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "recommended",
    defaultTimeoutMs: 35_000,
    runtimeSupport: ["chat"],
  },
  {
    name: "long_context_cancel",
    label: "Long Context Cancel",
    description: "Cancel a running detached long-context job and return its latest snapshot.",
    promptSnippet: "long_context_cancel: Abort an async long-context job by job_id.",
    promptGuidelines: [
      "Use long_context_cancel when an async long-context job is no longer needed, appears stuck, or the user asks to stop it.",
      "Report whether cancellation completed based on the returned status.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        job_id: { type: "string", description: "Job id returned by long_context_start." },
        reason: { type: "string", description: "Optional cancellation reason for the transcript." },
      },
      required: ["job_id"],
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "none",
    permissionScope: "long-context",
    supportsDryRun: false,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 10_000,
    runtimeSupport: ["chat"],
  },
];
