import type { DesktopToolDescriptor } from "./desktopToolDescriptorTypes";

export const messagingGatewayTelegramToolDescriptors: DesktopToolDescriptor[] = [
  {
    name: "ambient_messaging_telegram_remote_surface_preview",
    label: "Telegram Remote Surface Preview",
    description: "Preview owner-scoped Telegram Remote Ambient Surface binding setup without starting bridges, reading messages, or sending messages.",
    promptSnippet: "ambient_messaging_telegram_remote_surface_preview: Preview binding a Telegram owner conversation to a specific Ambient surface.",
    promptGuidelines: [
      "Use this typed tool when the user wants Telegram to control Ambient itself through Remote Ambient Surface.",
      "This is not the external Messaging Connector path. Do not use it to message other people or expose private Ambient context externally.",
      "For create, provide purpose=remote_ambient_surface, profileId, conversationId, ownerUserId, ambientSurface, and maxDisclosureLabel.",
      "If ownerUserId came from ambient_messaging_telegram_owner_handoff_apply, pass that result's sourceMessageId as ownerHandoffSourceMessageId.",
      "The tool checks redacted Telegram readiness and persisted session metadata before allowing apply.",
      "A preview never starts provider bridges, lists chats, reads provider messages, ingests events, or sends provider messages.",
      "Explain blockers and warnings clearly. If bridge startup is needed, that remains a later approved lifecycle step.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        action: { type: "string", enum: ["create", "revoke"] },
        purpose: { type: "string", enum: ["remote_ambient_surface"], description: "Required when action=create." },
        profileId: { type: "string", description: "Required when action=create. Local Telegram auth profile id." },
        conversationId: { type: "string", description: "Required when action=create. Telegram conversation id to bind." },
        ownerUserId: { type: "string", description: "Required when action=create. Authenticated owner sender id expected for the conversation." },
        ambientSurface: { type: "string", enum: ["chat", "projects", "workflow_agents", "settings", "notifications"], description: "Required when action=create." },
        maxDisclosureLabel: { type: "string", description: "Required when action=create. User-approved disclosure ceiling, for example owner-private-runtime-summary." },
        threadId: { type: "string" },
        projectId: { type: "string" },
        workflowId: { type: "string" },
        permissionProfileId: { type: "string" },
        guardProfileId: { type: "string" },
        ownerHandoffSourceMessageId: { type: "string", description: "Optional sourceMessageId returned by ambient_messaging_telegram_owner_handoff_apply; seeds poll dedupe so the setup-code message is not processed as a command." },
        bindingId: { type: "string", description: "Required when action=revoke." },
        reason: { type: "string", description: "Optional revocation reason." },
      },
      required: ["action"],
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "none",
    permissionScope: "messaging-telegram-remote-surface-preview",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 10_000,
    runtimeSupport: ["chat", "workflow"],
  },
  {
    name: "ambient_messaging_telegram_remote_surface_apply",
    label: "Telegram Remote Surface Apply",
    description: "With approval, create or revoke an owner-scoped Telegram Remote Ambient Surface binding record without starting bridges or sending messages.",
    promptSnippet: "ambient_messaging_telegram_remote_surface_apply: Apply approved Telegram owner Remote Ambient Surface binding setup.",
    promptGuidelines: [
      "Call ambient_messaging_telegram_remote_surface_preview first and explain readiness, disclosure, and safety boundaries.",
      "Use this only after explicit user approval.",
      "This persists or revokes routing metadata only. It does not start Telegram, list chats, read provider messages, ingest events, or send messages.",
      "If this create follows ambient_messaging_telegram_owner_handoff_apply, include ownerHandoffSourceMessageId from the handoff result.",
      "After create, call ambient_messaging_list_bindings and then ambient_messaging_synthetic_route for safe dogfood projection.",
      "After revoke, call ambient_messaging_list_bindings with includeInactive=true.",
      "Do not use generic ambient_messaging_binding_apply for Telegram Remote Ambient Surface setup unless this typed tool is unavailable.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        action: { type: "string", enum: ["create", "revoke"] },
        purpose: { type: "string", enum: ["remote_ambient_surface"], description: "Required when action=create." },
        profileId: { type: "string", description: "Required when action=create. Local Telegram auth profile id." },
        conversationId: { type: "string", description: "Required when action=create. Telegram conversation id to bind." },
        ownerUserId: { type: "string", description: "Required when action=create. Authenticated owner sender id expected for the conversation." },
        ambientSurface: { type: "string", enum: ["chat", "projects", "workflow_agents", "settings", "notifications"], description: "Required when action=create." },
        maxDisclosureLabel: { type: "string", description: "Required when action=create. User-approved disclosure ceiling, for example owner-private-runtime-summary." },
        threadId: { type: "string" },
        projectId: { type: "string" },
        workflowId: { type: "string" },
        permissionProfileId: { type: "string" },
        guardProfileId: { type: "string" },
        ownerHandoffSourceMessageId: { type: "string", description: "Optional sourceMessageId returned by ambient_messaging_telegram_owner_handoff_apply; seeds poll dedupe so the setup-code message is not processed as a command." },
        bindingId: { type: "string", description: "Required when action=revoke." },
        reason: { type: "string", description: "Optional revocation reason." },
      },
      required: ["action"],
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "write-workspace",
    permissionScope: "messaging-telegram-remote-surface-write",
    supportsDryRun: false,
    supportsUndo: true,
    idempotency: "recommended",
    defaultTimeoutMs: 10_000,
    runtimeSupport: ["chat", "workflow"],
  },
  {
    name: "ambient_runtime_surface_snapshot",
    label: "Ambient Runtime Surface Snapshot",
    description: "List the active runtime project, recent chats, workflow agents, and settings availability for chat-native/headless navigation.",
    promptSnippet: "ambient_runtime_surface_snapshot: Inspect active Ambient surfaces for Remote Ambient Surface navigation.",
    promptGuidelines: [
      "Use this when a remote user needs to choose between chats, projects, workflow agents, settings, notifications, or status.",
      "This tool reads runtime-owned state and does not require a visible Electron renderer.",
      "Use this snapshot to offer compact chat-native choices; do not claim it is a full Desktop UI mirror.",
      "For settings rows marked writable=false, do not promise chat/headless mutation yet.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        limit: { type: "number", description: "Maximum chats and workflow agents to return. Defaults to 10, max 25." },
      },
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "none",
    permissionScope: "runtime-surface-read",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 10_000,
    runtimeSupport: ["chat", "workflow"],
  },
  {
    name: "ambient_messaging_synthetic_route",
    label: "Ambient Messaging Synthetic Route",
    description: "Route a synthetic normalized inbound messaging event through binding lookup and chat-native projection without starting real provider bridges.",
    promptSnippet: "ambient_messaging_synthetic_route: Dogfood inbound messaging routing/projection from a normalized synthetic event.",
    promptGuidelines: [
      "Use this only for testing, planning, and dogfooding messaging projection behavior before real provider bridge startup.",
      "This tool does not connect to Telegram, Signal, Slack, or any provider; it does not read provider history and does not send messages.",
      "If no active binding matches the provider/conversation, treat the result as a setup prompt rather than permission to expose runtime state.",
      "For Messaging Connector bindings, this tool must not expose Ambient runtime state unless it is explicitly attached by a future connector context path.",
      "For Remote Ambient Surface bindings, use the projection as a compact chat-native view of the bound Ambient surface.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        providerId: { type: "string", description: "Exact messaging provider id, for example telegram-tdlib." },
        conversationId: { type: "string", description: "Provider conversation/chat/channel id." },
        threadId: { type: "string", description: "Optional provider thread/topic id." },
        senderId: { type: "string", description: "Provider sender/user id." },
        senderLabel: { type: "string", description: "Optional human-readable sender label." },
        text: { type: "string", description: "Synthetic inbound text body." },
      },
      required: ["providerId", "conversationId", "senderId", "text"],
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "none",
    permissionScope: "messaging-synthetic-route-read",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 10_000,
    runtimeSupport: ["chat", "workflow"],
  },
  {
    name: "ambient_messaging_telegram_bridge_event_route",
    label: "Telegram Bridge Event Route",
    description: "Route one normalized Telegram bridge inbound event through the real Remote Ambient Surface handoff without sending messages.",
    promptSnippet: "ambient_messaging_telegram_bridge_event_route: Route a normalized Telegram bridge event through active owner binding checks.",
    promptGuidelines: [
      "Use this for Telegram bridge inbound handoff dogfood and adapter tests, not for generic synthetic projection.",
      "The event must already be normalized from the approved Telegram bridge/session path. Do not use this to list chats, read history, or poll Telegram.",
      "This tool drops events unless an active remote_ambient_surface binding matches provider, profile, conversation, and owner sender.",
      "If the binding is missing, revoked, wrong-profile, or wrong-sender, no Ambient runtime state is projected and no queued projection is created.",
      "This tool never sends Telegram messages. Outbound replies require a separate future send approval path.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        profileId: { type: "string", description: "Local Telegram auth profile id that produced the event." },
        conversationId: { type: "string", description: "Telegram chat id from the bridge event." },
        messageId: { type: "string", description: "Telegram message id from the bridge event." },
        senderId: { type: "string", description: "Telegram sender user/chat id resolved by the bridge adapter." },
        senderLabel: { type: "string", description: "Optional human-readable sender label." },
        text: { type: "string", description: "Normalized inbound text body." },
        receivedAt: { type: "string", description: "Optional ISO timestamp from the bridge event." },
      },
      required: ["profileId", "conversationId", "messageId", "senderId", "text"],
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "none",
    permissionScope: "messaging-telegram-bridge-event-route",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "recommended",
    defaultTimeoutMs: 10_000,
    runtimeSupport: ["chat", "workflow"],
  },
  {
    name: "ambient_messaging_telegram_bridge_poll_preview",
    label: "Telegram Bridge Poll Preview",
    description: "Preview one bounded Telegram bridge unread poll for active owner Remote Ambient Surface bindings.",
    promptSnippet: "ambient_messaging_telegram_bridge_poll_preview: Preview a bounded Telegram unread poll behind active owner Remote Ambient Surface bindings.",
    promptGuidelines: [
      "Use this before polling Telegram bridge unread messages for Remote Ambient Surface.",
      "Preview is read-only and does not call the Telegram bridge unread endpoint or sender-profile endpoint.",
      "Polling is allowed only when Telegram is running in real mode and at least one active owner remote_ambient_surface binding matches the optional scope.",
      "When polling for a known fresh owner command, pass minReceivedAt from the setup/seed timestamp so older unread backlog is marked stale instead of projected.",
      "Explain blockers before apply. Do not fall back to chat listing, history reads, shell, browser, or send-message tools.",
      "Outbound Telegram replies remain unavailable; this flow only queues inbound projections.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        profileId: { type: "string", description: "Optional local Telegram auth profile id to scope polling." },
        bindingId: { type: "string", description: "Optional exact Remote Ambient Surface binding id to poll." },
        limit: { type: "number", description: "Max unread messages per binding. Defaults to 10, capped at 25." },
        minReceivedAt: { type: "string", description: "Optional ISO timestamp freshness anchor. Unread messages older than this are marked seen/stale and are not routed into Ambient projections." },
      },
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "none",
    permissionScope: "messaging-telegram-bridge-poll-preview",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 10_000,
    runtimeSupport: ["chat", "workflow"],
  },
  {
    name: "ambient_messaging_telegram_bridge_poll_apply",
    label: "Telegram Bridge Poll Apply",
    description: "With approval, perform one bounded Telegram bridge unread poll and route deduped owner events through Remote Ambient Surface.",
    promptSnippet: "ambient_messaging_telegram_bridge_poll_apply: Apply one approved bounded Telegram unread poll for active owner bindings.",
    promptGuidelines: [
      "Call ambient_messaging_telegram_bridge_poll_preview first and explain readiness, binding scope, and dedupe state.",
      "Use this only after explicit user approval.",
      "Use one-shot polling when the owner expects one command, a smoke test needs one inbound message, or the user explicitly asks for a single check.",
      "This tool reads the bridge unread endpoint and sender-profile endpoint only for active owner Remote Ambient Surface bindings.",
      "When polling for a command that should arrive after owner handoff or seeded setup, pass minReceivedAt to prevent stale unread backlog from becoming queued projections.",
      "If the user wants ongoing remote operation from Telegram, prefer the periodic polling preview/apply tools instead of repeatedly calling this tool.",
      "It writes workspace-local dedupe/high-water state so repeated polls do not re-ingest the same provider messages.",
      "It never starts the bridge, lists chats, reads arbitrary history, or sends Telegram messages.",
      "After apply, call ambient_messaging_gateway_status to inspect accepted/dropped dispatches and queued projections.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        profileId: { type: "string", description: "Optional local Telegram auth profile id to scope polling." },
        bindingId: { type: "string", description: "Optional exact Remote Ambient Surface binding id to poll." },
        limit: { type: "number", description: "Max unread messages per binding. Defaults to 10, capped at 25." },
        minReceivedAt: { type: "string", description: "Optional ISO timestamp freshness anchor. Unread messages older than this are marked seen/stale and are not routed into Ambient projections." },
      },
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "read-external",
    permissionScope: "messaging-telegram-bridge-poll-apply",
    supportsDryRun: false,
    supportsUndo: false,
    idempotency: "recommended",
    defaultTimeoutMs: 30_000,
    runtimeSupport: ["chat", "workflow"],
  },
  {
    name: "ambient_messaging_telegram_bridge_polling_status",
    label: "Telegram Bridge Polling Status",
    description: "Inspect the periodic Telegram bridge polling runner without reading provider messages or mutating polling state.",
    promptSnippet: "ambient_messaging_telegram_bridge_polling_status: Inspect periodic Telegram bridge polling runner state, last success/error, and dispatch counters.",
    promptGuidelines: [
      "Use this to answer whether Telegram bridge polling is running, stopped, or errored.",
      "This tool does not call the Telegram bridge, read unread messages, resolve senders, start bridges, or send provider messages.",
      "Use lastSuccessfulPollAt, lastError, accepted/dropped dispatch counts, duplicate counts, and nextPollDueAt to explain operational health.",
      "Pair this with ambient_messaging_gateway_status when the user asks about queued projections or provider readiness.",
    ],
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "none",
    permissionScope: "messaging-telegram-bridge-polling-status",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 10_000,
    runtimeSupport: ["chat", "workflow"],
  },
  {
    name: "ambient_messaging_telegram_bridge_polling_preview",
    label: "Telegram Bridge Polling Preview",
    description: "Preview starting or stopping periodic Telegram bridge polling for active owner Remote Ambient Surface bindings.",
    promptSnippet: "ambient_messaging_telegram_bridge_polling_preview: Preview approval-gated periodic Telegram unread polling start/stop boundaries.",
    promptGuidelines: [
      "Use this before starting or stopping periodic Telegram bridge polling.",
      "Use periodic polling when the owner wants an ongoing Remote Ambient Surface loop from Telegram without opening Desktop; use one-shot bridge poll for one expected command or smoke check.",
      "Start previews must explain interval, binding scope, readiness, dedupe state, and the no-send/no-history/no-chat-list boundary.",
      "When starting after owner handoff, setup, or activation, pass minReceivedAt set to the activation/command boundary so pre-existing unread backlog is counted as stale instead of projected.",
      "Stop previews should make clear they only stop Ambient's polling timer and do not revoke bindings or stop the Telegram bridge.",
      "Polling start is allowed only when Telegram is running in real mode and active owner remote_ambient_surface bindings match the optional scope.",
      "Do not call polling apply when preview is blocked.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        action: { type: "string", enum: ["start", "stop"], description: "Start or stop periodic polling." },
        profileId: { type: "string", description: "Optional local Telegram auth profile id to scope polling." },
        bindingId: { type: "string", description: "Optional exact Remote Ambient Surface binding id to poll." },
        limit: { type: "number", description: "Max unread messages per binding per poll. Defaults to 10, capped at 25." },
        minReceivedAt: { type: "string", description: "Optional ISO timestamp freshness anchor. Unread messages older than this are marked seen/stale and are not routed into Ambient projections." },
        intervalMs: { type: "number", description: "Polling interval in milliseconds. Defaults to 30000, min 5000, max 300000." },
      },
      required: ["action"],
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "none",
    permissionScope: "messaging-telegram-bridge-polling-preview",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 10_000,
    runtimeSupport: ["chat", "workflow"],
  },
  {
    name: "ambient_messaging_telegram_bridge_polling_apply",
    label: "Telegram Bridge Polling Apply",
    description: "Apply an approved periodic Telegram bridge polling start/stop operation using the bounded owner-only poll adapter.",
    promptSnippet: "ambient_messaging_telegram_bridge_polling_apply: Apply approved periodic Telegram unread polling start/stop for active owner bindings.",
    promptGuidelines: [
      "Call ambient_messaging_telegram_bridge_polling_preview first and explain the result before this tool.",
      "Start requires explicit user approval because it repeatedly reads the bridge unread endpoint and sender-profile endpoint.",
      "Use periodic polling only for an ongoing owner Remote Ambient Surface loop; use ambient_messaging_telegram_bridge_poll_apply for a single expected command.",
      "When starting after owner handoff, setup, or activation, pass minReceivedAt so the immediate and scheduled polls ignore pre-existing unread backlog.",
      "Stop only stops Ambient's polling timer; it does not revoke bindings, stop the Telegram bridge, read messages, or send messages.",
      "Starting runs one immediate bounded poll before scheduling future polls, then records last success/error counters.",
      "After apply, call ambient_messaging_telegram_bridge_polling_status and ambient_messaging_gateway_status.",
      "Never use this to send Telegram messages; outbound replies require a separate future approval-gated send path.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        action: { type: "string", enum: ["start", "stop"], description: "Start or stop periodic polling." },
        profileId: { type: "string", description: "Optional local Telegram auth profile id to scope polling." },
        bindingId: { type: "string", description: "Optional exact Remote Ambient Surface binding id to poll." },
        limit: { type: "number", description: "Max unread messages per binding per poll. Defaults to 10, capped at 25." },
        minReceivedAt: { type: "string", description: "Optional ISO timestamp freshness anchor. Unread messages older than this are marked seen/stale and are not routed into Ambient projections." },
        intervalMs: { type: "number", description: "Polling interval in milliseconds. Defaults to 30000, min 5000, max 300000." },
      },
      required: ["action"],
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "read-external",
    permissionScope: "messaging-telegram-bridge-polling-apply",
    supportsDryRun: false,
    supportsUndo: true,
    idempotency: "recommended",
    defaultTimeoutMs: 30_000,
    runtimeSupport: ["chat", "workflow"],
  },
  {
    name: "ambient_messaging_telegram_bridge_reply_preview",
    label: "Telegram Bridge Reply Preview",
    description: "Preview one outbound Telegram reply from a queued Remote Ambient Surface projection or relayable Remote Ambient Surface runtime event without sending.",
    promptSnippet: "ambient_messaging_telegram_bridge_reply_preview: Preview an approval-gated Telegram reply from a queued Remote Ambient Surface projection, or pass runtimeEventId to generate exact Ambient status text for a relayable runtime event.",
    promptGuidelines: [
      "Use this before any Telegram outbound reply.",
      "For normal replies, pass queuedProjectionId and the exact text to send.",
      "For Ambient runtime notifications listed by ambient_messaging_gateway_status, pass runtimeEventId by itself; Ambient will generate the exact relay text and route through the event's queued projection.",
      "Only target queued projections or runtime events created by accepted Remote Ambient Surface inbound events.",
      "Explain the exact text, queued projection id, destination conversation, reply-to message, readiness, and send boundary.",
      "If blocked, follow the Repair steps returned by the preview or call ambient_messaging_telegram_relay_diagnostics for a scoped readiness check before retrying.",
      "This preview never sends Telegram messages, reads provider messages, lists chats, reads history, or starts bridges.",
      "Do not use this for Messaging Connector external conversations; that path remains separate and firewalled.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        queuedProjectionId: { type: "string", description: "Queued Remote Ambient Surface projection id to reply to." },
        text: { type: "string", description: "Exact Telegram reply text. Must be 4000 characters or fewer. Required when runtimeEventId is not supplied." },
        runtimeEventId: { type: "string", description: "Recent Remote Ambient Surface runtime event id from ambient_messaging_gateway_status. When supplied without text, Ambient generates exact status relay text." },
      },
      anyOf: [
        { required: ["queuedProjectionId", "text"] },
        { required: ["runtimeEventId"] },
      ],
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "none",
    permissionScope: "messaging-telegram-bridge-reply-preview",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 10_000,
    runtimeSupport: ["chat", "workflow"],
  },
  {
    name: "ambient_messaging_telegram_bridge_reply_apply",
    label: "Telegram Bridge Reply Apply",
    description: "Send one approved Telegram Remote Ambient Surface reply through the Telegram bridge.",
    promptSnippet: "ambient_messaging_telegram_bridge_reply_apply: Send one approved Telegram reply for a queued Remote Ambient Surface projection, or pass runtimeEventId after preview approval to relay exact Ambient runtime-event status text.",
    promptGuidelines: [
      "Call ambient_messaging_telegram_bridge_reply_preview first and explain the result before this tool.",
      "Use this only after explicit user approval for the exact reply text.",
      "For normal replies, pass the same queuedProjectionId and exact text that were previewed.",
      "For runtime-event relays, pass the same runtimeEventId that was previewed so Ambient generates the same status text and records relay status on the event.",
      "This sends one provider message to the queued projection conversation through the Telegram bridge.",
      "It must not list chats, read provider history, read provider messages, start bridges, or send to Messaging Connector conversations.",
      "After apply, call ambient_messaging_gateway_status to inspect the outbound delivery record.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        queuedProjectionId: { type: "string", description: "Queued Remote Ambient Surface projection id to reply to." },
        text: { type: "string", description: "Exact Telegram reply text. Must be 4000 characters or fewer. Required when runtimeEventId is not supplied." },
        runtimeEventId: { type: "string", description: "Recent Remote Ambient Surface runtime event id from ambient_messaging_gateway_status. When supplied without text, Ambient generates exact status relay text." },
      },
      anyOf: [
        { required: ["queuedProjectionId", "text"] },
        { required: ["runtimeEventId"] },
      ],
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "write-external",
    permissionScope: "messaging-telegram-bridge-reply-apply",
    supportsDryRun: false,
    supportsUndo: false,
    idempotency: "recommended",
    defaultTimeoutMs: 30_000,
    runtimeSupport: ["chat", "workflow"],
  },
  {
    name: "ambient_messaging_remote_surface_reply_preview",
    label: "Remote Surface Reply Preview",
    description: "Preview the provider-specific owner reply for one Remote Ambient Surface runtime event by resolving the provider route from gateway status.",
    promptSnippet: "ambient_messaging_remote_surface_reply_preview: Preview a Remote Ambient Surface runtime-event reply using only runtimeEventId; Ambient resolves Telegram vs Signal and delegates to the reviewed provider adapter.",
    promptGuidelines: [
      "Prefer this for relay summaries returned by ambient_messaging_gateway_status or ambient_runtime_surface_snapshot.",
      "Pass only the exact runtimeEventId from the relay summary. Ambient generates the relay text and resolves the provider from queued projection, delivery, or persisted binding metadata.",
      "This preview delegates to the reviewed Telegram or Signal reply preview adapter. It does not send messages, request approval, read provider messages/history, start bridges, run provider CLIs, inspect desktop apps, mutate bindings, or expose Remote Ambient Surface state to Messaging Connector.",
      "If blocked, explain the returned repair steps and use the provider-specific diagnostics tool named in gateway status for deeper troubleshooting.",
      "Do not fall back to shell, browser, Telegram Desktop, Signal Desktop, provider CLIs, generic messaging tools, or Messaging Connector sends.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        runtimeEventId: { type: "string", description: "Exact recent Remote Ambient Surface runtime event id from ambient_messaging_gateway_status or ambient_runtime_surface_snapshot relay summaries." },
      },
      required: ["runtimeEventId"],
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "none",
    permissionScope: "messaging-remote-surface-reply-preview",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 10_000,
    runtimeSupport: ["chat", "workflow"],
  },
  {
    name: "ambient_messaging_remote_surface_reply_apply",
    label: "Remote Surface Reply Apply",
    description: "Apply one provider-resolved Remote Ambient Surface runtime-event reply through the reviewed Telegram or Signal adapter after preview and approval.",
    promptSnippet: "ambient_messaging_remote_surface_reply_apply: Send one approved Remote Ambient Surface runtime-event reply using only runtimeEventId; Ambient resolves the provider and delegates to the reviewed adapter.",
    promptGuidelines: [
      "Call ambient_messaging_remote_surface_reply_preview first and explain the exact generated reply text and provider route.",
      "Pass the same runtimeEventId that was previewed. Do not provide custom text; Ambient generates the relay text from the runtime event.",
      "This apply path delegates to the reviewed provider-specific adapter, which performs exact scope checks, duplicate blocking, and explicit first-party approval before any provider send.",
      "If approval is denied or preview is blocked, no provider message is sent.",
      "After apply, call ambient_messaging_gateway_status to inspect relay status, duplicate blocking, and outbound delivery metadata.",
      "Do not fall back to shell, browser, Telegram Desktop, Signal Desktop, provider CLIs, generic messaging tools, or Messaging Connector sends.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        runtimeEventId: { type: "string", description: "Exact recent Remote Ambient Surface runtime event id from the provider-neutral preview." },
      },
      required: ["runtimeEventId"],
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "write-external",
    permissionScope: "messaging-remote-surface-reply-apply",
    supportsDryRun: false,
    supportsUndo: false,
    idempotency: "recommended",
    defaultTimeoutMs: 30_000,
    runtimeSupport: ["chat", "workflow"],
  },
  {
    name: "ambient_messaging_remote_surface_command_preview",
    label: "Remote Surface Command Preview",
    description: "Preview executing one owner-authenticated Remote Ambient Surface command from a queued messaging projection.",
    promptSnippet: "ambient_messaging_remote_surface_command_preview: Preview a Remote Ambient Surface command such as status, switch surface, open project, switch project, create project, open chat, create chat, open workflow, create workflow, run exploration, compile from exploration, approve/reject workflow preview, cancel workflow, approve/deny request, revoke grant, set chat mode/thinking, set planner finalization, or set voice/speech/media/search settings.",
    promptGuidelines: [
      "Use this when a queued Remote Ambient Surface inbound projection contains owner text that looks like an Ambient runtime command.",
      "Only target queued projections that already passed Remote Ambient Surface owner/delegate authentication.",
      "This preview blocks Messaging Connector projections and does not expose Ambient runtime command execution to external connector conversations.",
      "Current supported commands are status, help, switch surface <chat|projects|workflow_agents|settings|notifications>, open project <number|path|name>, switch project <number|path|name>, create project <name>, create project <name> at <path>, open chat <number|id|title>, create chat <title>, open workflow <number|id|title>, create workflow <request>, create workflow <title> :: <request>, run exploration, run workflow exploration, compile from exploration, compile workflow, approve workflow preview, reject workflow preview, cancel workflow, answer <workflow discovery answer>, approve/deny request <number|id>, revoke grant <number|id|label>, set chat mode <agent|planner>, set chat thinking <minimal|low|medium|high|xhigh>, set planner autoFinalize <on|off>, set planner finalization <automatic|manual>, set voice <mode|enabled|autoplay|longReply|maxChars> <value>, set speech <enabled|language|autoSend|silence|noSpeechGate|rmsThreshold|stopTtsOnSpeech|queueWhileAgentRuns> <value>, set generated media autoplay <value>, clear search preference, and prefer/require search provider <alias>.",
      "Opening a project only changes the remote conversation binding. Switching a project is approval-gated and schedules the active Ambient project switch after the current Pi turn finishes.",
      "Preview does not read provider messages, list provider history, start provider bridges, send provider messages, or mutate workspace state.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        queuedProjectionId: { type: "string", description: "Queued Remote Ambient Surface projection id containing the command." },
        commandText: { type: "string", description: "Optional exact command text override when the original inbound text is unavailable." },
      },
      required: ["queuedProjectionId"],
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "none",
    permissionScope: "messaging-remote-surface-command-preview",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 10_000,
    runtimeSupport: ["chat", "workflow"],
  },
  {
    name: "ambient_messaging_remote_surface_command_apply",
    label: "Remote Surface Command Apply",
    description: "Apply one approved or low-risk Remote Ambient Surface command from a queued messaging projection.",
    promptSnippet: "ambient_messaging_remote_surface_command_apply: Apply a Remote Ambient Surface command after preview.",
    promptGuidelines: [
      "Call ambient_messaging_remote_surface_command_preview first and explain the result before this tool.",
      "Use this only for queued Remote Ambient Surface projections that already passed owner/delegate authentication.",
      "This slice applies low-risk navigation/status commands and approval-gated active project switching/project creation/chat creation/workflow creation/thread settings/settings updates/workflow discovery answers.",
      "It may persist binding navigation scope for switch surface/open project/switch project/open chat/open workflow, but it does not read provider messages or send provider messages.",
      "Active project switching, project creation, chat creation, workflow creation, selected chat mode/thinking updates, settings updates, and workflow discovery answers require explicit approval before apply because they mutate Ambient runtime state.",
      "Project open/select commands change only the remote binding project projection. Switch project commands schedule the active Ambient project switch after the current Pi turn finishes.",
      "After apply, use ambient_messaging_telegram_bridge_reply_preview if a Telegram reply should be sent with the resulting projection.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        queuedProjectionId: { type: "string", description: "Queued Remote Ambient Surface projection id containing the command." },
        commandText: { type: "string", description: "Optional exact command text override when the original inbound text is unavailable." },
      },
      required: ["queuedProjectionId"],
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "write-workspace",
    permissionScope: "messaging-remote-surface-command-apply",
    supportsDryRun: false,
    supportsUndo: true,
    idempotency: "recommended",
    defaultTimeoutMs: 10_000,
    runtimeSupport: ["chat", "workflow"],
  },
  {
    name: "ambient_messaging_telegram_relay_diagnostics",
    label: "Telegram Relay Diagnostics",
    description: "Inspect whether a Telegram Remote Ambient Surface owner conversation can relay Ambient runtime events through the real bridge.",
    promptSnippet: "ambient_messaging_telegram_relay_diagnostics: Read-only diagnostics for Telegram owner relay readiness, synthetic-vs-real bridge state, queued projections, runtime events, and relay deliveries.",
    promptGuidelines: [
      "Use this before real Telegram relay smoke tests or when explaining why a Remote Ambient Surface owner conversation cannot receive status replies.",
      "Pass profileId, conversationId, or bindingId when the user is asking about a specific Telegram owner conversation.",
      "This distinguishes synthetic dogfood routing from a real Telegram bridge; synthetic-active does not mean real Telegram is connected.",
      "Use the returned Repair steps as the authoritative retry path. Do not improvise with shell, browser, Telegram Desktop UI, bridge history scraping, Signal tools, generic messaging tools, or Messaging Connector sends.",
      "This tool does not start bridges, read Telegram messages, read provider history, mutate bindings, or send provider messages.",
      "If relayable runtime events are present and status is ready, use ambient_messaging_telegram_bridge_reply_preview with runtimeEventId before any apply.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        profileId: { type: "string", description: "Optional Telegram auth profile id to inspect." },
        conversationId: { type: "string", description: "Optional Telegram conversation/chat id to inspect." },
        bindingId: { type: "string", description: "Optional exact Remote Ambient Surface binding id to inspect." },
      },
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "none",
    permissionScope: "messaging-telegram-relay-diagnostics-read",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 10_000,
    runtimeSupport: ["chat", "workflow"],
  },
  {
    name: "ambient_messaging_gateway_status",
    label: "Ambient Messaging Gateway Status",
    description: "Inspect the in-process Ambient messaging gateway runner state, queued projections, runtime-event relay summaries, and safe provider readiness without starting provider bridges.",
    promptSnippet: "ambient_messaging_gateway_status: Inspect messaging gateway runner status, synthetic sessions, queued projections, runtime-event relay summaries, and provider readiness.",
    promptGuidelines: [
      "Use this after ambient_messaging_synthetic_route to inspect queued projections and synthetic provider activity.",
      "Use this after Remote Ambient Surface commands that schedule runtime changes, such as switch project, to inspect pending/completed/failed runtime events before summarizing or previewing a relay.",
      "For Remote Ambient Surface owner loops, pair this with ambient_messaging_telegram_bridge_polling_status to decide whether the ongoing polling runner is stopped, running, or errored.",
      "When Remote Ambient Surface relay summaries are present, use their Relay preview/apply/diagnostics tool names and duplicate-block state instead of guessing a provider-specific reply path.",
      "This tool may run safe provider readiness probes. For Telegram, readiness checks only the bridge root health endpoint and redacted local session metadata.",
      "This tool does not start bridges, start TDLib sessions, read provider history, read provider messages, or send provider messages.",
      "Use provider state, queued projection count, recent event count, readiness status, readiness diagnostics, and lastError to explain gateway readiness or failures.",
      "A synthetic-active provider means only synthetic dogfood events have been routed; it does not mean Telegram, Signal, or another provider is actually connected.",
      "This is read-only and safe in planner/headless contexts.",
    ],
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "none",
    permissionScope: "messaging-gateway-status-read",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 10_000,
    runtimeSupport: ["chat", "workflow"],
  },
  {
    name: "ambient_messaging_gateway_lifecycle_preview",
    label: "Ambient Messaging Gateway Lifecycle Preview",
    description: "Preview provider gateway start/stop consequences and readiness blockers without mutating lifecycle state, starting bridges, reading messages, or sending messages.",
    promptSnippet: "ambient_messaging_gateway_lifecycle_preview: Preview messaging provider gateway lifecycle start/stop boundaries and safe readiness blockers.",
    promptGuidelines: [
      "Use this before describing provider bridge startup or shutdown.",
      "This preview does not start Telegram, Signal, Slack, or any real provider bridge.",
      "For Telegram real-start previews, use the readiness section to explain whether local session metadata, API credentials, and bridge root health are present.",
      "Use mode=synthetic for current dogfood routing and mode=real only to preview future bridge consequences.",
      "Real provider startup must remain approval-gated and backed by a real adapter before it can read provider messages.",
      "Provider lifecycle is separate from binding lifecycle; do not treat a started provider as permission to expose Ambient state.",
      "This is read-only and safe in planner/headless contexts.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        action: { type: "string", enum: ["start", "stop"], description: "Lifecycle action to preview." },
        providerId: { type: "string", description: "Exact messaging provider id, for example telegram-tdlib." },
        mode: { type: "string", enum: ["synthetic", "real"], description: "Preview synthetic dogfood lifecycle or real provider bridge lifecycle. Defaults to synthetic." },
      },
      required: ["action", "providerId"],
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "none",
    permissionScope: "messaging-gateway-lifecycle-preview",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 10_000,
    runtimeSupport: ["chat", "workflow"],
  },
  {
    name: "ambient_messaging_gateway_lifecycle_apply",
    label: "Ambient Messaging Gateway Lifecycle Apply",
    description: "Apply an approved messaging gateway lifecycle start/stop operation. Synthetic mode mutates only the in-process runner; real mode is approval-gated and can attach to or launch a supervised safe bridge root without enabling ingestion or sends.",
    promptSnippet: "ambient_messaging_gateway_lifecycle_apply: Apply approved messaging gateway lifecycle start/stop with safe real-bridge boundaries.",
    promptGuidelines: [
      "Call ambient_messaging_gateway_lifecycle_preview first and explain readiness, bridge, read, and send consequences before this tool.",
      "Synthetic mode is for dogfood only and does not connect to providers.",
      "Real mode requires explicit user approval. Do not call real mode just because a provider exists.",
      "For Telegram in this slice, real start can attach to an already reachable bridge root or launch the Ambient Agent Telegram bridge process after readiness passes.",
      "Launching the bridge process only exposes the safe root health endpoint; this tool still does not call /sessions/*, ingest inbound provider messages, or send provider messages.",
      "Real stop stops a bridge process only when Ambient launched and manages it; otherwise it detaches Ambient runner state.",
      "This tool does not read provider history, ingest inbound provider messages, or send provider messages.",
      "After success or block, call ambient_messaging_gateway_status to verify runner state and readiness.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        action: { type: "string", enum: ["start", "stop"], description: "Lifecycle action to apply." },
        providerId: { type: "string", description: "Exact messaging provider id, for example telegram-tdlib." },
        mode: { type: "string", enum: ["synthetic", "real"], description: "Apply synthetic dogfood lifecycle or approved real provider bridge lifecycle. Defaults to synthetic." },
      },
      required: ["action", "providerId"],
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "run-process",
    permissionScope: "messaging-gateway-lifecycle-apply",
    supportsDryRun: false,
    supportsUndo: true,
    idempotency: "recommended",
    defaultTimeoutMs: 10_000,
    runtimeSupport: ["chat", "workflow"],
  },
];
