import type { DesktopToolDescriptor } from "./desktopToolDescriptorTypes";

export const capabilityBuilderToolDescriptors: DesktopToolDescriptor[] = [
  {
    name: "ambient_capability_builder_plan",
    label: "Capability Builder Plan",
    description: "Create a non-mutating implementation plan for a generated Ambient capability package.",
    promptSnippet: "ambient_capability_builder_plan: Plan an Ambient capability package before scaffolding, dependency installation, or registration.",
    promptGuidelines: [
      "Use ambient_capability_builder_plan when the user asks Ambient to create, build, add, or design a new capability, skill, tool, plugin, adapter, connector, artifact generator, or CLI package.",
      "This tool is read-only and allowed in Planner Mode; it does not write files, install dependencies, register packages, run code, or mutate Ambient state.",
      "Plan the product unit as an Ambient capability package, usually an Ambient CLI package with descriptor metadata, SKILL.md, executable commands, tests, health checks, env requirements, artifact rules, and validation.",
      "For assistant voice output, read-aloud chat, voice provider setup, or TTS provider requests, set installerShape to tts-provider unless the user explicitly wants only a one-off audio artifact generator.",
      "If an existing generated package already produces TTS/audio artifacts but is not selectable for chat voice output, do not validate, register, or re-register it as-is; use ambient_capability_builder_repair_plan to convert it to installerShape tts-provider first.",
      "For known providers, ambient_capability_builder_plan applies provider-catalog defaults for provider identity, locality, response formats, env names, network hosts, model assets, validation targets, and operational caveats.",
      "For known cloud TTS providers, preserve the voice-provider path: ElevenLabs should plan ELEVENLABS_API_KEY, api.elevenlabs.io, network locality, MP3 output, Builder-scoped secret capture, and tiny synthesis validation; Cartesia should plan CARTESIA_API_KEY, api.cartesia.ai, network locality, WAV output, Builder-scoped secret capture, and tiny synthesis validation.",
      "For known search providers, preserve catalog guidance: Brave Search plans BRAVE_API_KEY, api.search.brave.com, JSON stdout, and tiny API validation; SearXNG plans the local endpoint, Docker/Podman Compose lifecycle, health checks, persistent service state, and regular updates before any install proposal.",
      "For retrieval and deep-research providers, preserve catalog guidance and require a corpus/index state plan, model-serving/runtime plan, external search/scrape dependency plan, trace/report artifact plan, and bounded validation task before claiming the provider is usable.",
      "For social-media and agentic-service connectors, preserve catalog guidance: plan read-only/draft/sandbox validation first; externally visible or money-affecting actions need exact preview, account/object confirmation, explicit approval, idempotency where applicable, and audit metadata.",
      "For known provider templates, the selected template is binding after the user approves the plan. Preserve that implementation path through scaffold, dependency install, repair, validation, and registration.",
      "Do not switch runtimes, SDKs, model formats, package families, API vendors, or major install strategy merely because an upstream README, search result, or package page appears simpler. Treat those sources as implementation references for the selected path, not permission to choose a different path.",
      "If diagnosis shows the approved provider path is no longer viable, stop and present an explicit switch proposal before changing direction. The proposal must name the approved path, the proposed replacement path, why the approved path failed, dependency/model/credential changes, validation impact, and rollback or cleanup impact.",
      "For Builder-managed cloud TTS drafts, use ambient_capability_builder_secret_request before validation. Do not use ambient_cli_secret_request until after registration, and never ask the user to paste API keys into chat.",
      "If the user provides a URL, repo, model, provider, binary, or library, inspect the current host environment and upstream README/install/example docs before choosing an implementation or dependency strategy.",
      "The plan must include OS/architecture/runtime assumptions, relevant platform-specific install guidance, required sample/model/assets, model/download behavior and expected size when known, license notes, and whether local execution is viable before any scaffold or dependency install.",
      "For network/API capabilities, include exact env names and network hosts; for model capabilities, include model asset names, source URLs, expected sizes when known, license notes, cache path, and tiny validation input.",
      "For commands that accept user text, plan exact-text handling. Prefer file-input flags such as --text-file or --ref-text-file when punctuation, quotes, whitespace, or long text may be hard to pass safely as CLI args.",
      "For search-provider capabilities, put JSON/Markdown/text response shape in responseFormats and default to concise stdout; do not declare file artifacts unless the command intentionally writes files.",
      "For artifact generators, plan user-visible output paths and smoke tests that leave a declared file artifact for validation instead of writing final outputs only inside package internals.",
      "Ask clarifying questions only when a missing choice materially affects safety, provider/runtime selection, credentials, artifact behavior, or implementation feasibility.",
      "After this planning tool returns, present the plan and wait for user approval before any future scaffold, dependency install, validation, registration, or activation step.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        goal: { type: "string", description: "User-facing goal for the generated capability." },
        capabilityName: { type: "string", description: "Optional proposed package/capability name." },
        kind: {
          type: "string",
          description: "Optional capability kind, for example CLI tool, artifact generator, connector/API, local model, or file converter.",
        },
        installerShape: {
          type: "string",
          enum: ["tts-provider", "artifact-generator", "file-converter", "search-provider", "browser-tooling", "connector", "custom-cli"],
          description: "Optional typed installer/product shape. Use tts-provider for assistant voice output/read-aloud setup, even for unknown TTS providers.",
        },
        provider: { type: "string", description: "Optional provider, runtime, API, local binary, or library to build around." },
        outputFileArtifacts: {
          type: "array",
          items: { type: "string" },
          description: "Optional expected file artifact types only, for example WAV, MP3, PDF, CSV, HTML, JSON, or none. Do not use this for stdout/API response formats.",
        },
        outputFileArtifactTypes: {
          anyOf: [
            { type: "array", items: { type: "string" } },
            { type: "string" },
          ],
          description: "Backward-compatible alias for outputFileArtifacts. Prefer an array; a stringified empty array is accepted only for recovery from older Pi calls.",
        },
        responseFormats: {
          type: "array",
          items: { type: "string" },
          description: "Optional stdout/API response formats such as JSON, Markdown, or plain text. This does not require validation file artifacts.",
        },
        locality: {
          type: "string",
          enum: ["local", "network", "either"],
          description: "Whether the desired capability should prefer local execution, network/API execution, or either.",
        },
        envNames: {
          type: "array",
          items: { type: "string" },
          description: "Optional env variable names required by the capability, such as API keys. Secret values must never be provided.",
        },
        networkHosts: {
          type: "array",
          items: { type: "string" },
          description: "Optional exact outbound hostnames required by the capability, without protocol or path.",
        },
        modelAssets: {
          type: "array",
          items: { type: "string" },
          description: "Optional model/data asset names or URLs that the capability must download or cache.",
        },
        notes: { type: "string", description: "Optional constraints, examples, security concerns, or user preferences." },
      },
      required: ["goal"],
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "none",
    permissionScope: "capability-builder-plan",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 30_000,
    runtimeSupport: ["chat"],
  },
  {
    name: "ambient_capability_builder_scaffold",
    label: "Capability Builder Scaffold",
    description: "Create a managed draft Ambient CLI capability package with deterministic starter files and package-local Git.",
    promptSnippet: "ambient_capability_builder_scaffold: With approval, scaffold a draft Ambient capability package in managed workspace state.",
    promptGuidelines: [
      "Use ambient_capability_builder_scaffold only after the user approves a Capability Builder plan.",
      "Preserve the approved installerShape. Do not downgrade tts-provider plans into generic artifact-generator packages.",
      "For known provider scaffolds, pass the typed provider and shape so first-party templates are selected: ElevenLabs and Cartesia are tts-provider cloud templates, not generic MP3/WAV artifact generators.",
      "For known provider scaffolds, preserve the approved template/runtime path. Do not swap SDKs, runtimes, model formats, package families, vendors, or major install strategy during scaffold or later repair unless the user approves an explicit switch proposal.",
      "For search-provider scaffolds, pass the approved responseFormats and leave outputFileArtifactTypes empty unless the command intentionally writes files; JSON or Markdown search responses belong on stdout, not in file artifact declarations.",
      "This tool writes only inside .ambient/capability-builder/packages/<safe-name>/ in the active workspace and initializes a Git repo there.",
      "It creates starter ambient-cli.json, SKILL.md, wrapper script, smoke test, and build manifest files.",
      "It does not install dependencies, validate, register, activate, or run the generated capability beyond package-local Git initialization.",
      "This tool returns a canonical sourcePath. Use that exact sourcePath for later Builder preview, secret, repair, dependency, validation, registration, and removal tools.",
      "Do not use this tool in Planner Mode.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        name: { type: "string", description: "Optional package name. Ambient derives a safe ambient-* name when omitted." },
        goal: { type: "string", description: "User-facing goal for the generated capability." },
        installerShape: {
          type: "string",
          enum: ["tts-provider", "artifact-generator", "file-converter", "search-provider", "browser-tooling", "connector", "custom-cli"],
          description: "Typed installer/product shape from the approved plan. Preserve tts-provider for assistant voice output; do not downgrade it to an artifact generator.",
        },
        kind: { type: "string", description: "Optional capability kind, for example artifact generator or connector/API." },
        provider: { type: "string", description: "Optional provider, runtime, API, local binary, or library to build around." },
        outputFileArtifactTypes: {
          type: "array",
          items: { type: "string" },
          description: "Optional expected file artifact types only, for example WAV, MP3, PDF, CSV, HTML, or JSON. Leave empty for stdout-only tools such as most search providers.",
        },
        responseFormats: {
          type: "array",
          items: { type: "string" },
          description: "Optional stdout/API response formats from the approved plan, such as JSON, Markdown, or plain text. This does not require validation file artifacts.",
        },
        locality: {
          type: "string",
          enum: ["local", "network", "either"],
          description: "Whether the desired capability should prefer local execution, network/API execution, or either.",
        },
        envNames: {
          type: "array",
          items: { type: "string" },
          description: "Optional declared env variable names required by the generated scaffold. Secret values must never be provided.",
        },
        networkHosts: {
          type: "array",
          items: { type: "string" },
          description: "Optional exact outbound hostnames required by the generated scaffold, without protocol or path.",
        },
        modelAssets: {
          type: "array",
          items: { type: "string" },
          description: "Optional model/data asset names or URLs that the generated scaffold should declare.",
        },
      },
      required: ["goal"],
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "write-workspace",
    permissionScope: "capability-builder-scaffold",
    supportsDryRun: false,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 120_000,
    runtimeSupport: ["chat"],
  },
  {
    name: "ambient_capability_builder_preview",
    label: "Capability Builder Preview",
    description: "Statically review a managed draft Ambient capability package before dependency installation or registration.",
    promptSnippet: "ambient_capability_builder_preview: Inspect a managed draft capability package and summarize static review findings.",
    promptGuidelines: [
      "Use ambient_capability_builder_preview after scaffolding or editing a generated capability package and before dependency installation, validation, registration, or activation.",
      "This tool is read-only and allowed in Planner Mode; it only reads managed packages under .ambient/capability-builder/packages/.",
      "For any package under .ambient/capability-builder/packages/, treat this preview as inspection of Builder-managed source, not the installed Ambient CLI copy.",
      "Prefer the exact sourcePath returned by scaffold, preview, or history. packageName can refer to the descriptor name, manifest name, or folder slug when it is unique; use path only for a workspace-relative path under the managed builder root.",
      "Report errors, warnings, risks, descriptor commands, env requirements, artifact declarations, dependency declarations, and lifecycle scripts.",
      "Do not proceed to dependency installation, validation, registration, or activation until the user reviews the preview.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        packageName: { type: "string", description: "Managed package name, for example ambient-piper-tts or piper-tts." },
        path: { type: "string", description: "Optional workspace-relative path under .ambient/capability-builder/packages/." },
        sourcePath: { type: "string", description: "Canonical workspace-relative Builder source path returned by scaffold, preview, or history. Prefer this over packageName when available." },
      },
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "none",
    permissionScope: "capability-builder-preview",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 30_000,
    runtimeSupport: ["chat"],
  },
  {
    name: "ambient_capability_builder_list_files",
    label: "Capability Builder List Files",
    description: "List files in a managed Capability Builder package source without using generic workspace path resolution.",
    promptSnippet: "ambient_capability_builder_list_files: List package-relative files in Builder-managed source.",
    promptGuidelines: [
      "Use this instead of generic ls/read/bash for packages under .ambient/capability-builder/packages/.",
      "Pass the exact sourcePath returned by scaffold, preview, history, or another Builder file tool when available.",
      "This tool is read-only and allowed in Planner Mode; it only lists files under the selected Builder-managed package source.",
      "Default output is source-first and bounded: generated/dependency directories such as .venv, node_modules, caches, dist, and build are summarized instead of recursively listed.",
      "Use pathPrefix, maxEntries, maxDepth, and cursor for progressive discovery. Reuse the same selector/filter fields when following a next cursor.",
      "Set includeGenerated=true only with a narrow pathPrefix for the generated directory you need; never request generated content from the package root.",
      "Use the inventory artifact with file_read for exact filtered listing text or long_context_process for summarization, extraction, or QA; keep generated access scoped by the same includeGenerated/pathPrefix policy.",
      "Follow with ambient_capability_builder_read_file for exact package-relative file contents.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        packageName: { type: "string", description: "Managed package name, for example ambient-piper-tts or piper-tts." },
        path: { type: "string", description: "Optional workspace-relative path under .ambient/capability-builder/packages/." },
        sourcePath: { type: "string", description: "Canonical Builder sourcePath returned by scaffold, preview, history, or another Builder file tool. Prefer this when available." },
        pathPrefix: { type: "string", description: "Optional package-relative file or directory prefix to list, for example scripts or .venv/lib/python3.12/site-packages/pkg." },
        maxEntries: { type: "number", description: "Maximum files to return in this page. Defaults to a bounded page and is hard-capped by Ambient." },
        maxDepth: { type: "number", description: "Maximum directory depth to recurse below pathPrefix before returning omitted directory summaries." },
        includeGenerated: { type: "boolean", description: "Include generated/dependency directories only when paired with a narrow pathPrefix. Defaults to false." },
        cursor: { type: "string", description: "Opaque nextCursor returned by a previous bounded listing page. Keep the same selector and filter fields." },
      },
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "none",
    permissionScope: "capability-builder-read",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 30_000,
    runtimeSupport: ["chat"],
  },
  {
    name: "ambient_capability_builder_read_file",
    label: "Capability Builder Read File",
    description: "Read a package-relative UTF-8 text file from a managed Capability Builder package source.",
    promptSnippet: "ambient_capability_builder_read_file: Read Builder-managed source files by package-relative path.",
    promptGuidelines: [
      "Use this instead of generic file_read/read/bash for packages under .ambient/capability-builder/packages/.",
      "Pass sourcePath for the package and filePath for the package-relative file, for example SKILL.md, ambient-cli.json, scripts/run.mjs, tests/smoke.test.mjs, or capability-validation-log.jsonl.",
      "This tool is read-only and allowed in Planner Mode; it only reads files under the selected Builder-managed package source.",
      "Use maxChars only when a smaller preview is enough. The default is bounded but large enough for typical descriptor, skill, script, and validation log files.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        packageName: { type: "string", description: "Managed package name, for example ambient-piper-tts or piper-tts." },
        path: { type: "string", description: "Optional workspace-relative path under .ambient/capability-builder/packages/." },
        sourcePath: { type: "string", description: "Canonical Builder sourcePath returned by scaffold, preview, history, or another Builder file tool. Prefer this when available." },
        filePath: { type: "string", description: "Package-relative UTF-8 text file path to read, for example SKILL.md or scripts/run.mjs." },
        maxChars: { type: "number", description: "Optional max characters to return, capped by Ambient." },
      },
      required: ["filePath"],
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "none",
    permissionScope: "capability-builder-read",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 30_000,
    runtimeSupport: ["chat"],
  },
  {
    name: "ambient_capability_builder_write_file",
    label: "Capability Builder Write File",
    description: "With approval, create or replace one UTF-8 text file in a managed Capability Builder package source.",
    promptSnippet: "ambient_capability_builder_write_file: With approval, write a package-relative Builder-managed source file.",
    promptGuidelines: [
      "Use this instead of generic write/edit/bash for packages under .ambient/capability-builder/packages/.",
      "This tool is approval-gated and blocked in Planner Mode.",
      "Pass sourcePath for the package and filePath for the package-relative file, for example SKILL.md, ambient-cli.json, scripts/run.mjs, tests/smoke.test.mjs, or package.json.",
      "Provide the complete replacement file content and a concise reason. This tool does not apply patches.",
      "It refuses package Git metadata, Builder metadata/log files, and node_modules writes.",
      "After writing, run ambient_capability_builder_preview before dependency installation, validation, registration, or activation.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        packageName: { type: "string", description: "Managed package name, for example ambient-piper-tts or piper-tts." },
        path: { type: "string", description: "Optional workspace-relative path under .ambient/capability-builder/packages/." },
        sourcePath: { type: "string", description: "Canonical Builder sourcePath returned by scaffold, preview, history, or another Builder file tool. Prefer this when available." },
        filePath: { type: "string", description: "Package-relative UTF-8 text file path to create or replace." },
        content: { type: "string", description: "Complete UTF-8 replacement file content." },
        reason: { type: "string", description: "Plain-language reason for the approved write." },
      },
      required: ["filePath", "content", "reason"],
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "write-workspace",
    permissionScope: "capability-builder-write-file",
    supportsDryRun: false,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 120_000,
    runtimeSupport: ["chat"],
  },
  {
    name: "ambient_capability_builder_secret_request",
    label: "Capability Builder Secret Request",
    description: "Ask Desktop to open a user-facing secret entry dialog for a declared env requirement on a Builder-managed capability draft.",
    promptSnippet: "ambient_capability_builder_secret_request: Request Desktop-owned secret entry for a generated capability draft before validation/registration.",
    promptGuidelines: [
      "Use ambient_capability_builder_secret_request when a Builder-managed generated package needs a declared env secret before validation.",
      "Use this for packages under .ambient/capability-builder/packages before they are registered as installed Ambient CLI packages.",
      "Pass sourcePath or packageName/path plus envName. Prefer the exact sourcePath returned by scaffold, preview, or history. Do not ask the user to paste the secret into chat.",
      "This tool opens a Desktop dialog; Pi receives only that the request was surfaced, never the secret value.",
      "After the user saves the secret, retry ambient_capability_builder_validate.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        packageName: { type: "string", description: "Managed Builder package name, for example ambient-elevenlabs-tts or elevenlabs-tts." },
        path: { type: "string", description: "Optional workspace-relative path under .ambient/capability-builder/packages/." },
        sourcePath: { type: "string", description: "Canonical workspace-relative Builder source path returned by scaffold, preview, or history. Prefer this over packageName when available." },
        envName: { type: "string", description: "Declared environment variable name to request." },
      },
      required: ["envName"],
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "none",
    permissionScope: "capability-builder-secret",
    supportsDryRun: false,
    supportsUndo: false,
    idempotency: "recommended",
    defaultTimeoutMs: 30_000,
    runtimeSupport: ["chat"],
  },
  {
    name: "ambient_capability_builder_history",
    label: "Capability Builder History",
    description: "List preserved managed Capability Builder package sources, including unregistered generated capabilities no longer visible in Ambient CLI search.",
    promptSnippet: "ambient_capability_builder_history: Read preserved generated capability source history and statuses before update, removal, rollback, or re-registration.",
    promptGuidelines: [
      "Use ambient_capability_builder_history when the user asks what generated capabilities exist, what was unregistered, what can be restored, or when Ambient CLI search cannot find a previously generated capability.",
      "This tool is read-only and allowed in Planner Mode; it only scans .ambient/capability-builder/packages/ and installed Ambient CLI package metadata.",
      "It reports package status, builder source path, installed-package presence, validation/registration/unregistration timestamps, refs, commands, env requirements, artifacts, logs, and possible generated artifacts.",
      "Use this tool before rollback/re-register if the installed Ambient CLI package is no longer searchable but the builder source may still exist.",
      "After finding a preserved source, use ambient_capability_builder_preview or ambient_capability_builder_register as appropriate; re-run validation first if content changed since validation.",
      "Do not use shell, browser, direct filesystem, or generic Ambient CLI uninstall/install tools to discover preserved generated capability sources.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        packageName: { type: "string", description: "Optional managed package name to filter, for example ambient-piper-tts or piper-tts." },
        includeRegistered: { type: "boolean", description: "Whether to include currently registered packages. Defaults to true." },
        includeDrafts: { type: "boolean", description: "Whether to include draft/unknown packages. Defaults to true." },
      },
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "none",
    permissionScope: "capability-builder-history",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 30_000,
    runtimeSupport: ["chat"],
  },
  {
    name: "ambient_capability_builder_update_plan",
    label: "Capability Builder Update Plan",
    description: "Create a read-only structured update/rebuild plan for a managed generated Ambient capability package.",
    promptSnippet: "ambient_capability_builder_update_plan: Plan a generated capability update before edits, dependency installation, validation, or registration.",
    promptGuidelines: [
      "Use ambient_capability_builder_update_plan when the user asks to update, rebuild, change, repair, version, or improve a generated Ambient capability package.",
      "This tool is read-only and allowed in Planner Mode; it only reads managed packages under .ambient/capability-builder/packages/.",
      "Call this tool before editing files, installing dependencies, validating, registering, unregistering, or replacing a generated capability.",
      "Prefer the exact sourcePath returned by scaffold, preview, or history. Use requestedChanges to capture the user's requested update in plain language.",
      "Report the structured update steps, approval checkpoints, rollback plan, preview errors/warnings, descriptor commands, env requirements, artifact declarations, and provenance refs.",
      "Do not call ambient_capability_builder_preview separately for update planning; this tool already includes the static preview facts needed for the plan.",
      "After this update-plan tool returns, present the plan and wait for user approval before any future file mutation, dependency install, validation, registration, activation, or removal step.",
      "Do not use shell, browser, ambient_cli, direct filesystem, package install, validation, registration, or removal tools during update planning unless the user explicitly asks for a separate diagnostic.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        packageName: { type: "string", description: "Managed package name, for example ambient-piper-tts or piper-tts." },
        path: { type: "string", description: "Optional workspace-relative path under .ambient/capability-builder/packages/." },
        sourcePath: { type: "string", description: "Canonical workspace-relative Builder source path returned by scaffold, preview, or history. Prefer this over packageName when available." },
        requestedChanges: { type: "string", description: "Plain-language update, rebuild, or repair request from the user." },
        targetVersion: { type: "string", description: "Optional target package version to consider in the plan." },
        notes: { type: "string", description: "Optional constraints, examples, known failures, safety concerns, or migration notes." },
      },
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "none",
    permissionScope: "capability-builder-update-plan",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 30_000,
    runtimeSupport: ["chat"],
  },
  {
    name: "ambient_capability_builder_repair_plan",
    label: "Capability Builder Repair Plan",
    description: "Create a read-only structured repair plan for an invalid or warning-bearing managed generated Ambient capability package.",
    promptSnippet: "ambient_capability_builder_repair_plan: Plan generated capability repair before file edits, dependency installation, validation, or registration.",
    promptGuidelines: [
      "Use ambient_capability_builder_repair_plan when the user asks to repair, fix, diagnose, make valid, or recover a generated Ambient capability package, especially one surfaced as invalid or warning-bearing in Capability Builder history.",
      "Use this tool when a generated package produces TTS/audio artifacts but is not selectable for assistant voice output; request conversion into installerShape tts-provider with voiceProvider metadata before validation, registration, or re-registration.",
      "For TTS artifact-to-provider conversion, the requestedRepair should be exactly: Convert this TTS artifact generator into an Ambient tts-provider for chat voicing.",
      "This tool is read-only and allowed in Planner Mode; it only reads managed packages under .ambient/capability-builder/packages/.",
      "Call this tool before editing files, installing dependencies, validating, registering, unregistering, or replacing a generated capability during repair.",
      "Prefer the exact sourcePath returned by scaffold, preview, or history. Use requestedRepair to capture the user's repair request or observed failure in plain language.",
      "For tricky local installs, classify the failure first: missing binary, missing model/data asset, missing dynamic library, wrong architecture, unsupported platform, permission boundary, hardcoded path, or package-manager/runtime mismatch.",
      "Use the returned installerRecoveryTemplates as playbooks for Python native data paths, Node native rebuilds, local model assets, system binary wrappers, and stdout-vs-file-artifact contract repairs.",
      "If repair would require a protected system path, service install, driver, package-manager privilege, or admin/sudo credential, stop at planning and call ambient_privileged_action_request with a typed template instead of asking the user to copy terminal commands.",
      "Report static preview errors/warnings, intended descriptor/SKILL/script/test/dependency/env/artifact repairs, validation plan, approval checkpoints, provenance refs, and rollback guidance.",
      "After this repair-plan tool returns, present the plan and wait for user approval before any future file mutation, dependency install, validation, registration, activation, or removal step.",
      "Do not use shell, browser, ambient_cli, direct filesystem, package install, validation, registration, or removal tools during repair planning unless the user explicitly asks for a separate diagnostic.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        packageName: { type: "string", description: "Managed package name, for example ambient-piper-tts or piper-tts." },
        path: { type: "string", description: "Optional workspace-relative path under .ambient/capability-builder/packages/." },
        sourcePath: { type: "string", description: "Canonical workspace-relative Builder source path returned by scaffold, preview, or history. Prefer this over packageName when available." },
        requestedRepair: { type: "string", description: "Plain-language repair request, observed failure, or invalid-source finding from the user." },
        notes: { type: "string", description: "Optional constraints, known failures, safety concerns, or migration notes." },
      },
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "none",
    permissionScope: "capability-builder-repair-plan",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 30_000,
    runtimeSupport: ["chat"],
  },
  {
    name: "ambient_capability_builder_apply_repair",
    label: "Capability Builder Apply Repair",
    description: "With approval, apply exact repair file edits to a managed generated Ambient capability package.",
    promptSnippet: "ambient_capability_builder_apply_repair: With approval, write exact repair files after a repair plan and before preview/validation.",
    promptGuidelines: [
      "Use ambient_capability_builder_apply_repair only after ambient_capability_builder_repair_plan has been presented to the user and the user approves the exact file edits.",
      "This tool is approval-gated and blocked in Planner Mode.",
      "It writes only UTF-8 text files under .ambient/capability-builder/packages/<package>/ and refuses package Git metadata, Capability Builder metadata, logs, and node_modules writes.",
      "Include every path, full file content, and concise rationale; do not use this tool for partial patches, dependency installation, generated artifacts, secrets, env binding changes, validation, registration, or installed package state changes.",
      "After applying repairs, run ambient_capability_builder_preview and present the result before dependency installation, validation, registration, or activation.",
      "Edits made by this tool update only the Builder-managed source; the installed Ambient CLI copy remains stale until validation succeeds and ambient_capability_builder_register runs again.",
      "Because applying repairs clears stale validation metadata, do not call ambient_capability_builder_register until ambient_capability_builder_validate succeeds again.",
      "Prefer the exact sourcePath returned by scaffold, preview, history, or repair_plan when selecting the managed source to edit.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        packageName: { type: "string", description: "Managed package name, for example ambient-piper-tts or piper-tts." },
        path: { type: "string", description: "Optional workspace-relative path under .ambient/capability-builder/packages/." },
        sourcePath: { type: "string", description: "Canonical workspace-relative Builder source path returned by scaffold, preview, or history. Prefer this over packageName when available." },
        reason: { type: "string", description: "Plain-language reason for the approved repair." },
        files: {
          type: "array",
          description: "Exact package-relative UTF-8 text files to create or replace.",
          items: {
            type: "object",
            properties: {
              path: { type: "string", description: "Package-relative file path under the managed package root." },
              content: { type: "string", description: "Full UTF-8 file content to write." },
              rationale: { type: "string", description: "Why this file change is needed for the approved repair." },
            },
            required: ["path", "content", "rationale"],
            additionalProperties: false,
          },
        },
      },
      required: ["reason", "files"],
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "write-workspace",
    permissionScope: "capability-builder-apply-repair",
    supportsDryRun: false,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 120_000,
    runtimeSupport: ["chat"],
  },
  {
    name: "ambient_capability_builder_removal_plan",
    label: "Capability Builder Removal Plan",
    description: "Create a read-only safe removal/deactivation plan for a managed generated Ambient capability package.",
    promptSnippet: "ambient_capability_builder_removal_plan: Plan generated capability removal before unregistering, deleting source, artifacts, logs, or secrets.",
    promptGuidelines: [
      "Use ambient_capability_builder_removal_plan when the user asks to remove, uninstall, unregister, disable, deactivate, hide, delete, or clean up a generated Ambient capability package.",
      "This tool is read-only and allowed in Planner Mode; it only reads managed packages under .ambient/capability-builder/packages/ and installed metadata supplied in the request.",
      "Call this tool before unregistering installed Ambient CLI package state, deleting builder source, deleting logs, deleting artifacts, or changing env/secret metadata.",
      "Prefer the exact sourcePath returned by scaffold, preview, or history. Include installedPackageId and installedSource when known from generated capability provenance.",
      "Report installed state, builder source state, package Git/provenance refs, validation/dependency logs, possible artifacts, env requirements, registry visibility, preserve-by-default items, approval checkpoints, and rollback steps.",
      "Do not call ambient_capability_builder_preview separately for removal planning; this tool already includes static preview facts when builder source exists.",
      "After this removal-plan tool returns, present the plan and wait for user approval before any future unregister, delete, cleanup, activation, validation, registration, or package-state mutation.",
      "Do not use shell, browser, ambient_cli, direct filesystem, package install, validation, registration, unregister, uninstall, or cleanup tools during removal planning unless the user explicitly asks for a separate diagnostic.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        packageName: { type: "string", description: "Managed package name, for example ambient-piper-tts or piper-tts." },
        path: { type: "string", description: "Optional workspace-relative path under .ambient/capability-builder/packages/." },
        sourcePath: { type: "string", description: "Canonical workspace-relative Builder source path returned by scaffold, preview, or history. Prefer this over packageName when available." },
        installedPackageId: { type: "string", description: "Optional installed Ambient CLI package id from generated provenance." },
        installedSource: { type: "string", description: "Optional installed package source path or source ref from generated provenance." },
        reason: { type: "string", description: "Plain-language removal/deactivation reason from the user." },
        notes: { type: "string", description: "Optional constraints, retention preferences, known failures, safety concerns, or cleanup notes." },
      },
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "none",
    permissionScope: "capability-builder-removal-plan",
    supportsDryRun: true,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 30_000,
    runtimeSupport: ["chat"],
  },
  {
    name: "ambient_capability_builder_unregister",
    label: "Capability Builder Unregister",
    description: "With approval, unregister a generated Ambient CLI capability package while preserving builder source, logs, artifacts, and env/secret metadata.",
    promptSnippet: "ambient_capability_builder_unregister: With approval, remove generated capability installed visibility while preserving managed builder source.",
    promptGuidelines: [
      "Use ambient_capability_builder_unregister only after ambient_capability_builder_removal_plan has been presented to the user and the user approves least-destructive unregister/deactivation.",
      "This tool is approval-gated and blocked in Planner Mode.",
      "It only removes the installed Ambient CLI package copy from Ambient CLI package state; it preserves managed builder source, package-local Git history, validation logs, dependency logs, generated artifacts, env bindings, and secret metadata.",
      "Pass installedPackageId or installedSource from generated provenance when possible. Prefer sourcePath for the preserved Builder source; use packageName only when it uniquely identifies the installed generated package.",
      "Do not use this tool for non-generated Ambient CLI packages. Use ambient_cli_package_uninstall for ordinary Ambient CLI package removal.",
      "Do not delete builder source, logs, artifacts, env bindings, or secrets in this step.",
      "After unregistering, tell the user that the capability disappears from search/describe after Pi refresh or next turn, and that preserved builder source can be revalidated and registered for rollback.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        packageName: { type: "string", description: "Managed package name, for example ambient-piper-tts or piper-tts." },
        path: { type: "string", description: "Optional workspace-relative path under .ambient/capability-builder/packages/." },
        sourcePath: { type: "string", description: "Canonical workspace-relative Builder source path returned by scaffold, preview, or history. Prefer this over packageName when available." },
        installedPackageId: { type: "string", description: "Optional installed Ambient CLI package id from generated provenance." },
        installedSource: { type: "string", description: "Optional installed package source path or source ref from generated provenance." },
        reason: { type: "string", description: "Plain-language unregister/deactivation reason from the user." },
        notes: { type: "string", description: "Optional constraints, retention preferences, known failures, safety concerns, or cleanup notes." },
        preserveBuilderSource: {
          type: "boolean",
          description: "Must be true or omitted. Source deletion is intentionally not supported by this least-destructive unregister tool.",
        },
      },
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "write-workspace",
    permissionScope: "capability-builder-unregister",
    supportsDryRun: false,
    supportsUndo: true,
    idempotency: "not-supported",
    defaultTimeoutMs: 120_000,
    runtimeSupport: ["chat"],
  },
  {
    name: "ambient_capability_builder_repair_registration_metadata",
    label: "Capability Builder Registration Metadata Repair",
    description: "With approval, clear stale installed refs from generated capability Builder metadata when the installed package copy is already absent.",
    promptSnippet: "ambient_capability_builder_repair_registration_metadata: With approval, clear stale installed refs from Builder metadata after failed unregister/register recovery.",
    promptGuidelines: [
      "Use ambient_capability_builder_repair_registration_metadata only when ambient_capability_builder_history shows a generated Builder source with stale installed refs, installed present: no, or when ambient_capability_builder_unregister failed because the installed package copy is already missing.",
      "This tool is approval-gated and blocked in Planner Mode.",
      "It clears only stale installedPackageId, installedSource, installedVersion, and refs.installed in capability-build.json, then marks the Builder source unregistered.",
      "It refuses to run if the installed Ambient CLI package is still present; use ambient_capability_builder_unregister for normal unregister/deactivation.",
      "It preserves Builder source, package-local Git history, validation refs, validation logs, dependency logs, generated artifacts, env bindings, and secret metadata.",
      "Do not edit capability-build.json through shell or generic file tools to clear stale installed refs; use this tool after approval so the repair is auditable and typed.",
      "After repair, retry ambient_capability_builder_register only if validation metadata still matches; otherwise validate again first.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        packageName: { type: "string", description: "Managed package name, for example ambient-piper-tts or piper-tts." },
        path: { type: "string", description: "Optional workspace-relative path under .ambient/capability-builder/packages/." },
        sourcePath: { type: "string", description: "Canonical workspace-relative Builder source path returned by scaffold, preview, or history. Prefer this over packageName when available." },
        reason: { type: "string", description: "Plain-language reason for clearing stale installed refs." },
      },
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "write-workspace",
    permissionScope: "capability-builder-registration-metadata-repair",
    supportsDryRun: false,
    supportsUndo: true,
    idempotency: "not-supported",
    defaultTimeoutMs: 60_000,
    runtimeSupport: ["chat"],
  },
  {
    name: "ambient_capability_builder_install_deps",
    label: "Capability Builder Install Deps",
    description: "Run explicit, approval-gated dependency setup commands for a managed draft capability package.",
    promptSnippet: "ambient_capability_builder_install_deps: With approval, run exact dependency commands inside a managed draft capability package.",
    promptGuidelines: [
      "Use ambient_capability_builder_install_deps only after static preview and explicit user approval of the exact commands, cwd values, and rationale.",
      "This tool runs commands without a shell and confines cwd to .ambient/capability-builder/packages/<package>/.",
      "Provide command and args separately; do not pass shell pipelines, redirects, secret values, or interactive commands.",
      "For Python dependencies, default to package-local isolated environments: prefer `uv venv --python <version> .venv` followed by `uv pip install --python .venv/bin/python ...`, or `.venv/bin/python -m pip install ...`.",
      "Do not propose bare/global Python package installs such as `pip install`, `pip3 install`, `python -m pip install`, or `python3 -m pip install` unless that Python executable is inside the package-local virtual environment or the user explicitly approves global/user-site installation risk.",
      "Include a concise rationale for every command so the permission prompt explains why it is needed; for Python package commands, state the exact target environment where packages will be installed.",
      "The tool records bounded stdout/stderr previews and actual output lengths in capability-deps-log.jsonl.",
      "Dependency commands use the dependencyInstall timeout profile and reset idle timers on stdout/stderr progress.",
      "It does not register, activate, validate, or run generated capability commands beyond the approved dependency/setup commands.",
      "Prefer the exact sourcePath returned by scaffold, preview, or history when selecting the Builder package.",
      "Do not use this tool in Planner Mode.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        packageName: { type: "string", description: "Managed package name, for example ambient-piper-tts or piper-tts." },
        path: { type: "string", description: "Optional workspace-relative path under .ambient/capability-builder/packages/." },
        sourcePath: { type: "string", description: "Canonical workspace-relative Builder source path returned by scaffold, preview, or history. Prefer this over packageName when available." },
        commands: {
          type: "array",
          description: "Exact dependency/setup commands to run sequentially.",
          items: {
            type: "object",
            properties: {
              command: { type: "string", description: "Executable to run without a shell, for example npm, node, uv, or python3." },
              args: {
                type: "array",
                items: { type: "string" },
                description: "Executable arguments as separate strings.",
              },
              cwd: {
                type: "string",
                description: "Package-relative working directory. Defaults to . and must stay inside the managed package root.",
              },
              rationale: { type: "string", description: "Why this command is needed for the generated capability. For Python package commands, include the target environment, such as package-local .venv." },
            },
            required: ["command", "rationale"],
            additionalProperties: false,
          },
        },
      },
      required: ["commands"],
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "run-process",
    permissionScope: "capability-builder-install-deps",
    supportsDryRun: false,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 1_200_000,
    runtimeSupport: ["chat"],
  },
  {
    name: "ambient_capability_builder_validate",
    label: "Capability Builder Validate",
    description: "Run approved health checks and smoke tests for a managed draft capability package before registration.",
    promptSnippet: "ambient_capability_builder_validate: With approval, validate a managed draft capability package before registration.",
    promptGuidelines: [
      "Use ambient_capability_builder_validate after preview and any needed dependency installation, before registration or activation.",
      "This tool derives exact validation commands from descriptor healthCheck entries and tests/smoke.test.mjs.",
      "Artifact-generating packages must include a smoke test that runs the primary command path on tiny input and creates or updates a real declared file artifact; import-only health checks or static listings are not sufficient.",
      "It runs commands without a shell, captures bounded stdout/stderr previews with actual output lengths, and writes capability-validation-log.jsonl.",
      "Descriptor timeoutProfile, progressPatterns, and devicePolicy fields control validation command execution; use modelColdStart or liveGeneration for real local model work instead of forcing quick probes.",
      "It reports newly created or updated files as artifact references with sizes instead of dumping large content in chat.",
      "If validation fails, do not register, re-register, reinstall, or activate this Builder-managed package. Repair the source, preview if structure changed, validate again, and only register after validation succeeds.",
      "If a cloud/API provider validation failure is a missing declared env requirement, treat it as a secret-binding blocker: use ambient_capability_builder_secret_request for Builder-managed drafts before registration, or ambient_cli_secret_request / ambient_cli_env_bind for installed Ambient CLI packages. Never ask for the secret value in chat, and retry only after the Ambient-managed secret path is in place.",
      "Prefer the exact sourcePath returned by scaffold, preview, or history when selecting the Builder package.",
      "Do not use this tool in Planner Mode.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        packageName: { type: "string", description: "Managed package name, for example ambient-piper-tts or piper-tts." },
        path: { type: "string", description: "Optional workspace-relative path under .ambient/capability-builder/packages/." },
        sourcePath: { type: "string", description: "Canonical workspace-relative Builder source path returned by scaffold, preview, or history. Prefer this over packageName when available." },
        includeSmokeTests: {
          type: "boolean",
          description: "Whether to include tests/smoke.test.mjs when present. Defaults to true.",
        },
      },
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "run-process",
    permissionScope: "capability-builder-validate",
    supportsDryRun: false,
    supportsUndo: false,
    idempotency: "not-supported",
    defaultTimeoutMs: 1_200_000,
    runtimeSupport: ["chat"],
  },
  {
    name: "ambient_capability_builder_register",
    label: "Capability Builder Register",
    description: "Install or re-register a validated managed capability package into Ambient CLI package state.",
    promptSnippet: "ambient_capability_builder_register: With approval, register or re-register a validated managed capability package as an Ambient CLI package.",
    promptGuidelines: [
      "Use ambient_capability_builder_register only after ambient_capability_builder_validate succeeds, or to re-register a source-preserved generated package that ambient_capability_builder_unregister marked unregistered.",
      "This tool requires validation metadata to match the current package content before registration.",
      "It installs the package through Ambient CLI package state so the capability becomes searchable and describable.",
      "Use this tool, not ambient_cli_package_install, when updating or re-registering Builder-managed packages under .ambient/capability-builder/packages/.",
      "For rollback after unregister, use the preserved Builder sourcePath when available; re-run validation first if the package content changed since last validation.",
      "After registration, start a fresh Pi turn or session before relying on newly mounted skills.",
      "Live-test registered packages with ambient_cli_search, then ambient_cli_describe, then ambient_cli.",
      "Do not use this tool in Planner Mode.",
    ],
    inputSchema: {
      type: "object",
      properties: {
        packageName: { type: "string", description: "Managed package name, for example ambient-piper-tts or piper-tts." },
        path: { type: "string", description: "Optional workspace-relative path under .ambient/capability-builder/packages/." },
        sourcePath: { type: "string", description: "Canonical workspace-relative Builder source path returned by scaffold, preview, or history. Prefer this over packageName when available." },
      },
      additionalProperties: false,
    },
    source: "first-party",
    sideEffects: "write-workspace",
    permissionScope: "capability-builder-register",
    supportsDryRun: false,
    supportsUndo: true,
    idempotency: "recommended",
    defaultTimeoutMs: 1_200_000,
    runtimeSupport: ["chat"],
  },
];
