import { describe, expect, it, vi } from "vitest";

import type { DesktopState } from "../../shared/desktopTypes";
import { createAppShellSurfacePropsForApp, type AppShellSurfacePropsForAppInput } from "./AppShellSurfaceProps";

describe("App shell surface props", () => {
  it("packs grouped App owners into shell layout surface props", () => {
    const openApiKeyDialog = vi.fn();
    const openGitSummaryPanel = vi.fn();
    const openPanel = vi.fn();
    const runUpdateAction = vi.fn();
    const selectThread = vi.fn();
    const setSidebarOpen = vi.fn();

    const input = baseInput();
    input.credentialDialogActions.openApiKeyDialog = openApiKeyDialog;
    input.navigationActions.selectThread = selectThread;
    input.navigationActions.workspaceNavigationControls.selectThread = selectThread;
    input.rightPanelState.openGitSummaryPanel = openGitSummaryPanel;
    input.rightPanelState.openPanel = openPanel;
    input.shellUiState.setSidebarOpen = setSidebarOpen;
    input.updateActions.runUpdateAction = runUpdateAction;

    const props = createAppShellSurfacePropsForApp(input);

    expect(props.topbarProps.title).toBe("Build thread");
    props.topbarProps.onOpenApiKey();
    props.topbarProps.onOpenGitSummary();
    props.updateNoticeProps.onCheck();
    props.sidebarProps.onCloseSidebar();
    props.workspaceRouterProps.conversationMessagesProps.onOpenBrowserPanel();
    props.rightPanelHostProps.onSelectThread("thread-2");

    expect(openApiKeyDialog).toHaveBeenCalled();
    expect(openGitSummaryPanel).toHaveBeenCalled();
    expect(runUpdateAction).toHaveBeenCalledWith("check");
    expect(setSidebarOpen).toHaveBeenCalledWith(false);
    expect(openPanel).toHaveBeenCalledWith("browser");
    expect(selectThread).toHaveBeenCalledWith("thread-2");
  });
});

function baseInput(): AppShellSurfacePropsForAppInput {
  const noop = vi.fn();
  const state = desktopState();
  const activeThread = {
    id: "thread-1",
    title: "Build thread",
    memoryEnabled: true,
    workflowRecording: undefined,
    workspacePath: "/tmp/workspace",
  };
  const workflowRuntimeState = {
    callableWorkflowTaskCancelBusy: {},
    callableWorkflowTaskPauseBusy: {},
    callableWorkflowTaskResumeBusy: {},
    chatExportBusy: false,
    chatExportStatus: undefined,
    contextAttachments: [],
    contextError: undefined,
    contextRecoveryBusy: false,
    goalBusy: false,
    goalCompletionCelebrationId: undefined,
    goalMenuOpen: false,
    goalModeArmed: false,
    localDeepResearchModeArmed: false,
    orchestrationRevision: 1,
    setChatExportStatus: noop,
    setGoalMenuOpen: noop,
    setLocalDeepResearchBudgetOverride: noop,
    subagentApprovalActionBusy: {},
    subagentBarrierActionBusy: {},
    subagentChildCancelBusy: {},
    subagentChildCloseBusy: {},
    symphonyBuilderActionBusy: {},
    symphonyBuilderDraft: { open: false },
    workflowRevision: 1,
    orchestrationAutoRevision: 1,
    workflowCompileProgress: [],
    workflowDiscoveryProgress: [],
    workflowExplorationProgressByThreadId: {},
    setWorkflowCompileProgress: noop,
    setWorkflowExplorationProgressByThreadId: noop,
    setWorkflowRevision: noop,
  };
  const projectBoardActions = {
    addPlannerPlanToBoard: noop,
    buildProjectBoard: noop,
    confirmProjectBoardReset: noop,
    generatePlannerDurableArtifact: noop,
    openProjectBoard: noop,
  };
  const input = {
    actions: {
      applyAutomationDesktopState: noop,
      setError: noop,
      setState: noop,
    },
    activeThread,
    activeThreadModel: {
      activeActivity: undefined,
      activeChatBrowserUserAction: undefined,
      activePermissionRequest: undefined,
      activePrivilegedCredentialRequest: undefined,
      activeSecureInputRequest: undefined,
      activeThread,
      isMac: true,
      localDeepResearchReady: true,
      localDeepResearchRunActive: false,
      localDeepResearchRunBudget: { effort: "medium" },
      showTopbarThreadMemoryToggle: true,
    },
    agentMemoryControls: {
      refreshAgentMemoryDiagnostics: noop,
      runAgentMemoryEmbeddingLifecycleAction: noop,
    },
    automationShellState: {
      automationFolders: [],
      automationPopover: undefined,
      automationsCollapsed: false,
      selectedAutomationPane: "workflow-lab",
      setAutomationFolders: noop,
      setAutomationPopover: noop,
      setAutomationsCollapsed: noop,
      setWorkflowAgentFolders: noop,
      updateSidebarOrganize: noop,
      workflowAgentFolders: [],
    },
    browserActionControls: {
      cancelBrowserUserActionFromChat: noop,
      continueAfterBrowserUserActionIfReady: noop,
      openBrowserForUserAction: noop,
      openExternalUrl: noop,
      openUrlInAmbientBrowser: noop,
      resumeBrowserUserActionFromChat: noop,
    },
    capabilityPromptActions: {
      sendRemoteSurfaceActivationPrompt: noop,
      sendTelegramSessionSetupPrompt: noop,
      startCapabilityBuilderPrompt: noop,
      startWelcomeFirstRunCapabilityOnboarding: noop,
      startWelcomeProviderCatalogCardOnboarding: noop,
      startWelcomeRemoteSurfaceActivation: noop,
    },
    chatFindControls: {
      chatFindCount: 0,
      chatFindIndex: 0,
      chatFindInputRef: { current: null },
      chatFindOpen: false,
      chatFindQuery: "",
      onChatFindClose: noop,
      onChatFindNext: noop,
      onChatFindPrevious: noop,
      setChatFindQuery: noop,
    },
    composerInteractionControls: {
      chooseSymphonyPreflightCustom: noop,
      handleComposerChange: noop,
      handleComposerKeyDown: noop,
      handleComposerPaste: noop,
      removeSlashCommandSelection: noop,
      selectSlashCommandEntry: noop,
      showUnavailableSlashCommand: noop,
      submit: noop,
    },
    composerModelPickerControls: {
      composerModelOptions: [],
      focusModelPickerOption: noop,
      modelPickerButtonRef: { current: null },
      modelPickerOpen: false,
      modelPickerRef: { current: null },
      selectedComposerModelOption: undefined,
      setModelPickerOpen: noop,
    },
    composerRetryActions: { retryFailedPrompt: noop },
    composerShellState: {
      composerCanSubmit: true,
      composerDraftStore: { getSnapshot: () => "", subscribe: () => noop },
      composerInputRef: { current: null },
      getComposerDraft: () => "",
      selectedSlashCommand: undefined,
    },
    contextAttachmentActions: {
      addContextAttachments: noop,
      attachComposerFiles: noop,
      clearContextAttachments: noop,
      removeContextAttachment: noop,
    },
    conversationDisplayModel: {
      artifactPathHints: {},
      latestRecoveryPrompt: undefined,
      plannerArtifactByMessageId: new Map(),
      retryableMessageIds: new Set(),
      streamingAssistantId: undefined,
      transientThinkingActivityLines: [],
      visibleChatMessages: [],
      visibleRunActivityLines: [],
    },
    coreLifecycleControls: {
      handleMessagesScroll: noop,
      jumpToLatestMessage: noop,
      messageTailVisible: true,
      scrollRef: { current: null },
      showScrollToBottom: false,
    },
    credentialDialogActions: {
      clearSavedApiKey: noop,
      openAmbientKeys: noop,
      openAmbientCliSecretDialog: noop,
      openApiKeyDialog: noop,
      pasteAmbientCliSecret: noop,
      pasteApiKey: noop,
      saveAmbientCliSecret: noop,
      saveApiKey: noop,
      testApiKey: noop,
      updateAmbientCliSecretDialog: noop,
    },
    gitActions: {
      attachExistingWorktreeFromFooter: noop,
      createBranchFromFooter: noop,
      createThreadWorktreeFromFooter: noop,
      switchBranch: noop,
    },
    goalActions: {
      clearActiveGoal: noop,
      editActiveGoalObjective: noop,
      pauseOrResumeActiveGoal: noop,
      setActiveGoalBudget: noop,
      toggleGoalMode: noop,
    },
    localDeepResearchModeControls: {
      onToggleLocalDeepResearchMode: noop,
    },
    messageVoiceActions: {
      clearMessageVoiceArtifact: noop,
      regenerateMessageVoice: noop,
      revealMessageVoiceArtifact: noop,
    },
    navigationActions: {
      automationFolderControls: { moveAutomationThread: noop },
      automationSelectionControls: {
        openAutomationRunThread: noop,
        selectAutomationPane: noop,
        selectAutomationThread: noop,
        selectWorkflowAgentThread: noop,
        selectWorkflowRecordingForLab: noop,
      },
      createWorkspace: noop,
      loadWorkflowAgentFolders: noop,
      projectThreadActions: {
        confirmProjectActionDialog: noop,
        confirmThreadActionDialog: noop,
      },
      selectThread: noop,
      workspaceNavigationControls: { selectThread: noop },
    },
    permissionActions: {
      loadPermissionAudit: noop,
      loadPermissionGrants: noop,
      requestThreadPermissionModeChange: noop,
      respondPermissionRequest: noop,
      respondPrivilegedCredentialRequest: noop,
      respondSecureInputRequest: noop,
      revokePermissionGrant: noop,
      revokePermissionGrantIds: noop,
    },
    plannerActions: {
      answerPlannerDecisionQuestion: noop,
      finalizePlannerPlan: noop,
      implementPlannerPlan: noop,
      openPlannerRevisionDialog: noop,
      sendPlannerDurableRevision: noop,
      submitPlannerRevisionDialog: noop,
    },
    projectBoardControls: {
      activeProject: undefined,
      activeProjectBoardBusy: false,
      activeProjectBoardTopbarAction: undefined,
      activeThreadSuppressesProjectBoard: false,
      activeWorkspaceIsPreparedLocalTask: false,
      errorNeedsSessionRecovery: false,
      latestDurablePlannerPlanArtifact: undefined,
      projectBoardActions,
      projectBoardOpen: false,
      projectBoardPlanPickerOpen: false,
      projectBoardThreadPlanAction: undefined,
      readyPlannerPlanArtifacts: [],
      runProjectBoardThreadPlanAction: noop,
      sessionContextMissing: false,
      setProjectBoardOpen: noop,
    },
    projectShellState: {
      plannerRevisionDialog: undefined,
      projectActionDialog: undefined,
      projectBoardBusyProjectIds: new Set(),
      projectBoardFinalizeBusy: {},
      projectBoardKickoffDefaultsBusy: {},
      projectBoardProposalAnswerBusy: {},
      projectBoardProposalApplyBusy: {},
      projectBoardProposalCardReviewBusy: {},
      projectBoardRefineBusy: {},
      projectBoardRefineMode: {},
      projectBoardResetDialog: undefined,
      projectBoardRevisionBusy: {},
      projectBoardSourceBusy: {},
      projectBoardSourceImpactBusy: {},
      projectBoardSynthesisDeferBusy: {},
      projectBoardSynthesisPauseBusy: {},
      projectBoardSynthesisRetryBusy: {},
      setPlannerRevisionDialog: noop,
      setProjectActionDialog: noop,
      setProjectBoardResetDialog: noop,
      setThreadActionDialog: noop,
      threadActionDialog: undefined,
    },
    providerRuntimeActions: {
      cancelSttComposerRecording: noop,
      cancelSttMicTest: noop,
      discardSttComposerResult: noop,
      loadLocalDeepResearchRunHistory: noop,
      loadSttMicrophoneDeviceList: noop,
      loadSttProviders: noop,
      loadVoiceProviders: noop,
      localRuntimeActions: { setupLocalDeepResearchFromSettings: noop },
      openLocalDeepResearchFollowupIfSetupNeeded: noop,
      refreshVoiceCatalog: noop,
      retrySttComposerTranscription: noop,
      setupLocalDeepResearchFromSettings: noop,
      setupMiniCpmVisionProviderFromSettings: noop,
      setupSttProvider: noop,
      startSttComposerRecording: noop,
      startSttMicTest: noop,
      stopSttComposerRecording: noop,
      stopSttMicTestAndValidate: noop,
    },
    providerRuntimeState: {
      agentMemoryDiagnostics: undefined,
      agentMemoryDiagnosticsError: undefined,
      agentMemoryDiagnosticsLoading: false,
      agentMemoryEmbeddingActionError: undefined,
      agentMemoryEmbeddingActionLoading: false,
      agentMemoryEmbeddingActionResult: undefined,
      localDeepResearchFollowupOpen: false,
      localDeepResearchQ8Override: false,
      localDeepResearchRunHistory: [],
      localDeepResearchSetup: {},
      mcpContainerRuntimeInstallProgress: undefined,
      mcpDefaultCapabilityInstallProgress: undefined,
      miniCpmVisionEndpointUrl: "",
      miniCpmVisionRuntimePath: "",
      miniCpmVisionSetup: {},
      setLocalDeepResearchFollowupOpen: noop,
      setLocalDeepResearchQ8Override: noop,
      setMcpContainerRuntimeInstallProgress: noop,
      setMcpDefaultCapabilityInstallProgress: noop,
      setMiniCpmVisionEndpointUrl: noop,
      setMiniCpmVisionRuntimePath: noop,
      sttComposer: { status: "idle" },
      sttMicTest: {},
      sttMicrophoneDevices: [],
      sttMicrophoneDevicesError: undefined,
      sttMicrophoneDevicesLoading: false,
      sttProviderCacheActivity: undefined,
      sttProviderCacheStatus: undefined,
      sttProviderSetup: {},
      sttProviders: [],
      sttProvidersError: undefined,
      sttProvidersLoading: false,
      voiceCatalogRefresh: {},
      voiceProviderCacheActivity: undefined,
      voiceProviderCacheStatus: undefined,
      voiceProviders: [],
      voiceProvidersError: undefined,
      voiceProvidersLoading: false,
    },
    rightPanelState: {
      artifactPreviewRequest: undefined,
      gitPanelTabRequest: undefined,
      localFilePreviewRequest: undefined,
      openGitSummaryPanel: noop,
      openMcpRuntimeSettings: noop,
      openPanel: noop,
      openSearchWebSettings: noop,
      previewArtifact: noop,
      previewLocalFile: noop,
      rightPanel: undefined,
      rightPanelWidth: 420,
      setRightPanel: noop,
      settingsFocusRequest: undefined,
      togglePanel: noop,
    },
    runActivityState: {
      abortArmed: false,
      retryStatsByThread: {},
      runActivityLinesByThread: {},
      runStatus: { status: "idle" },
      runtimeStatusIndicatorsByThread: {},
      threadRunStatuses: {},
    },
    runDerivedState: {
      activeRunActivityLines: [],
      running: false,
      thinkingDisplayMode: "transient",
    },
    running: false,
    securityPromptState: {
      ambientCliSecretDialog: undefined,
      ambientCliSecretInputRef: { current: null },
      apiDialogOpen: false,
      apiKeyBusy: false,
      apiKeyDraft: "",
      apiKeyInputRef: { current: null },
      apiKeyStatus: undefined,
      clipboardCandidate: undefined,
      commandPaletteOpen: false,
      commandPaletteQuery: "",
      mediaPreviewModal: undefined,
      permissionAudit: [],
      permissionAuditError: undefined,
      permissionAuditRevision: 1,
      permissionGrantError: undefined,
      permissionGrantRevoking: {},
      permissionGrants: [],
      setAmbientCliSecretDialog: noop,
      setApiDialogOpen: noop,
      setApiKeyDraft: noop,
    },
    settingsActions: {
      clearAgentMemory: noop,
      hydrateSearchRoutingSettingsForSettingsPanel: noop,
      installModelProviderEndpoint: noop,
      runLocalModelRuntimeLifecycleAction: noop,
      saveModelProviderCredential: noop,
      updateFeatureFlagSettings: noop,
      updateLocalDeepResearchSettings: noop,
      updateMediaPlaybackSettings: noop,
      updateMemorySettings: noop,
      updateModelRuntimeSettings: noop,
      updatePlannerSettings: noop,
      updateSearchRoutingSettings: noop,
      updateSttSettings: noop,
      updateThinkingDisplaySettings: noop,
      updateVoiceSettings: noop,
    },
    shellCommandActions: {
      beginRightPanelResize: noop,
      beginSidebarResize: noop,
      beginWorkflowRecorderReviewResize: noop,
      commandItems: [],
      openMediaPreviewModal: noop,
      runPaletteCommand: noop,
      updateThemePreference: noop,
      updateThreadSettings: noop,
    },
    shellUiState: {
      clearError: noop,
      commandPaletteOpen: false,
      commandPaletteQuery: "",
      error: undefined,
      mediaPreviewModal: undefined,
      searchRoutingHydrationError: undefined,
      searchRoutingHydrating: false,
      setCommandPaletteOpen: noop,
      setCommandPaletteQuery: noop,
      setMediaPreviewModal: noop,
      setSidebarOpen: noop,
      setUpdatePopoverOpen: noop,
      sidebarArea: "projects",
      sidebarOpen: true,
      sidebarWidth: 280,
      updateBusy: false,
      updatePopoverOpen: false,
      workflowRecorderReviewPanelWidth: 360,
    },
    sidebarSelectionModel: {
      selectedAutomationFolder: undefined,
      selectedAutomationThread: undefined,
      selectedWorkflowAgentFolder: undefined,
      selectedWorkflowAgentThread: undefined,
    },
    state,
    subagentParentClusterActions: {
      cancelCallableWorkflowTask: noop,
      cancelSubagentChild: noop,
      closeSubagentChild: noop,
      openCallableWorkflowThread: noop,
      pauseCallableWorkflowTask: noop,
      resolveSubagentApprovalAction: noop,
      resolveSubagentBarrierAction: noop,
      resumeCallableWorkflowTask: noop,
      submitSubagentApprovalDecisionDialog: noop,
      submitSubagentBarrierDecisionDialog: noop,
    },
    subagentShellControls: {
      activeSubagentInspector: undefined,
      subagentParentClustersByMessageId: {},
      symphonyBuilderModel: undefined,
    },
    subagentUiEnabled: true,
    symphonyBuilderControls: {
      changeSymphonyBlocking: noop,
      changeSymphonyMetric: noop,
      changeSymphonyStepCustomText: noop,
      selectSymphonyPattern: noop,
      selectSymphonyStepChoice: noop,
      submitSymphonyBuilderAction: noop,
      toggleSymphonyBuilder: noop,
    },
    threadMaintenanceActions: {
      compactActiveThread: noop,
      duplicateActiveThreadFromTranscript: noop,
      exportActiveChat: noop,
      exportChatPdfThread: noop,
      exportDiagnostics: noop,
      importDiagnostics: noop,
      recoverActiveThreadContext: noop,
      recoverActiveThreadContextAndRetryLatest: noop,
    },
    updateActions: {
      runUpdateAction: noop,
    },
    voiceThreadControls: {
      activeThreadVoiceStatus: undefined,
      activeThreadVoiceStatusDismissKey: undefined,
      activeThreadVoiceStatusVisible: false,
      activeVoiceMessageId: undefined,
      autoplayVoiceKey: undefined,
      dismissActiveThreadVoiceStatus: noop,
      latestReadyVoiceAutoplay: undefined,
      setActiveVoiceMessageId: noop,
      voiceProviderLabels: {},
    },
    workflowRecordingActions: {
      applyLatestWorkflowRecordingSummary: noop,
      archiveWorkflowRecordingPlaybook: noop,
      confirmActiveWorkflowRecordingReview: noop,
      restoreWorkflowRecordingVersion: noop,
      retryWorkflowRecordingReview: noop,
      sendWorkflowRecordingReviewPrompt: noop,
      setWorkflowRecordingEnabled: noop,
      startWorkflowRecording: noop,
      stopActiveWorkflowRecording: noop,
      unarchiveWorkflowRecordingPlaybook: noop,
      updateActiveWorkflowRecordingReview: noop,
    },
    workflowRecordingLibraryControls: {
      refreshWorkflowRecordingLibrary: vi.fn(async () => undefined),
      selectedWorkflowRecording: undefined,
      selectedWorkflowRecordingId: undefined,
      setWorkflowLibraryIncludeArchived: noop,
      workflowLibraryIncludeArchived: false,
      workflowRecordingLibrary: [],
    },
    workflowRecordingPlaybookActions: {
      editWorkflowRecordingPlaybookInChat: noop,
    },
    workflowRecordingReviewControls: {
      conversationReviewPanelDocked: false,
      runStatusCardVisible: false,
      setWorkflowRecordingReviewPanelOpen: noop,
      workflowRecorderEmptyChatState: undefined,
      workflowRecordingReviewFeedbackActive: false,
      workflowRecordingReviewPanelOpen: false,
      workflowRecordingReviewRunning: false,
    },
    workflowRuntimeState,
    workspaceShellState: {
      activeGitReview: undefined,
      activeGitReviewError: undefined,
      browserRevision: 1,
      chatBrowserUserActionBusy: false,
      gitConfirmation: undefined,
      gitStatus: undefined,
      gitStatusError: undefined,
      pluginCatalogRevision: 1,
      setActiveGitReview: noop,
      setGitConfirmation: noop,
      setWorkspaceRevision: noop,
      welcomeAmbientPluginRegistry: undefined,
      workspaceRevision: 1,
    },
  } as unknown as AppShellSurfacePropsForAppInput;

  return input;
}

function desktopState(): DesktopState {
  return {
    activeThreadId: "thread-1",
    activeWorkspace: { path: "/tmp/workspace" },
    app: { update: { status: "idle" } },
    childMessagesByThreadId: {},
    messages: [],
    messageVoiceStates: {},
    projects: [],
    provider: { hasApiKey: true, providerLabel: "Ambient" },
    providerCatalog: undefined,
    settings: {
      localDeepResearch: {
        runBudget: {
          customMaxToolCalls: undefined,
          defaultEffort: "medium",
          onExhausted: "stop",
        },
      },
      media: { generatedMediaAutoplay: false },
      memory: { mode: "per_thread" },
      model: "model-1",
      modelRuntime: { showPromptCacheStatus: false },
      permissionMode: "full-access",
      stt: {
        enabled: false,
        providerCapabilityId: undefined,
        pushToTalkShortcut: undefined,
      },
      thinkingDisplay: { mode: "transient" },
      thinkingLevel: "medium",
    },
    sttQueue: undefined,
    subagentMailboxEvents: [],
    subagentRunEvents: [],
    threads: [],
    workspace: { name: "Workspace", path: "/tmp/workspace" },
  } as unknown as DesktopState;
}
