import type { SubagentParentClusterModel } from "./subagentParentClusterUiModel";
import { buildPatternGraphSnapshot } from "../../shared/subagentPatternGraph";
import { subagentPatternGraphRendererModel } from "./subagentPatternGraphUiModel";

export function subagentParentClusterFixtureModel(): SubagentParentClusterModel {
  return {
    parentMessageId: "message-1",
    title: "Parent waiting on sub-agents",
    summary: "2 children - 1 pattern graph - 1 workflow task - 1 blocking child",
    status: "Waiting",
    statusTone: "active",
    parentBlocking: {
      label: "Parent blocked on 1 child: approval needed",
      detail: "1 approval request / Reviewer",
      statusTone: "warning",
      blockingChildren: [{
        runId: "child-run-1",
        childThreadId: "child-thread-1",
        title: "Reviewer",
        label: "Reviewer: approval",
        detail: "Approval must be answered by parent. / approval-1 / this child thread",
        statusTone: "warning",
        kind: "approval",
      }],
    },
    patternGraphs: [
      subagentPatternGraphRendererModel(buildPatternGraphSnapshot({
        patternId: "imitate_and_verify",
        parentThreadId: "parent-thread-1",
        parentMessageId: "message-1",
        workflowTaskId: "workflow-task-1",
        workflowRunId: "workflow-run-1",
        updatedAt: "2026-06-13T00:00:00.000Z",
        childBindings: [
          {
            roleNodeId: "drafter",
            childRunId: "child-run-2",
            childThreadId: "child-thread-2",
            label: "Drafter",
            status: "completed",
            blockingParent: true,
            summary: "Draft complete.",
          },
          {
            roleNodeId: "verifier",
            childRunId: "child-run-1",
            childThreadId: "child-thread-1",
            label: "Verifier",
            status: "needs_attention",
            approvalState: "pending",
            blockingParent: true,
            summary: "Needs approval before continuing.",
          },
        ],
      })),
    ],
    barriers: [{
      id: "barrier-1",
      status: "Waiting",
      statusTone: "active",
      dependencyLabel: "All required children",
      childCountLabel: "2 children",
      blockingChildren: [{
        runId: "child-run-1",
        childThreadId: "child-thread-1",
        title: "Reviewer",
        canonicalTaskPath: "root/0:reviewer",
        status: "needs attention",
        statusTone: "warning",
        label: "Blocking child: reviewer",
        detail: "Reviewer is waiting on approval.",
      }],
      blockingChildLabels: ["Reviewer"],
      failurePolicyLabel: "Fail parent on required failure",
      effectRows: [{
        key: "unchanged-runs",
        label: "Unchanged 1 child",
        detail: "Runs: child-run-2",
        statusTone: "neutral",
      }],
      decisionLabel: "Retry requested",
      decisionSummary: "Retry after approval.",
      timeoutLabel: "30s timeout",
    }],
    workflowTasks: [{
      id: "workflow-task-1",
      title: "Imitate & Verify",
      status: "Running",
      statusTone: "active",
      modeLabel: "Blocking",
      sourceLabel: "Symphony recipe",
      workflowThreadId: "workflow-thread-1",
      workflowThreadLabel: "Workflow thread: workflow-thread-1",
      canOpenWorkflowThread: true,
      openWorkflowThreadTitle: "Open workflow thread workflow-thread-1",
      progressLabel: "Verifier active",
      capabilityLabels: ["Progress visible", "Token/cost", "Pause/resume/cancel"],
      telemetryLabels: ["3 events", "~42 tokens"],
      launchCardLabels: ["Risk: High", "Budget: 180,000 tokens"],
      provenanceLabels: [
        "Caller: sub-agent child",
        "Approval: Child Bridge Policy",
        "Worktree: isolated",
        "Nested fanout: Child Bridge Policy",
      ],
      canPause: true,
      pauseTitle: "Pause blocking workflow task",
      canCancel: true,
      cancelTitle: "Cancel blocking workflow task",
      canResume: false,
      resumeTitle: "Resume blocking workflow task",
      parentBlocker: {
        kind: "waiting",
        label: "Blocking: workflow work",
        detail: "Parent is blocked on workflow-task-1.",
        statusTone: "active",
      },
      detail: "Provenance: sub-agent child / worktree isolated / nested fanout required",
    }],
    mailboxActivities: [{
      id: "mailbox-1",
      label: "Approval requested",
      sourceLabel: "Child source: run child-run-1 / thread child-thread-1",
      statusTone: "warning",
      summary: "Tool approval needed",
      detail: "Approval request includes child identity.",
      approvalActions: [{
        label: "Approve child",
        title: "Approve for this child thread",
        decision: "approved",
        childRunId: "child-run-1",
        childThreadId: "child-thread-1",
        approvalId: "approval-1",
        approvalRequestParentMailboxEventId: "mailbox-1",
        requestedScope: "this_child_thread",
        effectiveScope: "this_child_thread",
      }],
      actions: [{
        label: "Retry barrier",
        title: "Retry required barrier",
        waitBarrierId: "barrier-1",
        decision: "retry_child",
        requiresUserDecision: false,
        requiresPartialSummary: false,
      }],
      actionLabels: ["Retry barrier", "Detach child"],
      updatedAt: "2026-06-10T00:00:00.000Z",
    }, {
      id: "mailbox-2",
      label: "Parent stopped",
      sourceLabel: "Child source: run child-run-1",
      statusTone: "danger",
      summary: "1 cancelled · 1 wait barrier cancelled",
      detail: "Parent cancellation requested by user.",
      effectRows: [{
        key: "cancelled-runs",
        label: "Cancelled 1 child",
        detail: "Runs: child-run-1",
        statusTone: "danger",
      }, {
        key: "cancelled-wait-barriers",
        label: "1 wait barrier cancelled",
        detail: "Wait barriers: barrier-1",
        statusTone: "warning",
      }, {
        key: "parent-cancellation-requested",
        label: "Parent cancellation requested",
        detail: "Parent run cancellation was requested by the barrier decision.",
        statusTone: "danger",
      }],
      updatedAt: "2026-06-10T00:00:01.000Z",
    }],
    children: [{
      runId: "child-run-1",
      childThreadId: "child-thread-1",
      workspacePath: "/workspace",
      canOpenThread: true,
      openThreadTitle: "Open child thread child-thread-1",
      title: "Reviewer",
      status: "Needs attention",
      runStatus: "needs_attention",
      statusTone: "warning",
      isTerminal: false,
      isSynthesisSafe: false,
      dependencyLabel: "Required",
      runtimeLabel: "Example Model",
      preview: "Needs approval before continuing.",
      canCancel: true,
      cancelTitle: "Cancel sub-agent Reviewer",
      canClose: false,
      closeTitle: "Close sub-agent Reviewer",
      parentBlocker: {
        kind: "approval",
        label: "Blocking: approval",
        detail: "Approval must be answered by parent.",
        statusTone: "warning",
        metaLabels: ["approval-1", "this child thread"],
      },
    }, {
      runId: "child-run-2",
      childThreadId: "child-thread-2",
      workspacePath: "/workspace",
      canOpenThread: false,
      openThreadTitle: "Child thread retained as summary",
      title: "Summarizer",
      status: "Completed",
      runStatus: "completed",
      statusTone: "success",
      isTerminal: true,
      isSynthesisSafe: true,
      dependencyLabel: "Optional",
      runtimeLabel: "Local text",
      preview: "Summary retained for parent synthesis.",
      canCancel: false,
      cancelTitle: "Cancel sub-agent Summarizer",
      canClose: true,
      closeTitle: "Close sub-agent Summarizer",
      retentionLabel: "Summary retained",
      retentionTitle: "Full transcript is retained until cleanup.",
    }],
  };
}
