import { contextBridge, ipcRenderer } from "electron";
import type { AgentMemoryClearInput, AgentMemoryEmbeddingLifecycleActionInput } from "../shared/agentMemoryDiagnostics";
import type { UpdateAgentMemorySettingsInput } from "../shared/agentMemorySettings";
import type { AgentMemoryStarterDisableInput, AgentMemoryStarterEnableInput, AgentMemoryStarterRepairInput } from "../shared/agentMemoryStarter";
import type { AutomationScheduleOccurrenceActionInput, CreateAutomationFolderInput, CreateAutomationScheduleInput, MoveAutomationThreadInput, UpdateAutomationScheduleInput } from "../shared/automationTypes";
import type { BrowserContentInput, BrowserKeypressInput, BrowserLocalPreviewInput, BrowserNavigateInput, BrowserPickInput, BrowserRevealInput, BrowserSearchInput, BrowserStartInput, BrowserViewBoundsInput, DeleteBrowserCredentialInput, SaveBrowserCredentialInput } from "../shared/browserTypes";
import type { AmbientDesktopApi, ApplyWorkflowRecordingSummaryInput, CompactThreadInput, CreateThreadInput, DesktopEvent, ForkThreadInput, ProjectActionInput, RecoverThreadContextInput, RequestThreadPermissionModeChangeInput, SelectProjectInput, SendMessageInput, SetThemePreferenceInput, ThreadActionInput, UpdateLocalDeepResearchSettingsInput, UpdateModelRuntimeSettingsInput, UpdatePlannerPlanArtifactInput, UpdatePlannerSettingsInput, UpdateProjectInput, UpdateSearchRoutingSettingsInput, UpdateSttSettingsInput, UpdateThinkingDisplaySettingsInput, UpdateThreadInput, UpdateThreadSettingsInput, UpdateVoiceSettingsInput } from "../shared/desktopTypes";
import type { UpdateFeatureFlagSettingsInput } from "../shared/featureFlags";
import type { LocalDeepResearchRunHistoryInput, LocalDeepResearchSetupInput, LocalModelRuntimeLifecycleActionInput, MessageVoiceArtifactInput, MiniCpmVisionAnalyzeInput, MiniCpmVisionSetupInput, RefreshVoiceProviderVoicesInput, RegenerateMessageVoiceInput, SetSttTtsSpeakingInput, SttProviderSetupInput, SttTestAudioInput, SttTranscribeAudioInput, VoiceArtifactRetentionInput } from "../shared/localRuntimeTypes";
import type { CreateAmbientPermissionGrantInput, PermissionPromptResponseMode, PrivilegedCredentialPromptResponseInput, RevokeAmbientPermissionGrantInput, SecureInputPromptResponseInput } from "../shared/permissionTypes";
import type { AnswerPlannerDecisionQuestionInput, GeneratePlannerDurableArtifactInput } from "../shared/plannerTypes";
import type { AddCodexMarketplaceInput, AmbientMcpContainerRuntimeInstallLaunchInput, AmbientMcpContainerRuntimeLifecyclePreviewInput, AmbientMcpContainerRuntimeLifecycleRunInput, AmbientMcpDefaultCapabilityInstallInput, AmbientMcpServerDescribeInput, AmbientMcpServerInstallInput, AmbientMcpServerSearchInput, AmbientMcpServerUninstallInput, AmbientMcpToolReviewAcceptInput, CapabilityBuilderHistoryInput, CompletePluginAppAuthInput, GetAmbientPluginCapabilityDiagnosticsInput, GoogleWorkspaceOAuthClientImportInput, GoogleWorkspaceSetupInput, GoogleWorkspaceValidationInput, ImportCodexPluginInput, InstallCodexPluginDependenciesInput, InstallPiExtensionSandboxPackageInput, InstallPiPackageInput, InstallPiPrivilegedPackageInput, ListAmbientPluginRuntimeCapabilitiesInput, PiPrivilegedPackageActionInput, PluginAuthAccountActionInput, PluginMcpRuntimeActionInput, PreviewPiExtensionSandboxPackageInput, PreviewPiPackageInstallInput, ReadCodexPluginInput, RemoveCodexMarketplaceInput, SaveAmbientCliSecretInput, ScanPiPrivilegedPackageInput, SetCodexPluginEnabledInput, SetCodexPluginTrustedInput, SetPiPackageEnabledInput, StartPluginAppAuthInput, UninstallCodexPluginInput, UninstallPiExtensionSandboxPackageInput, UninstallPiPackageInput, UninstallPiPrivilegedPackageInput } from "../shared/pluginTypes";
import type { AddProjectBoardCardRunFeedbackInput, AnswerProjectBoardQuestionInput, AnswerProjectBoardSynthesisProposalQuestionInput, ApplyProjectBoardDecisionImpactFeedbackInput, ApplyProjectBoardSourceImpactFeedbackInput, ApplyProjectBoardSynthesisProposalInput, ApproveProjectBoardCardInput, AttachProjectBoardLocalTaskInput, CancelProjectBoardRevisionInput, CopyProjectBoardSessionToThreadInput, CreateProjectBoardCardInput, CreateProjectBoardInput, CreateReadyProjectBoardTasksInput, DeferProjectBoardSynthesisSectionsInput, FinalizeProjectBoardKickoffInput, PauseProjectBoardSynthesisInput, ProjectBoardGitCardClaimInput, ProjectBoardGitCardClaimReleaseInput, ProjectBoardGitSyncInput, PromotePlannerPlanToBoardInput, RecomputeProjectBoardProofCoverageInput, RefineProjectBoardSynthesisInput, RefreshProjectBoardDecisionDraftsInput, RefreshProjectBoardSourceDraftsInput, RefreshProjectBoardSourcesInput, RegenerateProjectBoardDecisionDraftsInput, RegenerateProjectBoardSourceDraftsInput, RerunProjectBoardProofInput, ResetProjectBoardInput, ResolveProjectBoardCardPiUpdateInput, ResolveProjectBoardDeliverableIntegrationInput, ResolveProjectBoardProofDecisionInput, ResolveProjectBoardSplitDecisionInput, RetryProjectBoardSynthesisInput, ReviewProjectBoardSynthesisProposalCardInput, ReviseProjectBoardInput, SeedProjectBoardCanonicalProjectionDogfoodInput, SeedProjectBoardDeliverableIntegrationDogfoodInput, SeedProjectBoardProofJudgmentDogfoodInput, SeedProjectBoardSemanticIdleDogfoodInput, SplitProjectBoardCardInput, SuggestProjectBoardClarificationDefaultsInput, SuggestProjectBoardKickoffDefaultsInput, SuggestProjectBoardProofInput, UpdateProjectBoardCardCandidateInput, UpdateProjectBoardCardInput, UpdateProjectBoardSourceInput, UpdateProjectBoardStatusInput } from "../shared/projectBoardTypes";
import type { SlashCommandDescribeInput, SlashCommandSearchInput } from "../shared/slashCommandTypes";
import type { CancelSubagentRunInput, CloseSubagentRunInput, ResolveSubagentApprovalInput, ResolveSubagentWaitBarrierInput } from "../shared/subagentTypes";
import type { RequestTerminalStartInput, ResizeTerminalInput, StartTerminalInput, StopTerminalInput, SubmitTerminalCommandInput, TerminalControlInput } from "../shared/terminalTypes";
import type { ExportChatInput, ExportChatPdfInput, InstallModelProviderEndpointInput, SaveModelProviderCredentialInput, ThreadGoalClearInput, ThreadGoalGetInput, ThreadGoalSetInput } from "../shared/threadTypes";
import type { AdoptWorkflowLabVariantInput, AnswerWorkflowDiscoveryQuestionInput, ArchiveWorkflowRecordingInput, CancelCallableWorkflowTaskInput, CancelOrchestrationRunInput, CancelWorkflowRunInput, CompileWorkflowDebugRewriteInput, CompileWorkflowPreviewInput, ConfirmWorkflowRecordingInput, CreateOrchestrationTaskInput, CreateWorkflowAgentFolderInput, CreateWorkflowAgentThreadInput, CreateWorkflowLabRunInput, CreateWorkflowRevisionInput, DescribeWorkflowDiscoveryCapabilityInput, DescribeWorkflowRecordingInput, GetWorkflowLabRunInput, InvokeWorkflowNativeToolInput, ListWorkflowAgentChatMessagesInput, ListWorkflowLabRunsInput, ListWorkflowRevisionsInput, ListWorkflowVersionsInput, MoveWorkflowAgentThreadInput, PauseCallableWorkflowTaskInput, RecoverWorkflowRunInput, RepairOrchestrationWorkflowInput, RequestWorkflowRecordingReviewInput, ResolveOrchestrationWorkflowImpactInput, ResolveWorkflowApprovalInput, ResolveWorkflowDiscoveryAccessRequestInput, ResolveWorkflowRevisionInput, RestoreWorkflowRecordingVersionInput, RestoreWorkflowVersionInput, ResumeCallableWorkflowTaskInput, RevalidateWorkflowArtifactInput, RevealOrchestrationWorkspaceInput, ReviewWorkflowArtifactInput, RunWorkflowArtifactInput, RunWorkflowThreadExplorationInput, SaveSymphonyWorkflowRecipeInput, SearchWorkflowDiscoveryCapabilitiesInput, SearchWorkflowRecordingsInput, SetWorkflowRecordingEnabledInput, StartOrchestrationRunInput, StartWorkflowDiscoveryInput, StartWorkflowLabRunInput, StartWorkflowRecordingInput, StartWorkflowRevisionDiscoveryInput, StopWorkflowLabRunInput, StopWorkflowRecordingInput, UnarchiveWorkflowRecordingInput, UpdateOrchestrationTaskInput, UpdateOrchestrationWorkflowRawInput, UpdateOrchestrationWorkflowSettingsInput, UpdateWorkflowArtifactSourceInput, UpdateWorkflowConnectorGrantInput, UpdateWorkflowRecordingPlaybookInput, UpdateWorkflowRecordingReviewInput, UpdateWorkflowRevisionInput, WorkflowRunDetailInput } from "../shared/workflowTypes";
import type { PickWorkspaceContextInput } from "../shared/workspaceTypes";

const api: AmbientDesktopApi = {
  bootstrap: () => ipcRenderer.invoke("app:bootstrap"),
  setThemePreference: (input: SetThemePreferenceInput) => ipcRenderer.invoke("appearance:set-theme-preference", input),
  updateMediaPlaybackSettings: (input) => ipcRenderer.invoke("media:update-playback-settings", input),
  updateThinkingDisplaySettings: (input: UpdateThinkingDisplaySettingsInput) => ipcRenderer.invoke("thinking-display:update-settings", input),
  updateModelRuntimeSettings: (input: UpdateModelRuntimeSettingsInput) => ipcRenderer.invoke("model-runtime:update-settings", input),
  saveModelProviderCredential: (input: SaveModelProviderCredentialInput) => ipcRenderer.invoke("model-runtime:save-provider-credential", input),
  installModelProviderEndpoint: (input: InstallModelProviderEndpointInput) => ipcRenderer.invoke("model-runtime:install-endpoint-provider", input),
  runLocalModelRuntimeLifecycleAction: (input: LocalModelRuntimeLifecycleActionInput) => ipcRenderer.invoke("model-runtime:lifecycle-action", input),
  updateFeatureFlagSettings: (input: UpdateFeatureFlagSettingsInput) => ipcRenderer.invoke("feature-flags:update-settings", input),
  updateMemorySettings: (input: UpdateAgentMemorySettingsInput) => ipcRenderer.invoke("memory:update-settings", input),
  getAgentMemoryStarterStatus: () => ipcRenderer.invoke("memory:starter-status"),
  enableAgentMemoryStarter: (input?: AgentMemoryStarterEnableInput) => ipcRenderer.invoke("memory:starter-enable", input),
  repairAgentMemoryStarter: (input?: AgentMemoryStarterRepairInput) => ipcRenderer.invoke("memory:starter-repair", input),
  disableAgentMemoryStarter: (input?: AgentMemoryStarterDisableInput) => ipcRenderer.invoke("memory:starter-disable", input),
  getAgentMemoryDiagnostics: () => ipcRenderer.invoke("memory:diagnostics"),
  runAgentMemoryEmbeddingLifecycleAction: (input: AgentMemoryEmbeddingLifecycleActionInput) => ipcRenderer.invoke("memory:embedding-lifecycle-action", input),
  clearAgentMemory: (input: AgentMemoryClearInput) => ipcRenderer.invoke("memory:clear", input),
  updatePlannerSettings: (input: UpdatePlannerSettingsInput) => ipcRenderer.invoke("planner:update-settings", input),
  hydrateSearchRoutingSettings: () => ipcRenderer.invoke("search-routing:hydrate-settings"),
  updateSearchRoutingSettings: (input: UpdateSearchRoutingSettingsInput) => ipcRenderer.invoke("search-routing:update-settings", input),
  updateLocalDeepResearchSettings: (input: UpdateLocalDeepResearchSettingsInput) => ipcRenderer.invoke("local-deep-research:update-settings", input),
  listVoiceProviders: () => ipcRenderer.invoke("voice:list-providers"),
  listSttProviders: () => ipcRenderer.invoke("stt:list-providers"),
  setupSttProvider: (input: SttProviderSetupInput) => ipcRenderer.invoke("stt:setup-provider", input),
  setupMiniCpmVisionProvider: (input: MiniCpmVisionSetupInput) => ipcRenderer.invoke("vision:minicpm-setup-provider", input),
  analyzeMiniCpmVisionInput: (input: MiniCpmVisionAnalyzeInput) => ipcRenderer.invoke("vision:minicpm-analyze", input),
  setupLocalDeepResearch: (input: LocalDeepResearchSetupInput) => ipcRenderer.invoke("local-deep-research:setup", input),
  listLocalDeepResearchRuns: (input?: LocalDeepResearchRunHistoryInput) => ipcRenderer.invoke("local-deep-research:list-runs", input),
  saveSttTestAudio: (input: SttTestAudioInput) => ipcRenderer.invoke("stt:save-test-audio", input),
  transcribeSttAudio: (input: SttTranscribeAudioInput) => ipcRenderer.invoke("stt:transcribe-audio", input),
  cancelSttTranscription: () => ipcRenderer.invoke("stt:cancel-transcription"),
  setSttTtsSpeaking: (input: SetSttTtsSpeakingInput) => ipcRenderer.invoke("stt:set-tts-speaking", input),
  refreshVoiceProviderVoices: (input: RefreshVoiceProviderVoicesInput) => ipcRenderer.invoke("voice:refresh-provider-voices", input),
  getVoiceOnboardingHostFacts: () => ipcRenderer.invoke("voice:onboarding-host-facts"),
  regenerateMessageVoice: (input: RegenerateMessageVoiceInput) => ipcRenderer.invoke("voice:regenerate-message", input),
  revealMessageVoiceArtifact: (input: MessageVoiceArtifactInput) => ipcRenderer.invoke("voice:reveal-artifact", input),
  clearMessageVoiceArtifact: (input: MessageVoiceArtifactInput) => ipcRenderer.invoke("voice:clear-artifact", input),
  inspectVoiceArtifacts: (input?: VoiceArtifactRetentionInput) => ipcRenderer.invoke("voice:inspect-artifacts", input),
  pruneVoiceArtifacts: (input?: VoiceArtifactRetentionInput) => ipcRenderer.invoke("voice:prune-artifacts", input),
  updateVoiceSettings: (input: UpdateVoiceSettingsInput) => ipcRenderer.invoke("voice:update-settings", input),
  updateSttSettings: (input: UpdateSttSettingsInput) => ipcRenderer.invoke("stt:update-settings", input),
  openWorkspace: () => ipcRenderer.invoke("workspace:open"),
  createWorkspace: () => ipcRenderer.invoke("workspace:create"),
  createThread: (input?: CreateThreadInput) => ipcRenderer.invoke("thread:create", input),
  startWorkflowRecording: (input: StartWorkflowRecordingInput) => ipcRenderer.invoke("workflow-recorder:start", input),
  stopWorkflowRecording: (input: StopWorkflowRecordingInput) => ipcRenderer.invoke("workflow-recorder:stop", input),
  requestWorkflowRecordingReview: (input: RequestWorkflowRecordingReviewInput) => ipcRenderer.invoke("workflow-recorder:request-review", input),
  updateWorkflowRecordingReview: (input: UpdateWorkflowRecordingReviewInput) => ipcRenderer.invoke("workflow-recorder:update-review", input),
  confirmWorkflowRecording: (input: ConfirmWorkflowRecordingInput) => ipcRenderer.invoke("workflow-recorder:confirm", input),
  applyWorkflowRecordingSummary: (input: ApplyWorkflowRecordingSummaryInput) => ipcRenderer.invoke("workflow-recorder:apply-summary", input),
  searchWorkflowRecordings: (input?: SearchWorkflowRecordingsInput) => ipcRenderer.invoke("workflow-recorder:search", input),
  describeWorkflowRecording: (input: DescribeWorkflowRecordingInput) => ipcRenderer.invoke("workflow-recorder:describe", input),
  searchSlashCommands: (input?: SlashCommandSearchInput) => ipcRenderer.invoke("slash-commands:search", input),
  describeSlashCommand: (input: SlashCommandDescribeInput) => ipcRenderer.invoke("slash-commands:describe", input),
  setWorkflowRecordingEnabled: (input: SetWorkflowRecordingEnabledInput) => ipcRenderer.invoke("workflow-recorder:set-enabled", input),
  updateWorkflowRecordingPlaybook: (input: UpdateWorkflowRecordingPlaybookInput) => ipcRenderer.invoke("workflow-recorder:update-playbook", input),
  saveSymphonyWorkflowRecipe: (input: SaveSymphonyWorkflowRecipeInput) => ipcRenderer.invoke("workflow-recorder:save-symphony-recipe", input),
  archiveWorkflowRecording: (input: ArchiveWorkflowRecordingInput) => ipcRenderer.invoke("workflow-recorder:archive", input),
  unarchiveWorkflowRecording: (input: UnarchiveWorkflowRecordingInput) => ipcRenderer.invoke("workflow-recorder:unarchive", input),
  restoreWorkflowRecordingVersion: (input: RestoreWorkflowRecordingVersionInput) => ipcRenderer.invoke("workflow-recorder:restore-version", input),
  createWorkflowLabRun: (input: CreateWorkflowLabRunInput) => ipcRenderer.invoke("workflow-lab:create-run", input),
  listWorkflowLabRuns: (input?: ListWorkflowLabRunsInput) => ipcRenderer.invoke("workflow-lab:list-runs", input),
  getWorkflowLabRun: (input: GetWorkflowLabRunInput) => ipcRenderer.invoke("workflow-lab:get-run", input),
  startWorkflowLabRun: (input: StartWorkflowLabRunInput) => ipcRenderer.invoke("workflow-lab:start-run", input),
  stopWorkflowLabRun: (input: StopWorkflowLabRunInput) => ipcRenderer.invoke("workflow-lab:stop-run", input),
  adoptWorkflowLabVariant: (input: AdoptWorkflowLabVariantInput) => ipcRenderer.invoke("workflow-lab:adopt-variant", input),
  selectThread: (threadId) => ipcRenderer.invoke("thread:select", threadId),
  selectProject: (input: SelectProjectInput) => ipcRenderer.invoke("project:select", input),
  updateProject: (input: UpdateProjectInput) => ipcRenderer.invoke("project:update", input),
  removeProject: (input: ProjectActionInput) => ipcRenderer.invoke("project:remove", input),
  revealProject: (input: ProjectActionInput) => ipcRenderer.invoke("project:reveal", input),
  createProjectBoard: (input: CreateProjectBoardInput) => ipcRenderer.invoke("project-board:create", input),
  reviseProjectBoard: (input: ReviseProjectBoardInput) => ipcRenderer.invoke("project-board:revise", input),
  cancelProjectBoardRevision: (input: CancelProjectBoardRevisionInput) => ipcRenderer.invoke("project-board:cancel-revision", input),
  resetProjectBoard: (input: ResetProjectBoardInput) => ipcRenderer.invoke("project-board:reset", input),
  pauseProjectBoardSynthesis: (input: PauseProjectBoardSynthesisInput) => ipcRenderer.invoke("project-board:pause-synthesis", input),
  retryProjectBoardSynthesis: (input: RetryProjectBoardSynthesisInput) => ipcRenderer.invoke("project-board:retry-synthesis", input),
  abandonProjectBoardSynthesisRun: (input: { boardId: string; runId: string; reason?: string }) =>
    ipcRenderer.invoke("project-board:abandon-synthesis-run", input),
  seedProjectBoardSemanticIdleDogfood: (input: SeedProjectBoardSemanticIdleDogfoodInput) =>
    ipcRenderer.invoke("project-board:dogfood-seed-semantic-idle-section", input),
  seedProjectBoardProofJudgmentDogfood: (input: SeedProjectBoardProofJudgmentDogfoodInput) =>
    ipcRenderer.invoke("project-board:dogfood-seed-proof-judgment", input),
  seedProjectBoardCanonicalProjectionDogfood: (input: SeedProjectBoardCanonicalProjectionDogfoodInput) =>
    ipcRenderer.invoke("project-board:dogfood-seed-canonical-projection", input),
  seedProjectBoardDeliverableIntegrationDogfood: (input: SeedProjectBoardDeliverableIntegrationDogfoodInput) =>
    ipcRenderer.invoke("project-board:dogfood-seed-deliverable-integration", input),
  deferProjectBoardSynthesisSections: (input: DeferProjectBoardSynthesisSectionsInput) =>
    ipcRenderer.invoke("project-board:defer-synthesis-sections", input),
  updateProjectBoardStatus: (input: UpdateProjectBoardStatusInput) => ipcRenderer.invoke("project-board:update-status", input),
  promotePlannerPlanToBoard: (input: PromotePlannerPlanToBoardInput) => ipcRenderer.invoke("project-board:promote-plan", input),
  approveProjectBoardCard: (input: ApproveProjectBoardCardInput) => ipcRenderer.invoke("project-board:approve-card", input),
  resolveProjectBoardProofDecision: (input: ResolveProjectBoardProofDecisionInput) =>
    ipcRenderer.invoke("project-board:resolve-proof-decision", input),
  rerunProjectBoardProof: (input: RerunProjectBoardProofInput) => ipcRenderer.invoke("project-board:rerun-proof", input),
  resolveProjectBoardDeliverableIntegration: (input: ResolveProjectBoardDeliverableIntegrationInput) =>
    ipcRenderer.invoke("project-board:resolve-deliverable-integration", input),
  recomputeProjectBoardProofCoverage: (input: RecomputeProjectBoardProofCoverageInput) =>
    ipcRenderer.invoke("project-board:recompute-proof-coverage", input),
  suggestProjectBoardProof: (input: SuggestProjectBoardProofInput) => ipcRenderer.invoke("project-board:suggest-proof", input),
  resolveProjectBoardSplitDecision: (input: ResolveProjectBoardSplitDecisionInput) =>
    ipcRenderer.invoke("project-board:resolve-split-decision", input),
  createReadyProjectBoardTasks: (input: CreateReadyProjectBoardTasksInput) => ipcRenderer.invoke("project-board:create-ready-tasks", input),
  splitProjectBoardCard: (input: SplitProjectBoardCardInput) => ipcRenderer.invoke("project-board:split-card", input),
  createProjectBoardCard: (input: CreateProjectBoardCardInput) => ipcRenderer.invoke("project-board:create-card", input),
  attachProjectBoardLocalTask: (input: AttachProjectBoardLocalTaskInput) => ipcRenderer.invoke("project-board:attach-local-task", input),
  updateProjectBoardCard: (input: UpdateProjectBoardCardInput) => ipcRenderer.invoke("project-board:update-card", input),
  updateProjectBoardCardCandidate: (input: UpdateProjectBoardCardCandidateInput) => ipcRenderer.invoke("project-board:update-card-candidate", input),
  resolveProjectBoardCardPiUpdate: (input: ResolveProjectBoardCardPiUpdateInput) => ipcRenderer.invoke("project-board:resolve-card-pi-update", input),
  addProjectBoardCardRunFeedback: (input: AddProjectBoardCardRunFeedbackInput) => ipcRenderer.invoke("project-board:add-run-feedback", input),
  copyProjectBoardSessionToThread: (input: CopyProjectBoardSessionToThreadInput) =>
    ipcRenderer.invoke("project-board:copy-session-to-thread", input),
  suggestProjectBoardClarificationDefaults: (input: SuggestProjectBoardClarificationDefaultsInput) =>
    ipcRenderer.invoke("project-board:suggest-clarification-defaults", input),
  suggestProjectBoardKickoffDefaults: (input: SuggestProjectBoardKickoffDefaultsInput) =>
    ipcRenderer.invoke("project-board:suggest-kickoff-defaults", input),
  applyProjectBoardDecisionImpactFeedback: (input: ApplyProjectBoardDecisionImpactFeedbackInput) =>
    ipcRenderer.invoke("project-board:apply-decision-impact-feedback", input),
  refreshProjectBoardDecisionDrafts: (input: RefreshProjectBoardDecisionDraftsInput) =>
    ipcRenderer.invoke("project-board:refresh-decision-drafts", input),
  regenerateProjectBoardDecisionDrafts: (input: RegenerateProjectBoardDecisionDraftsInput) =>
    ipcRenderer.invoke("project-board:regenerate-decision-drafts", input),
  refreshProjectBoardSourceDrafts: (input: RefreshProjectBoardSourceDraftsInput) =>
    ipcRenderer.invoke("project-board:refresh-source-drafts", input),
  regenerateProjectBoardSourceDrafts: (input: RegenerateProjectBoardSourceDraftsInput) =>
    ipcRenderer.invoke("project-board:regenerate-source-drafts", input),
  applyProjectBoardSourceImpactFeedback: (input: ApplyProjectBoardSourceImpactFeedbackInput) =>
    ipcRenderer.invoke("project-board:apply-source-impact-feedback", input),
  refreshProjectBoardSources: (input: RefreshProjectBoardSourcesInput) => ipcRenderer.invoke("project-board:refresh-sources", input),
  refineProjectBoardSynthesis: (input: RefineProjectBoardSynthesisInput) => ipcRenderer.invoke("project-board:refine-synthesis", input),
  answerProjectBoardSynthesisProposalQuestion: (input: AnswerProjectBoardSynthesisProposalQuestionInput) =>
    ipcRenderer.invoke("project-board:answer-synthesis-proposal-question", input),
  reviewProjectBoardSynthesisProposalCard: (input: ReviewProjectBoardSynthesisProposalCardInput) =>
    ipcRenderer.invoke("project-board:review-synthesis-proposal-card", input),
  applyProjectBoardSynthesisProposal: (input: ApplyProjectBoardSynthesisProposalInput) =>
    ipcRenderer.invoke("project-board:apply-synthesis-proposal", input),
  updateProjectBoardSource: (input: UpdateProjectBoardSourceInput) => ipcRenderer.invoke("project-board:update-source", input),
  answerProjectBoardQuestion: (input: AnswerProjectBoardQuestionInput) => ipcRenderer.invoke("project-board:answer-question", input),
  finalizeProjectBoardKickoff: (input: FinalizeProjectBoardKickoffInput) => ipcRenderer.invoke("project-board:finalize-kickoff", input),
  getProjectBoardGitSyncStatus: (input: ProjectBoardGitSyncInput) => ipcRenderer.invoke("project-board:git-sync-status", input),
  exportProjectBoardGitArtifacts: (input: ProjectBoardGitSyncInput) => ipcRenderer.invoke("project-board:git-export", input),
  commitProjectBoardGitArtifacts: (input: ProjectBoardGitSyncInput) => ipcRenderer.invoke("project-board:git-commit", input),
  pushProjectBoardGitArtifacts: (input: ProjectBoardGitSyncInput) => ipcRenderer.invoke("project-board:git-push", input),
  pullProjectBoardGitArtifacts: (input: ProjectBoardGitSyncInput) => ipcRenderer.invoke("project-board:git-pull", input),
  applyPulledProjectBoardGitProjection: (input: ProjectBoardGitSyncInput) => ipcRenderer.invoke("project-board:git-apply-pulled", input),
  claimProjectBoardGitCard: (input: ProjectBoardGitCardClaimInput) => ipcRenderer.invoke("project-board:git-claim-card", input),
  releaseProjectBoardGitCardClaim: (input: ProjectBoardGitCardClaimReleaseInput) => ipcRenderer.invoke("project-board:git-release-card-claim", input),
  expireProjectBoardGitCardClaim: (input: ProjectBoardGitCardClaimReleaseInput) => ipcRenderer.invoke("project-board:git-expire-card-claim", input),
  resolveProjectBoardGitCardClaimConflicts: (input: ProjectBoardGitCardClaimReleaseInput) =>
    ipcRenderer.invoke("project-board:git-resolve-card-claim-conflicts", input),
  archiveProjectChats: (input: ProjectActionInput) => ipcRenderer.invoke("project:archive-chats", input),
  createPermanentProjectWorktree: (input: ProjectActionInput) => ipcRenderer.invoke("project:create-permanent-worktree", input),
  updateThread: (input: UpdateThreadInput) => ipcRenderer.invoke("thread:update", input),
  archiveThread: (input: ThreadActionInput) => ipcRenderer.invoke("thread:archive", input),
  markThreadUnread: (input: ThreadActionInput) => ipcRenderer.invoke("thread:mark-unread", input),
  revealThread: (input: ThreadActionInput) => ipcRenderer.invoke("thread:reveal", input),
  forkThread: (input: ForkThreadInput) => ipcRenderer.invoke("thread:fork", input),
  openThreadMiniWindow: (input: ThreadActionInput) => ipcRenderer.invoke("thread:open-mini-window", input),
  updateThreadSettings: (input: UpdateThreadSettingsInput) => ipcRenderer.invoke("thread:update-settings", input),
  requestThreadPermissionModeChange: (input: RequestThreadPermissionModeChangeInput) =>
    ipcRenderer.invoke("thread:request-permission-mode-change", input),
  updatePlannerPlanArtifact: (input: UpdatePlannerPlanArtifactInput) => ipcRenderer.invoke("planner-plan:update", input),
  generatePlannerDurableArtifact: (input: GeneratePlannerDurableArtifactInput) =>
    ipcRenderer.invoke("planner-plan:generate-durable-artifact", input),
  answerPlannerDecisionQuestion: (input: AnswerPlannerDecisionQuestionInput) =>
    ipcRenderer.invoke("planner-plan:answer-question", input),
  openAmbientKeys: () => ipcRenderer.invoke("ambient:open-keys"),
  openExternalUrl: (url: string) => ipcRenderer.invoke("links:open-external", url),
  readClipboardText: () => ipcRenderer.invoke("clipboard:read-text"),
  writeClipboardText: (text: string) => ipcRenderer.invoke("clipboard:write-text", text),
  saveAmbientApiKey: (apiKey: string) => ipcRenderer.invoke("ambient:save-api-key", apiKey),
  clearAmbientApiKey: () => ipcRenderer.invoke("ambient:clear-api-key"),
  testAmbientApiKey: (apiKey?: string) => ipcRenderer.invoke("ambient:test-api-key", apiKey),
  refreshSecureStorageStatus: () => ipcRenderer.invoke("secure-storage:refresh"),
  saveNamedSecret: (input) => ipcRenderer.invoke("named-secrets:save", input),
  updateNamedSecret: (input) => ipcRenderer.invoke("named-secrets:update", input),
  deleteNamedSecret: (input) => ipcRenderer.invoke("named-secrets:delete", input),
  brokerNamedSecretToLocalFixture: (input) => ipcRenderer.invoke("named-secrets:broker-local-fixture", input),
  exportNamedSecretMetadata: () => ipcRenderer.invoke("named-secrets:export-metadata"),
  getUpdateState: () => ipcRenderer.invoke("updates:get-state"),
  checkForUpdates: (reason) => ipcRenderer.invoke("updates:check", reason),
  downloadUpdate: () => ipcRenderer.invoke("updates:download"),
  installUpdateAndRestart: () => ipcRenderer.invoke("updates:install"),
  dismissUpdateNotification: () => ipcRenderer.invoke("updates:dismiss"),
  listWorkspaceFiles: () => ipcRenderer.invoke("workspace:list-files"),
  readWorkspaceFile: (path: string) => ipcRenderer.invoke("workspace:read-file", path),
  refreshOfficePreview: (path: string) => ipcRenderer.invoke("workspace:refresh-office-preview", path),
  previewLocalFile: (path: string) => ipcRenderer.invoke("local-file:preview", path),
  refreshLocalOfficePreview: (path: string) => ipcRenderer.invoke("local-file:refresh-office-preview", path),
  addLocalFolderAllowlistForThread: () => ipcRenderer.invoke("local-file:add-folder-allowlist"),
  pickWorkspaceContext: (input: PickWorkspaceContextInput) => ipcRenderer.invoke("workspace:pick-context", input),
  revealWorkspacePath: (path: string) => ipcRenderer.invoke("workspace:reveal-path", path),
  openWorkspacePath: (path: string) => ipcRenderer.invoke("workspace:open-path", path),
  listWorkspaceOpenTargets: () => ipcRenderer.invoke("workspace:list-open-targets"),
  openWorkspacePathWith: (input) => ipcRenderer.invoke("workspace:open-path-with", input),
  revealLocalPath: (path: string) => ipcRenderer.invoke("local-file:reveal-path", path),
  openLocalPath: (path: string) => ipcRenderer.invoke("local-file:open-path", path),
  openLocalPathWith: (input) => ipcRenderer.invoke("local-file:open-path-with", input),
  getWorkspaceDiff: () => ipcRenderer.invoke("workspace:diff"),
  getWorkspaceGitStatus: () => ipcRenderer.invoke("workspace:git-status"),
  switchWorkspaceBranch: (branch: string) => ipcRenderer.invoke("workspace:switch-branch", branch),
  getGitReview: () => ipcRenderer.invoke("git:review"),
  gitStageFile: (input) => ipcRenderer.invoke("git:stage-file", input),
  gitUnstageFile: (input) => ipcRenderer.invoke("git:unstage-file", input),
  gitStageAllFiles: () => ipcRenderer.invoke("git:stage-all-files"),
  gitUnstageAllFiles: () => ipcRenderer.invoke("git:unstage-all-files"),
  gitDiscardFile: (input) => ipcRenderer.invoke("git:discard-file", input),
  gitCommit: (input) => ipcRenderer.invoke("git:commit", input),
  gitCreateBranch: (input) => ipcRenderer.invoke("git:create-branch", input),
  gitRunAction: (action) => ipcRenderer.invoke("git:run-action", action),
  gitInitializeRepository: () => ipcRenderer.invoke("git:initialize"),
  gitCreateThreadWorktree: () => ipcRenderer.invoke("git:create-thread-worktree"),
  gitAttachExistingWorktree: () => ipcRenderer.invoke("git:attach-existing-worktree"),
  createPullRequestUrl: () => ipcRenderer.invoke("git:create-pr-url"),
  searchWorkspace: (input) => ipcRenderer.invoke("workspace:search", input),
  discoverCodexPlugins: () => ipcRenderer.invoke("plugins:discover"),
  readCodexPlugin: (input: ReadCodexPluginInput) => ipcRenderer.invoke("plugins:read", input),
  addCodexMarketplace: (input: AddCodexMarketplaceInput) => ipcRenderer.invoke("plugins:add-codex-marketplace", input),
  removeCodexMarketplace: (input: RemoveCodexMarketplaceInput) => ipcRenderer.invoke("plugins:remove-codex-marketplace", input),
  setCodexPluginEnabled: (input: SetCodexPluginEnabledInput) => ipcRenderer.invoke("plugins:set-enabled", input),
  setCodexPluginTrusted: (input: SetCodexPluginTrustedInput) => ipcRenderer.invoke("plugins:set-trusted", input),
  importCodexPlugin: (input: ImportCodexPluginInput) => ipcRenderer.invoke("plugins:import-codex-cache", input),
  uninstallCodexPlugin: (input: UninstallCodexPluginInput) => ipcRenderer.invoke("plugins:uninstall-codex", input),
  installCodexPluginDependencies: (input: InstallCodexPluginDependenciesInput) => ipcRenderer.invoke("plugins:install-dependencies", input),
  inspectCodexHostedMarketplace: () => ipcRenderer.invoke("plugins:hosted-marketplace"),
  inspectCodexPluginMcp: () => ipcRenderer.invoke("plugins:inspect-mcp"),
  listPluginMcpRuntimeSnapshots: () => ipcRenderer.invoke("plugins:mcp-runtimes"),
  restartPluginMcpRuntime: (input: PluginMcpRuntimeActionInput) => ipcRenderer.invoke("plugins:mcp-runtime-restart", input),
  stopPluginMcpRuntime: (input: PluginMcpRuntimeActionInput) => ipcRenderer.invoke("plugins:mcp-runtime-stop", input),
  listAmbientPluginRegistry: () => ipcRenderer.invoke("plugins:registry"),
  searchMcpRegistryServers: (input?: AmbientMcpServerSearchInput) => ipcRenderer.invoke("mcp:registry-search", input),
  describeMcpRegistryServer: (input: AmbientMcpServerDescribeInput) => ipcRenderer.invoke("mcp:registry-describe", input),
  listMcpInstalledServers: () => ipcRenderer.invoke("mcp:installed-list"),
  getMcpContainerRuntimeStatus: () => ipcRenderer.invoke("mcp:container-runtime-status"),
  launchMcpContainerRuntimeInstaller: (input?: AmbientMcpContainerRuntimeInstallLaunchInput) => ipcRenderer.invoke("mcp:container-runtime-launch-install", input),
  deferMcpContainerRuntimeSetup: () => ipcRenderer.invoke("mcp:container-runtime-defer"),
  previewMcpContainerRuntimeLifecycle: (input: AmbientMcpContainerRuntimeLifecyclePreviewInput) => ipcRenderer.invoke("mcp:container-runtime-lifecycle-preview", input),
  runMcpContainerRuntimeLifecycle: (input: AmbientMcpContainerRuntimeLifecycleRunInput) => ipcRenderer.invoke("mcp:container-runtime-lifecycle-run", input),
  installMcpDefaultCapability: (input: AmbientMcpDefaultCapabilityInstallInput) => ipcRenderer.invoke("mcp:default-capability-install", input),
  installMcpRegistryServer: (input: AmbientMcpServerInstallInput) => ipcRenderer.invoke("mcp:registry-install", input),
  uninstallMcpServer: (input: AmbientMcpServerUninstallInput) => ipcRenderer.invoke("mcp:server-uninstall", input),
  acceptMcpToolDescriptorReview: (input: AmbientMcpToolReviewAcceptInput) => ipcRenderer.invoke("mcp:tool-review-accept", input),
  listManagedDevServers: () => ipcRenderer.invoke("tools:managed-dev-servers"),
  stopManagedDevServer: (input) => ipcRenderer.invoke("tools:managed-dev-server-stop", input),
  getCapabilityBuilderHistory: (input?: CapabilityBuilderHistoryInput) => ipcRenderer.invoke("capability-builder:history", input),
  listAmbientPluginRuntimeCapabilities: (input: ListAmbientPluginRuntimeCapabilitiesInput) =>
    ipcRenderer.invoke("plugins:runtime-capabilities", input),
  getAmbientPluginCapabilityDiagnostics: (input: GetAmbientPluginCapabilityDiagnosticsInput) =>
    ipcRenderer.invoke("plugins:capability-diagnostics", input),
  getFirstPartyGoogleIntegration: () => ipcRenderer.invoke("integrations:google"),
  installGoogleWorkspaceCli: () => ipcRenderer.invoke("integrations:google-install-cli"),
  startGoogleWorkspaceSetup: (input: GoogleWorkspaceSetupInput) => ipcRenderer.invoke("integrations:google-setup-start", input),
  cancelGoogleWorkspaceSetup: () => ipcRenderer.invoke("integrations:google-setup-cancel"),
  importGoogleWorkspaceOAuthClient: (input?: GoogleWorkspaceOAuthClientImportInput) => ipcRenderer.invoke("integrations:google-import-oauth-client", input),
  validateGoogleWorkspace: (input?: GoogleWorkspaceValidationInput) => ipcRenderer.invoke("integrations:google-validate", input),
  disconnectGoogleWorkspace: (input: GoogleWorkspaceValidationInput) => ipcRenderer.invoke("integrations:google-disconnect", input),
  startPluginAppAuth: (input: StartPluginAppAuthInput) => ipcRenderer.invoke("plugins:auth-start", input),
  completePluginAppAuth: (input: CompletePluginAppAuthInput) => ipcRenderer.invoke("plugins:auth-complete", input),
  revokePluginAuthAccount: (input: PluginAuthAccountActionInput) => ipcRenderer.invoke("plugins:auth-revoke", input),
  disconnectPluginAuthAccount: (input: PluginAuthAccountActionInput) => ipcRenderer.invoke("plugins:auth-disconnect", input),
  testPluginAuthAccount: (input: PluginAuthAccountActionInput) => ipcRenderer.invoke("plugins:auth-test", input),
  inspectPiPackages: () => ipcRenderer.invoke("pi-packages:inspect"),
  previewPiPackageInstall: (input: PreviewPiPackageInstallInput) => ipcRenderer.invoke("pi-packages:preview-install", input),
  installPiPackage: (input: InstallPiPackageInput) => ipcRenderer.invoke("pi-packages:install", input),
  uninstallPiPackage: (input: UninstallPiPackageInput) => ipcRenderer.invoke("pi-packages:uninstall", input),
  setPiPackageEnabled: (input: SetPiPackageEnabledInput) => ipcRenderer.invoke("pi-packages:set-enabled", input),
  inspectPiExtensionSandboxPackages: () => ipcRenderer.invoke("pi-extension-sandbox:inspect"),
  previewPiExtensionSandboxPackage: (input: PreviewPiExtensionSandboxPackageInput) => ipcRenderer.invoke("pi-extension-sandbox:preview", input),
  installPiExtensionSandboxPackage: (input: InstallPiExtensionSandboxPackageInput) => ipcRenderer.invoke("pi-extension-sandbox:install", input),
  uninstallPiExtensionSandboxPackage: (input: UninstallPiExtensionSandboxPackageInput) => ipcRenderer.invoke("pi-extension-sandbox:uninstall", input),
  clearPiExtensionSandboxHistory: () => ipcRenderer.invoke("pi-extension-sandbox:clear-history"),
  inspectPiPrivilegedPackages: () => ipcRenderer.invoke("pi-privileged:inspect"),
  scanPiPrivilegedPackage: (input: ScanPiPrivilegedPackageInput) => ipcRenderer.invoke("pi-privileged:scan", input),
  installPiPrivilegedPackage: (input: InstallPiPrivilegedPackageInput) => ipcRenderer.invoke("pi-privileged:install", input),
  disablePiPrivilegedPackage: (input: PiPrivilegedPackageActionInput) => ipcRenderer.invoke("pi-privileged:disable", input),
  uninstallPiPrivilegedPackage: (input: UninstallPiPrivilegedPackageInput) => ipcRenderer.invoke("pi-privileged:uninstall", input),
  clearPiPrivilegedPackageHistory: () => ipcRenderer.invoke("pi-privileged:clear-history"),
  listBrowserCredentials: () => ipcRenderer.invoke("browser-credentials:list"),
  saveBrowserCredential: (input: SaveBrowserCredentialInput) => ipcRenderer.invoke("browser-credentials:save", input),
  deleteBrowserCredential: (input: DeleteBrowserCredentialInput) => ipcRenderer.invoke("browser-credentials:delete", input),
  getBrowserState: () => ipcRenderer.invoke("browser:get-state"),
  startBrowser: (input?: BrowserStartInput) => ipcRenderer.invoke("browser:start", input),
  stopBrowser: () => ipcRenderer.invoke("browser:stop"),
  revealBrowser: (input?: BrowserRevealInput) => ipcRenderer.invoke("browser:reveal", input),
  clearIsolatedBrowserProfile: () => ipcRenderer.invoke("browser:clear-isolated-profile"),
  copyChromeProfile: () => ipcRenderer.invoke("browser:copy-chrome-profile"),
  clearCopiedChromeProfile: () => ipcRenderer.invoke("browser:clear-copied-profile"),
  navigateBrowser: (input: BrowserNavigateInput) => ipcRenderer.invoke("browser:navigate", input),
  previewLocalPathInBrowser: (input: BrowserLocalPreviewInput) => ipcRenderer.invoke("browser:local-preview", input),
  searchBrowser: (input: BrowserSearchInput) => ipcRenderer.invoke("browser:search", input),
  readBrowserContent: (input: BrowserContentInput) => ipcRenderer.invoke("browser:content", input),
  keypressBrowser: (input: BrowserKeypressInput) => ipcRenderer.invoke("browser:keypress", input),
  screenshotBrowser: (input?: BrowserStartInput) => ipcRenderer.invoke("browser:screenshot", input),
  pickBrowser: (input: BrowserPickInput) => ipcRenderer.invoke("browser:pick", input),
  cancelBrowserPick: () => ipcRenderer.invoke("browser:cancel-pick"),
  resumeBrowserUserAction: () => ipcRenderer.invoke("browser:user-action-resume"),
  cancelBrowserUserAction: () => ipcRenderer.invoke("browser:user-action-cancel"),
  setBrowserViewBounds: (input: BrowserViewBoundsInput) => ipcRenderer.invoke("browser:set-view-bounds", input),
  listAutomationFolders: () => ipcRenderer.invoke("automations:list-folders"),
  createAutomationFolder: (input: CreateAutomationFolderInput) => ipcRenderer.invoke("automations:create-folder", input),
  moveAutomationThread: (input: MoveAutomationThreadInput) => ipcRenderer.invoke("automations:move-thread", input),
  listWorkflowAgentFolders: () => ipcRenderer.invoke("workflow-agents:list-folders"),
  createWorkflowAgentFolder: (input: CreateWorkflowAgentFolderInput) => ipcRenderer.invoke("workflow-agents:create-folder", input),
  moveWorkflowAgentThread: (input: MoveWorkflowAgentThreadInput) => ipcRenderer.invoke("workflow-agents:move-thread", input),
  createWorkflowAgentThread: (input: CreateWorkflowAgentThreadInput) => ipcRenderer.invoke("workflow-agents:create-thread", input),
  ensureWorkflowAgentChatThread: (input: { workflowThreadId: string }) => ipcRenderer.invoke("workflow-agents:ensure-chat-thread", input),
  listWorkflowAgentChatMessages: (input: ListWorkflowAgentChatMessagesInput) => ipcRenderer.invoke("workflow-agents:list-chat-messages", input),
  startWorkflowDiscovery: (input: StartWorkflowDiscoveryInput) => ipcRenderer.invoke("workflow-agents:start-discovery", input),
  startWorkflowRevisionDiscovery: (input: StartWorkflowRevisionDiscoveryInput) => ipcRenderer.invoke("workflow-agents:start-revision-discovery", input),
  answerWorkflowDiscoveryQuestion: (input: AnswerWorkflowDiscoveryQuestionInput) => ipcRenderer.invoke("workflow-agents:answer-discovery-question", input),
  resolveWorkflowDiscoveryAccessRequest: (input: ResolveWorkflowDiscoveryAccessRequestInput) =>
    ipcRenderer.invoke("workflow-agents:resolve-discovery-access-request", input),
  searchWorkflowDiscoveryCapabilities: (input: SearchWorkflowDiscoveryCapabilitiesInput) => ipcRenderer.invoke("workflow-agents:search-capabilities", input),
  describeWorkflowDiscoveryCapability: (input: DescribeWorkflowDiscoveryCapabilityInput) => ipcRenderer.invoke("workflow-agents:describe-capability", input),
  listWorkflowGraphSnapshots: (input) => ipcRenderer.invoke("workflow-agents:list-graph-snapshots", input),
  listWorkflowExplorationTraces: (input) => ipcRenderer.invoke("workflow-agents:list-exploration-traces", input),
  runWorkflowThreadExploration: (input: RunWorkflowThreadExplorationInput) => ipcRenderer.invoke("workflow-agents:run-exploration", input),
  listWorkflowVersions: (input: ListWorkflowVersionsInput) => ipcRenderer.invoke("workflow-agents:list-versions", input),
  restoreWorkflowVersion: (input: RestoreWorkflowVersionInput) => ipcRenderer.invoke("workflow-agents:restore-version", input),
  listWorkflowRevisions: (input: ListWorkflowRevisionsInput) => ipcRenderer.invoke("workflow-agents:list-revisions", input),
  createWorkflowRevision: (input: CreateWorkflowRevisionInput) => ipcRenderer.invoke("workflow-agents:create-revision", input),
  updateWorkflowRevision: (input: UpdateWorkflowRevisionInput) => ipcRenderer.invoke("workflow-agents:update-revision", input),
  resolveWorkflowRevision: (input: ResolveWorkflowRevisionInput) => ipcRenderer.invoke("workflow-agents:resolve-revision", input),
  invokeWorkflowNativeTool: (input: InvokeWorkflowNativeToolInput) => ipcRenderer.invoke("workflow-agents:invoke-native-tool", input),
  listAutomationSchedules: () => ipcRenderer.invoke("automations:list-schedules"),
  createAutomationSchedule: (input: CreateAutomationScheduleInput) => ipcRenderer.invoke("automations:create-schedule", input),
  updateAutomationSchedule: (input: UpdateAutomationScheduleInput) => ipcRenderer.invoke("automations:update-schedule", input),
  listAutomationScheduleExceptions: (input) => ipcRenderer.invoke("automations:list-schedule-exceptions", input),
  skipAutomationScheduleOccurrence: (input: AutomationScheduleOccurrenceActionInput) => ipcRenderer.invoke("automations:skip-schedule-occurrence", input),
  rescheduleAutomationScheduleOccurrence: (input: AutomationScheduleOccurrenceActionInput) => ipcRenderer.invoke("automations:reschedule-schedule-occurrence", input),
  updateAutomationScheduleOccurrenceRunLimits: (input: AutomationScheduleOccurrenceActionInput) =>
    ipcRenderer.invoke("automations:update-schedule-occurrence-run-limits", input),
  listOrchestrationBoard: () => ipcRenderer.invoke("orchestration:list-board"),
  createOrchestrationTask: (input: CreateOrchestrationTaskInput) => ipcRenderer.invoke("orchestration:create-task", input),
  updateOrchestrationTask: (input: UpdateOrchestrationTaskInput) => ipcRenderer.invoke("orchestration:update-task", input),
  prepareNextOrchestrationTasks: () => ipcRenderer.invoke("orchestration:prepare-next"),
  resolveOrchestrationWorkflowImpact: (input: ResolveOrchestrationWorkflowImpactInput) => ipcRenderer.invoke("orchestration:resolve-workflow-impact", input),
  repairOrchestrationWorkflow: (input: RepairOrchestrationWorkflowInput) => ipcRenderer.invoke("orchestration:repair-workflow", input),
  updateOrchestrationWorkflowSettings: (input: UpdateOrchestrationWorkflowSettingsInput) =>
    ipcRenderer.invoke("orchestration:update-workflow-settings", input),
  updateOrchestrationWorkflowRaw: (input: UpdateOrchestrationWorkflowRawInput) => ipcRenderer.invoke("orchestration:update-workflow-raw", input),
  startOrchestrationRun: (input: StartOrchestrationRunInput) => ipcRenderer.invoke("orchestration:start-run", input),
  cancelOrchestrationRun: (input: CancelOrchestrationRunInput) => ipcRenderer.invoke("orchestration:cancel-run", input),
  revealOrchestrationWorkspace: (input: RevealOrchestrationWorkspaceInput) => ipcRenderer.invoke("orchestration:reveal-workspace", input),
  getOrchestrationAutoDispatchStatus: () => ipcRenderer.invoke("orchestration:auto-status"),
  setOrchestrationAutoDispatchEnabled: (input) => ipcRenderer.invoke("orchestration:set-auto-dispatch", input),
  listWorkflowDashboard: () => ipcRenderer.invoke("workflow:list-dashboard"),
  getWorkflowRunDetail: (input: WorkflowRunDetailInput) => ipcRenderer.invoke("workflow:run-detail", input),
  createWorkflowSampleArtifact: () => ipcRenderer.invoke("workflow:create-sample"),
  compileWorkflowPreview: (input: CompileWorkflowPreviewInput) => ipcRenderer.invoke("workflow:compile-preview", input),
  compileWorkflowDebugRewrite: (input: CompileWorkflowDebugRewriteInput) => ipcRenderer.invoke("workflow:debug-rewrite", input),
  reviewWorkflowArtifact: (input: ReviewWorkflowArtifactInput) => ipcRenderer.invoke("workflow:review-artifact", input),
  updateWorkflowConnectorGrant: (input: UpdateWorkflowConnectorGrantInput) => ipcRenderer.invoke("workflow:update-connector-grant", input),
  revalidateWorkflowArtifact: (input: RevalidateWorkflowArtifactInput) => ipcRenderer.invoke("workflow:revalidate-artifact", input),
  updateWorkflowArtifactSource: (input: UpdateWorkflowArtifactSourceInput) => ipcRenderer.invoke("workflow:update-artifact-source", input),
  runWorkflowArtifact: (input: RunWorkflowArtifactInput) => ipcRenderer.invoke("workflow:run-artifact", input),
  recoverWorkflowRun: (input: RecoverWorkflowRunInput) => ipcRenderer.invoke("workflow:recover-run", input),
  cancelWorkflowRun: (input: CancelWorkflowRunInput) => ipcRenderer.invoke("workflow:cancel-run", input),
  cancelCallableWorkflowTask: (input: CancelCallableWorkflowTaskInput) => ipcRenderer.invoke("callable-workflow:cancel-task", input),
  pauseCallableWorkflowTask: (input: PauseCallableWorkflowTaskInput) => ipcRenderer.invoke("callable-workflow:pause-task", input),
  resumeCallableWorkflowTask: (input: ResumeCallableWorkflowTaskInput) => ipcRenderer.invoke("callable-workflow:resume-task", input),
  resolveWorkflowApproval: (input: ResolveWorkflowApprovalInput) => ipcRenderer.invoke("workflow:resolve-approval", input),
  resolveSubagentApproval: (input: ResolveSubagentApprovalInput) => ipcRenderer.invoke("subagents:resolve-approval", input),
  resolveSubagentWaitBarrier: (input: ResolveSubagentWaitBarrierInput) => ipcRenderer.invoke("subagents:resolve-wait-barrier", input),
  cancelSubagentRun: (input: CancelSubagentRunInput) => ipcRenderer.invoke("subagents:cancel-run", input),
  closeSubagentRun: (input: CloseSubagentRunInput) => ipcRenderer.invoke("subagents:close-run", input),
  exportDiagnosticBundle: () => ipcRenderer.invoke("diagnostics:export"),
  importDiagnosticBundle: () => ipcRenderer.invoke("diagnostics:import"),
  exportChat: (input: ExportChatInput) => ipcRenderer.invoke("thread:export-chat", input),
  exportChatPdf: (input: ExportChatPdfInput) => ipcRenderer.invoke("thread:export-chat-pdf", input),
  listPermissionAudit: () => ipcRenderer.invoke("permission:audit"),
  listPermissionGrants: () => ipcRenderer.invoke("permission:grants"),
  listPendingPermissionRequests: () => ipcRenderer.invoke("permission:pending"),
  createPermissionGrant: (input: CreateAmbientPermissionGrantInput) => ipcRenderer.invoke("permission:create-grant", input),
  revokePermissionGrant: (input: RevokeAmbientPermissionGrantInput) => ipcRenderer.invoke("permission:revoke-grant", input),
  respondPermissionRequest: (id: string, response: PermissionPromptResponseMode) => ipcRenderer.invoke("permission:respond", id, response),
  respondPrivilegedCredentialRequest: (input: PrivilegedCredentialPromptResponseInput) => ipcRenderer.invoke("privileged-credential:respond", input),
  respondSecureInputRequest: (input: SecureInputPromptResponseInput) => ipcRenderer.invoke("secure-input:respond", input),
  saveAmbientCliSecret: (input: SaveAmbientCliSecretInput) => ipcRenderer.invoke("ambient-cli:save-secret", input),
  requestTerminalStart: (input: RequestTerminalStartInput) => ipcRenderer.invoke("terminal:request-start", input),
  startTerminal: (input: StartTerminalInput) => ipcRenderer.invoke("terminal:start", input),
  submitTerminalCommand: (input: SubmitTerminalCommandInput) => ipcRenderer.invoke("terminal:submit-command", input),
  sendTerminalControl: (input: TerminalControlInput) => ipcRenderer.invoke("terminal:control", input),
  resizeTerminal: (input: ResizeTerminalInput) => ipcRenderer.invoke("terminal:resize", input),
  stopTerminal: (input: StopTerminalInput) => ipcRenderer.invoke("terminal:stop", input),
  sendMessage: (input: SendMessageInput) => ipcRenderer.invoke("message:send", input),
  abortRun: (threadId) => ipcRenderer.invoke("run:abort", threadId),
  getThreadGoal: (input: ThreadGoalGetInput) => ipcRenderer.invoke("thread-goal:get", input),
  setThreadGoal: (input: ThreadGoalSetInput) => ipcRenderer.invoke("thread-goal:set", input),
  clearThreadGoal: (input: ThreadGoalClearInput) => ipcRenderer.invoke("thread-goal:clear", input),
  getContextUsage: (threadId: string) => ipcRenderer.invoke("context:usage", threadId),
  compactThread: (input: CompactThreadInput) => ipcRenderer.invoke("context:compact", input),
  recoverThreadContext: (input: RecoverThreadContextInput) => ipcRenderer.invoke("context:recover", input),
  onEvent: (listener) => {
    const wrapped = (_: Electron.IpcRendererEvent, event: DesktopEvent) => listener(event);
    ipcRenderer.on("desktop:event", wrapped);
    return () => ipcRenderer.removeListener("desktop:event", wrapped);
  },
  emitE2eEvent: (event: DesktopEvent) => ipcRenderer.invoke("e2e:emit-event", event),
  resolveE2ePermissionGrant: (input) => ipcRenderer.invoke("e2e:resolve-permission-grant", input),
};

contextBridge.exposeInMainWorld("ambientDesktop", api);
