import { projectBoardArtifactExportFromSummary as projectBoardArtifactExportFromSummaryFromProjectBoardArtifactExport } from "../project-board/projectBoardArtifactExport";
import { projectBoardArtifactProjectionFromFiles as projectBoardArtifactProjectionFromFilesFromProjectBoardArtifactImport } from "../project-board/projectBoardArtifactImport";
import type {
  ProjectBoardArtifactProjection as ProjectBoardArtifactProjectionFromProjectBoardArtifactImport,
  ProjectBoardRunArtifactProjection as ProjectBoardRunArtifactProjectionFromProjectBoardArtifactImport,
} from "../project-board/projectBoardArtifactImport";
import {
  PROJECT_BOARD_ARTIFACT_SCHEMA_VERSION as PROJECT_BOARD_ARTIFACT_SCHEMA_VERSIONFromProjectBoardArtifacts,
  stableBoardArtifactId as stableBoardArtifactIdFromProjectBoardArtifacts,
} from "../project-board/projectBoardArtifacts";
import type {
  BoardEventArtifact as BoardEventArtifactFromProjectBoardArtifacts,
  ProposalManifestArtifact as ProposalManifestArtifactFromProjectBoardArtifacts,
  RunHandoffArtifact as RunHandoffArtifactFromProjectBoardArtifacts,
  RunManifestArtifact as RunManifestArtifactFromProjectBoardArtifacts,
  RunProofArtifact as RunProofArtifactFromProjectBoardArtifacts,
} from "../project-board/projectBoardArtifacts";
import {
  defaultProjectBoardClaimAgentId as defaultProjectBoardClaimAgentIdFromProjectBoardClaims,
  projectBoardClaimProjectionFromProjectBoardEvents as projectBoardClaimProjectionFromProjectBoardEventsFromProjectBoardClaims,
} from "../project-board/projectBoardClaims";
import {
  projectBoardClarificationDefaultAnsweredDecisions as projectBoardClarificationDefaultAnsweredDecisionsFromProjectBoardClarificationDefaultProvider,
  projectBoardClarificationDefaultQuestionsShareDecisionTopic as projectBoardClarificationDefaultQuestionsShareDecisionTopicFromProjectBoardClarificationDefaultProvider,
} from "../project-board/projectBoardClarificationDefaultProvider";
import type { ProjectBoardClarificationDefaultSuggestion as ProjectBoardClarificationDefaultSuggestionFromProjectBoardClarificationDefaultProvider } from "../project-board/projectBoardClarificationDefaultProvider";
import { buildProjectBoardKickoffContextBrief as buildProjectBoardKickoffContextBriefFromProjectBoardKickoffDefaultProvider } from "../project-board/projectBoardKickoffDefaultProvider";
import type { ProjectBoardKickoffDefaultSuggestion as ProjectBoardKickoffDefaultSuggestionFromProjectBoardKickoffDefaultProvider } from "../project-board/projectBoardKickoffDefaultProvider";
import type { ProjectBoardProofSuggestion as ProjectBoardProofSuggestionFromProjectBoardProofSuggestionProvider } from "../project-board/projectBoardProofSuggestionProvider";
import { buildProjectBoardRenderedCardLedger as buildProjectBoardRenderedCardLedgerFromProjectBoardRenderedCardLedger } from "../project-board/projectBoardRenderedCardLedger";
import {
  DURABLE_PLAN_SOURCE_AUTHORITY_REASON as DURABLE_PLAN_SOURCE_AUTHORITY_REASONFromProjectBoardSourceIdentity,
  GENERATED_REPORT_SOURCE_AUTHORITY_REASON as GENERATED_REPORT_SOURCE_AUTHORITY_REASONFromProjectBoardSourceIdentity,
  GENERATED_WORKFLOW_SOURCE_AUTHORITY_REASON as GENERATED_WORKFLOW_SOURCE_AUTHORITY_REASONFromProjectBoardSourceIdentity,
  hashProjectBoardSourceContent as hashProjectBoardSourceContentFromProjectBoardSourceIdentity,
  projectBoardSourceAuthorityRole as projectBoardSourceAuthorityRoleFromProjectBoardSourceIdentity,
  projectBoardSourceChangeState as projectBoardSourceChangeStateFromProjectBoardSourceIdentity,
  projectBoardSourceClassificationDefaults as projectBoardSourceClassificationDefaultsFromProjectBoardSourceIdentity,
  projectBoardSourceContentHash as projectBoardSourceContentHashFromProjectBoardSourceIdentity,
  projectBoardSourceDeterministicAuthorityLocked as projectBoardSourceDeterministicAuthorityLockedFromProjectBoardSourceIdentity,
  projectBoardSourceIncludedInSynthesis as projectBoardSourceIncludedInSynthesisFromProjectBoardSourceIdentity,
  projectBoardSourceKey as projectBoardSourceKeyFromProjectBoardSourceIdentity,
} from "../project-board/projectBoardSourceIdentity";
import { normalizeProjectBoardPmReviewReport as normalizeProjectBoardPmReviewReportFromProjectBoardSynthesis } from "../project-board/projectBoardSynthesis";
import type {
  ProjectBoardSynthesisCardInput as ProjectBoardSynthesisCardInputFromProjectBoardSynthesis,
  ProjectBoardSynthesisDraft as ProjectBoardSynthesisDraftFromProjectBoardSynthesis,
} from "../project-board/projectBoardSynthesis";
import {
  projectBoardTaskToolActionDiagnostics as projectBoardTaskToolActionDiagnosticsFromProjectBoardTaskTools,
  projectBoardTaskToolActionIntegrityIssues as projectBoardTaskToolActionIntegrityIssuesFromProjectBoardTaskTools,
  projectBoardTaskToolActionSummary as projectBoardTaskToolActionSummaryFromProjectBoardTaskTools,
  projectBoardTaskToolActionTitle as projectBoardTaskToolActionTitleFromProjectBoardTaskTools,
  projectBoardTaskToolActionsForScope as projectBoardTaskToolActionsForScopeFromProjectBoardTaskTools,
  projectBoardTaskToolActionsFromProofOfWork as projectBoardTaskToolActionsFromProofOfWorkFromProjectBoardTaskTools,
  projectBoardTaskToolBrowserTraces as projectBoardTaskToolBrowserTracesFromProjectBoardTaskTools,
  projectBoardTaskToolChangedFiles as projectBoardTaskToolChangedFilesFromProjectBoardTaskTools,
  projectBoardTaskToolCommands as projectBoardTaskToolCommandsFromProjectBoardTaskTools,
  projectBoardTaskToolCompleted as projectBoardTaskToolCompletedFromProjectBoardTaskTools,
  projectBoardTaskToolManualChecks as projectBoardTaskToolManualChecksFromProjectBoardTaskTools,
  projectBoardTaskToolProofSummary as projectBoardTaskToolProofSummaryFromProjectBoardTaskTools,
  projectBoardTaskToolRemaining as projectBoardTaskToolRemainingFromProjectBoardTaskTools,
  projectBoardTaskToolScreenshots as projectBoardTaskToolScreenshotsFromProjectBoardTaskTools,
  projectBoardTaskToolVisualChecks as projectBoardTaskToolVisualChecksFromProjectBoardTaskTools,
} from "../project-board/projectBoardTaskTools";
import type {
  ProjectBoardTaskToolAction as ProjectBoardTaskToolActionFromProjectBoardTaskTools,
  ProjectBoardTaskToolActionTransport as ProjectBoardTaskToolActionTransportFromProjectBoardTaskTools,
} from "../project-board/projectBoardTaskTools";
import {
  previewProjectBoardWorkflowRepair as previewProjectBoardWorkflowRepairFromProjectBoardWorkflowBootstrap,
  repairProjectBoardWorkflow as repairProjectBoardWorkflowFromProjectBoardWorkflowBootstrap,
  updateProjectBoardWorkflowRaw as updateProjectBoardWorkflowRawFromProjectBoardWorkflowBootstrap,
  updateProjectBoardWorkflowSettings as updateProjectBoardWorkflowSettingsFromProjectBoardWorkflowBootstrap,
} from "../project-board/projectBoardWorkflowBootstrap";

export const buildProjectBoardKickoffContextBrief = buildProjectBoardKickoffContextBriefFromProjectBoardKickoffDefaultProvider;
export const buildProjectBoardRenderedCardLedger = buildProjectBoardRenderedCardLedgerFromProjectBoardRenderedCardLedger;
export const defaultProjectBoardClaimAgentId = defaultProjectBoardClaimAgentIdFromProjectBoardClaims;
export const DURABLE_PLAN_SOURCE_AUTHORITY_REASON = DURABLE_PLAN_SOURCE_AUTHORITY_REASONFromProjectBoardSourceIdentity;
export const GENERATED_REPORT_SOURCE_AUTHORITY_REASON = GENERATED_REPORT_SOURCE_AUTHORITY_REASONFromProjectBoardSourceIdentity;
export const GENERATED_WORKFLOW_SOURCE_AUTHORITY_REASON = GENERATED_WORKFLOW_SOURCE_AUTHORITY_REASONFromProjectBoardSourceIdentity;
export const hashProjectBoardSourceContent = hashProjectBoardSourceContentFromProjectBoardSourceIdentity;
export const normalizeProjectBoardPmReviewReport = normalizeProjectBoardPmReviewReportFromProjectBoardSynthesis;
export const previewProjectBoardWorkflowRepair = previewProjectBoardWorkflowRepairFromProjectBoardWorkflowBootstrap;
export const PROJECT_BOARD_ARTIFACT_SCHEMA_VERSION = PROJECT_BOARD_ARTIFACT_SCHEMA_VERSIONFromProjectBoardArtifacts;
export const projectBoardArtifactExportFromSummary = projectBoardArtifactExportFromSummaryFromProjectBoardArtifactExport;
export const projectBoardArtifactProjectionFromFiles = projectBoardArtifactProjectionFromFilesFromProjectBoardArtifactImport;
export const projectBoardClaimProjectionFromProjectBoardEvents = projectBoardClaimProjectionFromProjectBoardEventsFromProjectBoardClaims;
export const projectBoardClarificationDefaultAnsweredDecisions =
  projectBoardClarificationDefaultAnsweredDecisionsFromProjectBoardClarificationDefaultProvider;
export const projectBoardClarificationDefaultQuestionsShareDecisionTopic =
  projectBoardClarificationDefaultQuestionsShareDecisionTopicFromProjectBoardClarificationDefaultProvider;
export const projectBoardSourceAuthorityRole = projectBoardSourceAuthorityRoleFromProjectBoardSourceIdentity;
export const projectBoardSourceChangeState = projectBoardSourceChangeStateFromProjectBoardSourceIdentity;
export const projectBoardSourceClassificationDefaults = projectBoardSourceClassificationDefaultsFromProjectBoardSourceIdentity;
export const projectBoardSourceContentHash = projectBoardSourceContentHashFromProjectBoardSourceIdentity;
export const projectBoardSourceDeterministicAuthorityLocked = projectBoardSourceDeterministicAuthorityLockedFromProjectBoardSourceIdentity;
export const projectBoardSourceIncludedInSynthesis = projectBoardSourceIncludedInSynthesisFromProjectBoardSourceIdentity;
export const projectBoardSourceKey = projectBoardSourceKeyFromProjectBoardSourceIdentity;
export const projectBoardTaskToolActionDiagnostics = projectBoardTaskToolActionDiagnosticsFromProjectBoardTaskTools;
export const projectBoardTaskToolActionIntegrityIssues = projectBoardTaskToolActionIntegrityIssuesFromProjectBoardTaskTools;
export const projectBoardTaskToolActionsForScope = projectBoardTaskToolActionsForScopeFromProjectBoardTaskTools;
export const projectBoardTaskToolActionsFromProofOfWork = projectBoardTaskToolActionsFromProofOfWorkFromProjectBoardTaskTools;
export const projectBoardTaskToolActionSummary = projectBoardTaskToolActionSummaryFromProjectBoardTaskTools;
export const projectBoardTaskToolActionTitle = projectBoardTaskToolActionTitleFromProjectBoardTaskTools;
export const projectBoardTaskToolBrowserTraces = projectBoardTaskToolBrowserTracesFromProjectBoardTaskTools;
export const projectBoardTaskToolChangedFiles = projectBoardTaskToolChangedFilesFromProjectBoardTaskTools;
export const projectBoardTaskToolCommands = projectBoardTaskToolCommandsFromProjectBoardTaskTools;
export const projectBoardTaskToolCompleted = projectBoardTaskToolCompletedFromProjectBoardTaskTools;
export const projectBoardTaskToolManualChecks = projectBoardTaskToolManualChecksFromProjectBoardTaskTools;
export const projectBoardTaskToolProofSummary = projectBoardTaskToolProofSummaryFromProjectBoardTaskTools;
export const projectBoardTaskToolRemaining = projectBoardTaskToolRemainingFromProjectBoardTaskTools;
export const projectBoardTaskToolScreenshots = projectBoardTaskToolScreenshotsFromProjectBoardTaskTools;
export const projectBoardTaskToolVisualChecks = projectBoardTaskToolVisualChecksFromProjectBoardTaskTools;
export const repairProjectBoardWorkflow = repairProjectBoardWorkflowFromProjectBoardWorkflowBootstrap;
export const stableBoardArtifactId = stableBoardArtifactIdFromProjectBoardArtifacts;
export const updateProjectBoardWorkflowRaw = updateProjectBoardWorkflowRawFromProjectBoardWorkflowBootstrap;
export const updateProjectBoardWorkflowSettings = updateProjectBoardWorkflowSettingsFromProjectBoardWorkflowBootstrap;

export type BoardEventArtifact = BoardEventArtifactFromProjectBoardArtifacts;
export type ProjectBoardArtifactProjection = ProjectBoardArtifactProjectionFromProjectBoardArtifactImport;
export type ProjectBoardClarificationDefaultSuggestion =
  ProjectBoardClarificationDefaultSuggestionFromProjectBoardClarificationDefaultProvider;
export type ProjectBoardKickoffDefaultSuggestion = ProjectBoardKickoffDefaultSuggestionFromProjectBoardKickoffDefaultProvider;
export type ProjectBoardProofSuggestion = ProjectBoardProofSuggestionFromProjectBoardProofSuggestionProvider;
export type ProjectBoardRunArtifactProjection = ProjectBoardRunArtifactProjectionFromProjectBoardArtifactImport;
export type ProjectBoardSynthesisCardInput = ProjectBoardSynthesisCardInputFromProjectBoardSynthesis;
export type ProjectBoardSynthesisDraft = ProjectBoardSynthesisDraftFromProjectBoardSynthesis;
export type ProjectBoardTaskToolAction = ProjectBoardTaskToolActionFromProjectBoardTaskTools;
export type ProjectBoardTaskToolActionTransport = ProjectBoardTaskToolActionTransportFromProjectBoardTaskTools;
export type ProposalManifestArtifact = ProposalManifestArtifactFromProjectBoardArtifacts;
export type RunHandoffArtifact = RunHandoffArtifactFromProjectBoardArtifacts;
export type RunManifestArtifact = RunManifestArtifactFromProjectBoardArtifacts;
export type RunProofArtifact = RunProofArtifactFromProjectBoardArtifacts;
