import { describe, expect, it } from "vitest";
import type {
  DiagnosticExportLocalRuntimeEvidence,
  DiagnosticExportSubagentReplayEvidence,
  DiagnosticExportSummary,
} from "../shared/types";
import {
  AMBIENT_SLASH_COMMANDS_FEATURE_FLAG,
  AMBIENT_SUBAGENTS_FEATURE_FLAG,
  AMBIENT_TENCENTDB_MEMORY_FEATURE_FLAG,
} from "../shared/featureFlags";
import {
  diagnosticImportResultFromBundleJson,
  diagnosticImportResultFromBundleText,
} from "./diagnosticBundleImport";

describe("diagnostic bundle import", () => {
  it("imports a diagnostic bundle into bounded summary and replay evidence only", () => {
    const result = diagnosticImportResultFromBundleJson({
      path: "/tmp/ambient-diagnostics.json",
      bytes: 4096,
      bundle: {
        schemaVersion: 1,
        createdAt: "2026-06-05T00:00:00.000Z",
        summary: diagnosticSummary(),
        environment: {
          ambientApiKey: "sk-secret-shaped-value",
        },
        logs: [{ message: "do not return log contents" }],
        subagents: {
          replayEvidence: {
            ...replayEvidence(),
            unexpectedSecret: "secret-shaped-child-metadata",
            runtimeEventTimeline: [{
              sequence: 1,
              createdAt: "2026-06-05T00:00:01.000Z",
              runId: "run-1",
              parentRunId: "parent-run",
              childThreadId: "child-thread",
              canonicalTaskPath: "root/0:summarizer",
              type: "subagent.runtime_event",
              status: "completed",
              messagePreview: "a".repeat(700),
              approvalId: "approval-worker",
              approvalSource: "permission_grant",
              worktreeIsolated: true,
              worktreePath: "/repo/.ambient-codex/worktrees/child-thread",
              unexpectedField: "not returned",
            }],
            parentMailboxTimeline: [{
              sequence: 1,
              id: "mailbox-1",
              createdAt: "2026-06-05T00:00:03.000Z",
              updatedAt: "2026-06-05T00:00:04.000Z",
              parentThreadId: "parent-thread",
              parentRunId: "parent-run",
              parentMessageId: "parent-message",
              type: "subagent.grouped_completion",
              deliveryState: "queued",
              childRunIds: ["run-1"],
              childThreadIds: ["child-thread"],
              canonicalTaskPaths: ["root/0:summarizer"],
              childSourceLabels: ["root/0:summarizer / run run-1 / thread child-thread"],
              idempotencyKey: "subagent:grouped_completion_notification:abc123",
              payloadPreview: "Grouped child completion notification.",
              payload: "do not return raw payload",
            }, {
              sequence: 2,
              id: "mailbox-tool-scope",
              createdAt: "2026-06-05T00:00:05.000Z",
              updatedAt: "2026-06-05T00:00:06.000Z",
              parentThreadId: "parent-thread",
              parentRunId: "parent-run",
              parentMessageId: "parent-message",
              type: "subagent.spawn_failed",
              deliveryState: "queued",
              childRunIds: ["run-1"],
              childThreadIds: ["child-thread"],
              canonicalTaskPaths: ["root/0:summarizer"],
              childSourceLabels: ["root/0:summarizer / run run-1 / thread child-thread"],
              idempotencyKey: "spawn:noninteractive-approval-unavailable",
              payloadPreview: "Requested sub-agent tool scope was denied.",
              failureStage: "tool_scope",
              approvalMode: "non_interactive",
              approvalUnavailable: true,
              deniedCategoryIds: ["connector.read"],
              deniedToolIds: ["connector_app:gmail.search"],
              deniedCategoryLabels: ["Connector Read (connector.read)"],
              deniedToolLabels: ["Connector App gmail.search / Connector Read (connector.read)"],
              payload: "do not return raw payload",
            }, {
              sequence: 3,
              id: "mailbox-guard",
              createdAt: "2026-06-05T00:00:07.000Z",
              updatedAt: "2026-06-05T00:00:08.000Z",
              parentThreadId: "parent-thread",
              parentRunId: "parent-run",
              parentMessageId: "parent-message",
              type: "subagent.wait_barrier_attention",
              deliveryState: "queued",
              childRunIds: ["run-1"],
              idempotencyKey: "wait-barrier-attention:guard",
              payloadPreview: "Child result is not synthesis-safe.",
              completionGuardSummary: {
                valid: false,
                synthesisAllowed: false,
                required: true,
                structuredEvidenceCount: 1,
                ambientEvidenceCount: 1,
                isolatedWorktreeEvidenceCount: 1,
                approvalEvidenceCount: 0,
                reason: "Missing approval provenance.",
                unexpectedField: "not returned",
              },
              payload: "do not return raw payload",
            }, {
              sequence: 4,
              id: "mailbox-lifecycle",
              createdAt: "2026-06-05T00:00:09.000Z",
              updatedAt: "2026-06-05T00:00:10.000Z",
              parentThreadId: "parent-thread",
              parentRunId: "parent-run",
              parentMessageId: "parent-message",
              type: "subagent.wait_barrier_decision",
              deliveryState: "delivered",
              childRunIds: ["run-1", "run-2"],
              childThreadIds: ["child-thread"],
              canonicalTaskPaths: ["root/0:summarizer"],
              childSourceLabels: ["root/0:summarizer / run run-1 / thread child-thread"],
              idempotencyKey: "barrier:cancel-parent",
              payloadPreview: "Parent cancelled required child work.",
              lifecycleSummary: {
                action: "cancel_parent",
                waitBarrierId: "barrier-1",
                barrierStatus: "cancelled",
                reason: "User stopped the parent.",
                userDecisionPreview: "Stop the parent task.",
                cancelledRunIds: ["run-1"],
                detachedRunIds: ["run-2"],
                unchangedRunIds: ["run-3"],
                cancelledWaitBarrierIds: ["barrier-1"],
                cancelledMailboxEventIds: ["mailbox-followup"],
                parentCancellationRequested: true,
                unexpectedField: "not returned",
              },
              payload: "do not return raw payload",
            }],
            callableWorkflowTaskTimeline: [{
              sequence: 1,
              taskId: "workflow-task-1",
              launchId: "workflow-launch-1",
              createdAt: "2026-06-05T00:00:04.000Z",
              updatedAt: "2026-06-05T00:00:05.000Z",
              parentThreadId: "parent-thread",
              parentRunId: "parent-run",
              parentMessageId: "parent-message",
              toolName: "ambient_workflow_map_reduce",
              sourceKind: "symphony_recipe",
              title: "Symphony Map-Reduce",
              status: "succeeded",
              statusLabel: "Succeeded",
              blocking: true,
              runnerDeferredReason: "workflow_run_succeeded",
              workflowThreadId: "workflow-thread-1",
              workflowArtifactId: "workflow-artifact-1",
              workflowArtifactTitle: "Replay Child Mutation",
              workflowArtifactStatus: "ready_for_preview",
              workflowRunId: "workflow-run-1",
              workflowRunStatus: "succeeded",
              workflowRunEventTypes: ["callable_workflow.task_started", "callable_workflow.task_finished"],
              artifactLinkState: "linked",
              runLinkState: "linked",
              callerKind: "subagent_child_thread",
              childThreadId: "child-thread",
              childRunId: "run-1",
              subagentRunId: "run-1",
              canonicalTaskPath: "root/0:summarizer",
              approvalSource: "child_bridge_policy",
              approvalScope: "this_child_thread",
              worktreeIsolated: true,
              worktreeStatus: "active",
              nestedFanoutSource: "child_bridge_policy",
              lastEventType: "callable_workflow.task_finished",
              lastEventMessage: "Callable workflow task finished.",
              rawExecutionPlan: "do not return raw workflow plan",
            }],
            restartRepair: {
              ...replayEvidence().restartRepair,
              callableWorkflowTaskIssues: [{
                sequence: 1,
                issueId: "callable-issue-1",
                kind: "active_task_interrupted",
                severity: "warning",
                messagePreview: "Callable workflow task workflow-task-1 was compiling during restart.",
                taskId: "workflow-task-1",
                taskStatus: "compiling",
                taskStatusLabel: "Compiling",
                blocking: true,
                runnerDeferredReason: "workflow_artifact_not_compiled",
                parentThreadId: "parent-thread",
                parentRunId: "parent-run",
                callerKind: "subagent_child_thread",
                callerThreadId: "child-thread",
                callerRunId: "run-1",
                childThreadId: "child-thread",
                childRunId: "run-1",
                subagentRunId: "run-1",
                canonicalTaskPath: "root/0:summarizer",
                childParentThreadId: "parent-thread",
                childParentRunId: "parent-run",
                approvalSource: "child_bridge_policy",
                approvalScope: "this_child_thread",
                worktreeRequired: true,
                worktreeIsolated: true,
                worktreeStatus: "active",
                nestedFanoutRequired: true,
                nestedFanoutSource: "child_bridge_policy",
                rawIssue: "do not return raw restart issue",
              }],
            },
          },
        },
      },
    });

    expect(result).toMatchObject({
      path: "/tmp/ambient-diagnostics.json",
      bytes: 4096,
      createdAt: "2026-06-05T00:00:00.000Z",
      summary: {
        featureFlags: {
          flags: {
            [AMBIENT_SUBAGENTS_FEATURE_FLAG]: {
              enabled: false,
              source: "startup_arg_disable",
              settingsEnabled: true,
            },
          },
        },
        subagents: {
          replayEvidence: {
            status: "healthy",
            runCount: 1,
            parentMailboxEventCount: 1,
            callableWorkflowTaskCount: 1,
          },
        },
      },
      subagents: {
        replayEvidence: {
          schemaVersion: "ambient-subagent-replay-evidence-v1",
          childThreads: [{ threadId: "child-thread", canonicalTaskPath: "root/0:summarizer" }],
          parentMailboxTimeline: [{
            id: "mailbox-1",
            parentMessageId: "parent-message",
            type: "subagent.grouped_completion",
            childRunIds: ["run-1"],
            childThreadIds: ["child-thread"],
            canonicalTaskPaths: ["root/0:summarizer"],
            childSourceLabels: ["root/0:summarizer / run run-1 / thread child-thread"],
            payloadPreview: "Grouped child completion notification.",
          }, {
            id: "mailbox-tool-scope",
            parentMessageId: "parent-message",
            type: "subagent.spawn_failed",
            childRunIds: ["run-1"],
            childThreadIds: ["child-thread"],
            canonicalTaskPaths: ["root/0:summarizer"],
            childSourceLabels: ["root/0:summarizer / run run-1 / thread child-thread"],
            payloadPreview: "Requested sub-agent tool scope was denied.",
            failureStage: "tool_scope",
            approvalMode: "non_interactive",
            approvalUnavailable: true,
            deniedCategoryIds: ["connector.read"],
            deniedToolIds: ["connector_app:gmail.search"],
            deniedCategoryLabels: ["Connector Read (connector.read)"],
            deniedToolLabels: ["Connector App gmail.search / Connector Read (connector.read)"],
          }, {
            id: "mailbox-guard",
            parentMessageId: "parent-message",
            type: "subagent.wait_barrier_attention",
            childRunIds: ["run-1"],
            payloadPreview: "Child result is not synthesis-safe.",
            completionGuardSummary: {
              valid: false,
              synthesisAllowed: false,
              required: true,
              structuredEvidenceCount: 1,
              ambientEvidenceCount: 1,
              isolatedWorktreeEvidenceCount: 1,
              approvalEvidenceCount: 0,
              reason: "Missing approval provenance.",
            },
          }, {
            id: "mailbox-lifecycle",
            parentMessageId: "parent-message",
            type: "subagent.wait_barrier_decision",
            childRunIds: ["run-1", "run-2"],
            payloadPreview: "Parent cancelled required child work.",
            lifecycleSummary: {
              action: "cancel_parent",
              waitBarrierId: "barrier-1",
              barrierStatus: "cancelled",
              reason: "User stopped the parent.",
              userDecisionPreview: "Stop the parent task.",
              cancelledRunIds: ["run-1"],
              detachedRunIds: ["run-2"],
              unchangedRunIds: ["run-3"],
              cancelledWaitBarrierIds: ["barrier-1"],
              cancelledMailboxEventIds: ["mailbox-followup"],
              parentCancellationRequested: true,
            },
          }],
          callableWorkflowTaskTimeline: [{
            taskId: "workflow-task-1",
            launchId: "workflow-launch-1",
            parentThreadId: "parent-thread",
            parentRunId: "parent-run",
            parentMessageId: "parent-message",
            toolName: "ambient_workflow_map_reduce",
            sourceKind: "symphony_recipe",
            title: "Symphony Map-Reduce",
            status: "succeeded",
            blocking: true,
            runnerDeferredReason: "workflow_run_succeeded",
            workflowThreadId: "workflow-thread-1",
            workflowArtifactId: "workflow-artifact-1",
            workflowArtifactTitle: "Replay Child Mutation",
            workflowArtifactStatus: "ready_for_preview",
            workflowRunId: "workflow-run-1",
            workflowRunStatus: "succeeded",
            workflowRunEventTypes: ["callable_workflow.task_started", "callable_workflow.task_finished"],
            artifactLinkState: "linked",
            runLinkState: "linked",
            callerKind: "subagent_child_thread",
            childThreadId: "child-thread",
            childRunId: "run-1",
            approvalSource: "child_bridge_policy",
            approvalScope: "this_child_thread",
            worktreeIsolated: true,
            worktreeStatus: "active",
            nestedFanoutSource: "child_bridge_policy",
            lastEventType: "callable_workflow.task_finished",
          }],
          restartRepair: {
            callableWorkflowTaskIssues: [{
              issueId: "callable-issue-1",
              kind: "active_task_interrupted",
              severity: "warning",
              messagePreview: "Callable workflow task workflow-task-1 was compiling during restart.",
              taskId: "workflow-task-1",
              taskStatus: "compiling",
              blocking: true,
              runnerDeferredReason: "workflow_artifact_not_compiled",
              parentThreadId: "parent-thread",
              parentRunId: "parent-run",
              callerKind: "subagent_child_thread",
              callerThreadId: "child-thread",
              callerRunId: "run-1",
              childThreadId: "child-thread",
              childRunId: "run-1",
              subagentRunId: "run-1",
              canonicalTaskPath: "root/0:summarizer",
              childParentThreadId: "parent-thread",
              childParentRunId: "parent-run",
              approvalSource: "child_bridge_policy",
              approvalScope: "this_child_thread",
              worktreeRequired: true,
              worktreeIsolated: true,
              worktreeStatus: "active",
              nestedFanoutRequired: true,
              nestedFanoutSource: "child_bridge_policy",
            }],
          },
        },
      },
    });
    expect(result.summary?.featureFlags?.flags[AMBIENT_SUBAGENTS_FEATURE_FLAG]).toMatchObject({
      enabled: false,
      source: "startup_arg_disable",
      defaultEnabled: false,
      settingsEnabled: true,
    });
    expect(result.subagents?.replayEvidence?.runtimeEventTimeline[0]?.messagePreview?.length).toBeLessThanOrEqual(500);
    expect(result.subagents?.replayEvidence?.runtimeEventTimeline[0]).toMatchObject({
      approvalId: "approval-worker",
      approvalSource: "permission_grant",
      worktreeIsolated: true,
      worktreePath: "/repo/.ambient-codex/worktrees/child-thread",
    });
    expect(JSON.stringify(result)).not.toContain("sk-secret-shaped-value");
    expect(JSON.stringify(result)).not.toContain("do not return log contents");
    expect(JSON.stringify(result)).not.toContain("do not return raw payload");
    expect(JSON.stringify(result)).not.toContain("do not return raw workflow plan");
    expect(JSON.stringify(result)).not.toContain("do not return raw restart issue");
    expect(JSON.stringify(result)).not.toContain("unexpectedSecret");
    expect(JSON.stringify(result)).not.toContain("unexpectedField");
  });

  it("imports bounded local runtime diagnostic evidence without raw runtime internals", () => {
    const result = diagnosticImportResultFromBundleJson({
      path: "/tmp/ambient-diagnostics.json",
      bytes: 2048,
      bundle: {
        schemaVersion: 1,
        createdAt: "2026-06-05T00:00:00.000Z",
        summary: {
          ...diagnosticSummary(),
          localRuntimes: localRuntimeSummary(),
        },
        localRuntimes: {
          evidence: {
            ...localRuntimeEvidence(),
            runtimes: [{
              ...localRuntimeEvidence().runtimes[0],
              endpoint: "https://localhost.example/health?".concat("a".repeat(700)),
              rawProcessEnvironment: "do not return raw runtime env",
            }],
            unexpectedSecret: "do not return runtime secret",
          },
        },
      },
    });

    expect(result.summary?.localRuntimes).toMatchObject({
      status: "needs_attention",
      runtimeCount: 1,
      activeLeaseCount: 1,
      stopBlockedCount: 1,
      restartBlockedCount: 1,
    });
    expect(result.localRuntimes?.evidence).toMatchObject({
      schemaVersion: "ambient-local-runtime-diagnostic-evidence-v1",
      source: "diagnostic_export",
      counts: {
        runtimes: 1,
        activeOwners: 1,
        blockedActions: 1,
        nextSafeActions: 1,
      },
      runtimes: [
        expect.objectContaining({
          runtimeEntryId: "local-text:runtime-1:5001",
          activeLeaseIds: ["lease-review"],
          ordinaryStopAllowed: false,
          ordinaryRestartAllowed: false,
          forceStopRequiresSubagentCancellation: true,
        }),
      ],
      activeOwners: [
        expect.objectContaining({
          leaseId: "lease-review",
          displayName: "sub-agent Review worker",
          subagentThreadId: "child-thread",
          modelRuntimeId: "runtime-1",
        }),
      ],
      blockedActions: [
        expect.objectContaining({
          action: "stop",
          blockerLeaseIds: ["lease-review"],
          affectedSubagentThreadIds: ["child-thread"],
        }),
      ],
      nextSafeActions: [
        expect.objectContaining({
          action: "wait-for-owner",
          safety: "blocked",
          runtimeEntryId: "local-text:runtime-1:5001",
          blockerLeaseIds: ["lease-review"],
        }),
      ],
    });
    expect(result.localRuntimes?.evidence?.runtimes[0]?.endpoint?.length).toBeLessThanOrEqual(500);
    expect(JSON.stringify(result)).not.toContain("do not return raw runtime env");
    expect(JSON.stringify(result)).not.toContain("unexpectedSecret");
  });

  it("imports bounded Tencent memory diagnostics without raw memory payloads", () => {
    const result = diagnosticImportResultFromBundleJson({
      path: "/tmp/ambient-diagnostics.json",
      bytes: 2048,
      bundle: {
        schemaVersion: 1,
        createdAt: "2026-06-13T00:00:00.000Z",
        summary: {
          ...diagnosticSummary(),
          agentMemory: {
            ...agentMemorySummary(),
            rawMemoryPayload: "do not return raw memory",
            runtimeSnapshots: [{
              ...agentMemorySummary().runtimeSnapshots[0],
              rawConversation: "do not return raw conversation",
            }],
          },
        },
      },
    });

    expect(result.summary?.agentMemory).toMatchObject({
      adapter: "tencentdb",
      status: "needs_attention",
      fileCount: 2,
      rawContentIncluded: false,
      nativePreflight: {
        status: "unavailable",
        coreModuleConfigured: false,
      },
      runtimeSnapshots: [{
        threadId: "thread-memory",
        lastContextInjection: {
          totalInjectedChars: 512,
        },
        lastInitialize: {
          status: "unavailable",
          message: "missing reviewed package",
        },
      }],
    });
    expect(JSON.stringify(result)).not.toContain("do not return raw memory");
    expect(JSON.stringify(result)).not.toContain("do not return raw conversation");
  });

  it("imports summary-only diagnostics when replay evidence is malformed", () => {
    const result = diagnosticImportResultFromBundleJson({
      path: "/tmp/ambient-diagnostics.json",
      bytes: 1024,
      bundle: {
        schemaVersion: 1,
        createdAt: "2026-06-05T00:00:00.000Z",
        summary: diagnosticSummary(),
        subagents: {
          replayEvidence: {
            ...replayEvidence(),
            liveTokens: true,
          },
        },
        localRuntimes: {
          evidence: {
            ...localRuntimeEvidence(),
            source: "live_runtime_probe",
          },
        },
      },
    });

    expect(result.summary?.subagents.replayEvidence.runCount).toBe(1);
    expect(result.subagents?.replayEvidence).toBeUndefined();
    expect(result.localRuntimes?.evidence).toBeUndefined();
  });

  it("rejects files that are not Ambient diagnostic bundle JSON", () => {
    expect(() =>
      diagnosticImportResultFromBundleText({
        path: "/tmp/not-json.json",
        bytes: 12,
        text: "{not json",
      })
    ).toThrow("Selected diagnostic bundle is not valid JSON.");

    expect(() =>
      diagnosticImportResultFromBundleJson({
        path: "/tmp/not-diagnostics.json",
        bytes: 12,
        bundle: {
          schemaVersion: 2,
          createdAt: "2026-06-05T00:00:00.000Z",
          summary: diagnosticSummary(),
        },
      })
    ).toThrow();
  });
});

function diagnosticSummary(): DiagnosticExportSummary {
  return {
    featureFlags: {
      schemaVersion: "ambient-feature-flags-v1",
      generatedAt: "2026-06-05T00:00:00.000Z",
      flags: {
        [AMBIENT_SUBAGENTS_FEATURE_FLAG]: {
          id: AMBIENT_SUBAGENTS_FEATURE_FLAG,
          enabled: false,
          source: "startup_arg_disable",
          defaultEnabled: false,
          settingsEnabled: true,
        },
        [AMBIENT_TENCENTDB_MEMORY_FEATURE_FLAG]: {
          id: AMBIENT_TENCENTDB_MEMORY_FEATURE_FLAG,
          enabled: false,
          source: "default",
          defaultEnabled: false,
        },
        [AMBIENT_SLASH_COMMANDS_FEATURE_FLAG]: {
          id: AMBIENT_SLASH_COMMANDS_FEATURE_FLAG,
          enabled: false,
          source: "default",
          defaultEnabled: false,
        },
      },
    },
    subagents: {
      repairDiagnostics: {
        status: "healthy",
        message: "Sub-agent repair diagnostics found no child-tree issues.",
        issueCount: 0,
        shownIssueCount: 0,
        errorCount: 0,
        warningCount: 0,
        infoCount: 0,
        truncatedIssues: false,
        affectedRunCount: 0,
        affectedThreadCount: 0,
        affectedBarrierCount: 0,
        topActions: [],
        errorMessages: [],
      },
      observability: {
        status: "healthy",
        message: "Sub-agent observability recorded activity with no support signals.",
        spawnAttempts: 1,
        failedSpawns: 0,
        failureRate: 0,
        waitDurationCount: 0,
        waitDurationTotalMs: 0,
        waitDurationMaxMs: 0,
        childIdleOpenRunCount: 0,
        childIdleTotalMs: 0,
        childIdleMaxMs: 0,
        cancellationCascades: 0,
        childRuntimeAborts: 0,
        toolDenialCount: 0,
        groupedCompletions: 0,
        needsAttentionRequests: 0,
        restartReconciliations: 0,
        tokenCount: 0,
        costMicros: 0,
        errorMessages: [],
      },
      attribution: {
        status: "healthy",
        message: "Sub-agent attribution audit found no child-originating events to inspect.",
        auditedRuntimeEventCount: 0,
        auditedParentMailboxEventCount: 0,
        issueCount: 0,
        shownIssueCount: 0,
        truncatedIssues: false,
        missingAttributionCount: 0,
        mismatchedRunIdCount: 0,
        issueSamples: [],
        errorMessages: [],
      },
      replayEvidence: {
        status: "healthy",
        message: "Sub-agent replay evidence captured timelines for 1 child run.",
        runCount: 1,
        childThreadCount: 1,
        persistedRunEventCount: 1,
        runtimeEventCount: 1,
        parentMailboxEventCount: 1,
        transcriptMessageCount: 1,
        callableWorkflowTaskCount: 1,
        truncated: false,
        errorMessages: [],
      },
    },
  };
}

function localRuntimeSummary(): NonNullable<DiagnosticExportSummary["localRuntimes"]> {
  return {
    status: "needs_attention",
    message: "Local runtime diagnostics found 1 runtime, 1 active lease, and 1 lifecycle blocker.",
    runtimeCount: 1,
    runningCount: 1,
    activeLeaseCount: 1,
    stopBlockedCount: 1,
    restartBlockedCount: 1,
    untrackedCount: 0,
    staleLeaseCount: 0,
    releasedLeaseCount: 0,
    crashedLeaseCount: 0,
    activeEstimatedResidentMemoryBytes: 6 * 1024 ** 3,
    activeActualResidentMemoryBytes: 4 * 1024 ** 3,
    memoryPolicyOutcome: "within-limit",
    memoryPolicyReason: "Projected memory remains under the configured ceiling.",
    errorMessages: [],
  };
}

function agentMemorySummary(): NonNullable<DiagnosticExportSummary["agentMemory"]> {
  return {
    schemaVersion: "ambient-agent-memory-diagnostics-v1",
    adapter: "tencentdb",
    storageScope: "workspace",
    checkedAt: "2026-06-13T00:00:00.000Z",
    status: "needs_attention",
    message: "TencentDB Agent Memory is enabled but the reviewed core module is unavailable.",
    featureEnabled: true,
    settingsEnabled: true,
    defaultThreadEnabled: false,
    embedding: {
      enabled: false,
      status: "disabled",
      message: "TencentDB memory embeddings are disabled.",
    },
    activeThreadCount: 1,
    threadEnabledCount: 1,
    dataDir: "/tmp/ambient-memory/tencentdb",
    dataDirExists: true,
    storageSchemaStatus: "current",
    storageSchemaPath: "/tmp/ambient-memory/tencentdb/ambient-memory-schema.json",
    storageSchemaExpectedVersion: "ambient-tencent-memory-storage-v1",
    storageSchemaVersion: "ambient-tencent-memory-storage-v1",
    storageSchemaMessage: "TencentDB Agent Memory storage schema marker is current.",
    fileCount: 2,
    totalBytes: 128,
    topLevelEntryCount: 1,
    rawContentIncluded: false,
    nativePreflight: {
      schemaVersion: "ambient-agent-memory-native-preflight-v1",
      checkedAt: "2026-06-13T00:00:00.000Z",
      platform: "darwin",
      arch: "arm64",
      nodeModuleVersion: "141",
      coreModuleConfigured: false,
      status: "unavailable",
      message: "Reviewed TencentDB Agent Memory core module is not configured.",
      dependencies: [{
        name: "sqlite-vec",
        expectedVersion: "0.1.7-alpha.2",
        resolvable: false,
        status: "unavailable",
        message: "sqlite-vec package metadata is not resolvable without the reviewed TencentDB memory core package.",
      }],
      errors: [],
    },
    runtimeSnapshots: [{
      threadId: "thread-memory",
      active: true,
      dataDir: "/tmp/ambient-memory/tencentdb",
      sessionKey: "ambient-thread:thread-memory",
      lastContextInjection: {
        at: "2026-06-13T00:00:00.000Z",
        messageCount: 3,
        originalUserChars: 48,
        recallContextChars: 300,
        offloadContextChars: 200,
        totalInjectedChars: 512,
        projectedUserMessageChars: 562,
        truncated: false,
      },
      lastInitialize: {
        status: "unavailable",
        at: "2026-06-13T00:00:00.000Z",
        message: "missing reviewed package",
      },
    }],
    errors: [],
  };
}

function localRuntimeEvidence(): DiagnosticExportLocalRuntimeEvidence {
  return {
    schemaVersion: "ambient-local-runtime-diagnostic-evidence-v1",
    source: "diagnostic_export",
    capturedAt: "2026-06-05T00:00:00.000Z",
    truncated: false,
    counts: {
      runtimes: 1,
      activeOwners: 1,
      blockedActions: 1,
      nextSafeActions: 1,
    },
    shownCounts: {
      runtimes: 1,
      activeOwners: 1,
      blockedActions: 1,
      nextSafeActions: 1,
    },
    runtimes: [{
      sequence: 1,
      runtimeEntryId: "local-text:runtime-1:5001",
      capability: "local-text",
      trackingStatus: "managed",
      running: true,
      providerId: "local",
      modelRuntimeId: "runtime-1",
      modelProfileId: "local-text-4b-q4",
      modelId: "local/text-4b",
      pid: 5001,
      endpoint: "http://127.0.0.1:43123/health",
      estimatedResidentMemoryBytes: 6 * 1024 ** 3,
      actualResidentMemoryBytes: 4 * 1024 ** 3,
      memorySampledAt: "2026-06-05T00:00:00.000Z",
      ownerLabels: ["sub-agent Review worker"],
      activeLeaseIds: ["lease-review"],
      staleLeaseIds: [],
      releasedLeaseIds: [],
      crashedLeaseIds: [],
      ordinaryStopAllowed: false,
      ordinaryRestartAllowed: false,
      stopReason: "In use by sub-agent Review worker.",
      restartReason: "In use by sub-agent Review worker.",
      forceStopAllowed: true,
      forceRestartAllowed: true,
      forceStopRequiresSubagentCancellation: true,
      forceRestartRequiresSubagentCancellation: true,
      untracked: false,
    }],
    activeOwners: [{
      sequence: 1,
      runtimeEntryId: "local-text:runtime-1:5001",
      leaseId: "lease-review",
      displayName: "sub-agent Review worker",
      status: "running",
      parentThreadId: "parent-thread",
      subagentThreadId: "child-thread",
      subagentRunId: "child-run",
      capabilityKind: "local-text",
      providerId: "local",
      modelRuntimeId: "runtime-1",
      modelProfileId: "local-text-4b-q4",
      modelId: "local/text-4b",
      estimatedResidentMemoryBytes: 6 * 1024 ** 3,
      actualResidentMemoryBytes: 4 * 1024 ** 3,
      pid: 5001,
      endpoint: "http://127.0.0.1:43123/health",
      acquiredAt: "2026-06-05T00:00:00.000Z",
      lastHeartbeatAt: "2026-06-05T00:00:00.000Z",
    }],
    blockedActions: [{
      sequence: 1,
      runtimeEntryId: "local-text:runtime-1:5001",
      action: "stop",
      reason: "Ordinary Stop disabled while sub-agent Review worker owns this runtime.",
      blockerLeaseIds: ["lease-review"],
      affectedSubagentLabels: ["sub-agent Review worker (run child-run, thread child-thread, lease lease-review)"],
      affectedSubagentThreadIds: ["child-thread"],
      forceAllowed: true,
      forceRequiresSubagentCancellation: true,
      untracked: false,
    }],
    nextSafeActions: [{
      sequence: 1,
      action: "wait-for-owner",
      safety: "blocked",
      reason: "Wait for sub-agent Review worker to release lease-review before ordinary Stop.",
      runtimeEntryId: "local-text:runtime-1:5001",
      capability: "local-text",
      blockerLeaseIds: ["lease-review"],
      affectedSubagentLabels: ["sub-agent Review worker (run child-run, thread child-thread, lease lease-review)"],
      ownershipResolution: {
        lifecycleAction: "stop",
        resolution: "cancel-or-mark-affected-subagents",
        requiresInventoryRefresh: true,
        reason: "Forced Stop must cancel or mark affected sub-agents first.",
        blockerLeaseIds: ["lease-review"],
        affectedSubagentLabels: ["sub-agent Review worker (run child-run, thread child-thread, lease lease-review)"],
      },
      untracked: false,
    }],
    memoryEvidence: {
      activeEstimatedResidentMemoryBytes: 6 * 1024 ** 3,
      activeActualResidentMemoryBytes: 4 * 1024 ** 3,
      activeResidentMemoryBasis: "actual-rss",
      projectedSystemMemoryUtilization: 0.62,
      projectedFreeMemoryRatio: 0.38,
      uncertaintyReasons: [],
      entryCountWithActualRss: 1,
      entryCountWithOnlyEstimate: 0,
      entryCountWithUnknownMemory: 0,
    },
  };
}

function replayEvidence(): DiagnosticExportSubagentReplayEvidence {
  return {
    schemaVersion: "ambient-subagent-replay-evidence-v1",
    source: "diagnostic_export",
    createdAt: "2026-06-05T00:00:00.000Z",
    liveTokens: false,
    truncated: false,
    counts: {
      runs: 1,
      childThreads: 1,
      persistedRunEvents: 1,
      runtimeEvents: 1,
      parentMailboxEvents: 1,
      transcriptMessages: 1,
      callableWorkflowTasks: 1,
    },
    shownCounts: {
      runs: 1,
      childThreads: 1,
      persistedRunEvents: 1,
      runtimeEvents: 1,
      parentMailboxEvents: 1,
      transcriptMessages: 1,
      callableWorkflowTasks: 1,
    },
    childThreads: [{
      threadId: "child-thread",
      runId: "run-1",
      parentThreadId: "parent-thread",
      parentRunId: "parent-run",
      canonicalTaskPath: "root/0:summarizer",
      collapsedByDefault: true,
      status: "completed",
    }],
    runtimeEventTimeline: [],
    persistedRunEventTimeline: [],
    parentMailboxTimeline: [{
      sequence: 1,
      id: "mailbox-1",
      createdAt: "2026-06-05T00:00:03.000Z",
      updatedAt: "2026-06-05T00:00:04.000Z",
      parentThreadId: "parent-thread",
      parentRunId: "parent-run",
      parentMessageId: "parent-message",
      type: "subagent.grouped_completion",
      deliveryState: "queued",
      childRunIds: ["run-1"],
      idempotencyKey: "subagent:grouped_completion_notification:abc123",
      payloadPreview: "Grouped child completion notification.",
    }],
    callableWorkflowTaskTimeline: [{
      sequence: 1,
      taskId: "workflow-task-1",
      launchId: "workflow-launch-1",
      createdAt: "2026-06-05T00:00:04.000Z",
      updatedAt: "2026-06-05T00:00:05.000Z",
      parentThreadId: "parent-thread",
      parentRunId: "parent-run",
      parentMessageId: "parent-message",
      toolName: "ambient_workflow_map_reduce",
      sourceKind: "symphony_recipe",
      title: "Symphony Map-Reduce",
      status: "succeeded",
      statusLabel: "Succeeded",
      blocking: true,
      runnerDeferredReason: "workflow_run_succeeded",
      workflowThreadId: "workflow-thread-1",
      workflowArtifactId: "workflow-artifact-1",
      workflowArtifactTitle: "Replay Child Mutation",
      workflowArtifactStatus: "ready_for_preview",
      workflowRunId: "workflow-run-1",
      workflowRunStatus: "succeeded",
      workflowRunEventTypes: ["callable_workflow.task_started", "callable_workflow.task_finished"],
      artifactLinkState: "linked",
      runLinkState: "linked",
      callerKind: "subagent_child_thread",
      childThreadId: "child-thread",
      childRunId: "run-1",
      subagentRunId: "run-1",
      canonicalTaskPath: "root/0:summarizer",
      approvalSource: "child_bridge_policy",
      approvalScope: "this_child_thread",
      worktreeIsolated: true,
      worktreeStatus: "active",
      nestedFanoutSource: "child_bridge_policy",
      lastEventType: "callable_workflow.task_finished",
      lastEventMessage: "Callable workflow task finished.",
    }],
    transcriptTimeline: [{
      sequence: 1,
      createdAt: "2026-06-05T00:00:02.000Z",
      threadId: "child-thread",
      role: "assistant",
      childRunId: "run-1",
      childThreadId: "child-thread",
      contentPreview: "done",
    }],
    restartRepair: {
      observedIssueKinds: [],
      repairedRunIds: [],
      repairedBarrierIds: [],
      repairedParentControlBarrierIds: [],
      repairableSpawnEdgeRunIds: [],
      danglingSpawnEdgeRunIds: [],
      diagnosticRunIds: [],
      callableWorkflowTaskIssues: [],
    },
  };
}
