import type { McpPermissionCorpusEntry } from "./mcpPermissionCorpusService";

export const mcpPermissionCorpusFixtureEntries: McpPermissionCorpusEntry[] = [
  {
    id: "fixture-public-web-firecrawl",
    label: "Firecrawl style crawler",
    category: "public-web",
    evidenceText: "Crawls public web pages, follows URLs, fetches markdown, and may require an API token for hosted search limits.",
  },
  {
    id: "fixture-public-web-tavily",
    label: "Tavily style search",
    category: "public-web",
    evidenceText: "Searches the internet, fetches result URLs, summarizes web pages, and authenticates with an API key.",
  },
  {
    id: "fixture-public-web-brave-search",
    label: "Brave Search style connector",
    category: "public-web",
    evidenceText: "Queries public search results over HTTPS and requires a bearer token for the search API.",
  },
  {
    id: "fixture-public-web-scraper",
    label: "Generic page scraper",
    category: "public-web",
    evidenceText: "Scrapes arbitrary user-provided URLs, crawls links, extracts web page text, and can persist optional cache data.",
  },
  {
    id: "fixture-public-web-youtube",
    label: "YouTube transcript fetcher",
    category: "public-web",
    evidenceText: "Fetches public YouTube transcript URLs and internet metadata; may call a cloud API endpoint for captions.",
  },
  {
    id: "fixture-public-web-browserbase",
    label: "Hosted browser crawler",
    category: "public-web",
    evidenceText: "Uses browser automation, Chrome screenshots, hosted API endpoints, and a credential token to crawl webpages.",
  },
  {
    id: "fixture-fixed-api-context7",
    label: "Context7 hosted docs",
    category: "fixed-remote-api",
    evidenceText: "Connects to a fixed remote MCP HTTPS endpoint for documentation lookup and optional Authorization bearer token.",
  },
  {
    id: "fixture-fixed-api-sentry",
    label: "Sentry API helper",
    category: "fixed-remote-api",
    evidenceText: "Calls the Sentry cloud API endpoint, lists projects, and requires an API token for external account access.",
  },
  {
    id: "fixture-fixed-api-stripe",
    label: "Stripe account API",
    category: "fixed-remote-api",
    evidenceText: "Connects to Stripe HTTPS API endpoint, reads charges, mutates invoices, and requires secret API key credentials.",
  },
  {
    id: "fixture-fixed-api-cloudflare",
    label: "Cloudflare account API",
    category: "fixed-remote-api",
    evidenceText: "Uses Cloudflare HTTPS endpoint, zone account credentials, bearer token authorization, and external account mutation tools.",
  },
  {
    id: "fixture-fixed-api-linear",
    label: "Linear issue API",
    category: "fixed-remote-api",
    evidenceText: "Calls Linear SaaS API endpoint for issue search, create, update, OAuth login, and workspace account access.",
  },
  {
    id: "fixture-fixed-api-notion",
    label: "Notion workspace API",
    category: "fixed-remote-api",
    evidenceText: "Connects to Notion cloud API endpoint, reads pages, writes database rows, and uses integration secret credentials.",
  },
  {
    id: "fixture-local-ghidra",
    label: "Ghidra local bridge",
    category: "local-bridge",
    evidenceText: "Requires Ghidra desktop extension, local bridge on localhost 127.0.0.1, and user-guided setup before MCP calls.",
  },
  {
    id: "fixture-local-blender",
    label: "Blender local bridge",
    category: "local-bridge",
    evidenceText: "Controls Blender desktop app through a local bridge extension on localhost and reads scene data from the desktop app.",
  },
  {
    id: "fixture-local-figma",
    label: "Figma desktop bridge",
    category: "local-bridge",
    evidenceText: "Uses Figma desktop app plugin, localhost websocket bridge, extension install, and local endpoint preflight.",
  },
  {
    id: "fixture-local-unity",
    label: "Unity editor bridge",
    category: "local-bridge",
    evidenceText: "Talks to Unity editor extension through 127.0.0.1 local bridge and can mutate scenes in the desktop app.",
  },
  {
    id: "fixture-local-obsidian",
    label: "Obsidian local vault bridge",
    category: "local-bridge",
    evidenceText: "Requires Obsidian desktop plugin, localhost REST endpoint, local app permission, and vault filesystem folder access.",
  },
  {
    id: "fixture-local-browser-devtools",
    label: "Chrome DevTools local bridge",
    category: "local-bridge",
    evidenceText: "Connects to Chrome local debugging endpoint on localhost, browser screenshots, tabs, and page automation runtime.",
  },
  {
    id: "fixture-database-postgres",
    label: "Postgres database connector",
    category: "database",
    evidenceText: "Connects to Postgres database, runs SQL queries, reads tables, mutates rows, and uses database credentials.",
  },
  {
    id: "fixture-database-mysql",
    label: "MySQL database connector",
    category: "database",
    evidenceText: "Uses MySQL connection string, SQL read/write tools, database password secret, and schema inspection.",
  },
  {
    id: "fixture-database-sqlite",
    label: "SQLite project database",
    category: "database",
    evidenceText: "Reads local SQLite database file path, writes records, indexes data, and needs filesystem access.",
  },
  {
    id: "fixture-database-redis",
    label: "Redis memory database",
    category: "database",
    evidenceText: "Connects to Redis database, stores cache keys, persists memory values, and uses authorization password.",
  },
  {
    id: "fixture-database-mongodb",
    label: "MongoDB database connector",
    category: "database",
    evidenceText: "Connects to MongoDB Atlas cloud API endpoint, reads collections, writes documents, and requires credentials.",
  },
  {
    id: "fixture-database-supabase",
    label: "Supabase database connector",
    category: "database",
    evidenceText: "Uses Supabase HTTPS endpoint, Postgres SQL, API key, storage buckets, and external account project access.",
  },
  {
    id: "fixture-filesystem-reference",
    label: "Filesystem reference server",
    category: "filesystem",
    evidenceText: "Reads files and directories from a mounted workspace folder, writes output files, and lists project paths.",
  },
  {
    id: "fixture-filesystem-git",
    label: "Git repository helper",
    category: "filesystem",
    evidenceText: "Reads repository files, writes patches, runs git command line tools, and accesses workspace directory paths.",
  },
  {
    id: "fixture-filesystem-doc-index",
    label: "Document indexer",
    category: "filesystem",
    evidenceText: "Indexes local folder documents, stores embeddings, watches directory paths, and persists vector cache files.",
  },
  {
    id: "fixture-filesystem-markdown",
    label: "Markdown notes writer",
    category: "filesystem",
    evidenceText: "Reads and writes markdown files, creates output folders, edits workspace notes, and manages local paths.",
  },
  {
    id: "fixture-filesystem-media",
    label: "Media asset processor",
    category: "filesystem",
    evidenceText: "Reads image file paths, writes generated output files, calls CLI runtime commands, and stores metadata cache.",
  },
  {
    id: "fixture-filesystem-vault",
    label: "Knowledge vault filesystem",
    category: "filesystem",
    evidenceText: "Mounts a vault folder, reads files, writes memory notes, recalls indexed content, and supports deletion controls.",
  },
  {
    id: "fixture-memory-knowledge-graph",
    label: "Knowledge graph memory",
    category: "memory",
    evidenceText: "Stores persistent memory entities, recalls relationships, deletes facts, and keeps retention metadata in a graph store.",
  },
  {
    id: "fixture-memory-vector-qdrant",
    label: "Qdrant vector memory",
    category: "memory",
    evidenceText: "Stores embeddings in Qdrant vector database, indexes documents, recalls context, and supports deletion by collection.",
  },
  {
    id: "fixture-memory-chroma",
    label: "Chroma semantic memory",
    category: "memory",
    evidenceText: "Uses Chroma vector store, persists embeddings, remembers user facts, recalls notes, and deletes stale memory.",
  },
  {
    id: "fixture-memory-zep",
    label: "Zep cloud memory",
    category: "memory",
    evidenceText: "Calls Zep cloud API endpoint, stores conversation memory, recalls summaries, and uses API key credentials.",
  },
  {
    id: "fixture-memory-local-index",
    label: "Local project memory index",
    category: "memory",
    evidenceText: "Indexes workspace files into persistent cache storage, remembers project facts, forgets entries, and writes database files.",
  },
  {
    id: "fixture-memory-redis",
    label: "Redis session memory",
    category: "memory",
    evidenceText: "Stores persistent memory in Redis database, recalls session facts, expires keys, and requires password secret.",
  },
  {
    id: "fixture-runtime-shell",
    label: "Shell command runner",
    category: "runtime-process",
    evidenceText: "Runs shell command tools, subprocess execution, CLI package runtime, and user-provided command arguments.",
  },
  {
    id: "fixture-runtime-docker",
    label: "Docker controller",
    category: "runtime-process",
    evidenceText: "Controls Docker container runtime, lists images, starts containers, mounts folders, and mutates local processes.",
  },
  {
    id: "fixture-runtime-kubernetes",
    label: "Kubernetes CLI helper",
    category: "runtime-process",
    evidenceText: "Runs kubectl CLI commands, connects to cluster API, mutates deployments, and uses kubeconfig credentials.",
  },
  {
    id: "fixture-runtime-terraform",
    label: "Terraform runner",
    category: "runtime-process",
    evidenceText: "Runs terraform CLI command, reads workspace files, writes plan output, and mutates cloud infrastructure accounts.",
  },
  {
    id: "fixture-runtime-python",
    label: "Python package runner",
    category: "runtime-process",
    evidenceText: "Executes Python subprocess package tools through uvx or pipx, reads input files, and writes generated artifacts.",
  },
  {
    id: "fixture-runtime-node",
    label: "Node package runner",
    category: "runtime-process",
    evidenceText: "Runs npx npm package commands, starts local server process, and fetches package dependencies at install time.",
  },
  {
    id: "fixture-browser-playwright",
    label: "Playwright browser runtime",
    category: "browser-runtime",
    evidenceText: "Launches Chromium browser automation, takes screenshots, navigates public URLs, and controls page interactions.",
  },
  {
    id: "fixture-browser-puppeteer",
    label: "Puppeteer screenshot server",
    category: "browser-runtime",
    evidenceText: "Uses Puppeteer Chrome runtime, screenshot tools, public web crawling, and local browser process execution.",
  },
  {
    id: "fixture-browser-selenium",
    label: "Selenium web driver",
    category: "browser-runtime",
    evidenceText: "Controls Selenium browser runtime, remote web driver endpoint, screenshots, and form automation.",
  },
  {
    id: "fixture-external-github",
    label: "GitHub account tools",
    category: "external-account",
    evidenceText: "Uses GitHub API token, reads repositories, writes issues, accesses external account data, and calls HTTPS API endpoint.",
  },
  {
    id: "fixture-external-slack",
    label: "Slack workspace tools",
    category: "external-account",
    evidenceText: "Connects to Slack external account, reads channels, sends messages, OAuth login, and bearer token credentials.",
  },
  {
    id: "fixture-external-google-drive",
    label: "Google Drive tools",
    category: "external-account",
    evidenceText: "Uses Google Drive external account, reads files, writes docs, OAuth credentials, and cloud API endpoints.",
  },
  {
    id: "fixture-external-jira",
    label: "Jira project tools",
    category: "external-account",
    evidenceText: "Calls Jira SaaS API endpoint, reads tickets, mutates project issues, and uses API token authorization.",
  },
  {
    id: "fixture-external-aws",
    label: "AWS account tools",
    category: "external-account",
    evidenceText: "Uses AWS credentials, cloud account APIs, mutates resources, runs CLI commands, and accesses secret tokens.",
  },
  {
    id: "fixture-external-gmail",
    label: "Gmail account tools",
    category: "external-account",
    evidenceText: "Connects to Gmail external account through OAuth login, reads messages, sends email, and calls Google API endpoints.",
  },
  {
    id: "fixture-unknown-readme-only",
    label: "Readme-only MCP listing",
    category: "unknown",
    evidenceText: "MCP adapter listing contains a name and short tagline only, with no transport or capability details.",
  },
  {
    id: "fixture-unknown-custom-binary",
    label: "Custom binary bridge",
    category: "unknown",
    evidenceText: "Project says install the bridge and configure it manually, but gives no documented permissions or stable interface.",
  },
  {
    id: "fixture-unknown-private-repo",
    label: "Private repo connector",
    category: "unknown",
    evidenceText: "Repository metadata is unavailable and the listing only says enterprise connector with setup instructions hidden.",
  },
  {
    id: "fixture-unknown-ai-tool",
    label: "Generic AI assistant bridge",
    category: "unknown",
    evidenceText: "Brief catalog entry says AI helper for productivity with no endpoints, tools, schemas, or permission evidence.",
  },
  {
    id: "fixture-unknown-unmaintained",
    label: "Unmaintained server listing",
    category: "unknown",
    evidenceText: "Old listing has no current manifest, no clear transport, and no reviewable runtime or data access description.",
  },
  {
    id: "fixture-unknown-marketplace",
    label: "Marketplace placeholder",
    category: "unknown",
    evidenceText: "Marketplace row has title only and no documented source, setup, data access, or permission model.",
  },
];
