import { readFile } from "node:fs/promises";

import { describe, expect, it } from "vitest";

async function readText(path) {
  return readFile(new URL(`../${path}`, import.meta.url), "utf8");
}

describe("sub-agent Desktop dogfood harness wiring", () => {
  it("exposes the full Desktop dogfood lane through package scripts", async () => {
    const packageJson = JSON.parse(await readText("package.json"));

    expect(packageJson.scripts["test:subagents:desktop-dogfood"]).toContain("scripts/run-electron-dogfood.mjs");
    expect(packageJson.scripts["test:subagents:desktop-dogfood"]).toContain("AMBIENT_PROVIDER=${AMBIENT_PROVIDER:-ambient}");
    expect(packageJson.scripts["test:subagents:desktop-dogfood:unit"]).toContain("scripts/subagent-desktop-dogfood.test.mjs");
    expect(packageJson.scripts["test:subagents:desktop-dogfood-repeat"]).toContain("scripts/subagent-desktop-dogfood-repeat.mjs");
    expect(packageJson.scripts["test:subagents:desktop-dogfood-repeat"]).toContain("AMBIENT_PROVIDER=${AMBIENT_PROVIDER:-ambient}");
    expect(packageJson.scripts["test:subagents:desktop-dogfood-repeat:unit"]).toContain("scripts/subagent-desktop-dogfood-repeat.test.mjs");
    expect(packageJson.scripts["subagents:desktop-dogfood-history-report"]).toContain("scripts/subagent-desktop-dogfood-history-report.mjs");
    expect(packageJson.scripts["test:subagents:desktop-dogfood-history-report:unit"]).toContain("scripts/subagent-desktop-dogfood-history-report.test.mjs");
  });

  it("keeps the runner anchored to Electron, feature flags, visual artifacts, and accessibility snapshots", async () => {
    const runner = await readText("scripts/subagent-desktop-dogfood.mjs");
    const supervisor = await readText("scripts/run-electron-dogfood.mjs");
    const placeholder = await readText("scripts/llama-server-placeholder.mjs");
    const e2e = await readText("src/main/subagentDesktopDogfood.e2e.test.ts");

    expect(supervisor).toContain("verifyHarnessCheckout");
    expect(supervisor).toContain("AMBIENT_SUBAGENT_DESKTOP_DOGFOOD_CDP_PORT");
    expect(supervisor).toContain("getAvailablePort");
    expect(supervisor).toContain("electron-dogfood-latest.manifest.json");
    expect(supervisor).toContain("staleElectronProcessPids");
    expect(runner).toContain("AMBIENT_SUBAGENT_DESKTOP_DOGFOOD");
    expect(runner).toContain("AMBIENT_SUBAGENT_DESKTOP_DOGFOOD_RUNTIME_PID");
    expect(runner).toContain("scripts/llama-server-placeholder.mjs");
    expect(runner).toContain("AMBIENT_SUBAGENT_DESKTOP_DOGFOOD_UNTRACKED_RUNTIME_PID");
    expect(runner).toContain("AMBIENT_SUBAGENT_DESKTOP_DOGFOOD_UNTRACKED_RUNTIME_ID");
    expect(runner).toContain("AMBIENT_SUBAGENT_DESKTOP_DOGFOOD_UNTRACKED_RUNTIME_ENDPOINT");
    expect(runner).toContain("AMBIENT_SUBAGENT_DESKTOP_DOGFOOD_UNTRACKED_RUNTIME_MODEL");
    expect(runner).toContain("seedBraveSearchWorkspaceSecret");
    expect(runner).toContain("seedBraveSearchPreference");
    expect(runner).toContain("brave_api_key.txt");
    expect(runner).toContain("com~apple~CloudDocs");
    expect(runner).toContain("BRAVE_API_KEY");
    expect(runner).toContain("brave-search");
    expect(runner).toContain("\"brave-search\", \"exa-mcp-default\", \"ambient-browser\"");
    expect(runner).toContain("AMBIENT_SUBAGENT_DESKTOP_DOGFOOD_BRAVE_SEARCH");
    expect(runner).toContain("AMBIENT_LEGACY_WORKFLOW_COMPILER");
    expect(runner).toContain("src/main/subagentDesktopDogfoodSeed.test.ts");
    expect(runner).toContain("AMBIENT_E2E_USER_DATA");
    expect(runner).toContain("scripts/subagent-desktop-dogfood-history-report.mjs");
    expect(runner).toContain("staleLatestArtifactPath");
    expect(runner).toContain("\"test-results\", \"subagent-desktop-dogfood\", \"latest.json\"");
    expect(runner).toContain("await rm(staleLatestArtifactPath, { force: true })");
    expect(runner).toContain("--append-latest=test-results/subagent-desktop-dogfood/latest.json");
    expect(runner).toContain("--append-latest-if-exists=test-results/subagent-desktop-dogfood/latest.json");
    expect(placeholder).toContain("AMBIENT_SUBAGENT_DESKTOP_DOGFOOD_UNTRACKED_PLACEHOLDER");
    expect(placeholder).toContain("setInterval");
    expect(e2e).toContain("test-results/subagent-desktop-dogfood");
    expect(e2e).toContain("AMBIENT_SUBAGENT_DESKTOP_DOGFOOD_SEED");
    expect(e2e).toContain("AMBIENT_SUBAGENT_DESKTOP_DOGFOOD_CDP_PORT");
    expect(e2e).toContain("cdpPort: port");
    expect(e2e).toContain("headful: true");
    expect(e2e).toContain("--remote-debugging-port");
    expect(e2e).toContain("--enable-feature=${AMBIENT_SUBAGENTS_FEATURE_FLAG}");
    expect(e2e).toContain("Accessibility.getFullAXTree");
    expect(e2e).toContain(".subagent-parent-cluster");
    expect(e2e).toContain("approval_parent_blocking");
    expect(e2e).toContain("Blocking: approval");
    expect(e2e).toContain("Approval requested");
    expect(e2e).toContain("approvalFlow");
    expect(e2e).toContain("approvalButtonsNameChild");
    expect(e2e).toContain("workflow_execution_parent_blocking");
    expect(e2e).toContain("workflowExecution");
    expect(e2e).toContain("workflow-execution-desktop.png");
    expect(e2e).toContain("mutating_worker_dogfood_behavior");
    expect(e2e).toContain("mutatingWorkerDogfood");
    expect(e2e).toContain("mutating-worker-dogfood-desktop.png");
    expect(e2e).toContain("Symphony Self-Healing Loop");
    expect(e2e).toContain("Mutating child worker");
    expect(e2e).toContain("Staged mutation: src/feature.txt");
    expect(e2e).toContain("Parent workspace unchanged");
    expect(e2e).toContain("mutating_worker_evidence");
    expect(e2e).toContain("desktop_mutating_worker_dogfood");
    expect(e2e).toContain("workflow_high_load_dogfood");
    expect(e2e).toContain("workflowHighLoad");
    expect(e2e).toContain("workflow-high-load-desktop.png");
    expect(e2e).toContain("Symphony Adversarial Debate");
    expect(e2e).toContain("Symphony Imitate and Verify");
    expect(e2e).toContain("Symphony Pipeline");
    expect(e2e).toContain("Symphony Ensemble");
    expect(e2e).toContain("workflow_high_load");
    expect(e2e).toContain("desktop_workflow_high_load");
    expect(e2e).toContain("pattern_graph_snapshot_persistence");
    expect(e2e).toContain("inspectPatternGraphRuntime");
    expect(e2e).toContain("patternGraphRuntime");
    expect(e2e).toContain("pattern_graph_runtime");
    expect(e2e).toContain("desktop_pattern_graph_runtime");
    expect(e2e).toContain("workflowTaskId");
    expect(e2e).toContain("Open Review worker thread from Map-Reduce");
    expect(e2e).toContain("effective_role_snapshot_inspector");
    expect(e2e).toContain("inspectEffectiveRoleSnapshot");
    expect(e2e).toContain("effective-role-snapshot-desktop.png");
    expect(e2e).toContain("Reviewer + Mapper");
    expect(e2e).toContain("denied_scope_explanation_behavior");
    expect(e2e).toContain("deniedScopeExplanation");
    expect(e2e).toContain("denied-scope-explanation-desktop.png");
    expect(e2e).toContain("Approval unavailable");
    expect(e2e).toContain("Connector App gmail.search");
    expect(e2e).toContain("desktop_denied_scope_explanations");
    expect(e2e).toContain("denied_scope_explanations");
    expect(e2e).toContain("Symphony Map-Reduce");
    expect(e2e).toContain("Blocking: workflow work");
    expect(e2e).toContain("Workflow blocked");
    expect(e2e).toContain("pauseControlVisible");
    expect(e2e).toContain("workflowTaskRehydrated");
    expect(e2e).toContain("approval_forwarding_behavior");
    expect(e2e).toContain("approvalForwarding");
    expect(e2e).toContain("approval-forwarding-dialog.png");
    expect(e2e).toContain("approval-forwarded-desktop.png");
    expect(e2e).toContain("forwardedAndRequestSameChild");
    expect(e2e).toContain("childRowDataMatchesApprovalChild");
    expect(e2e).toContain("childRowStillBlocksApprovalChild");
    expect(e2e).toContain("parentStillBlockedAfterForward");
    expect(e2e).toContain("childReturnedToNeedsSteering");
    expect(e2e).toContain("approvalAuthorityContract");
    expect(e2e).toContain("requestExported");
    expect(e2e).toContain("forwardedExported");
    expect(e2e).toContain("requestedToolMatches");
    expect(e2e).toContain("parentBlockingResumeMatches");
    expect(e2e).toContain("forwardedParentBlockingResumeMatches");
    expect(e2e).toContain("waitBarrierMatches");
    expect(e2e).toContain("restart_rehydration_behavior");
    expect(e2e).toContain("restartRehydration");
    expect(e2e).toContain("restart-rehydration-desktop.png");
    expect(e2e).toContain("defaultCollapsedAfterRelaunch");
    expect(e2e).toContain("completedChildResultSummaryRehydrated");
    expect(e2e).toContain("workflow_rehydrated_navigation_behavior");
    expect(e2e).toContain("workflowRehydratedNavigation");
    expect(e2e).toContain("workflow-rehydrated-navigation-desktop.png");
    expect(e2e).toContain("workflowThreadSidebarSelected");
    expect(e2e).toContain("workflowThreadMatchesExpectedId");
    expect(e2e).toContain("desktop_workflow_rehydrated_navigation");
    expect(e2e).toContain("workflow_artifact_rehydration_behavior");
    expect(e2e).toContain("workflowArtifactRehydration");
    expect(e2e).toContain("workflow-artifact-rehydration-desktop.png");
    expect(e2e).toContain("workflowArtifactSourceRelativePath");
    expect(e2e).toContain("workflowArtifactStateRelativePath");
    expect(e2e).toContain("sourceContentMatchesExpected");
    expect(e2e).toContain("desktop_workflow_artifact_rehydration");
    expect(e2e).toContain("local_runtime_ownership_ui");
    expect(e2e).toContain("untracked_runtime_safety_behavior");
    expect(e2e).toContain("localRuntimeOwnership");
    expect(e2e).toContain("local-runtime-ownership-desktop.png");
    expect(e2e).toContain("In use by sub-agent Review worker");
    expect(e2e).toContain("stopDisabledVisible");
    expect(e2e).toContain("affectedSubagentVisible");
    expect(e2e).toContain("untrackedRuntimeVisible");
    expect(e2e).toContain("untrackedStopDisabledVisible");
    expect(e2e).toContain("untrackedRestartDisabledVisible");
    expect(e2e).toContain("untrackedForceUnavailableVisible");
    expect(e2e).toContain("untrackedExternalStopGuidanceVisible");
    expect(e2e).toContain("lifecycle_edge_desktop_behavior");
    expect(e2e).toContain("inspectLifecycleEdgeVisibility");
    expect(e2e).toContain("lifecycle-edge-visibility-desktop.png");
    expect(e2e).toContain("Timeout edge worker");
    expect(e2e).toContain("Continue with partial");
    expect(e2e).toContain("Partial approved");
    expect(e2e).toContain("Retry edge worker");
    expect(e2e).toContain("Retry requested");
    expect(e2e).toContain("retry_edge");
    expect(e2e).toContain("Child detached");
    expect(e2e).toContain("desktop_lifecycle_edges");
    expect(e2e).toContain("lifecycle_edge_visibility");
    expect(e2e).toContain("operator_child_controls");
    expect(e2e).toContain("operatorControls");
    expect(e2e).toContain("Cancel sub-agent Review worker");
    expect(e2e).toContain("Close sub-agent Context summarizer");
    expect(e2e).toContain("operator_control_behavior");
    expect(e2e).toContain("operatorBehavior");
    expect(e2e).toContain("completedChildClosed");
    expect(e2e).toContain("attentionChildCancelled");
    expect(e2e).toContain("operator-behavior-desktop.png");
    expect(e2e).toContain("multi_parent_cluster_stress");
    expect(e2e).toContain("multiClusterStress");
    expect(e2e).toContain("multi-cluster-stress-desktop.png");
    expect(e2e).toContain("stressClustersAfterParentMessages");
    expect(e2e).toContain("chat_export_child_bundle");
    expect(e2e).toContain("exportChatAndInspectChildBundle");
    expect(e2e).toContain("desktop-chat-export.zip");
    expect(e2e).toContain("AMBIENT_E2E_CHAT_EXPORT_PATH");
    expect(e2e).toContain("desktop_chat_export_child_bundle");
    expect(e2e).toContain("child_transcript_export");
    expect(e2e).toContain("policy_provenance_export");
    expect(e2e).toContain("pattern_graph_export_links");
    expect(e2e).toContain("childToolScopeSnapshotsIncluded");
    expect(e2e).toContain("patternGraphLinksIncluded");
    expect(e2e).toContain("visualAssertions");
    expect(e2e).toContain("buildDesktopVisualAssertions");
    expect(e2e).toContain("parent_child_placement");
    expect(e2e).toContain("default_collapsed_state");
    expect(e2e).toContain("blocking_attention_indicators");
    expect(e2e).toContain("approval_runtime_ownership_labels");
    expect(e2e).toContain("workflow_artifact_rehydration");
    expect(e2e).toContain("layout_safety");
    expect(e2e).toContain("workflow_task_continuity");
    expect(e2e).toContain("desktop_multi_cluster_stress");
    expect(e2e).toContain("horizontalOverflowFree");
    expect(e2e).toContain("collapsed-desktop.png");
    expect(e2e).toContain("expanded-narrow.png");
  });
});
