import { readFile } from "node:fs/promises";

import { describe, expect, it } from "vitest";

async function readText(path) {
  return readFile(new URL(`../${path}`, import.meta.url), "utf8");
}

async function readDogfoodE2eContractSource() {
  const e2e = await readText("src/main/subagents/subagentDesktopDogfood.e2e.test.ts");
  const support = await readText("src/main/subagents/subagentDesktopDogfoodE2eSupport.ts");
  const inspectors = await readText("src/main/subagents/subagentDesktopDogfoodUiInspectors.ts");
  const lifecycleRuntimeInspectors = await readText("src/main/subagents/subagentDesktopDogfoodLifecycleRuntimeInspectors.ts");
  const assertions = await readText("src/main/subagents/subagentDesktopDogfoodAssertions.ts");
  return { e2e, e2eContractSource: `${e2e}\n${support}\n${inspectors}\n${lifecycleRuntimeInspectors}\n${assertions}` };
}

describe("sub-agent Desktop dogfood harness wiring", () => {
  it("exposes the full Desktop dogfood lane through package scripts", async () => {
    const packageJson = JSON.parse(await readText("package.json"));

    expect(packageJson.scripts["test:subagents:desktop-dogfood"]).toContain("scripts/run-electron-dogfood.mjs");
    expect(packageJson.scripts["test:subagents:desktop-dogfood"]).toContain("AMBIENT_PROVIDER=${AMBIENT_PROVIDER:-ambient}");
    expect(packageJson.scripts["test:subagents:desktop-dogfood:unit"]).toContain("scripts/subagent-desktop-dogfood.test.mjs");
    expect(packageJson.scripts["test:subagents:desktop-dogfood-repeat"]).toContain("scripts/subagent-desktop-dogfood-repeat.mjs");
    expect(packageJson.scripts["test:subagents:desktop-dogfood-repeat"]).toContain("AMBIENT_PROVIDER=${AMBIENT_PROVIDER:-ambient}");
    expect(packageJson.scripts["test:subagents:desktop-dogfood-repeat:unit"]).toContain("scripts/subagent-desktop-dogfood-repeat.test.mjs");
    expect(packageJson.scripts["subagents:desktop-dogfood-history-report"]).toContain(
      "scripts/subagent-desktop-dogfood-history-report.mjs",
    );
    expect(packageJson.scripts["test:subagents:desktop-dogfood-history-report:unit"]).toContain(
      "scripts/subagent-desktop-dogfood-history-report.test.mjs",
    );
  });

  it("keeps the runner anchored to Electron, feature flags, visual artifacts, and accessibility snapshots", async () => {
    const runner = await readText("scripts/subagent-desktop-dogfood.mjs");
    const supervisor = await readText("scripts/run-electron-dogfood.mjs");
    const placeholder = await readText("scripts/llama-server-placeholder.mjs");
    const { e2e, e2eContractSource } = await readDogfoodE2eContractSource();

    expect(e2e).toContain("subagentDesktopDogfoodAssertions");

    expect(supervisor).toContain("verifyHarnessCheckout");
    expect(supervisor).toContain('DEFAULT_DOGFOOD_PROVIDER = "ambient"');
    expect(supervisor).toContain('DEFAULT_DOGFOOD_MODEL = "example/model-id"');
    expect(supervisor).toContain("dogfoodLaunchEnv");
    expect(supervisor).toContain("providerSnapshot(launchEnv ?? dogfoodLaunchEnv(process.env))");
    expect(supervisor).toContain("AMBIENT_SUBAGENT_DESKTOP_DOGFOOD_CDP_PORT");
    expect(supervisor).toContain("getAvailablePort");
    expect(supervisor).toContain("electron-dogfood-latest.manifest.json");
    expect(supervisor).toContain("staleElectronProcessPids");
    expect(supervisor).toContain("scripts/symphony-gap-phase4-dogfood.mjs");
    expect(supervisor).toContain("test-results/symphony-gap-phase4-dogfood/latest.json");
    expect(supervisor).toContain("scripts/symphony-gap-phase5-dogfood.mjs");
    expect(supervisor).toContain("test-results/symphony-gap-phase5-dogfood/latest.json");
    expect(supervisor).toContain("scripts/symphony-gap-phase6-dogfood.mjs");
    expect(supervisor).toContain("test-results/symphony-gap-phase6-dogfood/latest.json");
    expect(runner).toContain("AMBIENT_SUBAGENT_DESKTOP_DOGFOOD");
    expect(runner).toContain("AMBIENT_SUBAGENT_DESKTOP_DOGFOOD_RUNTIME_PID");
    expect(runner).toContain('DEFAULT_DOGFOOD_PROVIDER = "ambient"');
    expect(runner).toContain('DEFAULT_DOGFOOD_MODEL = "example/model-id"');
    expect(runner).toContain("dogfoodProviderEnv(process.env)");
    expect(runner).toContain("GMI_CLOUD_MODEL: modelId");
    expect(runner).toContain("AMBIENT_LIVE_MODEL: modelId");
    expect(runner).toContain("scripts/llama-server-placeholder.mjs");
    expect(runner).toContain("AMBIENT_SUBAGENT_DESKTOP_DOGFOOD_UNTRACKED_RUNTIME_PID");
    expect(runner).toContain("AMBIENT_SUBAGENT_DESKTOP_DOGFOOD_UNTRACKED_RUNTIME_ID");
    expect(runner).toContain("AMBIENT_SUBAGENT_DESKTOP_DOGFOOD_UNTRACKED_RUNTIME_ENDPOINT");
    expect(runner).toContain("AMBIENT_SUBAGENT_DESKTOP_DOGFOOD_UNTRACKED_RUNTIME_MODEL");
    expect(runner).toContain("seedBraveSearchWorkspaceSecret");
    expect(runner).toContain("seedBraveSearchPreference");
    expect(runner).toContain("brave_api_key.txt");
    expect(runner).toContain("com~apple~CloudDocs");
    expect(runner).toContain("BRAVE_API_KEY");
    expect(runner).toContain("brave-search");
    expect(runner).toContain('"brave-search", "exa-mcp-default", "ambient-browser"');
    expect(runner).toContain("AMBIENT_SUBAGENT_DESKTOP_DOGFOOD_BRAVE_SEARCH");
    expect(runner).toContain("AMBIENT_LEGACY_WORKFLOW_COMPILER");
    expect(runner).toContain("src/main/subagents/subagentDesktopDogfoodSeed.test.ts");
    expect(runner).toContain("AMBIENT_SUBAGENT_DESKTOP_DOGFOOD_RESULTS_DIR");
    expect(runner).toContain("AMBIENT_SUBAGENT_DESKTOP_DOGFOOD_HISTORY_APPEND");
    expect(runner).toContain("AMBIENT_E2E_USER_DATA");
    expect(runner).toContain("scripts/subagent-desktop-dogfood-history-report.mjs");
    expect(runner).toContain("staleLatestArtifactPath");
    expect(runner).toContain('defaultResultsDir = join("test-results", "subagent-desktop-dogfood")');
    expect(runner).toContain("await rm(staleLatestArtifactPath, { force: true })");
    expect(runner).toContain("appendHistory");
    expect(runner).toContain("`--append-latest=${latestArtifactRelativePath}`");
    expect(runner).toContain("`--append-latest-if-exists=${latestArtifactRelativePath}`");
    expect(placeholder).toContain("AMBIENT_SUBAGENT_DESKTOP_DOGFOOD_UNTRACKED_PLACEHOLDER");
    expect(placeholder).toContain("setInterval");
    expect(e2eContractSource).toContain("test-results/subagent-desktop-dogfood");
    expect(e2eContractSource).toContain("AMBIENT_SUBAGENT_DESKTOP_DOGFOOD_SEED");
    expect(e2eContractSource).toContain("AMBIENT_SUBAGENT_DESKTOP_DOGFOOD_CDP_PORT");
    expect(e2eContractSource).toContain("cdpPort: port");
    expect(e2eContractSource).toContain("headful: true");
    expect(e2eContractSource).toContain("--remote-debugging-port");
    expect(e2eContractSource).toContain("--enable-feature=${AMBIENT_SUBAGENTS_FEATURE_FLAG}");
    expect(e2eContractSource).toContain("Accessibility.getFullAXTree");
    expect(e2eContractSource).toContain(".subagent-parent-cluster");
    expect(e2eContractSource).toContain("approval_parent_blocking");
    expect(e2eContractSource).toContain("Blocking: approval");
    expect(e2eContractSource).toContain("Approval requested");
    expect(e2eContractSource).toContain("approvalFlow");
    expect(e2eContractSource).toContain("approvalButtonsNameChild");
    expect(e2eContractSource).toContain("workflow_execution_parent_blocking");
    expect(e2eContractSource).toContain("workflowExecution");
    expect(e2eContractSource).toContain("workflow-execution-desktop.png");
    expect(e2eContractSource).toContain("mutating_worker_dogfood_behavior");
    expect(e2eContractSource).toContain("mutatingWorkerDogfood");
    expect(e2eContractSource).toContain("mutating-worker-dogfood-desktop.png");
    expect(e2eContractSource).toContain("Symphony Self-Healing Loop");
    expect(e2eContractSource).toContain("Mutating child worker");
    expect(e2eContractSource).toContain("Staged mutation: src/feature.txt");
    expect(e2eContractSource).toContain("Parent workspace unchanged");
    expect(e2eContractSource).toContain("mutating_worker_evidence");
    expect(e2eContractSource).toContain("desktop_mutating_worker_dogfood");
    expect(e2eContractSource).toContain("workflow_high_load_dogfood");
    expect(e2eContractSource).toContain("workflowHighLoad");
    expect(e2eContractSource).toContain("workflow-high-load-desktop.png");
    expect(e2eContractSource).toContain("Symphony Adversarial Debate");
    expect(e2eContractSource).toContain("Symphony Imitate and Verify");
    expect(e2eContractSource).toContain("Symphony Pipeline");
    expect(e2eContractSource).toContain("Symphony Ensemble");
    expect(e2eContractSource).toContain("workflow_high_load");
    expect(e2eContractSource).toContain("desktop_workflow_high_load");
    expect(e2eContractSource).toContain("pattern_graph_snapshot_persistence");
    expect(e2eContractSource).toContain("inspectPatternGraphRuntime");
    expect(e2eContractSource).toContain("patternGraphRuntime");
    expect(e2eContractSource).toContain("pattern_graph_runtime");
    expect(e2eContractSource).toContain("desktop_pattern_graph_runtime");
    expect(e2eContractSource).toContain("workflowTaskId");
    expect(e2eContractSource).toContain("Open Review worker thread from Map-Reduce");
    expect(e2eContractSource).toContain("effective_role_snapshot_inspector");
    expect(e2eContractSource).toContain("inspectEffectiveRoleSnapshot");
    expect(e2eContractSource).toContain("effective-role-snapshot-desktop.png");
    expect(e2eContractSource).toContain("Reviewer + Mapper");
    expect(e2eContractSource).toContain("denied_scope_explanation_behavior");
    expect(e2eContractSource).toContain("deniedScopeExplanation");
    expect(e2eContractSource).toContain("denied-scope-explanation-desktop.png");
    expect(e2eContractSource).toContain("Approval unavailable");
    expect(e2eContractSource).toContain("Connector App gmail.search");
    expect(e2eContractSource).toContain("desktop_denied_scope_explanations");
    expect(e2eContractSource).toContain("denied_scope_explanations");
    expect(e2eContractSource).toContain("Symphony Map-Reduce");
    expect(e2eContractSource).toContain("Blocking: workflow work");
    expect(e2eContractSource).toContain("Workflow blocked");
    expect(e2eContractSource).toContain("pauseControlVisible");
    expect(e2eContractSource).toContain("workflowTaskRehydrated");
    expect(e2eContractSource).toContain("approval_forwarding_behavior");
    expect(e2eContractSource).toContain("approvalForwarding");
    expect(e2eContractSource).toContain("approval-forwarding-dialog.png");
    expect(e2eContractSource).toContain("approval-forwarded-desktop.png");
    expect(e2eContractSource).toContain("forwardedAndRequestSameChild");
    expect(e2eContractSource).toContain("childRowDataMatchesApprovalChild");
    expect(e2eContractSource).toContain("childRowStillBlocksApprovalChild");
    expect(e2eContractSource).toContain("parentStillBlockedAfterForward");
    expect(e2eContractSource).toContain("childReturnedToNeedsSteering");
    expect(e2eContractSource).toContain("approvalAuthorityContract");
    expect(e2eContractSource).toContain("requestExported");
    expect(e2eContractSource).toContain("forwardedExported");
    expect(e2eContractSource).toContain("requestedToolMatches");
    expect(e2eContractSource).toContain("parentBlockingResumeMatches");
    expect(e2eContractSource).toContain("forwardedParentBlockingResumeMatches");
    expect(e2eContractSource).toContain("waitBarrierMatches");
    expect(e2eContractSource).toContain("restart_rehydration_behavior");
    expect(e2eContractSource).toContain("restartRehydration");
    expect(e2eContractSource).toContain("restart-rehydration-desktop.png");
    expect(e2eContractSource).toContain("defaultCollapsedAfterRelaunch");
    expect(e2eContractSource).toContain("completedChildResultSummaryRehydrated");
    expect(e2eContractSource).toContain("workflow_rehydrated_navigation_behavior");
    expect(e2eContractSource).toContain("workflowRehydratedNavigation");
    expect(e2eContractSource).toContain("workflow-rehydrated-navigation-desktop.png");
    expect(e2eContractSource).toContain("workflowThreadSidebarSelected");
    expect(e2eContractSource).toContain("workflowThreadMatchesExpectedId");
    expect(e2eContractSource).toContain("desktop_workflow_rehydrated_navigation");
    expect(e2eContractSource).toContain("workflow_artifact_rehydration_behavior");
    expect(e2eContractSource).toContain("workflowArtifactRehydration");
    expect(e2eContractSource).toContain("workflow-artifact-rehydration-desktop.png");
    expect(e2eContractSource).toContain("workflowArtifactSourceRelativePath");
    expect(e2eContractSource).toContain("workflowArtifactStateRelativePath");
    expect(e2eContractSource).toContain("sourceContentMatchesExpected");
    expect(e2eContractSource).toContain("desktop_workflow_artifact_rehydration");
    expect(e2eContractSource).toContain("local_runtime_ownership_ui");
    expect(e2eContractSource).toContain("untracked_runtime_safety_behavior");
    expect(e2eContractSource).toContain("localRuntimeOwnership");
    expect(e2eContractSource).toContain("local-runtime-ownership-desktop.png");
    expect(e2eContractSource).toContain("In use by sub-agent Review worker");
    expect(e2eContractSource).toContain("stopDisabledVisible");
    expect(e2eContractSource).toContain("affectedSubagentVisible");
    expect(e2eContractSource).toContain("untrackedRuntimeVisible");
    expect(e2eContractSource).toContain("untrackedStopDisabledVisible");
    expect(e2eContractSource).toContain("untrackedRestartDisabledVisible");
    expect(e2eContractSource).toContain("untrackedForceUnavailableVisible");
    expect(e2eContractSource).toContain("untrackedExternalStopGuidanceVisible");
    expect(e2eContractSource).toContain("lifecycle_edge_desktop_behavior");
    expect(e2eContractSource).toContain("inspectLifecycleEdgeVisibility");
    expect(e2eContractSource).toContain("lifecycle-edge-visibility-desktop.png");
    expect(e2eContractSource).toContain("Timeout edge worker");
    expect(e2eContractSource).toContain("Continue with partial");
    expect(e2eContractSource).toContain("Partial approved");
    expect(e2eContractSource).toContain("Retry edge worker");
    expect(e2eContractSource).toContain("Retry requested");
    expect(e2eContractSource).toContain("retry_edge");
    expect(e2eContractSource).toContain("Child detached");
    expect(e2eContractSource).toContain("desktop_lifecycle_edges");
    expect(e2eContractSource).toContain("lifecycle_edge_visibility");
    expect(e2eContractSource).toContain("operator_child_controls");
    expect(e2eContractSource).toContain("operatorControls");
    expect(e2eContractSource).toContain("Cancel sub-agent Review worker");
    expect(e2eContractSource).toContain("Close sub-agent Context summarizer");
    expect(e2eContractSource).toContain("operator_control_behavior");
    expect(e2eContractSource).toContain("operatorBehavior");
    expect(e2eContractSource).toContain("completedChildClosed");
    expect(e2eContractSource).toContain("attentionChildCancelled");
    expect(e2eContractSource).toContain("operator-behavior-desktop.png");
    expect(e2eContractSource).toContain("multi_parent_cluster_stress");
    expect(e2eContractSource).toContain("multiClusterStress");
    expect(e2eContractSource).toContain("multi-cluster-stress-desktop.png");
    expect(e2eContractSource).toContain("stressClustersAfterParentMessages");
    expect(e2eContractSource).toContain("chat_export_child_bundle");
    expect(e2eContractSource).toContain("exportChatAndInspectChildBundle");
    expect(e2eContractSource).toContain("desktop-chat-export.zip");
    expect(e2eContractSource).toContain("AMBIENT_E2E_CHAT_EXPORT_PATH");
    expect(e2eContractSource).toContain("desktop_chat_export_child_bundle");
    expect(e2eContractSource).toContain("child_transcript_export");
    expect(e2eContractSource).toContain("policy_provenance_export");
    expect(e2eContractSource).toContain("pattern_graph_export_links");
    expect(e2eContractSource).toContain("childToolScopeSnapshotsIncluded");
    expect(e2eContractSource).toContain("patternGraphLinksIncluded");
    expect(e2eContractSource).toContain("visualAssertions");
    expect(e2eContractSource).toContain("buildDesktopVisualAssertions");
    expect(e2eContractSource).toContain("parent_child_placement");
    expect(e2eContractSource).toContain("default_collapsed_state");
    expect(e2eContractSource).toContain("blocking_attention_indicators");
    expect(e2eContractSource).toContain("approval_runtime_ownership_labels");
    expect(e2eContractSource).toContain("workflow_artifact_rehydration");
    expect(e2eContractSource).toContain("layout_safety");
    expect(e2eContractSource).toContain("workflow_task_continuity");
    expect(e2eContractSource).toContain("desktop_multi_cluster_stress");
    expect(e2eContractSource).toContain("horizontalOverflowFree");
    expect(e2eContractSource).toContain("collapsed-desktop.png");
    expect(e2eContractSource).toContain("expanded-narrow.png");
  });

  it("keeps the Symphony Phase 4 launch bridge dogfood wired to durable child and wait evidence", async () => {
    const phase4 = await readText("scripts/symphony-gap-phase4-dogfood.mjs");

    expect(phase4).toContain("ambient_workflow_symphony_imitate_and_verify");
    expect(phase4).toContain("launchBridgeVerified");
    expect(phase4).toContain("callable_workflow_tasks");
    expect(phase4).toContain("subagent_runs");
    expect(phase4).toContain("subagent_wait_barriers");
    expect(phase4).toContain('expectedPatternRoles = ["drafter", "verifier"]');
    expect(phase4).toContain("SUB-AGENT");
    expect(phase4).toContain("Accessibility.getFullAXTree");
    expect(phase4).toContain("headful: true");
    expect(phase4).toContain("--enable-feature=${SUBAGENTS_FEATURE_FLAG}");
  });

  it("keeps the Symphony Phase 5 recovery dogfood wired to denial and restart evidence", async () => {
    const phase5 = await readText("scripts/symphony-gap-phase5-dogfood.mjs");
    const { e2eContractSource } = await readDogfoodE2eContractSource();

    expect(phase5).toContain("ambient-symphony-gap-phase5-dogfood-v1");
    expect(phase5).toContain("symphony_gap_phase5_failure_approval_recovery");
    expect(phase5).toContain("AMBIENT_SUBAGENT_DESKTOP_DOGFOOD_PHASE5_RECOVERY");
    expect(phase5).toContain("source-subagent-desktop-dogfood");
    expect(phase5).toContain("AMBIENT_SUBAGENT_DESKTOP_DOGFOOD_RESULTS_DIR: sourceResultsDir");
    expect(phase5).toContain('AMBIENT_SUBAGENT_DESKTOP_DOGFOOD_HISTORY_APPEND: "0"');
    expect(phase5).toContain("denies child approval and rehydrates Symphony recovery state");
    expect(phase5).toContain("approvalDenial.forwardedVisible === true");
    expect(phase5).toContain("approvalDenial.deniedDecisionVisible === true");
    expect(phase5).toContain("restartRehydration.approvalForwardedRehydrated === true");
    expect(phase5).toContain("restartRehydration.parentStillBlockedAfterRelaunch === true");
    expect(phase5).toContain("restartRehydration.childRowsRehydrated === true");
    expect(e2eContractSource).toContain("phase5RecoveryDogfoodIt");
    expect(e2eContractSource).toContain("Deny child request");
    expect(e2eContractSource).toContain("inspectApprovalDenial");
    expect(e2eContractSource).toContain('approvalDecisionLabel: "Denied"');
    expect(e2eContractSource).toContain("phase5-restart-rehydration-desktop.png");
  });

  it("keeps the Symphony Phase 6 suite-separation dogfood mode-aware", async () => {
    const phase6 = await readText("scripts/symphony-gap-phase6-dogfood.mjs");

    expect(phase6).toContain("ambient-symphony-gap-phase6-dogfood-v1");
    expect(phase6).toContain("symphony_gap_phase6_suite_separation");
    expect(phase6).toContain('modeUnderTest: "generic_and_symphony_suite_separation"');
    expect(phase6).toContain('expectedOrchestrationPolicy: "generic_off_no_pattern_required__symphony_on_pattern_required"');
    expect(phase6).toContain('failureClassIfPatternMissing: generic ? "symphony_not_armed" : "symphony_orchestration_missing"');
    expect(phase6).toContain('userFacingMissingPatternLabel: generic ? "Symphony not armed" : "Symphony orchestration missing"');
    expect(phase6).toContain("waitForPersistedGenericUserMessage");
    expect(phase6).toContain("waitForGenericModePostSendEvidence");
    expect(phase6).toContain("latestRunTerminal");
    expect(phase6).toContain("latestRunSucceeded");
    expect(phase6).toContain('latestRun.status === "done"');
    expect(phase6).toContain("!latestRun.error_message");
    expect(phase6).toContain("assistantMessages.length > 0");
    expect(phase6).toContain("readRuns");
    expect(phase6).toContain("waitForPersistedSymphonyUserMessage");
    expect(phase6).toContain("composerIntentAbsent");
    expect(phase6).toContain("genericRunDidNotLaunchSymphonyWorkflow");
    expect(phase6).toContain("unexpectedSymphonyWorkflowTaskCount === 0");
    expect(phase6).toContain("symphonyRunPersistedWithSymphonyIntent");
    expect(phase6).toContain("ensureSymphonyBlockingEnabled");
    expect(phase6).toContain("blockingEnabled");
    expect(phase6).toContain('expectedWorkflowTool = "ambient_workflow_symphony_map_reduce"');
    expect(phase6).toContain("waitForPhase6LaunchEvidence");
    expect(phase6).toContain("parentRunFailedBeforeWorkflowTask");
    expect(phase6).toContain("parent run failed before workflow launch");
    expect(phase6).toContain("parentRunCompletedWithoutWorkflowTask");
    expect(phase6).toContain("parent run completed without launching workflow task");
    expect(phase6).toContain("task.parent_thread_id === persistedSymphonyUserMessage.threadId");
    expect(phase6).toContain("task?.parent_message_id");
    expect(phase6).toContain("parentRun?.assistant_message_id");
    expect(phase6).toContain("task.parent_message_id === parentRun.assistant_message_id");
    expect(phase6).toContain("launchBridgeContract?.parentMessageId === parentRun.assistant_message_id");
    expect(phase6).toContain("graph.parentMessageId === parentRun.assistant_message_id");
    expect(phase6).toContain("parentMessageLinkVerified");
    expect(phase6).toContain("graph.parentMessageId");
    expect(phase6).toContain("workflowOwnedParentMessageIds.has(message.id)");
    expect(phase6).toContain("parentMessageMetadataReferencesWorkflowTask");
    expect(phase6).toContain("allowedParentConductorTools");
    expect(phase6).toContain("ambient_callable_workflow_catalog_search");
    expect(phase6).toContain("ambient_callable_workflow_catalog_describe");
    expect(phase6).toContain("forbiddenParentToolNames.length === 0");
    expect(phase6).toContain("conductorLockProven === true");
    expect(phase6).toContain("launch.launchBridgeVerified === true");
    expect(phase6).toContain("childWaitEvidenceVerified");
    expect(phase6).toContain("parentAssistantMessagesAfterTask");
    expect(phase6).toContain("assistantMessagesAfterTask.length === 0");
    expect(phase6).not.toContain("isSubstantiveParentSynthesisMessage");
    expect(phase6).not.toContain("isDeterministicParentStatusMessage");
    expect(phase6).not.toContain("parentSubstantiveMessagesAfterTask");
    expect(phase6).toContain("failMissingCdpPort");
    expect(phase6).not.toContain("return cdpPortFromEnv() ?? 9222");
    expect(phase6).toContain("const genericPort = dogfoodCdpPort()");
    expect(phase6).toContain("const symphonyPort = await allocateAdditionalCdpPort(genericPort)");
    expect(phase6).toContain("cdpPorts: {");
    expect(phase6).toContain("reportAvoidsAmbiguousOrchestrationNotDetected");
    expect(phase6).toContain("releaseGateTerminologyEvidence");
    expect(phase6).toContain("classifyPhase6Failure");
    expect(phase6).toContain("symphony_parent_run_failed_before_workflow_launch");
    expect(phase6).toContain('message.includes("parent run completed without launching workflow task")');
    expect(phase6).toContain("failureStage");
    expect(phase6).toContain("failureClass,");
    expect(phase6).toContain("requiredConsecutiveCleanHeadfulSymphonyRunsBeforeBroadening: 3");
    expect(phase6).toContain("symphony-gap-phase6-generic-mode.png");
    expect(phase6).toContain("symphony-gap-phase6-generic-mode-sent.png");
    expect(phase6).toContain("symphony-gap-phase6-symphony-mode.png");
    expect(phase6).toContain("symphony-gap-phase6-symphony-mode-sent.png");
  });
});
