import {
  messagingInboundEventFromTelegramBridge as messagingInboundEventFromTelegramBridgeFromTelegram,
  telegramBridgeEventRouteInput as telegramBridgeEventRouteInputFromTelegram,
} from "../telegram/telegramBridgeEvents";
import {
  applyTelegramBridgeReply as applyTelegramBridgeReplyFromTelegram,
  buildTelegramBridgeReplyPreview as buildTelegramBridgeReplyPreviewFromTelegram,
  telegramBridgeReplyApprovalDetail as telegramBridgeReplyApprovalDetailFromTelegram,
  telegramBridgeReplyInput as telegramBridgeReplyInputFromTelegram,
  telegramBridgeReplyPreviewText as telegramBridgeReplyPreviewTextFromTelegram,
  telegramBridgeReplyResultText as telegramBridgeReplyResultTextFromTelegram,
} from "../telegram/telegramBridgeOutbound";
import type {
  TelegramBridgeReplyPreview as TelegramBridgeReplyPreviewFromTelegram,
  TelegramBridgeReplyResult as TelegramBridgeReplyResultFromTelegram,
} from "../telegram/telegramBridgeOutbound";
import {
  TelegramBridgePollingRunner as TelegramBridgePollingRunnerFromTelegram,
  applyTelegramBridgePoll as applyTelegramBridgePollFromTelegram,
  buildTelegramBridgePollPlan as buildTelegramBridgePollPlanFromTelegram,
  telegramBridgePollApprovalDetail as telegramBridgePollApprovalDetailFromTelegram,
  telegramBridgePollBlockedResult as telegramBridgePollBlockedResultFromTelegram,
  telegramBridgePollDeniedResult as telegramBridgePollDeniedResultFromTelegram,
  telegramBridgePollPlanText as telegramBridgePollPlanTextFromTelegram,
  telegramBridgePollResultText as telegramBridgePollResultTextFromTelegram,
  telegramBridgePollToolInput as telegramBridgePollToolInputFromTelegram,
  telegramBridgePollingApprovalDetail as telegramBridgePollingApprovalDetailFromTelegram,
  telegramBridgePollingControlInput as telegramBridgePollingControlInputFromTelegram,
  telegramBridgePollingControlPreviewText as telegramBridgePollingControlPreviewTextFromTelegram,
  telegramBridgePollingControlResultText as telegramBridgePollingControlResultTextFromTelegram,
  telegramBridgePollingStatusText as telegramBridgePollingStatusTextFromTelegram,
} from "../telegram/telegramBridgePolling";
import type {
  TelegramBridgePollPlan as TelegramBridgePollPlanFromTelegram,
  TelegramBridgePollResult as TelegramBridgePollResultFromTelegram,
  TelegramBridgePollingControlInput as TelegramBridgePollingControlInputFromTelegram,
  TelegramBridgePollingControlPreview as TelegramBridgePollingControlPreviewFromTelegram,
  TelegramBridgePollingControlResult as TelegramBridgePollingControlResultFromTelegram,
  TelegramBridgePollingRuntimeStatus as TelegramBridgePollingRuntimeStatusFromTelegram,
} from "../telegram/telegramBridgePolling";
import {
  TelegramBridgeSupervisor as TelegramBridgeSupervisorFromTelegram,
} from "../telegram/telegramBridgeSupervisor";
import {
  applyTelegramConversationDirectory as applyTelegramConversationDirectoryFromTelegram,
  buildTelegramConversationDirectoryPreview as buildTelegramConversationDirectoryPreviewFromTelegram,
  telegramConversationDirectoryApprovalDetail as telegramConversationDirectoryApprovalDetailFromTelegram,
  telegramConversationDirectoryBlockedResult as telegramConversationDirectoryBlockedResultFromTelegram,
  telegramConversationDirectoryDeniedResult as telegramConversationDirectoryDeniedResultFromTelegram,
  telegramConversationDirectoryInput as telegramConversationDirectoryInputFromTelegram,
  telegramConversationDirectoryPreviewText as telegramConversationDirectoryPreviewTextFromTelegram,
  telegramConversationDirectoryResultText as telegramConversationDirectoryResultTextFromTelegram,
  telegramConversationDirectorySetupCard as telegramConversationDirectorySetupCardFromTelegram,
} from "../telegram/telegramConversationDirectory";
import {
  createTelegramMessagingReadinessAdapter as createTelegramMessagingReadinessAdapterFromTelegram,
} from "../telegram/telegramMessagingReadiness";
import {
  applyTelegramOwnerHandoff as applyTelegramOwnerHandoffFromTelegram,
  buildTelegramOwnerHandoffPreview as buildTelegramOwnerHandoffPreviewFromTelegram,
  telegramOwnerHandoffApprovalDetail as telegramOwnerHandoffApprovalDetailFromTelegram,
  telegramOwnerHandoffBlockedResult as telegramOwnerHandoffBlockedResultFromTelegram,
  telegramOwnerHandoffDeniedResult as telegramOwnerHandoffDeniedResultFromTelegram,
  telegramOwnerHandoffInput as telegramOwnerHandoffInputFromTelegram,
  telegramOwnerHandoffPreviewText as telegramOwnerHandoffPreviewTextFromTelegram,
  telegramOwnerHandoffResultText as telegramOwnerHandoffResultTextFromTelegram,
} from "../telegram/telegramOwnerHandoff";
import {
  buildTelegramOwnerLoopActivationPlan as buildTelegramOwnerLoopActivationPlanFromTelegram,
  telegramOwnerLoopActivationCard as telegramOwnerLoopActivationCardFromTelegram,
  telegramOwnerLoopActivationInput as telegramOwnerLoopActivationInputFromTelegram,
  telegramOwnerLoopActivationPlanText as telegramOwnerLoopActivationPlanTextFromTelegram,
} from "../telegram/telegramOwnerLoopActivation";
import {
  buildTelegramRelayDiagnostics as buildTelegramRelayDiagnosticsFromTelegram,
  telegramRelayDiagnosticsInput as telegramRelayDiagnosticsInputFromTelegram,
  telegramRelayDiagnosticsText as telegramRelayDiagnosticsTextFromTelegram,
} from "../telegram/telegramRelayDiagnostics";
import {
  buildTelegramRemoteSurfaceBindingPlan as buildTelegramRemoteSurfaceBindingPlanFromTelegram,
  telegramRemoteSurfaceBindingAppliedResult as telegramRemoteSurfaceBindingAppliedResultFromTelegram,
  telegramRemoteSurfaceBindingApprovalDetail as telegramRemoteSurfaceBindingApprovalDetailFromTelegram,
  telegramRemoteSurfaceBindingBlockedResult as telegramRemoteSurfaceBindingBlockedResultFromTelegram,
  telegramRemoteSurfaceBindingCreateInput as telegramRemoteSurfaceBindingCreateInputFromTelegram,
  telegramRemoteSurfaceBindingDeniedResult as telegramRemoteSurfaceBindingDeniedResultFromTelegram,
  telegramRemoteSurfaceBindingInput as telegramRemoteSurfaceBindingInputFromTelegram,
  telegramRemoteSurfaceBindingRevokeInput as telegramRemoteSurfaceBindingRevokeInputFromTelegram,
  telegramRemoteSurfaceBindingText as telegramRemoteSurfaceBindingTextFromTelegram,
} from "../telegram/telegramRemoteSurfaceBinding";
import type {
  TelegramRemoteSurfaceBindingPlan as TelegramRemoteSurfaceBindingPlanFromTelegram,
  TelegramRemoteSurfaceBindingToolInput as TelegramRemoteSurfaceBindingToolInputFromTelegram,
} from "../telegram/telegramRemoteSurfaceBinding";
import {
  applyTelegramSessionBootstrap as applyTelegramSessionBootstrapFromTelegram,
  previewTelegramSessionBootstrap as previewTelegramSessionBootstrapFromTelegram,
  telegramSessionBootstrapPreviewText as telegramSessionBootstrapPreviewTextFromTelegram,
  telegramSessionBootstrapResultText as telegramSessionBootstrapResultTextFromTelegram,
  telegramSessionBootstrapSetupCard as telegramSessionBootstrapSetupCardFromTelegram,
} from "../telegram/telegramSessionBootstrap";
import type {
  TelegramSessionBootstrapInput as TelegramSessionBootstrapInputFromTelegram,
  TelegramSessionBootstrapOptions as TelegramSessionBootstrapOptionsFromTelegram,
} from "../telegram/telegramSessionBootstrap";

export const applyTelegramBridgePoll = applyTelegramBridgePollFromTelegram;
export const applyTelegramBridgeReply = applyTelegramBridgeReplyFromTelegram;
export const applyTelegramConversationDirectory = applyTelegramConversationDirectoryFromTelegram;
export const applyTelegramOwnerHandoff = applyTelegramOwnerHandoffFromTelegram;
export const applyTelegramSessionBootstrap = applyTelegramSessionBootstrapFromTelegram;
export const buildTelegramBridgePollPlan = buildTelegramBridgePollPlanFromTelegram;
export const buildTelegramBridgeReplyPreview = buildTelegramBridgeReplyPreviewFromTelegram;
export const buildTelegramConversationDirectoryPreview = buildTelegramConversationDirectoryPreviewFromTelegram;
export const buildTelegramOwnerHandoffPreview = buildTelegramOwnerHandoffPreviewFromTelegram;
export const buildTelegramOwnerLoopActivationPlan = buildTelegramOwnerLoopActivationPlanFromTelegram;
export const buildTelegramRelayDiagnostics = buildTelegramRelayDiagnosticsFromTelegram;
export const buildTelegramRemoteSurfaceBindingPlan = buildTelegramRemoteSurfaceBindingPlanFromTelegram;
export const createTelegramMessagingReadinessAdapter = createTelegramMessagingReadinessAdapterFromTelegram;
export const messagingInboundEventFromTelegramBridge = messagingInboundEventFromTelegramBridgeFromTelegram;
export const previewTelegramSessionBootstrap = previewTelegramSessionBootstrapFromTelegram;
export const telegramBridgeEventRouteInput = telegramBridgeEventRouteInputFromTelegram;
export const telegramBridgePollApprovalDetail = telegramBridgePollApprovalDetailFromTelegram;
export const telegramBridgePollBlockedResult = telegramBridgePollBlockedResultFromTelegram;
export const telegramBridgePollDeniedResult = telegramBridgePollDeniedResultFromTelegram;
export const telegramBridgePollingApprovalDetail = telegramBridgePollingApprovalDetailFromTelegram;
export const telegramBridgePollingControlInput = telegramBridgePollingControlInputFromTelegram;
export const telegramBridgePollingControlPreviewText = telegramBridgePollingControlPreviewTextFromTelegram;
export const telegramBridgePollingControlResultText = telegramBridgePollingControlResultTextFromTelegram;
export const TelegramBridgePollingRunner = TelegramBridgePollingRunnerFromTelegram;
export const telegramBridgePollingStatusText = telegramBridgePollingStatusTextFromTelegram;
export const telegramBridgePollPlanText = telegramBridgePollPlanTextFromTelegram;
export const telegramBridgePollResultText = telegramBridgePollResultTextFromTelegram;
export const telegramBridgePollToolInput = telegramBridgePollToolInputFromTelegram;
export const telegramBridgeReplyApprovalDetail = telegramBridgeReplyApprovalDetailFromTelegram;
export const telegramBridgeReplyInput = telegramBridgeReplyInputFromTelegram;
export const telegramBridgeReplyPreviewText = telegramBridgeReplyPreviewTextFromTelegram;
export const telegramBridgeReplyResultText = telegramBridgeReplyResultTextFromTelegram;
export const TelegramBridgeSupervisor = TelegramBridgeSupervisorFromTelegram;
export const telegramConversationDirectoryApprovalDetail = telegramConversationDirectoryApprovalDetailFromTelegram;
export const telegramConversationDirectoryBlockedResult = telegramConversationDirectoryBlockedResultFromTelegram;
export const telegramConversationDirectoryDeniedResult = telegramConversationDirectoryDeniedResultFromTelegram;
export const telegramConversationDirectoryInput = telegramConversationDirectoryInputFromTelegram;
export const telegramConversationDirectoryPreviewText = telegramConversationDirectoryPreviewTextFromTelegram;
export const telegramConversationDirectoryResultText = telegramConversationDirectoryResultTextFromTelegram;
export const telegramConversationDirectorySetupCard = telegramConversationDirectorySetupCardFromTelegram;
export const telegramOwnerHandoffApprovalDetail = telegramOwnerHandoffApprovalDetailFromTelegram;
export const telegramOwnerHandoffBlockedResult = telegramOwnerHandoffBlockedResultFromTelegram;
export const telegramOwnerHandoffDeniedResult = telegramOwnerHandoffDeniedResultFromTelegram;
export const telegramOwnerHandoffInput = telegramOwnerHandoffInputFromTelegram;
export const telegramOwnerHandoffPreviewText = telegramOwnerHandoffPreviewTextFromTelegram;
export const telegramOwnerHandoffResultText = telegramOwnerHandoffResultTextFromTelegram;
export const telegramOwnerLoopActivationCard = telegramOwnerLoopActivationCardFromTelegram;
export const telegramOwnerLoopActivationInput = telegramOwnerLoopActivationInputFromTelegram;
export const telegramOwnerLoopActivationPlanText = telegramOwnerLoopActivationPlanTextFromTelegram;
export const telegramRelayDiagnosticsInput = telegramRelayDiagnosticsInputFromTelegram;
export const telegramRelayDiagnosticsText = telegramRelayDiagnosticsTextFromTelegram;
export const telegramRemoteSurfaceBindingAppliedResult = telegramRemoteSurfaceBindingAppliedResultFromTelegram;
export const telegramRemoteSurfaceBindingApprovalDetail = telegramRemoteSurfaceBindingApprovalDetailFromTelegram;
export const telegramRemoteSurfaceBindingBlockedResult = telegramRemoteSurfaceBindingBlockedResultFromTelegram;
export const telegramRemoteSurfaceBindingCreateInput = telegramRemoteSurfaceBindingCreateInputFromTelegram;
export const telegramRemoteSurfaceBindingDeniedResult = telegramRemoteSurfaceBindingDeniedResultFromTelegram;
export const telegramRemoteSurfaceBindingInput = telegramRemoteSurfaceBindingInputFromTelegram;
export const telegramRemoteSurfaceBindingRevokeInput = telegramRemoteSurfaceBindingRevokeInputFromTelegram;
export const telegramRemoteSurfaceBindingText = telegramRemoteSurfaceBindingTextFromTelegram;
export const telegramSessionBootstrapPreviewText = telegramSessionBootstrapPreviewTextFromTelegram;
export const telegramSessionBootstrapResultText = telegramSessionBootstrapResultTextFromTelegram;
export const telegramSessionBootstrapSetupCard = telegramSessionBootstrapSetupCardFromTelegram;

export type TelegramBridgePollingControlInput = TelegramBridgePollingControlInputFromTelegram;
export type TelegramBridgePollingControlPreview = TelegramBridgePollingControlPreviewFromTelegram;
export type TelegramBridgePollingControlResult = TelegramBridgePollingControlResultFromTelegram;
export type TelegramBridgePollingRunner = InstanceType<typeof TelegramBridgePollingRunnerFromTelegram>;
export type TelegramBridgePollingRuntimeStatus = TelegramBridgePollingRuntimeStatusFromTelegram;
export type TelegramBridgePollPlan = TelegramBridgePollPlanFromTelegram;
export type TelegramBridgePollResult = TelegramBridgePollResultFromTelegram;
export type TelegramBridgeReplyPreview = TelegramBridgeReplyPreviewFromTelegram;
export type TelegramBridgeReplyResult = TelegramBridgeReplyResultFromTelegram;
export type TelegramBridgeSupervisor = InstanceType<typeof TelegramBridgeSupervisorFromTelegram>;
export type TelegramRemoteSurfaceBindingPlan = TelegramRemoteSurfaceBindingPlanFromTelegram;
export type TelegramRemoteSurfaceBindingToolInput = TelegramRemoteSurfaceBindingToolInputFromTelegram;
export type TelegramSessionBootstrapInput = TelegramSessionBootstrapInputFromTelegram;
export type TelegramSessionBootstrapOptions = TelegramSessionBootstrapOptionsFromTelegram;
