import {
  createAmbientEditOperations as createAmbientEditOperationsFromPi,
  createAmbientFindOperations as createAmbientFindOperationsFromPi,
  createAmbientGrepOperations as createAmbientGrepOperationsFromPi,
  createAmbientLsOperations as createAmbientLsOperationsFromPi,
  createAmbientReadOperations as createAmbientReadOperationsFromPi,
  createAmbientWriteOperations as createAmbientWriteOperationsFromPi,
  createPiStreamWatchdog as createPiStreamWatchdogFromPi,
  discoverPiExtensionHostTools as discoverPiExtensionHostToolsFromPi,
  enableAtomicPiSessionPersistence as enableAtomicPiSessionPersistenceFromPi,
  normalizePiEvent as normalizePiEventFromPi,
  runPiExtensionHostTool as runPiExtensionHostToolFromPi,
  workspaceBoundedAgentContextFiles as workspaceBoundedAgentContextFilesFromPi,
} from "../pi/piAgentRuntimeContract";
import type {
  AmbientFileAuthorityRequest as AmbientFileAuthorityRequestFromPi,
  AmbientFileAuthorityRequester as AmbientFileAuthorityRequesterFromPi,
  NormalizedPiEvent as NormalizedPiEventFromPi,
  PiExtensionHostRunResult as PiExtensionHostRunResultFromPi,
  PiExtensionHostTool as PiExtensionHostToolFromPi,
  PiStreamWatchdog as PiStreamWatchdogFromPi,
  SubagentChildRuntimeAdapter as SubagentChildRuntimeAdapterFromPi,
  SubagentChildRuntimeApprovalRequest as SubagentChildRuntimeApprovalRequestFromPi,
  SubagentChildRuntimeApprovalResponseInput as SubagentChildRuntimeApprovalResponseInputFromPi,
  SubagentChildRuntimeApprovalResponseResult as SubagentChildRuntimeApprovalResponseResultFromPi,
  SubagentChildRuntimeCancelInput as SubagentChildRuntimeCancelInputFromPi,
  SubagentChildRuntimeCancelResult as SubagentChildRuntimeCancelResultFromPi,
  SubagentChildRuntimeFollowupInput as SubagentChildRuntimeFollowupInputFromPi,
  SubagentChildRuntimeFollowupResult as SubagentChildRuntimeFollowupResultFromPi,
  SubagentChildRuntimeRetryInput as SubagentChildRuntimeRetryInputFromPi,
  SubagentChildRuntimeRetryResult as SubagentChildRuntimeRetryResultFromPi,
  SubagentChildRuntimeStartInput as SubagentChildRuntimeStartInputFromPi,
  SubagentChildRuntimeStartResult as SubagentChildRuntimeStartResultFromPi,
  SubagentChildRuntimeWaitInput as SubagentChildRuntimeWaitInputFromPi,
  SubagentChildRuntimeWaitResult as SubagentChildRuntimeWaitResultFromPi,
  SubagentRuntimeEventEmitter as SubagentRuntimeEventEmitterFromPi,
  ToolResultDetails as ToolResultDetailsFromPi,
} from "../pi/piAgentRuntimeContract";

export const createAmbientEditOperations = createAmbientEditOperationsFromPi;
export const createAmbientFindOperations = createAmbientFindOperationsFromPi;
export const createAmbientGrepOperations = createAmbientGrepOperationsFromPi;
export const createAmbientLsOperations = createAmbientLsOperationsFromPi;
export const createAmbientReadOperations = createAmbientReadOperationsFromPi;
export const createAmbientWriteOperations = createAmbientWriteOperationsFromPi;
export const createPiStreamWatchdog = createPiStreamWatchdogFromPi;
export const discoverPiExtensionHostTools = discoverPiExtensionHostToolsFromPi;
export const enableAtomicPiSessionPersistence =
  enableAtomicPiSessionPersistenceFromPi;
export const normalizePiEvent = normalizePiEventFromPi;
export const runPiExtensionHostTool = runPiExtensionHostToolFromPi;
export const workspaceBoundedAgentContextFiles = workspaceBoundedAgentContextFilesFromPi;

export type AmbientFileAuthorityRequest = AmbientFileAuthorityRequestFromPi;
export type AmbientFileAuthorityRequester = AmbientFileAuthorityRequesterFromPi;
export type NormalizedPiEvent = NormalizedPiEventFromPi;
export type PiExtensionHostRunResult = PiExtensionHostRunResultFromPi;
export type PiExtensionHostTool = PiExtensionHostToolFromPi;
export type PiStreamWatchdog = PiStreamWatchdogFromPi;
export type SubagentChildRuntimeAdapter = SubagentChildRuntimeAdapterFromPi;
export type SubagentChildRuntimeApprovalRequest =
  SubagentChildRuntimeApprovalRequestFromPi;
export type SubagentChildRuntimeApprovalResponseInput =
  SubagentChildRuntimeApprovalResponseInputFromPi;
export type SubagentChildRuntimeApprovalResponseResult =
  SubagentChildRuntimeApprovalResponseResultFromPi;
export type SubagentChildRuntimeCancelInput = SubagentChildRuntimeCancelInputFromPi;
export type SubagentChildRuntimeCancelResult =
  SubagentChildRuntimeCancelResultFromPi;
export type SubagentChildRuntimeFollowupInput =
  SubagentChildRuntimeFollowupInputFromPi;
export type SubagentChildRuntimeFollowupResult =
  SubagentChildRuntimeFollowupResultFromPi;
export type SubagentChildRuntimeRetryInput = SubagentChildRuntimeRetryInputFromPi;
export type SubagentChildRuntimeRetryResult = SubagentChildRuntimeRetryResultFromPi;
export type SubagentChildRuntimeStartInput = SubagentChildRuntimeStartInputFromPi;
export type SubagentChildRuntimeStartResult = SubagentChildRuntimeStartResultFromPi;
export type SubagentChildRuntimeWaitInput = SubagentChildRuntimeWaitInputFromPi;
export type SubagentChildRuntimeWaitResult = SubagentChildRuntimeWaitResultFromPi;
export type SubagentRuntimeEventEmitter = SubagentRuntimeEventEmitterFromPi;
export type ToolResultDetails = ToolResultDetailsFromPi;
