import type { ProviderCatalogEntry } from "./providerCatalogTypes";
import { localDeepResearchModelProfilesManifest, localDeepResearchModelAssetNames } from "./providerLocalDeepResearchFacade";

const reviewedAt = "2026-05-11";

export const providerCatalogDeepResearchEntries: ProviderCatalogEntry[] = [
  {
    id: "deep.literesearcher-4b",
    displayName: "Local Deep Research (LiteResearcher-4B)",
    capabilityArea: "deep-research",
    installerShape: "custom-cli",
    providerKind: "hybrid",
    sourceModel: "open-source",
    recommendationTier: "recommended",
    recommendationSummary:
      "First-party Local Deep Research path using LiteResearcher-4B through Ambient-managed llama.cpp, pinned Q4/Q8 GGUF profiles, 16k target context, and Ambient-brokered search/fetch preferences.",
    recommendationMemo: {
      deploymentRole: "primary",
      recommendation:
        "Use the first-party Local Deep Research setup when the user wants local mixed-source research from Ambient Desktop. LiteResearcher-4B provides the local reasoning/tool-call model, while Ambient resolves search and fetch providers from the user's current Search & Web preferences at run start.",
      dogfoodTargets: [
        "Run ambient_local_deep_research_setup validate and smoke against the selected pinned LiteResearcher-4B profile through the shared Ambient-managed llama.cpp runtime.",
        "Run one bounded mixed multi-source research task through ambient_local_deep_research_run and verify provider snapshot, search/fetch trace, final citations, and run artifact paths.",
        "Compare the same benchmark with Q4_K_M and Q8_0, keeping Q8 defaulted to high-memory hosts or explicit override with memory preflight.",
        "Change Search & Web provider preferences and verify the next run records the new provider snapshot without changing the installed model.",
      ],
      promotionCriteria: [
        "Setup/install/repair/validate/smoke actions expose managed model/runtime status, memory policy, provider snapshot, and user-visible diagnostics.",
        "Run artifacts include model profile, 16k/8k context decision, provider preference snapshot, tool executions, sources, final report, and deterministic citation validation.",
        "The estimated release gate passes with labeled 16/32/64 GB host-class telemetry plus real current-host telemetry, with strict real-only telemetry tracked separately as hardening.",
        "Search and scraping provider changes affect the next run through Ambient-owned provider preference resolution, not through model reinstall or upstream Serper/Scrape.do keys.",
      ],
      fallbackGuidance: [
        "Use DR-Venus-4B when comparing another 4B search/visit agent with GGUF/checkpoint options.",
        "Use Infoseeker-4B Reproduction for DDGS/tool-server and tool-format experiments.",
        "Use OpenResearcher or OpenSeeker only on server-class hardware.",
      ],
    },
    bestFor: [
      "First-party local deep research",
      "Ambient-approved search/fetch provider routing",
      "Mixed multi-source synthesis with inspectable citations",
      "Privacy-sensitive local reasoning with provider-aware web access",
    ],
    tradeoffs: [
      "Search/fetch still uses the user's configured providers and may contact cloud services",
      "Q8 and 16k context need memory-aware process supervision",
      "Strict 16/32/64 GB physical-host telemetry is still tracked as post-release hardening",
    ],
    avoidWhen: [
      "The user needs fully offline research with no web provider calls",
      "The machine cannot hold the selected local model profile or a managed llama.cpp process",
    ],
    platforms: ["macos-arm64", "linux-x64", "windows-x64"],
    platformSupport: [
      {
        platform: "macos-arm64",
        status: "supported",
        runtime: "shared Ambient-managed llama.cpp Metal runtime with pinned LiteResearcher-4B GGUF profile",
        installMode:
          "Recommended managed install through ambient_local_deep_research_setup with Q4 default on non-high-memory hosts and Q8 on workstation-class hosts or approved override.",
        evidence: [
          "Real Q4 GGUF smoke",
          "Q8 live Ambient/Pi mixed-source run under GMI Cloud",
          "Q4/Q8 profile benchmark",
          "Estimated release gate with current 128 GB+ host telemetry",
        ],
        caveats: ["Estimated 16/32/64 GB host-class telemetry remains labeled until physical-host hardening evidence is imported."],
      },
      {
        platform: "linux-x64",
        status: "conditional",
        runtime: "shared Ambient-managed llama.cpp Vulkan candidate",
        installMode:
          "Manifest-shaped and policy-tested; keep managed install conditional until Linux runtime/platform smoke evidence lands.",
        evidence: ["Runtime platform certification row", "Shared llama.cpp manifest policy"],
        caveats: ["GPU/backend, driver, process lifecycle, and cache behavior need real Linux validation before default enablement."],
      },
      {
        platform: "windows-x64",
        status: "experimental",
        runtime: "shared llama.cpp Windows x64 CPU candidate",
        installMode:
          "Pinned but default-disabled until Windows process lifecycle, path quoting, local firewall, and cache behavior are validated.",
        evidence: ["Runtime platform certification row"],
        caveats: ["No real Windows smoke evidence yet; GPU support is deferred."],
      },
    ],
    hardwareFit: [
      "Q4_K_M is the default profile for most hosts and targets 16k context, with 8k safe mode below 24 GiB or under pressure.",
      "Q8_0 is the high-memory and advanced override profile; default selection starts at 64 GiB with Q4 fallback under pressure.",
    ],
    firstPartyTemplate: {
      available: true,
      templateId: "local-deep-research:literesearcher-llamacpp",
      notes:
        "Use ambient_local_deep_research_setup for status/install/repair/validate/smoke and ambient_local_deep_research_run for bounded research; do not scaffold a custom Capability Builder package for the first-party path.",
    },
    capabilityBuilderDefaults: {
      provider: "Local Deep Research (LiteResearcher-4B)",
      locality: "local",
      responseFormats: ["text", "json"],
      envNames: [],
      networkHosts: ["huggingface.co", "github.com", "localhost"],
      modelAssets: localDeepResearchModelAssetNames(),
    },
    ambientContract: {
      commandContract:
        "First-party setup tool installs/repairs/validates/smokes the managed LiteResearcher model and shared llama.cpp runtime; first-party run tool executes bounded research with Ambient-brokered search/fetch, provider preference snapshots, model profile selection, trace capture, and citation validation.",
      descriptorRequirements: [
        "first-party capability id local.deep-research.literesearcher",
        "ambient_local_deep_research_setup action contract",
        "ambient_local_deep_research_run input/result contract",
        "pinned Q4/Q8 model asset declaration",
        "shared llama.cpp runtime manifest",
        "Ambient search/fetch provider preference snapshot",
        "run artifact and citation-validation schema",
      ],
      artifactPolicy:
        "Save setup validation, smoke, provider preference smoke, memory telemetry, full run traces, sources, final reports, and citation-validation details; return bounded previews to Pi.",
      validationTarget:
        "Run setup validate/smoke plus a bounded mixed multi-source synthesis task through Ambient/Pi, then inspect provider preference snapshot, tool-call evidence, citation validation, runtime/profile metadata, and persisted artifacts.",
    },
    secrets: [],
    networkHosts: ["huggingface.co", "github.com", "localhost"],
    modelAssets: localDeepResearchModelProfilesManifest.profiles.map((profile) => ({
      name: `${profile.repoId}:${profile.quantization}`,
      sourceUrl: profile.sourceUrl,
      expectedSize: `${profile.filename}; ${profile.sizeBytes} bytes; sha256 ${profile.sha256}`,
      licenseNote: profile.licenseNote,
      cachePolicy: "Ambient model cache under the Local Deep Research capability; not bundled into the app.",
    })),
    localArtifactReadiness: {
      status: "local-ready",
      verifiedArtifacts: [
        "Pinned Q4_K_M GGUF metadata",
        "Pinned Q8_0 GGUF metadata",
        "released inference code",
        "search/visit tool protocol",
        "shared Ambient-managed llama.cpp runtime install path",
        "Local Deep Research setup/install/repair/validate/smoke tool",
        "Local Deep Research run tool",
        "provider preference snapshot and smoke coverage",
        "deterministic citation validation",
        "Q4 real GGUF smoke",
        "Q8 live Ambient/Pi mixed-source run under GMI Cloud",
        "Q4/Q8 mixed-source profile benchmark",
        "estimated memory telemetry release gate",
      ],
      missingOrBlockingArtifacts: [
        "Strict real-only 16/32/64 GB physical-host telemetry before release hardening; not blocking the current estimated implementation gate",
      ],
      minimumLocalSmokeTest:
        "Run ambient_local_deep_research_setup validate, run ambient_local_deep_research_setup smoke against the selected GGUF profile, then run one bounded mixed multi-source synthesis task through ambient_local_deep_research_run and verify provider snapshot, source trace, final report, and citation validation.",
    },
    runtimeState: {
      externalService: true,
      serviceKind: "local-daemon",
      statePaths: [
        "Ambient-managed model cache",
        "shared llama.cpp runtime cache",
        ".ambient/local-deep-research validation, smoke, memory, provider-preference, server, and run artifacts",
      ],
      healthCheck:
        "ambient_local_deep_research_setup validate plus optional smoke against the selected GGUF profile and shared llama.cpp runtime.",
      updatePolicy: "Pinned LiteResearcher GGUF revision and pinned shared runtime manifests; no automatic model/runtime upgrades.",
    },
    costPrivacyNotes: [
      "LiteResearcher model inference runs locally after model/runtime assets are installed.",
      "The user's selected Ambient search/fetch providers may receive queries, URLs, or fetched pages and may incur provider cost.",
      "Model/runtime downloads contact declared model/runtime hosts.",
    ],
    maintenanceNotes: [
      "Keep local model serving separate from search/scraping provider setup.",
      "Track pinned GGUF revision, checksums, memory policy, context policy, provider preference snapshot schema, citation-validation schema, and release-gate evidence.",
    ],
    safetyBoundaries: [
      "Do not claim the capability is ready until ambient_local_deep_research_setup reports ready or validation passes.",
      "Do not bypass Ambient provider preference routing with upstream Serper/Scrape.do keys.",
      "Do not treat unobserved final citation URLs as valid sources.",
    ],
    knownQuirks: [
      "Uses ReAct-style search/visit tags internally and expects compatible first-party tool handling.",
      "Separate llama-server processes make memory additive with MiniCPM; supervisor leases serialize or fallback under pressure.",
      "Estimated 16/32/64 GB memory telemetry is accepted for the current gate but remains labeled until strict physical-host evidence is imported.",
    ],
    researchStatus: "live-dogfooded",
    evidence: [
      {
        date: reviewedAt,
        type: "docs-review",
        summary:
          "Initial LiteResearcher review identified the local-small model, tool protocol, and setup artifacts that became the first-party Local Deep Research path.",
      },
      {
        date: "2026-05-28",
        type: "docs-review",
        summary:
          "Pinned LiteResearcher Q4_K_M and Q8_0 GGUF profile metadata from Hugging Face repo revision for Ambient-managed local model selection.",
      },
      {
        date: "2026-05-28",
        type: "local-smoke",
        summary:
          "Real Q4 GGUF smoke passed through the shared Ambient-managed llama.cpp runtime, setup validation, provider preference smoke, and memory telemetry artifacts.",
      },
      {
        date: "2026-05-28",
        type: "pi-live-dogfood",
        summary:
          "GMI-backed Ambient/Pi live run used the Q8 profile at 16k context, executed four research tool calls through Ambient provider routing, persisted run artifacts, and passed citation validation.",
      },
    ],
    docs: [
      { label: "LiteResearcher repo", url: "https://github.com/simplex-ai-inc/LiteResearcher", lastReviewed: reviewedAt },
      { label: "LiteResearcher model", url: "https://huggingface.co/simplex-ai-inc/LiteResearcher-4B", lastReviewed: reviewedAt },
      {
        label: "LiteResearcher GGUF profiles",
        url: "https://huggingface.co/mradermacher/LiteResearcher-4B-GGUF",
        lastReviewed: "2026-05-28",
      },
    ],
  },
  {
    id: "deep.openresearcher",
    displayName: "OpenResearcher",
    capabilityArea: "deep-research",
    installerShape: "custom-cli",
    providerKind: "local",
    sourceModel: "open-source",
    recommendationTier: "experimental",
    recommendationSummary:
      "Strong fully open deep-research reference with enough artifacts, but too GPU-heavy for default desktop guidance.",
    recommendationMemo: {
      deploymentRole: "reserved",
      recommendation:
        "Use OpenResearcher as a deployment-heavy lab/server reference for fully open deep-research orchestration, not as the desktop recommendation; the reviewed path expects substantial GPU capacity and multi-service search/model setup.",
      dogfoodTargets: [
        "On an approved GPU server, start the documented vLLM and search services and run one tiny BrowseComp/GAIA-style task.",
        "Save service logs, local-search state, model revision, full trace/source/report artifacts, and GPU/runtime footprint notes.",
        "Compare the same prompt against LiteResearcher-4B or DR-Venus-4B so deployment cost is measured against a local-small candidate.",
      ],
      promotionCriteria: [
        "A server-class validation host is documented, including GPU count/VRAM, service lifecycle, and reproducible startup/shutdown steps.",
        "The offline/local search path is validated without requiring users to discover hidden service state.",
        "Pi guidance clearly reserves this card for lab/server evaluation and does not route desktop users here by default.",
      ],
      fallbackGuidance: [
        "Use LiteResearcher-4B as the first local-small smoke candidate.",
        "Use DR-Venus-4B or AgentCPM-Explore when a 4B/GGUF-capable path is more important than full OpenResearcher parity.",
        "Use Step-DeepResearch only as a hosted/API reference, not as a local replacement.",
      ],
    },
    bestFor: ["Lab/server deep research experiments", "Offline search environment study", "Training/eval recipe reference"],
    tradeoffs: ["Multi-service setup", "GPU-heavy vLLM and dense search path"],
    avoidWhen: ["The user expects laptop-friendly local setup"],
    platforms: ["linux-x64"],
    hardwareFit: ["Repo references 8 A100 80 GB setup and examples using multiple GPUs"],
    capabilityBuilderDefaults: {
      provider: "OpenResearcher",
      locality: "local",
      responseFormats: ["text", "json"],
      envNames: ["SERPER_API_KEY"],
      networkHosts: ["serper.dev"],
      modelAssets: ["OpenResearcher/OpenResearcher-30B-A3B"],
    },
    ambientContract: {
      commandContract: "Server/lab wrapper starts model/search services explicitly and runs bounded evaluation tasks.",
      descriptorRequirements: ["model asset declaration", "service state notes", "trace artifact output"],
      artifactPolicy: "Save logs, traces, and report outputs by path.",
      validationTarget: "Smoke test only on a machine with enough GPU/server capacity.",
    },
    secrets: [{ envName: "SERPER_API_KEY", required: false, capture: "ambient_capability_builder_secret_request" }],
    networkHosts: ["serper.dev"],
    modelAssets: [
      {
        name: "OpenResearcher/OpenResearcher-30B-A3B",
        sourceUrl: "https://huggingface.co/OpenResearcher/OpenResearcher-30B-A3B",
        expectedSize: "32B params",
        licenseNote: "MIT",
      },
    ],
    localArtifactReadiness: {
      status: "deployment-heavy",
      verifiedArtifacts: ["Code", "model checkpoint", "dataset links", "offline search setup", "run scripts", "benchmark/evaluation paths"],
      missingOrBlockingArtifacts: ["Desktop-friendly resource profile"],
      minimumLocalSmokeTest: "On a GPU server, start vLLM/search services and run one bounded BrowseComp/GAIA-style task.",
    },
    runtimeState: { externalService: true, serviceKind: "local-daemon", statePaths: ["logs", "local search index", "model cache"] },
    costPrivacyNotes: ["Can use local search for some benchmarks; Serper path sends queries externally."],
    maintenanceNotes: ["Treat as lab/server card until resource footprint is measured on Ambient hardware."],
    safetyBoundaries: ["Do not present as default local-desktop recommendation."],
    knownQuirks: ["Requires trust_remote_code for direct Transformers usage and substantial serving resources."],
    researchStatus: "researched",
    evidence: [{ date: reviewedAt, type: "docs-review", summary: "Enough artifacts exist, but deployment is heavy." }],
    docs: [
      { label: "OpenResearcher repo", url: "https://github.com/TIGER-AI-Lab/OpenResearcher", lastReviewed: reviewedAt },
      { label: "OpenResearcher model", url: "https://huggingface.co/OpenResearcher/OpenResearcher-30B-A3B", lastReviewed: reviewedAt },
    ],
  },
  {
    id: "deep.step-deepresearch",
    displayName: "Step-DeepResearch",
    capabilityArea: "deep-research",
    installerShape: "custom-cli",
    providerKind: "cloud",
    sourceModel: "closed-source",
    recommendationTier: "research-needed",
    recommendationSummary:
      "Hosted/API reference for deep research orchestration; not local-ready until downloadable weights or local inference instructions exist.",
    recommendationMemo: {
      deploymentRole: "reserved",
      recommendation:
        "Use Step-DeepResearch only as a hosted/API reference for deep-research orchestration until downloadable weights or documented local inference are available; do not use it to validate local-small-model onboarding.",
      dogfoodTargets: [
        "If StepFun credentials are intentionally provided through Ambient-managed secret capture, run one hosted tiny research task and save trace/source/report artifacts.",
        "Verify the wrapper never exposes STEP_MODEL_API_KEY or STEP_SEARCH_API_KEY in prompts, tool args, logs, descriptors, or artifacts.",
        "Record hosted API latency, cost/privacy notes, error shapes, and how its orchestration compares with local-small candidates.",
      ],
      promotionCriteria: [
        "Credentialed hosted dogfood succeeds with no secret leakage and with clear report/source artifacts.",
        "Documentation or model releases establish whether any local path exists; until then, the card remains hosted-reference only.",
        "Selection guidance names LiteResearcher-4B, DR-Venus-4B, Infoseeker-4B Reproduction, or AgentCPM-Explore for local-small research.",
      ],
      fallbackGuidance: [
        "Use LiteResearcher-4B as the first local-small candidate.",
        "Use DR-Venus-4B or Infoseeker-4B Reproduction for 4B search/visit or DDGS/tool-server experiments.",
        "Use OpenResearcher/OpenSeeker only when server-class local open systems are explicitly desired.",
      ],
    },
    bestFor: ["Research reference", "Hosted StepFun API experiments if credentials are intentionally provided"],
    tradeoffs: ["Requires StepFun API/search keys", "No verified local weights path in the reviewed quick start"],
    avoidWhen: ["The user asks for local deep research"],
    platforms: ["any"],
    hardwareFit: ["Hosted API path avoids local model serving"],
    capabilityBuilderDefaults: {
      provider: "Step-DeepResearch",
      locality: "network",
      responseFormats: ["text", "json"],
      envNames: ["STEP_MODEL_API_KEY", "STEP_SEARCH_API_KEY"],
      networkHosts: ["api.stepfun.com"],
    },
    ambientContract: {
      commandContract: "Hosted workflow wrapper must declare StepFun model/search credentials and save traces/reports.",
      descriptorRequirements: ["required env declarations", "hosted-reference readiness", "trace artifact output"],
      artifactPolicy: "Save report and trace artifacts, never secret values.",
      validationTarget: "Test only as hosted/API workflow with explicitly provided StepFun credentials.",
    },
    secrets: [
      { envName: "STEP_MODEL_API_KEY", required: true, capture: "ambient_capability_builder_secret_request" },
      { envName: "STEP_SEARCH_API_KEY", required: true, capture: "ambient_capability_builder_secret_request" },
    ],
    networkHosts: ["api.stepfun.com"],
    modelAssets: [],
    localArtifactReadiness: {
      status: "hosted-reference",
      verifiedArtifacts: ["Demo app", "orchestration code", "hosted API quick start"],
      missingOrBlockingArtifacts: ["Downloadable local weights", "documented local model path"],
      minimumLocalSmokeTest: "None until local weights/inference are released; hosted smoke requires StepFun credentials.",
    },
    runtimeState: { externalService: true, serviceKind: "hosted-api" },
    costPrivacyNotes: ["Queries and research tasks go to StepFun hosted services."],
    maintenanceNotes: ["Re-check if local weights or local inference path are released."],
    safetyBoundaries: ["Do not use to validate local deep-research onboarding."],
    knownQuirks: ["Quick start points to beta API access rather than local model setup."],
    researchStatus: "researched",
    evidence: [{ date: reviewedAt, type: "docs-review", summary: "Repo reviewed and classified as hosted-reference." }],
    docs: [
      { label: "StepDeepResearch repo", url: "https://github.com/stepfun-ai/StepDeepResearch", lastReviewed: reviewedAt },
      { label: "Step-DeepResearch paper", url: "https://arxiv.org/abs/2512.20491", lastReviewed: reviewedAt },
    ],
  },
  {
    id: "deep.dr-venus-4b",
    displayName: "DR-Venus-4B",
    capabilityArea: "deep-research",
    installerShape: "custom-cli",
    providerKind: "hybrid",
    sourceModel: "open-source",
    recommendationTier: "experimental",
    recommendationSummary:
      "Promising 4B edge-scale deep research agent with released code/checkpoints, but external tools remain part of the reference path.",
    recommendationMemo: {
      deploymentRole: "research",
      recommendation:
        "Use DR-Venus-4B as the second local-small deep-research candidate after LiteResearcher when comparing 4B search/visit agents, especially where GGUF/checkpoint options matter; keep external Serper/Jina/summarizer/judge dependencies explicit.",
      dogfoodTargets: [
        "Configure a reviewed checkpoint or GGUF path, run run_demo or the web demo with approved search/visit tools, and bound the task tightly.",
        "Save model revision, tool endpoint config, full trace/source/report artifacts, and notes for every external search/fetch/summarizer/judge dependency.",
        "Compare one identical tiny task against LiteResearcher-4B and a deterministic search/scrape baseline for citation quality and tool-call reliability.",
      ],
      promotionCriteria: [
        "Ambient adapter handles search/visit protocol cleanly and stores trace/source/report artifacts without semantic output repair.",
        "GGUF or checkpoint path runs on an approved local target with measured latency, memory, and tool-step bounds.",
        "External dependency guidance distinguishes local model execution from networked search/fetch/summarizer/judge services.",
      ],
      fallbackGuidance: [
        "Use LiteResearcher-4B for the first local-small smoke because its role is clearer.",
        "Use Infoseeker-4B Reproduction for DDGS/tool-server experiments with a simpler reproduction shape.",
        "Use AgentCPM-Explore when the experiment is primarily about AgentDock/MCP tool sandboxing.",
      ],
    },
    bestFor: ["Small local/open deep research research", "Search/visit tool protocol comparison"],
    tradeoffs: ["External search/fetch/summarizer/judge dependencies", "Needs Ambient adapter dogfood"],
    avoidWhen: ["The user wants production-ready local-only research"],
    platforms: ["linux-x64", "macos-arm64"],
    hardwareFit: ["4B model; GGUF exists, but long-context agent use still needs measurement"],
    capabilityBuilderDefaults: {
      provider: "DR-Venus-4B",
      locality: "either",
      responseFormats: ["text", "json"],
      envNames: ["SERPER_API_KEY"],
      networkHosts: ["serper.dev", "r.jina.ai"],
      modelAssets: ["inclusionAI/DR-Venus-4B-RL"],
    },
    ambientContract: {
      commandContract: "Wrapper runs bounded search/visit tasks and records full trace/source artifacts.",
      descriptorRequirements: ["model asset declaration", "search/visit tool protocol notes", "external dependency declarations"],
      artifactPolicy: "Save full trace, sources, and final report artifacts.",
      validationTarget: "Run one bounded task through approved search/visit tools and inspect formatting/tool reliability.",
    },
    secrets: [{ envName: "SERPER_API_KEY", required: false, capture: "ambient_capability_builder_secret_request" }],
    networkHosts: ["serper.dev", "r.jina.ai"],
    modelAssets: [
      { name: "inclusionAI/DR-Venus-4B-RL", sourceUrl: "https://huggingface.co/inclusionAI/DR-Venus-4B-RL", expectedSize: "4B params" },
    ],
    localArtifactReadiness: {
      status: "conditional-local",
      verifiedArtifacts: ["SFT/RL checkpoints", "GGUF versions", "SFT/RL/inference code", "search/visit tool protocol"],
      missingOrBlockingArtifacts: ["Fully local replacement for Serper/Jina/summarizer/judge dependencies"],
      minimumLocalSmokeTest: "Configure model path, run run_demo or web demo with approved tools, and inspect trace/source output.",
    },
    runtimeState: {
      externalService: true,
      serviceKind: "local-daemon",
      statePaths: ["model cache", "tool server logs", "research traces"],
    },
    costPrivacyNotes: ["Reference path can send search/fetch/summarization requests to external services."],
    maintenanceNotes: ["Track checkpoint choice, GGUF viability, and tool endpoint configuration."],
    safetyBoundaries: ["Keep as experimental until Ambient dogfoods tool-call and citation behavior."],
    knownQuirks: ["Claims long context and up to 200 tool-call steps; enforce bounded Ambient validation tasks."],
    researchStatus: "researched",
    evidence: [{ date: reviewedAt, type: "docs-review", summary: "Enough artifacts exist for conditional local smoke testing." }],
    docs: [
      { label: "DR-Venus repo", url: "https://github.com/inclusionAI/DR-Venus", lastReviewed: reviewedAt },
      { label: "DR-Venus RL model", url: "https://huggingface.co/inclusionAI/DR-Venus-4B-RL", lastReviewed: reviewedAt },
    ],
  },
  {
    id: "deep.openseeker-v1-30b",
    displayName: "OpenSeeker v1 30B SFT",
    capabilityArea: "deep-research",
    installerShape: "custom-cli",
    providerKind: "local",
    sourceModel: "open-source",
    recommendationTier: "experimental",
    recommendationSummary:
      "Fully open search-agent reference with model/data/code, but 31B BF16 weights make it server-class rather than desktop-default.",
    recommendationMemo: {
      deploymentRole: "reserved",
      recommendation:
        "Use OpenSeeker v1 30B SFT as a server-class open search-agent reference only when 31B/GPU resources are available; it is not a Qwen-4B-class desktop candidate.",
      dogfoodTargets: [
        "On a GPU/server host, deploy the model server with run_openseeker.sh and run one tiny generate_answer or eval task through declared search/visit tools.",
        "Save model revision, output JSONL, service logs, trace/source/report artifacts, and GPU/runtime footprint notes.",
        "Compare the same task against a 4B local-small candidate so quality gains are weighed against packaging and operating cost.",
      ],
      promotionCriteria: [
        "A reproducible GPU/server setup documents 31B model serving, startup/shutdown, and output artifact paths.",
        "Search/visit tool adapter is explicit and does not rely on hidden global state.",
        "Pi guidance keeps this reserved for lab/server experiments and routes desktop local-small asks to LiteResearcher-4B or DR-Venus-4B.",
      ],
      fallbackGuidance: [
        "Use LiteResearcher-4B or DR-Venus-4B for local-small exploration.",
        "Use OpenResearcher for a deployment-heavy fully open deep-research system comparison.",
        "Use Infoseeker-4B Reproduction when a smaller tool-server reproduction is enough.",
      ],
    },
    bestFor: ["Server-side search-agent experiments", "Open training data reference", "30B-class comparison"],
    tradeoffs: ["Large model", "Requires model server and search/visit tooling"],
    avoidWhen: ["The user needs a Qwen 4B-class local candidate"],
    platforms: ["linux-x64"],
    hardwareFit: ["31B BF16 model; plan for GPU/server resources"],
    capabilityBuilderDefaults: {
      provider: "OpenSeeker",
      locality: "local",
      responseFormats: ["text", "json"],
      modelAssets: ["PolarSeeker/OpenSeeker-v1-30B-SFT"],
    },
    ambientContract: {
      commandContract: "Server-class wrapper starts model server and runs bounded search/visit evaluation tasks.",
      descriptorRequirements: ["model asset declaration", "service state notes", "trace artifact output"],
      artifactPolicy: "Save traces, result JSONL, and evaluation outputs by path.",
      validationTarget: "Only smoke test on a machine with enough GPU/server capacity.",
    },
    secrets: [],
    networkHosts: [],
    modelAssets: [
      {
        name: "PolarSeeker/OpenSeeker-v1-30B-SFT",
        sourceUrl: "https://huggingface.co/PolarSeeker/OpenSeeker-v1-30B-SFT",
        expectedSize: "31B params",
        licenseNote: "MIT",
      },
    ],
    localArtifactReadiness: {
      status: "deployment-heavy",
      verifiedArtifacts: ["v1 model weights", "training data", "repo", "search/visit tools", "run_openseeker.sh", "evaluation scripts"],
      missingOrBlockingArtifacts: ["Desktop-friendly runtime profile"],
      minimumLocalSmokeTest: "Deploy model server with run_openseeker.sh and run one tiny eval/generate_answer task.",
    },
    runtimeState: { externalService: true, serviceKind: "local-daemon", statePaths: ["model cache", "outputs", "service logs"] },
    costPrivacyNotes: ["Local model can avoid hosted LLM calls, but web tools may still access external pages."],
    maintenanceNotes: ["Track v2 separately because model exists but repo says v2 code is coming soon."],
    safetyBoundaries: ["Do not mark as default local-desktop provider."],
    knownQuirks: ["Large BF16 checkpoint; GGUF quants exist but need separate validation."],
    researchStatus: "researched",
    evidence: [{ date: reviewedAt, type: "docs-review", summary: "Artifacts exist, but resource footprint is deployment-heavy." }],
    docs: [
      { label: "OpenSeeker repo", url: "https://github.com/rui-ye/OpenSeeker", lastReviewed: reviewedAt },
      { label: "OpenSeeker model", url: "https://huggingface.co/PolarSeeker/OpenSeeker-v1-30B-SFT", lastReviewed: reviewedAt },
    ],
  },
  {
    id: "deep.infoseeker-repro-4b",
    displayName: "Infoseeker-4B Reproduction",
    capabilityArea: "deep-research",
    installerShape: "custom-cli",
    providerKind: "hybrid",
    sourceModel: "open-source",
    recommendationTier: "experimental",
    recommendationSummary: "Research-grade 4B search-agent reproduction with enough artifacts for a local/tool-server smoke test.",
    recommendationMemo: {
      deploymentRole: "research",
      recommendation:
        "Use Infoseeker-4B Reproduction as a focused 4B tool-format and DDGS/tool-server experiment, not as a production deep-research recommendation.",
      dogfoodTargets: [
        "Run direct Transformers inference for one fixed prompt, then run a DDGS/tool-server search path for one fixed question.",
        "Save tool-server logs, emitted <search>/<answer> turns, source URLs/snippets, final answer, model revision, and runtime/error notes.",
        "Compare the answer and trace against LiteResearcher-4B or DR-Venus-4B to decide whether the reproduction is useful beyond tool-format learning.",
      ],
      promotionCriteria: [
        "DDGS/tool-server setup is reproducible and declared as local state with health checks and log paths.",
        "Tool-call format is valid enough for Ambient routing without brittle semantic rewriting.",
        "English-only and production-safety limitations are visible in Pi guidance before any user-facing install recommendation.",
      ],
      fallbackGuidance: [
        "Use LiteResearcher-4B for the first local-small deep-research smoke.",
        "Use DR-Venus-4B when checkpoint/GGUF choices and broader search/visit comparisons matter.",
        "Use deterministic web-search plus scraping when production safety matters more than agent autonomy.",
      ],
    },
    bestFor: ["Small-model tool-use research", "Qwen 4B-class search-agent experiments", "DDGS-backed search-agent experiments"],
    tradeoffs: ["Reproduction, English-only, limited training", "Peak performance requires live search backend"],
    avoidWhen: ["The user needs production-ready deep research"],
    platforms: ["linux-x64", "macos-arm64"],
    hardwareFit: ["4B model; tool server/search backend adds runtime complexity"],
    capabilityBuilderDefaults: {
      provider: "Infoseeker-4B Reproduction",
      locality: "either",
      responseFormats: ["text", "json"],
      networkHosts: ["localhost"],
      modelAssets: ["orbit-ai/infoseeker-repro-4b"],
    },
    ambientContract: {
      commandContract: "Wrapper handles <search> and <answer> tool protocol through a bounded local/search tool server.",
      descriptorRequirements: ["model asset declaration", "tool protocol notes", "tool server state notes"],
      artifactPolicy: "Save trace and final answer artifacts for inspection.",
      validationTarget: "Start DDGS/tool server, run one bounded query, and inspect tool-call format.",
    },
    secrets: [],
    networkHosts: ["localhost"],
    modelAssets: [
      {
        name: "orbit-ai/infoseeker-repro-4b",
        sourceUrl: "https://huggingface.co/orbit-ai/infoseeker-repro-4b",
        expectedSize: "4B params",
        licenseNote: "Apache-2.0",
      },
    ],
    localArtifactReadiness: {
      status: "conditional-local",
      verifiedArtifacts: ["4B weights", "Apache-2.0 license", "tool-format details", "direct Transformers usage", "verl-tool path"],
      missingOrBlockingArtifacts: ["Production safety filtering", "Validated Ambient adapter"],
      minimumLocalSmokeTest: "Run direct inference and a tool-server search path against one fixed question.",
    },
    runtimeState: { externalService: true, serviceKind: "local-daemon", statePaths: ["tool server logs", "model cache"] },
    costPrivacyNotes: ["DDGS-backed live search sends queries to configured search backends."],
    maintenanceNotes: ["Track search backend reliability and tool server setup."],
    safetyBoundaries: ["Keep research-grade; do not promote without safety and quality dogfood."],
    knownQuirks: ["Card states English-only and not intended for production without additional safety filtering."],
    researchStatus: "researched",
    evidence: [{ date: reviewedAt, type: "docs-review", summary: "Enough artifacts exist for conditional local smoke test." }],
    docs: [{ label: "Infoseeker repro model", url: "https://huggingface.co/orbit-ai/infoseeker-repro-4b", lastReviewed: reviewedAt }],
  },
  {
    id: "deep.agentcpm-explore",
    displayName: "AgentCPM-Explore",
    capabilityArea: "deep-research",
    installerShape: "custom-cli",
    providerKind: "hybrid",
    sourceModel: "open-source",
    recommendationTier: "experimental",
    recommendationSummary: "Strong 4B on-device agent candidate with model/GGUF and infrastructure, but tool sandbox setup is advanced.",
    recommendationMemo: {
      deploymentRole: "research",
      recommendation:
        "Use AgentCPM-Explore when the research question is on-device 4B agent behavior plus AgentDock/MCP-style tool sandboxing; do not choose it for a simple provider install until the tool service lifecycle is dogfooded.",
      dogfoodTargets: [
        "Run the AgentCPM quickstart with a tiny task against explicitly declared model-service and MCP manager URLs.",
        "Save outputs/quickstart_results/dialog.json, tool traces, Docker/AgentDock service logs, model revision, and sandbox capability notes.",
        "Verify the allowed tools are listed before execution and compare the same task with LiteResearcher-4B or DR-Venus-4B.",
      ],
      promotionCriteria: [
        "AgentDock/tool-service lifecycle has start, health, stop, cleanup, and artifact paths that Ambient can manage.",
        "Quickstart dialog and tool traces demonstrate bounded tool use with no undeclared sandbox expansion.",
        "Pi guidance separates model serving, Docker/MCP services, and user approval boundaries for every external capability.",
      ],
      fallbackGuidance: [
        "Use LiteResearcher-4B when search/visit deep research is the main target.",
        "Use DR-Venus-4B when a 4B/GGUF search/visit comparison is desired without AgentDock first.",
        "Use Infoseeker-4B Reproduction for a narrower DDGS/tool-server proof.",
      ],
    },
    bestFor: ["4B local agent research", "Long-horizon benchmark comparison", "MCP/tool sandbox experiments"],
    tradeoffs: ["AgentDock/tool sandbox setup is nontrivial", "Needs Ambient dogfood before recommendation"],
    avoidWhen: ["The user wants a simple provider install"],
    platforms: ["linux-x64", "macos-arm64"],
    hardwareFit: ["4B weights and GGUF help local testing; Docker/eval tooling may need more resources"],
    capabilityBuilderDefaults: {
      provider: "AgentCPM-Explore",
      locality: "either",
      responseFormats: ["text", "json"],
      networkHosts: ["localhost"],
      modelAssets: ["openbmb/AgentCPM-Explore"],
    },
    ambientContract: {
      commandContract: "Wrapper runs bounded tasks through declared MCP/tool service endpoints and saves dialog traces.",
      descriptorRequirements: ["model asset declaration", "tool sandbox state notes", "trace artifact output"],
      artifactPolicy: "Save dialog.json and tool traces by path.",
      validationTarget: "Run quickstart with a tiny task and inspect dialog/tool-call trace.",
    },
    secrets: [],
    networkHosts: ["localhost"],
    modelAssets: [
      {
        name: "openbmb/AgentCPM-Explore",
        sourceUrl: "https://huggingface.co/openbmb/AgentCPM-Explore",
        expectedSize: "4B params",
        licenseNote: "Apache-2.0",
      },
      {
        name: "openbmb/AgentCPM-Explore-GGUF",
        sourceUrl: "https://huggingface.co/openbmb/AgentCPM-Explore-GGUF",
        licenseNote: "Apache-2.0",
      },
    ],
    localArtifactReadiness: {
      status: "conditional-local",
      verifiedArtifacts: ["4B weights", "GGUF", "vLLM/SGLang/Transformers usage", "AgentCPM repo", "Docker-based evaluation/tooling"],
      missingOrBlockingArtifacts: ["Dogfooded AgentDock setup", "Ambient-specific tool adapter"],
      minimumLocalSmokeTest: "Run the AgentCPM quickstart against a tiny task and inspect outputs/quickstart_results/dialog.json.",
    },
    runtimeState: {
      externalService: true,
      serviceKind: "docker-compose",
      statePaths: ["AgentDock services", "outputs/quickstart_results"],
    },
    costPrivacyNotes: ["Local model possible; external tool endpoints depend on configured sandbox tools."],
    maintenanceNotes: ["Separate model serving from AgentDock/tool service lifecycle."],
    safetyBoundaries: ["Do not let tool sandbox capabilities expand without explicit user approval."],
    knownQuirks: ["Quickstart expects model service and MCP manager URL configuration."],
    researchStatus: "researched",
    evidence: [{ date: reviewedAt, type: "docs-review", summary: "Enough artifacts exist for advanced local smoke testing." }],
    docs: [
      { label: "AgentCPM repo", url: "https://github.com/OpenBMB/AgentCPM", lastReviewed: reviewedAt },
      { label: "AgentCPM-Explore model", url: "https://huggingface.co/openbmb/AgentCPM-Explore", lastReviewed: reviewedAt },
    ],
  },
];
